### ISSUE TITLE
Meson release notes 0.61 are missing the yet in place again change to positional arguments from i18n.merge_file

### ISSUE THREAD

**Issue by fabiscafe** [mesonbuild/meson#10036]
**Describe the bug**
With Meson 0.60 there was a change to [no longer accept positional arguments](https://mesonbuild.com/Release-notes-for-0-60-0.html#the-python-modules-dependency-method-no-longer-accepts-positional-arguments). This was changed back to a warning in [0.60.1](https://github.com/mesonbuild/meson/commit/2b01a14090748c4df2d174ea9832f212f5899491), with the goal to take place again in 0.61.
Yet it is in place again, but on the release notes there is no info about it.
https://mesonbuild.com/Release-notes-for-0-61-0.html

**To Reproduce**
Have a meson build that still uses positional arguments, builds with 0.60.3 and try to build with 0.61 until it fails. Lock at the 0.61 release notes.

**Expected behavior**
There now should be something to indicate the change

**system parameters**
Meson 0.61.x

Related issue: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/654
Previous bug-report: https://github.com/mesonbuild/meson/issues/9441

**Comment by eli-schwartz** [comment]
Those release notes don't have anything to do with i18n.merge_file(), the release notes are for python_mod.find_installation().dependency() -- and the reason there is a release notes snippet for that is because we treated the dependency() method specially due to its similarity to the generic dependency() method.

Why are we relitigating i18n.merge_file when it was already discussed in the previous bug report? That has been emitting errors since October, and we are now almost two months since 0.61.0 release anyway. The time for release notes is long since passed... and this was never something release notes worthy to begin with, every single release has *tons* of hardening against invalid inputs and this is not really exceptional.

**Comment by fabiscafe** [comment]
I don't try to relitigate i18n.merge_file. It was just about the changelog and if I was wrong about this then, sorry. So we can close this?

**Comment by tristan957** [comment]
@eli-schwartz closeable

**Comment by eli-schwartz** [comment]
Indeed.
