### ISSUE TITLE
[Feature Request] add function `files_with_ext`

### ISSUE THREAD

**Issue by realmazharhussain** [mesonbuild/meson#10031]
I understand that file globing does not exist in meson because it can take a lot of time and is unreliable. But most of us just want to do something like `files('*.py')` to select all python files in working directory. So, I suggest adding a function `files_with_ext` with the following parameters

```
files_with_ext(ext, dir)

ext: type=str (required)
dir: type=str default_value=current_source_directory (optional)
```

This function could use simple globing under the hood, which does not take that much of time and can be re-run whenever needed.

For each extension (py, in, c, blp), I created 10,000 empty files with filenames like 0.py, 1.py, 2.py, etc. and ran the command `time s=(*.py)` in bash shell. Its output was

```
real	0m0.038s
user	0m0.024s
sys	0m0.014s
```

This amount of time does not seem a lot to me.

**Comment by eli-schwartz** [comment]
> But most of us just want to do something like `files('*.py')`

That's literally globbing. I'm not convinced that this is a compelling argument to make in order to overturn Meson's current "no globbing" policy.

**Comment by dcbaker** [comment]
Here's the problem you're missing. What happens if you add a new .py file? We have no way to detect that, so we have to consider the generated build system (xcode, ninja, vs solution) *always* out of date, and on every invocation of ninja/msbuild/xcode re-run meson to ensure that the generated build system is up-to-date. *That* is slow.
