### ISSUE TITLE
Wayland module: Generate both client and server sides

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#10040]
CC @markbolhuis 

Some projects (e.g. Mesa I get told) uses both client and server side at the same time. In that case the .c file generated is identical, but the header is different. Currently trying to generate both cause that error:

```
meson.build:13:0: ERROR: Tried to create target "xdg-shell-protocol", but a target of that name already exists.
```

What about allowing that syntax: `wl_mod.scan_xml(xml, side: ['client', 'server'])` that would return 3 files: one c file and 2 headers?

**Comment by fooishbar** [comment]
Most Wayland compositors also need this.

**Comment by ppaalanen** [comment]
What if your project has some executables that are pure servers, some are pure clients, and some are both?

Hmm... what if `side: ['client', 'server']` was the _only_ option?

The difference is in headers, and the `.c` file is identical to both. You pick which header you use by the `#include` in your program.

**Comment by xclaesse** [comment]
> Hmm... what if `side: ['client', 'server']` was the _only_ option?

To be honest, why then wayland-scanner itself does not gen 3 files in 1 call?

**Comment by xclaesse** [comment]
Oh, and now I also realize we need to document that the header file name is `{name}-{side}-protocol.h` otherwise user cannot know how to `#include` them.

**Comment by ppaalanen** [comment]
> To be honest, why then wayland-scanner itself does not gen 3 files in 1 call?

That's a good question. Historical reasons? Not needing a `.c` file at all would be nice too, somehow.

I have got the feeling that in the early days of Wayland there was a lot of premature optimization going on.

**Comment by markbolhuis** [comment]
I was aware of this but didn't consider it a problem since you can run scan_xml from different subdirs and it works no problem.
Do projects that require both client and server headers typically place client and server code in the same directory and thus the same meson.build file?

Also I don't agree that 3 files should be generated.
Either two boolean flags like so, where either one or the other must be true, or both:
```
gen = wl_mod.scan_xml('protocol.xml', client : true, server : true)
``
as suggested in #9895 

Either that or as @xclaesse suggests.

**Comment by xclaesse** [comment]
> `gen = wl_mod.scan_xml('protocol.xml', client : true, server : true)`

yes, that's even better I think.

**Comment by fooishbar** [comment]
> To be honest, why then wayland-scanner itself does not gen 3 files in 1 call?

The header files are ... header files ... that you need to include from your source code. For instance, if you're a client who wants to use dmabuf, you'd need to call `zwp_linux_dmabuf_v1_create_params()`; that needs to have a declaration, so you need to generate a header which declares that. This is the client-header; since it depends on client-side typedefs, it also includes `wayland-client.h`.

If you're a server who wants to implement the protocol, you also need those declarations so you can call e.g. `zwp_linux_dmabuf_v1_send_modifier()`. This is the server-header; since it depends on server-side typedefs, it also includes `wayland-server.h`.

In addition to the helper functions (used to both send and handle requests/events), we also need interface tables which are used to declare the format of each message so the core libwayland can correctly (de)serialise it, as the protocol does not carry the message format over the wire. This is generated as a set of static const arrays of structs in C format, which is the protocol target.

If you are writing a client, you need the client-header and the protocol; if you are writing a compositor you need the server-header and the protocol. If you are writing a client which is also a compositor (e.g. because you have a nested backend, so you can run your compositor within another session for development), you need all three targets. Tests are also another common cause for needing all three.

> I was aware of this but didn't consider it a problem since you can run scan_xml from different subdirs and it works no problem.
> Do projects that require both client and server headers typically place client and server code in the same directory and thus the same meson.build file?

Yes, they do. Even if the users do end up in different subdirectories, you often centralise things into a single `protocol` subdirectory. Originally this was because it was so painful to call the scanner it was much easier to centralise things so you didn't have to open-code the whole scanner work. A further benefit is that you don't waste time regenerating the same source files over and over when you could just do it once.

Even with this module making it easier to generate the sources, you still can't generate the same source twice, so if you use it from multiple places in your source tree (e.g. Weston uses the client extensions as part of its nested backend in `libweston/backend-wayland/` but also as part of its tests in `tests/`) then you need a common place to autogenerate them. And it makes sense to have the server side next to the client side.

> That's a good question. Historical reasons? Not needing a .c file at all would be nice too, somehow.

Mmm, I can't immediately think of how that would work but it might have been possible if we'd made different choices. Having libwayland-{client,server} merged into a single interface would definitely have made life easier.

**Comment by xclaesse** [comment]
For the record, I ported GTK to wayland module to give it a try: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4541.

**Comment by xclaesse** [comment]
Made a PR to fix everything we mentioned here: https://github.com/mesonbuild/meson/pull/10047.
