### ISSUE TITLE
install_headers ignores 'subdir:' if 'install_dir:' is set

### ISSUE THREAD

**Issue by keith-packard** [mesonbuild/meson#10046]
**Describe the bug**
The install_headers function provides both `install_dir` and `subdir` parameters and documents that the `subdir` parameter is added to any `install_dir` parameter. However, the code ignores `subdir` when `install_dir` is specified.

**To Reproduce**
[install-header.zip](https://github.com/mesonbuild/meson/files/8165005/install-header.zip)

**Expected behavior**
The header file should be installed in install_dir / subdir

**system parameters**
* plain native build
* Debian unstable
* Python 3.9.10
* meson version 0.61.2
* ninja version 1.10.1

**Suggested Fix**
Because existing meson will ignore subdir, I suggest that the documentation be changed to indicate that you cannot use both options at the same time and then make the code raise an error if they are both specified.

**Comment by eli-schwartz** [comment]
Based on a discussion in IRC, where I investigated the implementation in `mesonbuild.backend.backends` and concluded that it probably was not ever intended to support both at the same time. I spot checked version 0.37.0 and the code should be entirely ignoring subdir if install_dir is set, which actually makes sense to me since the purpose of a subdir argument is to work together with the global `--includedir` option.

I think the documentation is just deeply misleading.

However, the implementation doesn't loudly yell at you if you use both, so that's an obvious bug, we should not silently accept a footgun and produce results the user did not expect. :)
