### ISSUE TITLE
Caching packagecache directory in CI leads to stale caches

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#10159]
CI caching is useful for a lot of reasons which we are all well aware of. Meson currently lacks the ability to do this properly. I'll give an example:

I have two projects:
1. Python bindings (P)
2. C library (C)

P uses a `wrap-git` fallback for C
C uses a `wrap-file` fallback (F)

If C updates F, there is no way to communicate that to P's CI cache key prior to `meson setup`, so you're left with an old version of F in your cache in perpetuity.

I am not really sure what the solution is here. Some sort of manifest file/lock file potentially? One awkward solution is adding version keys to `wrap-redirect`s and committing them to repos although this is ugly.

This isn't a showstopper by any means. I just wanted to open it to document this and maybe generate organized discussion.

**Comment by tristan957** [comment]
I think the new title might articulate this a little bit better.

**Comment by xclaesse** [comment]
What we do in GStreamer project is we run `meson subprojects download` while generating docker images and copy that somewhere in the image. When running a job we first copy subprojects back into the job's workdir, and run `meson subprojects update --reset`. You probably can do similar using CI's cache instead of docker images. You'll have to skip caching .wrap files though.

**Comment by eli-schwartz** [comment]
Yeah, indeed I misread it.

**Comment by tristan957** [comment]
I can't use `meson subprojects download` because the command fails if it encounters a cmake subproject. Fun!

**Comment by xclaesse** [comment]
> I can't use `meson subprojects download` because the command fails if it encounters a cmake subproject. Fun!

report the bug :)

**Comment by tristan957** [comment]
According to @eli-schwartz it is not a bug :). We just discussed this in Matrix/IRC

**Comment by tristan957** [comment]
The error is "Subproject has no meson.build files" or whatever. My thought is just skip the subproject recursion instead of erroring out

**Comment by eli-schwartz** [comment]
Specifically, the issue is that we "know" whether a given subproject is one of the two supported types:
- meson
- cmake

And in the former case, we error out if meson.build does not exist, while in the latter case we error out if CMakeLists.txt does not exist.

However, the only way to flag a subproject as a cmake one is to do it from meson.build by invoking `cmake.subproject()` so this isn't very useful to people running `meson subprojects download`.

:(

This is not a bug, but it could possibly be argued to be an enhancement opportunity. I don't know what that enhancement might be, but I won't rule out the possibility that someone who cares more about cmake than I do, can figure out how to frame one.

**Comment by xclaesse** [comment]
We should check for meson.build or cmakelist.txt.

**Comment by eli-schwartz** [comment]
The latter would be ***incorrect*** and a bug to check, for a meson-based subproject.

And a major use case of subproject wraps is, in fact, to wrap a cmake project so that it can be built with meson. So we absolutely want to detect if that is broken.

**Comment by tristan957** [comment]
Maybe we should add a "type" keyword to wrap files?

**Comment by deepbluev7** [comment]
Having proper cmake wraps would be great, see #7943

**Comment by tristan957** [comment]
https://github.com/hse-project/hse-python/pull/47/files#diff-0037998623628727f890ef6e994b01f3c469c3e0769ac8c887d2f4f979f2a514R88

I pulled this off after giving it more thought. Easy enough. I think I had some misunderstanding somewhere when I initially created this ticket.
