### ISSUE TITLE
Open cross-file within meson.build

### ISSUE THREAD

**Issue by perigoso** [mesonbuild/meson#10156]
We have a project (embedded) with multiple targets/platforms, with different arcquitectures and a cross file for each, the target is chosen with a build option that configures the build for it (about 90% the codebase is shared), this is defined by a build option and not which crossfile is used because some targets share the cross-file (same arch)

What I want to be able to do is provide the target to the build through a build option (what we're doing now) and within the main meson.build determine and import the correct cross file

What we're doing:
` meson .. --cross-file ../platform/example.ini -Dtarget=ae-1ph`

What I want to do:
` meson .. -Dtarget=ae-1ph`
(inside meson.build)
```
target= get_option('target')
if target== 'ae-1ph'
  crossfile('platform/example.ini')
  # other target configs
elif target== 'ae-3ph'
  crossfile('platform/example_2.ini')
  # other target configs
endif
```

**Comment by perigoso** [comment]
I don't think something like this is possible right now, so this is a feature request.

**Comment by tristan957** [comment]
What does `target` mean here? Is that a build target like an executable?

**Comment by jpakkane** [comment]
This is not possible by design. The "build environment" is fixed before any build file is even parsed and must be immutable over time. If you've ever had to deal with cache variables and their ilk in CMake, you should probably have a pretty good idea why that is the case.

The common solution is to have a setup script something like `setup_cross.sh` that does the thing you need (it can even sniff the environment and set up separate build dirs for all toolchains on the current machine). Typically you need to set other options as well so having them in a single file that you can directly run from e.g. CI is nice.

**Comment by tristan957** [comment]
@eli-schwartz seems closeable to me
