### ISSUE TITLE
Release version number reported as latest not up-to-date

### ISSUE THREAD

**Issue by Ricky-Tigg** [mesonbuild/meson#10223]
**Issue**

Hello. By mistake the version [reported](https://github.com/mesonbuild/meson/releases) here as _latest_ – _0.61.4_ now – is not the one with the highest **stable** version number – _0.62.0_ now – which is also reported in [linked](https://mesonbuild.com/Getting-meson.html) [page](https://pypi.python.org/pypi/meson) and the one available by default for download.

**Comment by eli-schwartz** [comment]
Github automatically marks this, it's not selected by projects.

0.61.4 is the chronologically most *recent* release, since it was released after 0.62.0, but it is not the semver *highest*.

Github's "latest" marker is defined and selected by Github, and Github says it means "most recently created", not "highest and most preferred version".

In comparison, this works properly at https://pypi.org/project/meson/#history
