### ISSUE TITLE
boost interprocess may require linking against librt

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10274]
**Describe the bug**
When using shared memory objects from boost::interprocess, the concrete implementation on my Ubuntu installation uses shm_open, which, on the same machine, is provided by librt. Do I have to include this linker dependency by myself?

**To Reproduce**
main.cpp
```
#include <tuple>
#include <boost/interprocess/shared_memory_object.hpp>
int main()
{
    std::ignore = new boost::interprocess::shared_memory_object(
        boost::interprocess::create_only,
        "shm",
        boost::interprocess::read_write);
}
```

meson.build
```
project('test', 'cpp')
boost_dep = dependency('boost')
executable('app', 'main.cpp', dependencies: boost_dep)
```

Compile and link on Ubuntu hirsute. I'm confident that the erroneous behavior is not limited to that particular distribution!

**Expected behavior**
I would not expect linking errors! boost_dep should contain -lrt ... but of course only when necessary.

I realize that this scenario is not easily recognized and needs some help from the meson.build writer. Blindly adding -lrt to the boost dependency is not a good idea. At the very least, this should be limited to the module 'interprocess' - but since that is a "header-only" boost library, no such module exists. Also, if I'm not using shared memory objects but, for instance, only file locks, then I don't need to link against librt.

Effectively, this report is not meant to complain about a bug, but rather to ask for the intended behavior and whether there is any intention to address such issues. (There are more instances of additional linking requirements when using "header-only" boost libraries.)

**system parameters**
* plain build
* Ubuntu Hirsute (21.04)
* Python 3.9.5
* Meson 0.62.0
* Ninja 1.10.1

**Comment by jpakkane** [comment]
The unfortunate problem here is that Boost does not provide pkg-config files. If they did, this would not be an issue. Similarly I _think_ that glibc developers intend to fold librt into the main libc file so the whole thing becomes unnecessary in the future.

We can't really add all potential dep libs like this because that has side effects, especially if using `as-needed`. The workaround is fairly simple:

```meson
rt_dep = meson.get_compiler('cpp').find_library('rt', required: false)
```

and then using that in targets that need it. Unfortunately as there is no reliable way to detect beforehand whether the project is going to use those parts or not, I don't think we can make this happen automatically for your use case.

**Comment by eli-schwartz** [comment]
@mensinda

**Comment by mensinda** [comment]
From the [boost docs](https://www.boost.org/doc/libs/1_79_0/doc/html/interprocess.html):

> In POSIX systems, Boost.Interprocess uses pthread system calls to implement classes like mutexes, condition variables, etc... In some operating systems, these POSIX calls are implemented in separate libraries that are not automatically linked by the compiler. For example, in some Linux systems POSIX pthread functions are implemented in librt.a library, so you might need to add that library when linking an executable or shared library that uses Boost.Interprocess. If you obtain linking errors related to those pthread functions, please revise your system's documentation to know which library implements them. 

This is an absolute mess. Not because it is hard, but because there is no way to extract this information from the boot JAM (or CMake) files in the boost source code (which is just a dummy file to just include tests).

Additionally, there are no installed `*.cmake` files for `Boost.Interprocess` which we could parse. To check this on Arch-based distros use: `pacman -Ql boost | grep '/usr/lib/cmake' | grep -v '\.cmake'`

This is the only information available to us that can be reasonably parsed. Feel free to correct me if I am wrong / have missed something.

So, the only option we have to support such libraries out of the box in Meson would be to **manually** maintain this dependency information in Meson (and also watch out for the `librt.so` merger into libc). This would mean for Meson to:
- periodically check the boost docs manually
- maintain this list in our [`boost.py`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/boost.py) and update it accordingly
  - the real fun starts here when different boost versions have different requirements
- do this for all **143** boost libraries

IMHO this is too much of a maintenance burden to be feasible for a single (granted big and widely used) dependency. So, unless there are some other opinions here (or better solutions) this will be a wontfix.

---

The same issue also exists for CMake projects (not that this is a real argument, since we aim to be better than CMake :smiley:):

```cmake
cmake_minimum_required(VERSION 3.0.0)

project(TTT)

# This does not work beacuse there is no `boost_interprocessConfig.cmake`
#find_package(Boost REQUIRED COMPONENTS date_time interprocess)

find_package(Boost REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main Boost::headers)
```

**Comment by eli-schwartz** [comment]
> and also watch out for the `librt.so` merger into libc

https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=30639e79d3370243ee5ef3a029204a4c71e15856

Committed June 2021, released in 2.34

**Comment by eli-schwartz** [comment]
>  There is no need to compile Boost.Interprocess, since it's a header only library. Just include your Boost header directory in your compiler include path.
> 
> Boost.Interprocess depends on [Boost.DateTime](https://www.boost.org/libs/date_time/), which needs separate compilation. However, the subset used by Boost.Interprocess does not need any separate compilation so the user can define BOOST_DATE_TIME_NO_LIB to avoid Boost from trying to automatically link the Boost.DateTime.

Alright, how the heck does this work anyway. :p Since it explicitly doesn't claim to need anything other than "add the header directory to cflags", how does it "depend on XXX" and how does boost try to "automatically link" anything?

**Comment by mensinda** [comment]
I will close this as a won't fix for now, since there is the workaround from @jpakkane and because of the maintenance burden for Meson if we commit to fixing boosts dependency situation...

Feel free to reopen if we missed something and/or there are new developments.
