### ISSUE TITLE
Explicit modeling of Python module dependencies

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#10316]
**Describe the bug**
Consider this meson build file:
```
project('test', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('test', 'test.c',
  install : true)

test('basic', exe)

py3_mod = import('python')
py3_inst = py3_mod.find_installation('python3')

run_target('check-build',
    command: [py3_inst, files('check-tool.py'), exe]
)

run_target('check-build2',
    command: [py3_inst, files('check-tool2.py'), exe]
)
```
Further assume that `check-tool.py` depends on the Python module `abc` and `check-tool2.py` depends on the Python module `xyz`.
I did not find a possibility to model the depedency specific for the target, i.e. to say Meson that the check for the module `abc` is only necessary for the target `check-build`.
I only found that `find_installation` takes an extra argument `modules` to specify all modules globally.
But in this case a user may never want to execute the run targets and `abc` and `xyz` may be complicated to install.

Some kind of autodetect feature would be nice so it the presence of the module is modeled as normal `dependency` or is such a feature already present?

**Comment by eli-schwartz** [comment]
You could do multiple

```meson
py3_inst1 = find_installation(modules: ['abc'], required: false)
py3_inst2 = find_installation(modules: ['xyz'], required: false)
```

If you don't mark them as not required, it is a moot point because the configure check will abort due to the inability to satisfy the prereq of a single run_target in your build configuration.

This is a bit different from how dependencies are usually modeled (looking up the variant, not looking up an always-there dependency while checking if it has certain attributes), but not unusually different. There are some dependencies that actually work exactly like this -- qt5, boost, llvm all have the concept of a modules kwarg that the specific dependency lookup needs to take into account, and you can look up any of the three multiple times, each time checking for a different set of components that certain subsets of the build need.

**Comment by gerion0** [comment]
Nice. If I get it right, this would be a complete working example:
```
project('test', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('test', 'test.c',
  install : true)

test('basic', exe)

py_mod = import('python')
py_inst1 = py_mod.find_installation(modules: ['abc'], required: false, disabler: true)
py_inst2 = py_mod.find_installation(modules: ['xyz'], required: false, disabler: true)

run_target('check-build',
    command: [py_inst1, files('check-tool.py'), exe]
)

run_target('check-build2',
    command: [py_inst2, files('check-tool2.py'), exe]
)
```

This modeling may be a litte tedious for a bunch of different module combinations but this may be a workaround:
```
project('test', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('test', 'test.c',
  install : true)

test('basic', exe)

py_mod = import('python')

py = py_mod.find_installation(disabler: true)

mod_abc = py_mod.find_installation(modules: ['abc'], required: false, disabler: true).dependency()
mod_xyz = py_mod.find_installation(modules: ['xyz'], required: false, disabler: true).dependency()

run_target('check-build',
    command: [py, files('check-tool.py'), exe]
    depends: mod_abc
)

run_target('check-build2',
    command: [py, files('check-tool2.py'), exe]
    depends: mod_xyz
)

run_target('check-build3',
    command: [py, files('check-tool3.py'), exe]
    depends: [mod_abc, mod_xyz]
)
```

**Comment by gerion0** [comment]
> ```
> project('test', 'c',
>   version : '0.1',
>   default_options : ['warning_level=3'])
> 
> exe = executable('test', 'test.c',
>   install : true)
> 
> test('basic', exe)
> 
> py_mod = import('python')
> 
> py = py_mod.find_installation(disabler: true)
> 
> mod_abc = py_mod.find_installation(modules: ['abc'], required: false, disabler: true).dependency()
> mod_xyz = py_mod.find_installation(modules: ['xyz'], required: false, disabler: true).dependency()
> 
> run_target('check-build',
>     command: [py, files('check-tool.py'), exe]
>     depends: mod_abc
> )
> 
> run_target('check-build2',
>     command: [py, files('check-tool2.py'), exe]
>     depends: mod_xyz
> )
> 
> run_target('check-build3',
>     command: [py, files('check-tool3.py'), exe]
>     depends: [mod_abc, mod_xyz]
> )
> ```

Does not work unfortunately, since `depends` of `run_target` only excepts `array[BuildTarget | CustomTarget]` as dependencies, not dependencies.

I also tried to bind the module dependency to the file with `declare_dependency` but am unable to get the correct filepath again.
Best try so far:
```
project('test2', 'c',
  version : '0.1',
  default_options : ['warning_level=3'])

exe = executable('testa', 'test.c',
  install : true)

test('basic', exe)

py_mod = import('python')

py = py_mod.find_installation(disabler: true)

requests = py_mod.find_installation(modules: ['requests'], required: false, disabler: true).dependency()

req = declare_dependency(
  sources: files('check-tool.py'),
  variables: {'file': 'check-tool.py'},
  dependencies: requests
)

run_target('check-build',
    command: [py, req.get_variable('file'), exe],
)
```
However, the `check-tool.py` variable is a string, not a file and therefore not resolved relative to the build directory and wrong. I'm also unable to put the absolute path of `check-tool.py` into the crafted dependency because a FileHolder object does not have a `full_path` method.

**Comment by eli-schwartz** [comment]
A dependency() is a CFLAGS/LDLIBS interface. run_target doesn't have a compiler infrastructure and doesn't expect that. Targets which do expect that, generally accept a "dependencies" kwarg.

What it does support is a kwarg called "depends" which is admittedly a bit confusingly similar, and allows adding *file* dependencies rather than compile flag interface dependencies.

It doesn't semantically make much sense to add `-I/usr/include/python3.10` as a dependency of a run_target. Specializing the find_installation (which returns an ExternalProgram, just like find_program does) seems like the best option to me.

I guess if you really wanted you could rewrite your run_target commands in C targeting the CPython api, link them to a find_installation(...).dependency(embed: true), and then use that executable() output as a `depends` or even as the `command: `. But that seems more convoluted even if technically possible.
