### ISSUE TITLE
Feature Request, user level default behaviour for thread use when compiling

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#10340]
ninja, unlike make, uses all available threads by default. I am sure this had good reasons but the reality in most systems I work on is that I run out of memory before compilation ends. As a result my system freezes and I have to kill the computer, sometimes loosing work as a result. I often can only realistically use one or two threads as I am bottlenecked by available RAM.

One can of course pass `-j2` when calling `meson compile` but I don;t always remember to do so. Morevover, `meson install` calls compilation under the hood but I don't think you can pass the -j2 argument to install. The consequence is that if I try to do `meson install` in most of my computers I have to go through a painful process of running, compile files until I run out of RAM, reboot, repeat, until all files are compiled, which is... painful.

It would be awesome if one could configure meson/ninja to behave like make in this regard, use a single thread (or a fixed number of threads regardless of system availability). Since this would be user defined it would not affect people that can take advantage of all their threads, but it would stop the problem of accidentally running out of RAM on systems with less memory.

**Comment by eli-schwartz** [comment]
make also lets you export `MAKEFLAGS=-j2` in the environment. Unfortunately, the ninja developers have decided that using environment variables to control parallelism is "slow" (because getenv is slow?) and/or produces different build artifacts. They consider this a point of pride:

> Ninja supports one environment variable to control its behavior: NINJA_STATUS, the progress status printed before the rule being run.

The official recommendation of the ninja developers is that you write a python script (python > sh because Windows portability) that executes ninja with your chosen -j argument, and place it in your $PATH as `ninja` before the "real" ninja. Despite numerous people explaining why that doesn't work at scale or in various specialized environments, they have spent *years* remaining adamant that they will not implement an environment variable `NINJAFLAGS=-j2`.

My recommendation is to use https://github.com/michaelforney/samurai, an independent POSIX reimplementation of ninja that does indeed support `$SAMUFLAGS`.
