### ISSUE TITLE
Changing contents of a wrap file doesn't trigger a rebuild of the subproject.

### ISSUE THREAD

**Issue by ericonr** [mesonbuild/meson#10348]
**Describe the bug**

If I have a project with a wrap file and I change some information in the file (such as version), that isn't picked up by ninja to make meson run configure again.

**To Reproduce**

I don't think a reproducer is needed, but if one is, I can cook it up on request.

**Expected behavior**

ninja will trigger a meson reconfiguration, which will pick up differences in the wrap file. 

**system parameters**
* Native build
* Ubuntu 20.04
* python 3.8
* meson master
* samurai

In case this is intended behavior, I think it should be documented (or I missed it in the docs :c )

**Comment by eli-schwartz** [comment]
Leaving aside the question of docs, the implementation itself currently assumes that ninja rebuilds are triggered when the subproject itself changes.

Wrap files aren't the subproject itself, though... They only describe how to download one (as well as which deps/progs it provides). To put it another way... Even if you manually reconfigure, for example by running `meson setup --wipe`, it won't actually update a wrap-git to the new revision, or re-extract the patch_directory of a wrap-file. There is a dedicated.command to do that though, `meson subprojects update`.

In the event that a reconfigure is triggered for some other reason, the subproject will be resolved again, and if the directory for it exists it will be considered to be cached and blindly reused. If the wrap file updates to a new version and that version is a tarball with a different directory key, Meson will treat it as missing (not know that the old directory name even exists) and run the download/extract stage of subproject resolution as a "missing" subproject, rather than an out of date one.

Any suggestions or PRs to make this clearer in the docs will be gratefully welcomed. I think you're not the first person who wasn't initially clear on how that works.

**Comment by jpakkane** [comment]
If you do `meson wrap update foo` then IIRC it will only touch the wrap file. Thus it won't trigger an update on recompilation, which would be unexpected.

**Comment by mkow** [comment]
> the implementation itself currently assumes that ninja rebuilds are triggered when the subproject itself changes.

@eli-schwartz: What is the definition of subproject here? For me the changes in `meson.build` inside `packagefiles` are also silently ignored. This made both me and other devs I work with waste many hours debugging problems which were non-existent, just because the subprojects builds got stale silently.

> Any suggestions or PRs to make this clearer in the docs will be gratefully welcomed. I think you're not the first person who wasn't initially clear on how that works.

I'm not sure this will help much, in our project we painfully rediscover this Meson quirk from time to time despite we all knew about this at some point in the past. It's just super unintuitive for us that Meson can sometimes generate incorrect build results if you don't run `meson subprojects purge --confirm`.
Couldn't Meson track these dependencies somehow?

**Comment by xclaesse** [comment]
One of the reason it's not updating the subproject checkout when changing the wrap or packagefiles is you could lose local changes to the subproject.  The command to ensure you build up to date subproject is `meson subprojects update --reset`.

**Comment by eli-schwartz** [comment]
> @eli-schwartz: What is the definition of subproject here? For me the changes in `meson.build` inside `packagefiles` are also silently ignored. This made both me and other devs I work with waste many hours debugging problems which were non-existent, just because the subprojects builds got stale silently.

The subproject is the files in `subprojects/<subproject_name>/`, note ending directory slash.

The changes inside `packagefiles/` are not "a subproject", they are instructions for how to download a subproject. In fact, they are *literally* an alternative way to provide the same content normally provided by patch_url, which is a network resource.

If the file `subprojects/<subproject_name>/meson.build` gets updated, then it triggers a buildsystem reconfigure, just like any other meson.build in any subdir which gets parsed to contribute its build rules.

...

If you want to apply updates to ***the source code*** of a subproject, then as I said above, there is a dedicated command for that, `meson subprojects update`, and as @xclaesse pointed out, this must be done manually, thereby acknowledging that you want to destroy any local changes. It won't be done automatically.

Note that this is NOT a buildsystem reconfigure. It is a source code update. It's the same codepath that will also run `git fetch` and re-checkout the latest upstream version of a branch.

> Couldn't Meson track these dependencies somehow?

What should it track, exactly? The input in question is your `packagefiles/` directory, and the *output* is not the build directory, but the subprojects/ source code. If dependencies *were* tracked, then the action they would trigger would be to run `meson subprojects update --reset`, a potentially destructive action that isn't related to building at all.

**Comment by mkow** [comment]
> One of the reason it's not updating the subproject checkout when changing the wrap or packagefiles is you could lose local changes to the subproject.

Couldn't this be solved by building subprojects inside build directory? This is another thing which surprised me after reading https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project (I recently went through all the entry-level docs), it seemed to be Meson's philosophy to build everything in the build directory. But then I noticed that it changes stuff in `subprojects/` in-place.

> What should it track, exactly? The input in question is your `packagefiles/` directory, and the output is not the build directory, but the subprojects/ source code. If dependencies were tracked, then the action they would trigger would be to run `meson subprojects update --reset`, a potentially destructive action that isn't related to building at all.

Assuming you need to stick with in-tree build here for some reason: Maybe it could at least throw an error/warning in such case and suggest the `update` command, with a disclaimer that it may be destructive? Is there any case where the user modified `packagefiles/`, but doesn't want the change to be noticed by the buildsystem? At least in my usages this was always an accidental error and what I really wanted was a rebuild.

**Comment by eli-schwartz** [comment]
> it seemed to be Meson's philosophy to build everything in the build directory. But then I noticed that it changes stuff in subprojects/ in-place.

> stick with in-tree build here for some reason: 

> what I really wanted was a rebuild.

Correct terminology is relevant here. This isn't building. This is checking out or otherwise downloading source code.

...

> Couldn't this be solved by building subprojects inside build directory? This is another thing which surprised me after reading https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project (I recently went through all the entry-level docs), it seemed to be Meson's philosophy to build everything in the build directory. But then I noticed that it changes stuff in subprojects/ in-place.

Multiple build directories may exist and should share source code. Additionally, subprojects should not have source code .c and build artifact .o in the same directory (even if it is a build directory).

And ***definitely*** you want downloaded tarballs to be cached in subprojects/packagecache/ and not builddir/subprojects/packagecache/

**Comment by eli-schwartz** [comment]
> Maybe it could at least throw an error/warning in such case and suggest the update command, with a disclaimer that it may be destructive?

Maybe? I don't know what that would look like. It would probably involve configure-time scanning of the packagefiles directory as we really have no idea when the subproject is downloaded, via automatic fallback or manually by the subprojects command or via `meson dist --include-subprojects`.

**Comment by mkow** [comment]
> This is checking out or otherwise downloading source code.

Hmm, but it also consist of applying the overlay? So it's not "just downloading"?

> Additionally, subprojects should not have source code .c and build artifact .o in the same directory (even if it is a build directory).

This seems to be rather a technicality? You could have 2 directories inside build directory, one with the subprojects' sources and the other for their build outputs?

> And _**definitely**_ you want downloaded tarballs to be cached in subprojects/packagecache/ and not builddir/subprojects/packagecache/

To be honest, I myself would prefer to have them copied a few times (and they are _usually_ rather small) than wasting time debugging binaries built incorrectly.

> Maybe? I don't know what that would look like. It would probably involve configure-time scanning of the packagefiles directory as we really have no idea when the subproject is downloaded, via automatic fallback or manually by the subprojects command or via `meson dist --include-subprojects`.

I'm more concerned about the case where the `packagefiles/` included in the main project has changed. If you change some remote resource then it's expected and (IMO) intuitive that you may need a forced clean rebuild. But if you change something in your own project then I'd expect that this will properly be noticed by dependency checking in the build system.

Anyways, I'm just saying this as a pretty new user which doesn't know Meson internals, who tries to migrate to Meson in a few projects. This is quite a pain point for us, as multiple people from our team hit this problem more than once.

**Comment by nosracd** [comment]
>@xclaesse  One of the reason it's not updating the subproject checkout when changing the wrap or packagefiles is you could lose local changes to the subproject. 

That's a good point. Could it check to make sure there are no local changes and only update the subproject checkout in that case?

The most common user error I've seen people encounter when working with Meson is that they checkout a revision of the main project which includes changes to the revisions in the subproject wrap files and don't think to blow away their subprojects before running Meson. If Meson were to check the actual subproject revision against the revision in the wrap file it would fix a lot of user error.

If the Meson team would be open to some variant of that feature, I'd be happy to take a stab at implementing it.

**Comment by nosracd** [comment]
I like the general concept. If we're not trying to detect local changes, though, and just whether the user has modified any of the inputs, would it be sufficient to just check the `.wrap` file and the contents of `packagefiles`? I'm thinking it could store off a hash of the wrap file, as well as a hash of any packagefiles directory that the wrap points to. Then when meson runs it could recalculate the hashes and compare them against the stored hashes. If either don't match, it could log a warning like

> Subproject  <proj_name> may be out of date. Changes have been made to  <proj_name>.wrap or the packagefiles since the subproject was initially configured.

**Comment by eli-schwartz** [comment]
> would it be sufficient to just check the `.wrap` file and the contents of `packagefiles`? I'm thinking it could store off a hash of the wrap file, as well as a hash of any packagefiles directory that the wrap points to.

Maybe. I did offer the disclaimer that I was engaging in shower thoughts. I guess since the wrap file already contains a hash of any url-based tarballs, the packagecache/ tarball cannot really change without the wrap file changing.

> If the Meson team would be open to some variant of that feature, I'd be happy to take a stab at implementing it.

I am absolutely open to this idea, or any idea you have to improve the user experience, which based on this discussion I think I agree definitely has some sharp edges.

Specifically for one possible solution, I don't want it to automatically update the subproject because I'm concerned that this cannot be done 100% safely, only 99.9% safely, and in that 0.1% case we will overwrite someone's work. I don't expect to hear arguments that will change my mind, but you're welcome to try...

Anything short of that is definitely fair game, and I am brainstorming possible solutions for you to run with -- you did say you'd be open to take a stab at implementing it, which means the exact details of how you implement it are up to you, and I will simply review it to see if it behaves as expected, potentially offer helpful suggestions, and ultimately almost certainly accept the feature you design if we both agree it helps your use case and doesn't regress the experience for other users.
