### ISSUE TITLE
gtkdoc, g-ir-scanner, and more don't set CC environment variable before being run

### ISSUE THREAD

**Issue by lantw44** [mesonbuild/meson#1035]
```
Building documentation for gstreamer
Traceback (most recent call last):
  File "/path/to/meson/meson.py", line 26, in <module>
    sys.exit(main())
  File "/path/to/meson/meson.py", line 23, in main
    return mesonmain.run(launcher, sys.argv[1:])
  File "/path/to/meson/mesonbuild/mesonmain.py", line 249, in run
    sys.exit(run_script_command(args[1:]))
  File "/path/to/meson/mesonbuild/mesonmain.py", line 239, in run_script_command
    return cmdfunc(cmdargs)
  File "/path/to/meson/mesonbuild/scripts/gtkdochelper.py", line 183, in run
    options.ignore_headers.split('@@') if options.ignore_headers else [])
  File "/path/to/meson/mesonbuild/scripts/gtkdochelper.py", line 104, in build_gtkdoc
    gtkdoc_run_check(scanobjs_cmd, abs_out)
  File "/path/to/meson/mesonbuild/scripts/gtkdochelper.py", line 55, in gtkdoc_run_check
    raise MesonException('\n'.join(err_msg))
mesonbuild.mesonlib.MesonException: 'gtkdoc-scangobj' failed with status 127
sh: gcc: not found
Compilation of scanner failed:
```

`gtkdoc-scangobj` defaults to `gcc` when `CC` environment variable is not set. To avoid external commands from using their own ways to detect the compiler, meson should always set `CC` environment variable before running commands.

**Comment by nirbheek** [comment]
`g-ir-scanner` has the same problem.

```
unable to execute 'gcc': Permission denied
Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 535, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 443, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/lib64/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/lib64/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "/usr/lib64/gobject-introspection/giscanner/ccompiler.py", line 199, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 123, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

**Comment by tp-m** [comment]
Yes, this is definitely needed for `g-ir-scanner` and friends, I know it solved some weird problems with some setups (ostree). Here's what we do in GStreamer in the autotools build:
```
Gst-1.0.gir: $(INTROSPECTION_SCANNER) libgstreamer-1.0.la
	GST_PLUGIN_SYSTEM_PATH_1_0="" GST_PLUGIN_PATH_1_0="" GST_REGISTRY_UPDATE=no GI_SCANNER_DISABLE_CACHE=yes \
		CPPFLAGS="$(CPPFLAGS)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)" CC="$(CC)" PKG_CONFIG="$(PKG_CONFIG)" DLLTOOL="$(DLLTOOL)" \
		$(INTROSPECTION_SCANNER) -v --namespace ...
```

**Comment by nirbheek** [comment]
This needs a wrapper to be implemented for running `g-ir-scanner` and such. Can't do it for this release since it'll probably break something...

My long-term plan is to add support for setting environment variables to Ninja so we don't have to use wrappers whenever we want to set an environment variable.

**Comment by QuLogic** [comment]
Can't `scripts/meson_exe.py` be used as the wrapper instead of a custom one?

**Comment by nirbheek** [comment]
Yes, and we already use it for `CustomTarget`s when we want to get the output of a command, so it's not too difficult.

**Comment by jpakkane** [comment]
There is a correct solution for this, which is to make the tools take the compiler to use as a command line argument rather than an envvar. Envvars are a bunch of hidden magic state, and thus should be minimized (and they are a pain to set up in most backends). That requires fixing compilers upstream, though.

**Comment by nirbheek** [comment]
The interesting thing here is that every backend except Ninja already supports setting per-target environment variables and I have seen codebases in the wild that rely on that.

I think that realistically we need to do both: add command line options for CC and LD and also add support for setting those environment variables in Meson.

For instance, gtk-doc already supports `--cc` and `--ld` and we already pass those, but it seems to get lost somewhere in the middle. `g-ir-scanner` doesn't, and even after adding that we would need to support the env variables otherwise it will be broken for most of the world.

**Comment by ford-prefect** [comment]
May or may not be related, but I see this on a Fedora system while running g-ir-scanner:

`gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`

**Comment by ignatenkobrain** [comment]
`gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`

that seems like something doesn't escape `,` properly...  `-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld`

**Comment by ebassi** [comment]
While I'd love to add `--cc`, `--ldflags` and friends to the introspection scanner, sadly `g-ir-scanner` uses Python's distutils to find the compiler, which uses 'CC', 'CXX' and other environment variables.

**Comment by nirbheek** [comment]
There's three possible solutions, in increasing order of difficulty, and increasing order of correctness:

* Use a wrapper for running `g-ir-scanner`

* `g-ir-scanner` could use avoid using the `distutils` module if `--cc` is passed.

* Add support for setting environment variables to ninja (https://github.com/ninja-build/ninja/issues/1002)

**Comment by nirbheek** [comment]
The way `g-ir-scanner` reads `CFLAGS`, etc is currently broken too when you have spaces in an argument: https://bugzilla.gnome.org/show_bug.cgi?id=778971
