### ISSUE TITLE
Compiler base options ('b_lundef', 'b_asneeded', etc) are not always valid for the cross-compiler

### ISSUE THREAD

**Issue by msink** [mesonbuild/meson#1037]
Have `-Wl,--no-undefined` and `-Wl,--as-needed` any meaning when cross-comliling?
In case of cross-compilation linker can't check for this correctly, I'm wrong?

I'm asking because cross-compiler to macosx ([osxcross](https://github.com/tpoechtrager/osxcross)) does not support these options, and I'm unsure is this bug of that toolchain, or bug of meson?

**Comment by QuLogic** [comment]
I don't see why the linker wouldn't be able to check such things? Certainly clang natively on OSX can do it.

**Comment by nirbheek** [comment]
This is related to #1040. Basically, right now we set the same compiler and build options on both the native and the cross compiler. We need to think of a way to fix this and make it such that only options that are common to both are applied, and that the rest can be overridden in the cross-info file.

**Comment by jpakkane** [comment]
If an option is valid for the native compiler but not cross compiler, then the cross compiler will just ignore that option (and vice versa). The question really is whether we want to have an option that is valid on both compilers but has opposite values.

I would really, _really_, **really** like to not have to support that. It complicates the implementation and common case a lot because _all_ options become duplicated. Having only one setting for forbidding missing symbols (and for all compiler options really) seems like a reasonable limitation to have.

Note that we already have a similar limitation. Many options (including lundef) is the same across languages, so you can't, for example, permit missing symbols in C++ libraries but forbid them in plain C libraries.

**Comment by msink** [comment]
> then the cross compiler will just ignore that option (and vice versa).

This one - does not:
```
meson build --buildtype release^
 --cross-file compilers\osx-clang-64.txt^
 -D b_lundef=false -D b_asneeded=false
ninja -C build
```

```
.....
ninja: Entering directory `build'
[1/2] Compiling c object hello@exe/hello.c.o
[2/2] Linking target hello
FAILED: hello 
c:/cygwin-cross/bin/x86_64-apple-darwin14-clang @hello.rsp
ld: unknown option: -O1
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Command exited with code 1
```
Full log here - https://ci.appveyor.com/project/msink/hello-c/build/job/e5ejhl0onqa9mrdo
Project - https://github.com/msink/hello-c

**Comment by msink** [comment]
As I can see, actually compiler.py have some special cases for 'b_lundef', 'b_asneeded' and -Wl,O1 on OSX, but only in native mode.
And cross-compiling for OSX is detected in environment.for_darwin()
So everything is in place, but not connected :)
