### ISSUE TITLE
Dependency found and cached via subproject prevents containing project using more constrained version

### ISSUE THREAD

**Issue by detly** [mesonbuild/meson#10414]
If a subproject uses a dependency that the containing project also uses, but permits an older version, *and that older version is found*, then the dependency cache only provides the older version which prevents the whole project from configuring.

**To Reproduce**

[Example repo here](https://gitlab.com/detly/meson-issue).

Top level `meson.build`:

```meson
project(
    'a', 'c',
    meson_version: '>=0.62.1',
)

b_proj = subproject('b')
dep_b = b_proj.get_variable('b_dep')

dep_zmq = dependency('libczmq', version : '>=4.2.2')

executable(
	'a',
	sources : ['main.c'],
	dependencies : [dep_b, dep_zmq],
)
```

`subprojects/b/meson.build` (note zmq dependency has no version):

```meson
project('b', 'c',
    meson_version: '>=0.62.1',
)

dep_zmq = dependency('libczmq')

b_dep = declare_dependency()
```

`subprojects/libczmq.wrap`:

```none
[wrap-git]
url = https://github.com/zeromq/czmq.git
revision = d4fc9d07b33bf6fa46573bc8a7afec9dbe034eb9
patch_directory = libczmq
```

`subprojects/packagefiles/libczmq/meson.build`:

```meson
project('CZMQ', 'c',
    meson_version : '>=0.62.1',
)

mod = import('unstable_external_project')

run_command(
    'autogen.sh',
    check: true
)

p = mod.add_project(
    'configure',
    configure_options : [
        '--prefix=@PREFIX@',
        '--libdir=@PREFIX@/@LIBDIR@',
        '--includedir=@PREFIX@/@INCLUDEDIR@',
    ],
)
```

Note that:
- my build machine runs Ubuntu 21.10
- this has libczmq 4.2.1 installed via apt
- that wrap file refers to a git commit that meson correctly detects as 4.2.2
- that `meson.build` patch file for libczmq successfully configures if subproject b is removed

**Expected behavior**

libczmq 4.2.2 as provided via the wrap file would satisfy both the containing project and the subproject, so I would expect that to be used **for both**, or at least attempted before bailing.

**System Parameters**
* Native build
* Ubuntu 21.10
* Python version 3.9.7 (in a virtualenv)
* Meson 0.62.1
* Ninja 1.10.1

**Comment by detly** [comment]
This seems related to #9281 but not identical.

**Comment by xclaesse** [comment]
This is the expected behavior, one a dependency is found on the system we cannot mix it with a fallback dependency later. Linking different versions of the same dependency is not going to end well. It is the first dependency() calls that wins, it is main project's responsibility to make sure it checks for the latest version first. User can also work around that by using --force-fallback-for=libczmq.

**Comment by detly** [comment]
> once a dependency is found on the system we cannot mix it with a fallback dependency later. Linking different versions of the same dependency is not going to end well

I wouldn't expect them to be mixed. In this case there is a single dependency that would satisfy both project and subproject, 4.2.2.

**Comment by eli-schwartz** [comment]
> libczmq 4.2.2 as provided via the wrap file would satisfy both the containing project and the subproject, so I would expect that to be used **for both**, or at least attempted before bailing.

This would only be possible by introducing backtracking.

Once the first dependency lookup is found and succeeds for the system version, arbitrary user-specified logic may be operating based on the found dependency's `.version()` attribute, lookup of pkg-config variables, or various other approaches. Later, changing that dependency to the subproject one, means we'd have to re-evaluate the entire build using the subproject instead.

Diamond dependencies are tricky to get right. I think the best thing you *can* do, really, is give things a bit of a manual prompt by using `--force-fallback-for=libczmq`. Another option, if you have that luxury, is to reorganize the dependency lookups so that the "first one wins" resolution mechanism prioritizes the one with the tighter constraints.

**Comment by detly** [comment]
> This would only be possible by introducing backtracking.

Might it also be possible by doing a pass for version info first, and deferring any dependent computations until it's all resolved? I'm not volunteering to design or build such a thing though, if it's just me who gets into this situation then I'll work around it as suggested.

> I think the best thing you can do, really, is give things a bit of a manual prompt by using --force-fallback-for=libczmq. Another option, if you have that luxury, is to reorganize the dependency lookups so that the "first one wins" resolution mechanism prioritizes the one with the tighter constraints.

I am in control of both containing project and subproject; my main annoyance here was having to replicate the wrap file/patch file/etc. in both container and subproject (or do something with links or whatever). The options you've provided for workarounds should be perfectly fine.
