### ISSUE TITLE
Non colored compiler output

### ISSUE THREAD

**Issue by cdecompilador** [mesonbuild/meson#10525]
**Describe the bug**
Neither ninja or vs backend produce color on their compiler warnings and errors

**system parameters**
* Windows 11 (tested in every terminal I have)
* Python 3.9.x
* Meson 0.63.0.rc1
* Ninja 1.11.0 (last version)

**Comment by eli-schwartz** [comment]
Meson has a `-Db_colorout=always` option, it defaults to always. This is respected by e.g. the GCC / clang compilers, but is wholly ignored on MSVC, which I assume is because MSVC doesn't support an option to enable or disable color.

Which compiler are you using? What is the configured value of the option I mentioned?

Note also that ninja will edit the output and delete all colors from it, if it doesn't detect an interactive terminal. It also internally runs commands using a methodology that doesn't register as an interactive terminal to the compiler (this is why Meson has to set "always" as the default).

(samurai, a ninja-compatible implementation, doesn't have this issue. I assume VS doesn't either.)

**Comment by cdecompilador** [comment]
I tried with MSVC and clang, both without color, thats why this was unexpected to me and I suspected meson instead of the compilers/ninja

**Comment by eli-schwartz** [comment]
Samurai's Windows support can be accurately described as "someone was trying to add that support but was having issues with the process creation model and took a hiatus from working on it".

I wouldn't think about it at all, I merely noted that it's an implementation issue of ninja itself.

**Comment by bruchar1** [comment]
Not sure about Windows 11, but on Windows 10, ansi colors are not enabled by defaut on the terminal. One option is to use ConEmu or Cmder instead. See https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling.

I'm using Cmder and I see colors. Therefore, I think this is not a bug, but a configuration issue.

**Comment by eli-schwartz** [comment]
I think so, yes. As I mentioned above, I think it's fundamentally either a ninja issue or a configuration issue.

I never did get a response about that setting, either...
