### ISSUE TITLE
"c_std=gnu99" fails after compiling once

### ISSUE THREAD

**Issue by yueduz** [mesonbuild/meson#10548]
"c_std=gnu99" is only valid for the first compilation after changing the source code file. After modifying the code and running "meson compile" again, the flag will be ignored.

archlinux 
meson -v：0.62.2

```
project('libaudio', ['c'],
  version : '0.1',
  default_options : [ 
                      'c_std=gnu99',
                      'warning_level=3',
                    ]
        )

cc = meson.get_compiler('c')
math = cc.find_library('m', required : false)
pipewire = dependency('libpipewire-0.3')

exe = executable('audio_stream', 'audio_stream.c',dependencies : [pipewire,math], install : true)
library('audio_stream', 'audio_stream.c',dependencies : [pipewire,math], install : true)
# test('basic', exe)

```

It was successful the first time it was compiled. When I change the c file, "meson compile" again fails with the following partial error:
```
  211 | ({                                                                              \
      | ^
/usr/include/spa-0.2/spa/utils/hook.h:247:9: 附注：in expansion of macro ‘spa_callbacks_call_res’
  247 |         spa_callbacks_call_res(&(iface)->cb,method_type,res,method,vers,##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/spa-0.2/spa/support/thread.h:109:9: 附注：in expansion of macro ‘spa_interface_call_res’
  109 |         spa_interface_call_res(&o->iface,
      |         ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/spa-0.2/spa/support/thread.h: 在函数‘spa_thread_utils_acquire_rt’中:
/usr/include/spa-0.2/spa/utils/hook.h:211:1: 警告：ISO C 不允许在表达式中使用花括号组 [-Wpedantic]
  211 | ({                                                                              \
      | ^
/usr/include/spa-0.2/spa/utils/hook.h:247:9: 附注：in expansion of macro ‘spa_callbacks_call_res’
  247 |         spa_callbacks_call_res(&(iface)->cb,method_type,res,method,vers,##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/spa-0.2/spa/support/thread.h:121:9: 附注：in expansion of macro ‘spa_interface_call_res’
  121 |         spa_interface_call_res(&o->iface,
```

When I add a useless blank line to "meson.build" and again "meson compile" it works again.

**Comment by yueduz** [comment]
[Peek 2022-06-30 10-09.webm](https://user-images.githubusercontent.com/1448159/176577743-9500d87c-a495-43e5-a54e-6dabf95e1296.webm)
I recorded a video, hoping to make the problem clear.

**Comment by eli-schwartz** [comment]
I would find it a lot easier to understand words. :)

**Comment by yueduz** [comment]
> I would find it a lot easier to understand words. :)

Very sorry my English level is almost 0, I use google translate. In the video, when the compilation fails, I just add a blank line to 'meson.build' and the compilation succeeds.

Maybe it's not a problem with the 'c_std=gnu99' flag, but something else.

**Comment by QuLogic** [comment]
There is no error in your video; just warnings. The second time it doesn't "magically work"; it just has no work to do because it's already been compiled the first time.

**Comment by yueduz** [comment]
> There is no error in your video; just warnings. The second time it doesn't "magically work"; it just has no work to do because it's already been compiled the first time.

So why did the warning go away after I put a blank line in 'meson.build'? How can I disable these warnings, since there are so many warnings that it might drown out real errors.

**Comment by obilaniu** [comment]
@yueduz In that video,
1. The first time you compiled, everything was already configured and compiled so you got `ninja: no work to do.`
2. The second time you compiled, the C source file was "changed" but `meson.build` wasn't, so Meson didn't reconfigure and `ninja` ran only the commands required to recompile your changed C source files and everything that depended on it.
You got a `-Wpedantic` warning because you set in `default_options` the maximum `warning_level=3`. Set it to `2`, `1` or `0` if you want fewer or no warnings, and **_then_ delete the build directory** so that the `default_options` array gets re-read and `warning_level=2` detected.
Or you could do this to override warnings one-by-one:
    ```meson
    if cc.get_argument_syntax() == 'gcc'
      no_warn_list = [
        '-Wno-pedantic',
      ]
      add_project_arguments(cc.get_supported_arguments(no_warn_list), language: 'c')
    endif
    ```
3. The third time you compiled, you changed `meson.build` so Meson reconfigured itself, but because you only added an empty line, the reconfiguration produced the same Ninja build commands. _Everything_ specified by these build commands **was already build and up-to-date**, so no compilers were called, no files were recompiled and no warnings were printed.

The whole time your `c_std` stayed `gnu99`, and your `warning_level=3`. Warnings get printed by the compiler, so if there's no need for recompilation, then the warnings won't get printed. Not every change to a `meson.build` causes a rebuild from scratch.
