### ISSUE TITLE
wrap fallback build-time dependencies are installed

### ISSUE THREAD

**Issue by llohse** [mesonbuild/meson#10561]
**Describe the bug**
When the `eigen3` wrap dependency fallback is used, the subproject is installed even though the files are only required at build time.
The project has a built-time dependency on eigen3, which is declared as a `dependency`.
The dependencies are wrapped via `meson wrap install eigen3`.
When running `meson setup builddir` and `meson install --destdir tmp -Cbuilddir` the eigen3 headers are installed.
This is particular annoying when building python packages with meson-python, because the headers are also included in the resulting python package.

Could be related to #2550

**To Reproduce**
```
pybind11_dep = dependency('pybind11')
eigen3_dep = dependency('eigen3', version : '>=3.4')

src_solver = ['solver.cpp']

dependencies = [py3_dep, pybind11_dep, eigen3_dep]

mod_solver = py3.extension_module('_solver',
  sources : src_solver,
  dependencies : dependencies,
  install : true,
  subdir : 'solver'
  )
```
Make sure to not have eigen3>=3.4 installed. Most LTS distributions currently only ship 3.3.

**Expected behavior**
The dependency headers should not be installed.

**system parameters**
* Rocky Linux 8
* meson 0.62.1

**Comment by tristan957** [comment]
@eli-schwartz closeable.

@llohse you can use `--skip-subprojects` to skip installing portions of subprojects.

**Comment by eli-schwartz** [comment]
meson-python now handles this better IIRC. For example you can pass meson arguments in pyproject.toml

More generally, this is a clash of expectations between some projects that want to install subprojects, and projects that don't. You can opt out of installing subprojects, but due to existing usage it's not clear we can change the default.

The topic has been discussed a few times (sorry, I don't have links handy right now) and in the long run I'd *like* to add a new kind of metaproject and have subprojects not install by default. But that will take time and thought to re-architect.
