### ISSUE TITLE
Meson crashes when calling dependency with no specified languages if a C toolchain is not installed

### ISSUE THREAD

**Issue by K4rakara** [mesonbuild/meson#10586]
**Describe the bug**
If your system doesn't have a C toolchain installed and you have a project with no specified languages, and try to call the dependency function, meson will encounter an uncaught exception and crash.

I encountered this while installing meson as an overlay package on fedora silverblue.

**To Reproduce**
- have no C toolchain installed
- place the following in `meson.build`:
```meson
project('foo',
  version: '0.1.0',
  meson_version: '>= 0.59.0',
  default_options: [ 'warning_level=2', 'werror=false' ])

dependency('openssl', version: '>= 3.0', required: false)
```
- `meson build`

**Expected behavior**
No crash, possibly an error telling the user that no C toolchain is installed.

**System Parameters**
* Native build
* Fedora Silverblue 36
* Python 3.10.5
* Meson 0.62.2
* Ninja 1.10.2

**Comment by smallwood-d** [comment]
Hi,
We opened a WIP PR - #10747.

**Comment by eli-schwartz** [comment]
Thanks for looking into that! It looks like potentially a neat and clever solution to solve this systematically.

**Comment by eli-schwartz** [comment]
And for a bit more context on this problem:

> If your system doesn't have a C toolchain installed and you have a project with no specified languages, and try to call the dependency function, meson will encounter an uncaught exception and crash.

It's actually slightly different in cause. pkg-config dependencies work fine, but some dependencies with a builtin "system" detection type do the equivalent of manual `cc.find_library()` and `cc.has_header()` checks. In such cases, whether you have a compiler installed is irrelevant, but...

... if you're missing one specified in the project setup, then Meson internally cannot reference `self.clib_compiler` to do those checks. It currently detects this ad-hoc and piecemeal in one or two custom dependency lookups which return "not-found" if there is no C-like compiler. The rest of the time, it crashes with a logic error. The proposed PR would fix this systematically.

It's not especially common for the case to come up, which is why people don't usually notice such a crash... because usually (but not always) the point of a dependency is to add it to some build target that is built with a C-like compiler.
