### ISSUE TITLE
Unusable WrapDB. SSL certificate failing 

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#10610]
**Describe the bug**

ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/releases.json with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**To Reproduce**

```
meson wrap install <some-package>
```

ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v2/releases.json with error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Expected behavior**

Secure connection does not fail

**system parameters**

MacOS

**Comment by eli-schwartz** [comment]
This is a bug in your python install having outdated or incomplete certificates.

I'm not sure how it works on macOS, but on Linux this always reliably works when the system ca-certificates are up to date (needed to use browsers), and on Windows this often fails until you visit the website using the Edge browser (which secretly installs the certificate for you because someone thought that a JIT certificate store was a good idea?).

**Comment by germandiagogomez** [comment]
Then I think I will close it. Sorry for the noise.
