### ISSUE TITLE
Cannot locate python file for `meson test` that was found during `meson setup`

### ISSUE THREAD

**Issue by tabedzki** [mesonbuild/meson#10669]
**Describe the bug**
Cannot locate python file for `meson test` that was found during `meson setup builddir`. I was trying to call a python script for a test. 
[bug_report.txt](https://github.com/mesonbuild/meson/files/9290974/bug_report.txt)

**To Reproduce**
0. Extract [mwe-cant-find-python-file-2.zip](https://github.com/mesonbuild/meson/files/9290944/mwe-cant-find-python-file-2.zip) and cd into it
1. `meson setup builddir`
2. `meson test -C builddir`

**Expected behavior**
The test to pass or fail based off the results within the python script.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
  * Plain native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * Pop OS 22.04 LTS
* what Python version are you using e.g. 3.8.0
  * 3.9.7
* what `meson --version`
  * 0.63.0
* what `ninja --version` if it's a Ninja build
  * 1.10.0

**Comment by eli-schwartz** [comment]
There's a lot of detail in this zip that doesn't seem to have anything to do with the behavior you're trying to reproduce.

**Comment by tabedzki** [comment]
Thanks Eli your quick response and feedback. I've simplified the example down further and edited the original comment.

**Comment by eli-schwartz** [comment]
It could be simplified down more. :) Those languages aren't needed (particularly I don't have cuda installed).

Anyway, the script you're using fails to run, because its shebang is `#!python3`. Meson doesn't know what kind of script it is, it simply attempts to execute it as `./tol_diff.py` and this fails.

I'd suggest using `#!/usr/bin/env python3`.

...

Independent of that, we badly handle this case, in large part because the kernel returns the same error status if the script itself doesn't exist, or the shebang interpreter doesn't exist. There's a trick that e.g. bash uses here which I could try to implement for meson, that would make the error message less confusing.

**Comment by tabedzki** [comment]
Thanks! That fixed it. Sorry about some low-level questions. I am new to meson and didn't know what are the bare minimums were for the meson.build aside from the `project` being required so I padded a bit.

--- 

Can I get your feedback on designing integration tests for meson and specifically how I should be referring to locations within the project folder? 

I want to do a integration test so when I refactor code, `meson test` compares the old prototype code's output against the refactor's. I have a folder of examples that each contain a known and expected output of a simulation in `reference.dat` (so `project/examples/ex1/reference.dat`). I want to be able to run the exe generated from my meson.build (`a.out`) and compare the resulting `data.dat` against the known `reference.dat` (`tol_diff.py`). My intended solution would be to cd into each example folder, run a short simulation and then use a small python script to compare the tolerance difference (all wrapped up in a single bash script). 

When I try using '$(pwd)/examples/ex1' in the args for test, it doesn't evaluate to a path and writing the full path defeats the purpose. 

What would be a better way implementing this sort of check?

**Comment by eli-schwartz** [comment]
custom_target and test commands aren't shell commands (especially on Windows where no bash shell exists by default). So you cannot expand shell commands using shell syntax such as `$()` (although you can do so inside the implementation of tol_diff.py I guess).

However you don't need to, because you can use `meson.current_source_dir()` or its build dir and/or project root variants.

These will calculate the correct directory locations during configuration based on the working directory that the command will eventually be run using, and pass it as a string argument. Thus preventing you from needing to hardcode anything.

**Comment by tabedzki** [comment]
oh wonderful! I've been able to get things working using this. 

I realized that probably a better idea would be to copy the `examples/*` folders into the builddir itself (`project/builddir/examples/ex1`) and have the executable run in the folder and then have a python script compare the two outputs. 
I don't see an explicit way to copy the folders into builddir. Using meson, how can achieve this goal?

I was thinking about including them as a dependency but I don't know if that would be appropriate.

**Comment by eli-schwartz** [comment]
Hmm, I'm not sure why you'd want to copy them into the build directory as they would not get updated when a `git pull` updates the sources.

Tests don't need to depend on source files anyway as they always run. (They do need to depend on compiled outputs if relevant.)

**Comment by tabedzki** [comment]
I was thinking about compiling both a debug and release version of the code and would not want them to execute within the same folder in case they overwrite each other's output file. 

I know that if I do something like have a subdir with a meson.build, it creates that subfolder within the builddir. Would it be possible then to have a custom_target to that would allow the files to get updated when a `git pull` happens?

**Comment by eli-schwartz** [comment]
My assumption is that you'd write `data.dat` to the build directory, and compare it to `reference.dat` in the source directory.

**Comment by tabedzki** [comment]
Yeah, that could work. Thanks!
