### ISSUE TITLE
Support .netrc when fetching subprojects using wrap files 

### ISSUE THREAD

**Issue by cfoch** [mesonbuild/meson#10677]
**Describe the bug**
Currently, the only way to fetch urls with authentication is `source_url = ftp://user123:pass123@foo.com/some/file.zip`

However, critical information like passwords should be ideally hidden.

**To Reproduce**
Create a ~/.netrc with the following information:
```
machine foo.com
login user123
password pass123
```

Meson ignores the ~/.netrc file, and the following error appears when fetching the subproject:
```
<urlopen error ftp error: error_perm('530 Login incorrect.')>
WARNING: failed to download with error: could not get ftp://foo.com/some/file.zip is the internet available?. Trying after a delay...
```

**Expected behavior**
Defining a wrap file with `source_url = ftp://foo.com/some/file.zip` and fetch from it should not give any error, and should authenticate with data from the ~/.netrc file.

**system parameters**
```
$ meson --version
0.63.0
```

I write in representation of [Fluendo](https://fluendo.com). We want to implement it. Do you wish this feature?

**Comment by eli-schwartz** [comment]
For context, we currently use urllib from the python standard library, which doesn't automatically do this. See `mesonbuild/wrap/wrap.py`.

The need for authentication isn't the most commonly encountered occurrence, e.g. it's not needed for the WrapDB or more generally OSS projects... It's interesting that no one has mentioned it before now for proprietary wraps (especially as our documentation describes how to wrap prebuilt proprietary binaries). Although IIRC at least some of these people are using internally networked locations and don't need authentication.

> I write in representation of [Fluendo](https://fluendo.com/). We want to implement it. Do you wish this feature?

I have no objections to this feature.

It's great news that you're willing to implement it -- because it's not a priority for me at least to implement. 😉 I'll be happy to review it though.
