### ISSUE TITLE
Installs in local/ subdir

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#10707]
meson seems to install itself in a local subdirectory when this wasn't requested. This means that `jhbuild buildone meson` creates an inaccessible version of meson. This also happens with `0.63.1`.

[jhbuild-output.txt](https://github.com/mesonbuild/meson/files/9372767/jhbuild-output.txt)

**Comment by eli-schwartz** [comment]
> meson seems to install itself in a local subdirectory when this wasn't requested.

You didn't run the meson software to install Meson though...

You ran `python3 setup.py install`, all the actual installation is handled by:
- https://github.com/pypa/setuptools/
- Debian: https://salsa.debian.org/cpython-team/python3/-/blob/master/debian/patches/sysconfig-debian-schemes.diff

Where and how files are installed is thus entirely the decision of that interaction, which is... flaky.

**Comment by hadess** [comment]
How does one use `setup.py` to install in the right directory then?

**Comment by eli-schwartz** [comment]
Debian packages have some magic performed by dh_python (I think currently `$DEB_PYTHON_INSTALL_LAYOUT`) which allows you the grand total of two options: "use local/" and "use /usr as well as dist-packages instead of site-packages". Setting that environment variable "*should*" mean it stops installing in:

```
{prefix}/local/lib/python3.10/site-packages
```
and instead installs to:
```
{prefix}/lib/python3/dist-packages
```

The alternative is micro-management. setuptools itself supports using `--install-lib /home/hadess/Projects/gnome-install/lib/python3.10/site-packages` to exactly specify the exact directory

**Comment by hadess** [comment]
> The alternative is micro-management. setuptools itself supports using `--install-lib /home/hadess/Projects/gnome-install/lib/python3.10/site-packages` to exactly specify the exact directory

That would still install the binary in the wrong place...

Consider this a request to build and install meson using meson (which given that an uninstalled `meson.py` exists isn't that ludicrous).

**Comment by eli-schwartz** [comment]
There's a similar --install-scripts option for setuptools.

As for building with Meson, we want that -- it would mean that Meson no longer has third-party dependencies that are required just to run it. I actually have a commit that adds it: https://github.com/eli-schwartz/meson/commit/83a2e6692c6c2b75c532048cc7c230beb43194ea

However this is missing dist-info metadata which Meson currently doesn't handle (and requires tomllib from CPython 3.11, sadly) so that might be a ways away... Eventually meson will build its own wheel for itself though.

**Comment by hadess** [comment]
Can you reopen this issue so I retitle it or point me to the issue that's already opened for it?

**Comment by hadess** [comment]
> Can you reopen this issue so I retitle it or point me to the issue that's already opened for it?

Hello?

**Comment by eli-schwartz** [comment]
#7863 is the general issue for adding a python PEP 517 build backend that produces python wheels.

The PoC for it would include dogfooding it by using it to build Meson itself.

**Comment by hadess** [comment]
Cool, thanks
