### ISSUE TITLE
Name collision between binaries and standard library in C++

### ISSUE THREAD

**Issue by studentenherz** [mesonbuild/meson#10713]
**Description of the issue**
When my defined binaries have the same name as something imported later there is a collision and it leads to a lengthy error.

**To Reproduce**
[Here](https://github.com/studentenherz/meson_collision_issue) is a repo that reproduces this issue.

1. Build normally, it works
2. Make some change so that ninja tries to build and try building again

**Expected behavior**
It's expected that the rebuild works, but it happens that the compiler confuses the standard library `vector` need for `#include <vector>` with my created `vector` binary.

The issue is solved by changing my binary name, to something different but I don't know why we would need to include the binaries directory when compiling.

`meson --version 0.63.1`
`ninja --version 1.11.0`

**Comment by dcbaker** [comment]
Meson includes the directory in both the source and build directory by default, because in general people want that. You can change that behavior with the implicit_include_directories keyword argument

**Comment by eli-schwartz** [comment]
(Specifically, people often generate headers for example using configure_file() to create `config.h`.)

By the way, this is why C++ as a language fundamentally sucks due to the absolutely bizarre decision to make the standard library not include file extensions in header names.

It's such a silly thing to invite footguns this way.

**Comment by Tachi107** [comment]
So I believe this can be closed?
