### ISSUE TITLE
devenv doesn't work on Windows inside MSYS2 shell

### ISSUE THREAD

**Issue by punytroll** [mesonbuild/meson#10815]
**Describe the bug**

When using Meson inside of MSYS2 on Windows, `meson devenv` doesn't seem to work.

**To Reproduce**

meson.build

```
project('test', 'cpp')
executable('app', 'main.cpp', install: true)
```

with trivial main.cpp containing an empty main().

Inside of MSYS2, with the packaged meson (0.63.1), running `meson devenv -C build app` results in `ERROR: Command not found: app`. The same goes for `meson devenv -C build app.exe`.

If I do a `meson devenv -C build` and in the resulting devenv console type `app` or `app.exe` it works.
Also, when calling `meson devenv -C build env` I can see that a path to the build directory has been added to PATH. (I'm calling it **a** path, because of the different path formats inside of MSYS2: some `/c/Windows/System32/...`, some `/home/...`, some `C:\Program Files\...`)
Also, when calling `meson devenv -C build which app` or `meson devenv -C build which app.exe` it comes back with the correct path.

I'm happy to give more diagnostics if needed.

**Expected behavior**

I would think, that app.exe should be found and executed.

**system parameters**
* Native build
* Windows inside MSYS2 environment
* Python: 3.10.6
* Meson: 0.63.1
* Ninja: 1.11.1

**Comment by xclaesse** [comment]
`meson devenv` is largely based on GStreamer's `gst-env.py` script. I see they made a fix recently that seems to be the same issue: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2397. However that MR only seems to affect when `os.name == 'nt'` which is not the case in MSYS2. I also faced similar issue recently on Linux where it seemed to be random failure to find the executable, changing the command to `./app` seems to be working but it's hard to be sure when the failure is random: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/850.

Digging a bit more this issue, I think the problem is `subprocess.call()` does not look into PATH at all unless we pass `shell=True`. Another solution would be to use `shutil.which(args[0], path=devenv.get('PATH', None))`. Not sure which way is best.

**Comment by punytroll** [comment]
Yeah, I also got the feeling, that the problem might lie in python's `subprocess.call()` or its use.

I can confirm that adding `shell=True` to `subprocess.call()` works! Maybe it actually resolves this issue without making problems elsewhere!?

**Comment by punytroll** [comment]
Placing `args[0] = shutil.which(args[0], path=devenv.get('PATH', None))` right before `subprocess.call()` also works perfectly and is probably more to the point, since `shell=True` encompasses a lot of other stuff that is not needed.

**Comment by xclaesse** [comment]
> Placing `args[0] = shutil.which(args[0], path=devenv.get('PATH', None))` right before `subprocess.call()` also works perfectly and is probably more to the point, since `shell=True` encompasses a lot of other stuff that is not needed.

Exactly, see my comment there: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2397#note_1552061.

I opted for which() but we need to be careful in the case args[0] is like `./app`, so if we cannot resolve args[0] I just leave it alone.

**Comment by punytroll** [comment]
Sounds reasonable to me. I'd love to see this merged. Thanks for the fast help!
