### ISSUE TITLE
custom_target's env parameter does not accept an instance of ExternalProgram

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/meson#10901]
**Describe the bug**

The `custom_target`'s `env` parameter does not accept an instance of `ExternalProgram`.

![imagen](https://user-images.githubusercontent.com/13498015/194442300-1a42ad8f-930b-41fc-90d1-181b17a85b34.png)

Although this is correct according to [`custom_target`'s documentation](https://mesonbuild.com/Reference-manual_functions.html#custom_target), 

![imagen](https://user-images.githubusercontent.com/13498015/194442022-48b970db-0bbf-4e5d-b88e-ae98d51b0e22.png)

this is not consistent with [`external_program`](https://mesonbuild.com/Reference-manual_returned_external_program.html#external_programfull_path):

![imagen](https://user-images.githubusercontent.com/13498015/194442127-a9cabb87-3705-4934-8f89-4f93ced3b2f7.png)

**To Reproduce**
```
extractor = find_program('capture_build_options.py', required: true)
dumpbin = find_program('dumpbin', required: true)
x = custom_target('definitions',
  output: 'i.def',
  command: extractor,
  env: {
    'NM': dumpbin
  }
)
```

**Expected behavior**
The full path of dumpbin should be inferred and stored in the `NM` environment variable for the `definitions` target.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Windows 10 21H2
* what Python version are you using e.g. 3.8.0: 3.10.0
* what `meson --version`: 0.63.2
* what `ninja --version` if it's a Ninja build: 1.10.2

**Comment by eli-schwartz** [comment]
I think whoever wrote that documentation didn't consider the case of env as part of "all cases", but was thinking of using it as part of a command invocation.

It's not strictly speaking true then either, because a program could accept an argument such as `--nm=/path/to/dumpbin` and for string joining with = there, it can't be the program object. Arguably, the program should accept an argument sequence of `--nm /path/to/dumpbin`, but some programs are ~~weird~~ inflexible.

I'm actually not sure whether or not to add support in env? It's a bit magical, and doesn't have an obvious relationship to the use case.

**Comment by amyspark** [comment]
> Arguably, the program should accept an argument sequence of --nm /path/to/dumpbin, but some programs are weird inflexible

The original script piggy backs on GNU Make's environment variables, so this is what I did to work around the issue.

**Comment by eli-schwartz** [comment]
> It's not strictly speaking true then either, because a program could accept an argument such as `--nm=/path/to/dumpbin` and for string joining with = there, it can't be the program object. Arguably, the program should accept an argument sequence of `--nm /path/to/dumpbin`, but some programs are ~weird~ inflexible.

Since it's clearly bogus to claim that "passing the object itself should work in all cases", as that cannot and will not ever handle `--nm=/path/to/dumpbin` with required joining via the equals sign...

... I think the documentation should be "fixed" either way to align with reality, which is that it should work in "most" cases, not "all" of them. This would also cover the case of env, because the docs would no longer imply that it works in "all" cases that a string is a valid argument.

It also would cover the case of `message(dumpbin)`, and more.
