### ISSUE TITLE
Using conan for package management, meson cannot identify gtest environment via .pc files

### ISSUE THREAD

**Issue by roninracer** [mesonbuild/meson#11342]
**Describe the bug**
We're using conan (not configured for cmake) to pull in packages from jfrog artifactory inside gitlab. We have no issues with pulling in the gtest package and having pkg-config generate the appropriate .pc files (like gmock_lib.pc). However we are using meson to build our app which also works. We additionally want to build unit test programs that are linked against the gtest and gmock libs, but meson can't figure out the environment to pull them in.
I have scoured the docs and attempted various solutions from online sources with no positive result. 
We also do not want to use wrappers or meson's package management in this scenario. 

Could someone recommend the proper or best practice method to parse the .pc files (likely using pkgconfig) so I can build these unit test programs?

**To Reproduce**
our meson.build file is pretty basic, but isn't representative of the situation as several attempts to solve this issue were made, like using subprojects, pkgconfig, etc.

**Expected behavior**
Some methodology to allow meson to parse the .pc files created by conan's pkg-config for use in building code that links packages installed by conan. 

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
- Native build in Red Hat Linux docker instance.

* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
- registry.access.redhat.com/ubi8/ubi:latest

* what Python version are you using e.g. 3.8.0
- python39-3.9.13-2

* what `meson --version`
- meson-0.63.3 

* what `ninja --version` if it's a Ninja build
- ninja-1.11.1

**Comment by bruchar1** [comment]
I'm not sure to understand your problem. 

Normally, you simply need to declare a dependency: `gtest = declare_dependency('gtest')` (or `gtest_main` if you need gtest to provide the main() function), and to put in in the `dependencies` list of you executable.

**Comment by eli-schwartz** [comment]
> Some methodology to allow meson to parse the .pc files created by conan's pkg-config for use in building code that links packages installed by conan.

I don't know what you mean by "to parse". If I had to guess, the issue is finding it, not parsing it? If you leave aside Meson for a moment, and run this:

```
pkg-config --cflags --libs gtest
```

What does it say? For me, this is:
```
$ pkg-config --cflags --libs gtest
-DGTEST_HAS_PTHREAD=1 -lgtest -lpthread 
```

But it's possible for you, it says:
```
$ pkg-config --cflags --libs gtest
Package gtest was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtest.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtest', required by 'virtual:world', not found
```

Meson logs this general sort of information in builddir/meson-logs/meson-log.txt (meson in git master logs the stderr, stable versions of Meson only log the command that was run).

I'm assuming conan installs to some kind of dedicated environment, and you'll probably have to add that dedicated environment's pkgconfig directory to the search path. Once that is done, `pkg-config --cflags --libs <name>` will work, and so will Meson.

**Comment by bruchar1** [comment]
If your problem is how to tell meson where to find the conan generated pc files, then its more a conan thing that a meson thing...


Your conanfile.py should be something like that:

```
from conans import ConanFile
from conan.tools.gnu import PkgConfigDeps
from conan.tools.meson import Meson, MesonToolchain

class MyPackage(ConanFile):

    ...


    def generate(self):
        pc = PkgConfigDeps(self)
        pc.generate()

        tc = MesonToolchain(self)
        tc.generate()

    def build(self):
         meson = Meson(self)
         meson.configure(build_folder="build")
         meson.build()

```

The MesonToolchain generator will generate the meson config needed to configure your project.
The meson.configure() will call `meson setup` using that generated config file.

**Comment by roninracer** [comment]
Thank you all for your responses.

So it turns out that the 'dependency()' function in meson was what I needed for it to properly identify the .pc files/gtest environment so my test code could link properly. 

We didn't use the MesonToolchain generator for this project as we configured manually like so:
```
    def build(self):
        """Build package using Meson."""
        meson = Meson(conanfile=self, backend="ninja", build_type=None)
        meson.configure(
            # args=None,
            # defs=None,
            # source_folder=f"{self.source_folder}/src",
            build_folder="build",
            pkg_config_paths=None,
            # cache_build_folder=None,
            # append_vcvars=False,
        )
        meson.build(args=None, build_dir="build", targets=None)
```


My test code was in a subdir which had it's own meson.build file. I had spent a lot of time trying to see/print out the environment when things weren't working so I could kind of see the disconnect between conan and meson. 

It is clear from the generated .pc files and the conanbuildinfo.txt that conan had set up the environment for gtest along with the specific install paths for the package. It just wasn't clear how to get meson to read any of that for the build. 

I still don't know exactly how or why the 'dependency()' function worked when all other methods I tried did not, but I had found this issue which led me to the clue:
https://github.com/mesonbuild/meson/issues/4876

my functioning test/meson.build file ended up looking like this:
```
test_dependencies = dependency('gtest')

test_source_files = [
    'test.cpp'
]

test_executable = executable(
    'DEV-TESTS',
    test_source_files,
    dependencies: test_dependencies,
)

test('test', test_executable)
```
Again, thank you all for your help!

**Comment by eli-schwartz** [comment]
> I still don't know exactly how or why the 'dependency()' function worked when all other methods I tried did not

I'm not entirely clear on what you tried (the original post doesn't include e.g. a sample meson.build indicating the test setup you used) but in general `dependency()` is the correct way to get any external, well, dependencies. It is a unified interface for looking up both pkg-config and cmake packages and also supports seamless subproject fallbacks via https://mesonbuild.com/Wrap-dependency-system-manual.html

Unfortunately you cannot always use that, because some dependencies don't provide pkg-config files (and aren't built with cmake / don't provide a cmake program that can be used to run cmake and print out the flags inside that cmake program). In that case, you can use `cc.find_library()`, which is the equivalent of adding `-lfoo` in a Makefile instead of using `$(shell pkg-config --libs foo-project)`.
