### ISSUE TITLE
`run_command` too strict in determining interpreter

### ISSUE THREAD

**Issue by stefanv** [mesonbuild/meson#11356]
**Describe the bug**

Calling `run_command('my_util.py', check: true).stdout()` fails when the script contains:

```
#!python
...
```

Using `#!/usr/bin/env python` works, but we need `#!python` (I think?) to be compatible with  Windows.

Presumably, `run_command` executes in the current env, so should find `python` (the script runs from the shell).

**Expected behavior**

Command should execute, instead of Meson printing:

```
meson.build:1:0: ERROR: Could not execute command ...
```

**system parameters**
Linux, Python 3.10, meson 1.0.0

**Comment by eli-schwartz** [comment]
> Using `#!/usr/bin/env python` works, but we need `#!python` (I think?) to be compatible with Windows.

Nope, Meson will handle detecting an "env" shebang for you on Windows, but Windows itself simply ignores the entire shebang line and doesn't use either version.

Note that `#!python` is technically an invalid shebang -- it cannot be used by any system, you cannot run it directly on Linux. And if the script is executable, Meson doesn't try to parse the shebang for you on Linux, because it assumes it is already runnable.

So, disregarding Meson, `#!python` with an executable script is broken on Linux, and completely pointless on Windows.

**Comment by stefanv** [comment]
OK, I've made a patch to use /usr/bin/env. Thanks, @eli-schwartz!
