### ISSUE TITLE
meson fail with 'StopIteration'

### ISSUE THREAD

**Issue by yurivict** [mesonbuild/meson#11361]
**Describe the bug**
Build of meson-based projects fail when some extra python packages are installed:
```
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==1.0.0', 'console_scripts', 'meson')())
  File "/usr/local/bin/meson", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**To Reproduce**
Build fails when many other Python packages are installed. It is unclear what exact package causes this problem.

**system parameters**
* what operating system: FreeBSD 13.1
* Python-3.9

```
$ meson --version
Traceback (most recent call last):
  File "/usr/local/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==1.0.0', 'console_scripts', 'meson')())
  File "/usr/local/bin/meson", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by eli-schwartz** [comment]
This code comes from setuptools, not meson.

**Comment by yurivict** [comment]
Lines 33 and 25 in /usr/local/bin/meson come from meson.

**Comment by eli-schwartz** [comment]
Since you don't seem to be interested in my reasons for saying the code comes from setuptools -- only interested in telling me I am wrong -- I cordially invite you to point me to the exact lines in the meson repository that you are referring to.

**Comment by yurivict** [comment]
You didn't provide any reasoning for your statement.

Every line in the error message comes from Meson.

And ```StopIteration``` is a Python error message.

**Comment by eli-schwartz** [comment]
I refer you to my above comment.

**Comment by yurivict** [comment]
Thank you very much.

Your involvement is incredibly unhelpful.

**Comment by eli-schwartz** [comment]
I told you that this code comes from setuptools, but you felt the need to correct me in order to inform me that actually I'm wrong and the code comes from meson.

This is an easy difference of opinion to resolve, since you're so sure that the code is part of the meson codebase despite disclaimers to the contrary -- point to the code and prove it beyond all shadow of a doubt.

At any time, you're welcome to stop ***informing*** the meson developers that they don't know what code is present in the meson codebase, and instead ask them to clarify what they mean. Afterwards, you're still going to end up visiting setuptools to ask for help.

...

Either way, I can't help you with your problem if I don't understand what's causing it. But on the off chance that I've correctly identified which project the code came from, I've been very helpful indeed -- I've directed you how to find the people best suited to answering what's going on.

**Comment by yurivict** [comment]
meson fails. And you close the issue. How is this reasonable?

**Comment by eli-schwartz** [comment]
I'm not sure I understand. There's many reasons that Meson could fail, but I'd still close the issue, because meson isn't responsible.

For example, Meson could fail because: the system doesn't boot, python segfaults, python fails with an Exec format error (because python was built for the wrong operating system or architecture), python fails because of ModuleNotFoundError when trying to import the stdlib...

In this case, Meson fails because Meson itself was unable to be started to begin with. Some setuptools code couldn't find Meson to start Meson.

It's not a Meson bug (unless you don't believe that the code is setuptools code, apparently), so there's literally nothing I can do. I can't even explain what's going on, because I don't know.

The only thing I know is the name of the project that *can* explain what's going on -- and maybe even fix it. I've given you the name of that project, but you don't believe me.

What exactly do you want here? Do you want me to leave the bug report open, to symbolize that the problem is unsolved, while also tagging it with labels for "invalid" and "not our bug", to symbolize that the ticket itself should be transferred and refiled to another project except that no one here has the right github permissions to administrate bugs for that other project?

What practical difference would that make?

**Comment by yurivict** [comment]
So this leaves meson just broken.

**Comment by eli-schwartz** [comment]
No.

Meson documents 3 different ways to use it, and a fourth which is Windows specific: https://mesonbuild.com/Getting-meson.html

If you have non-Meson problems which have a side effect of causing Meson to not work when using methods comparable to option 3 (that is, using the PyPA-compliant setup.py) *and* you don't want to seek answers regarding what is going wrong...

... then you are more than welcome to use option 1 or option 2.

Even if that weren't the case, "Meson" isn't broken, and even "Meson on FreeBSD" isn't broken. But "Meson on Yuri's system" may very well be broken. This is very sad, but also very much not actionable because we don't know what the problem is and we also can't even reproduce your issue.
