### ISSUE TITLE
mtest: emojis render as white squares

### ISSUE THREAD

**Issue by trhd** [mesonbuild/meson#11413]
Not all fonts implement moons/earth, scissors and triangles. Seeing emtpy space or even worse, white squares, in their place make the test log ugly and misaligned. Suppose some dependency could also be added to some fontpack but not sure about that.

There is currently a check for character encoding that disables these emojis in case the encoding is not UTF but that doesn't take into account that many fonts don't implement e.g. scissors.

Arguably the emojis bring very little to the table and e.g. their ascii versions (already in the code) could just be used instead.

![image](https://user-images.githubusercontent.com/11553916/219631873-95dfd9b3-d3f5-4778-bff4-d1b42e945f0a.png)

**Comment by tristan957** [comment]
This is a good change imo. Emojis are generally worthless for stuff like this anyway.

**Comment by eli-schwartz** [comment]
Dates back to commit 111f22a4f8c45e2191caeed42de739953a41d4fa, see e.g. https://github.com/mesonbuild/meson/pull/8200#issuecomment-760805455

> Not all fonts implement moons/earth, scissors and triangles. Seeing emtpy space or even worse, white squares, in their place make the test log ugly and misaligned. Suppose some dependency could also be added to some fontpack but not sure about that.

I refuse to be the defender of fancy emojis in a terminal console, and I ***definitely*** do not consider "add a dependency to some fontpack" to be a viable approach, so there is that. :)

**Comment by tristan957** [comment]
Summoning @bonzini for thoughts 😄

**Comment by bonzini** [comment]
The cropped image is not clear and does not show whether the font has the triangle `▶`, but apparently it does have the horizontal line. I'm curious what font is this, since the output has been in Meson for more than two years and this is the first report.

I disagree that the graphical symbols are worthless. The scissors or triangles are simple but helpful visual cues that  _do_ add something in day-to-day use. Even for the emoji, of course I am not extremely attached to them but they were not added lightly. I switched from one version to another in day-to-day development *of projects using meson* for some time, before deciding to go for it because the ASCII spinner[1] was too subtle and didn't stand out enough.

[1] right now it is `..` `:.` `.:`, but when developing the `meson test` improvements I also tried the rotating bar `[\]` `[-]` `[/]` `[|]`.

**Comment by eli-schwartz** [comment]
I suppose one possibility might be, detecting whether any available fonts actually provide the character. This *can* be done programmatically, if you assume on Linux that fontconfig is installed:
```
fc-list ':charset=1f317'
```

But I don't know how to do it for Windows, and assuming fontconfig is installed isn't even guaranteed on Linux, even if libfontconfig.so is installed as a system dependency because you have GUI frameworks installed.

**Comment by xclaesse** [comment]
My 2 cents is that empty space or square is not that bad, still perfectly readable. IMHO it would be overreacting to remove good looking display to everyone just because a small minority (1 report in 2 years) experience a slightly less nice looking output. There is no functional bug here.

**Comment by tristan957** [comment]
Perhaps a solution is to just add a `--no-emoji` option to `meson test` or something.
