### ISSUE TITLE
Better integration with meson-python

### ISSUE THREAD

**Issue by FFY00** [mesonbuild/meson#11462]
Hi, think one of the main quirks of using Meson for Python packaging is that currently, you must use meson-python to build your artifacts. However, Python artifacts are limited in scope in what and where they can install. This leaves us in a weird position, if you install your package with Meson directly, you are missing the Python package metadata, which is required for the project to be picked up an as installed Python package, if you use meson-python to build the Python distribution artifacts, you lose support for some things, among other issues (I can expand on this if required, but I don't think it's very relevant to get into it right now). Being able to install via Meson directly, would be very useful for distributors in certain situations.

My proposal would be for Meson to check for a `pyproject.toml` file, and if it is present and specifies meson-python as the build backend, Meson would call meson-python to generate the Python metadata. meson-python would expose an internal API specifically for Meson to use for this purpose.
Regarding dependencies, this can be implemented purely as an optional feature.

Does this sound reasonable?

**Comment by eli-schwartz** [comment]
This can actually work already:

```meson
custom_target(
    output: 'foo-@@@.dist-info'.format(meson.project_version()),
    command: [py, '-m', 'mesonpy', '--flag-that-makes-distinfo', '--outdir', '@OUTDIR@'],
    install: true,
    install_dir: py.get_install_dir(),
)
```
The interesting trick here is that you can actually output a directory from a custom_target, and it mostly works as far as ninja is concerned. `meson install` has support for this use case by detecting whether custom_target outputs are a file or directory, and treating directories the same as install_subdir.

**Comment by FFY00** [comment]
Interesting. That also needs a guard, to avoid installing when it's being built via meson-python.

While that's a reasonable workaround, support still needs to be added to every project manually, which in practice I think most projects won't do it, and distributors won't have this feature available. So, I still think feature makes sense to have in Meson. Please let me know how yall feel about it.

**Comment by eli-schwartz** [comment]
Since they'd both install the exact same files it may not actually need a guard. The guard could also be done from either end as the custom target would be in the introspection files.

**Comment by xclaesse** [comment]
Maybe meson's python module could have a method to wrap that custom target?

**Comment by FFY00** [comment]
Yes, that's a reasonable option too IMO.

**Comment by eli-schwartz** [comment]
What additional utility does this provide, though?

I don't like the idea of `git add`ing a file not named meson.build, causing Meson to suddenly generate new installation rules, especially if we then have to look up additional dependencies and check which *version* they are, even. So IMO it does need to be an actual function call, and projects could define suitable minimum dependencies for the custom_targets they use. But if that's the case, what's the difference between copy-pasting a custom target from the meson-python docs, vs. making a meson module function?

As a fully user-defined custom_target, this can be implemented by individual projects with a new release of meson-python, without ***also*** waiting for a new feature release of meson, and meson doesn't get locked into providing a DSL method for the next half decade. Since meson-python has significantly smaller scope, it's a lot more free to bump the major version if it wants to delete an API.

Since I do expect meson to gain builtin functionality along these lines, I'd like to avoid locking us into providing multiple ways to do the same thing. And it's probably not going to be an exactly equal implementation, for example with regard to mesonpy-specific settings in pyproject.toml, or just in general the idea of pin-compatible dynamic dependencies. (We are not dragging in a non-stdlib dependency on `packaging.requirements` for this, even if it makes a lot of sense for meson-python to do so.)

**Comment by FFY00** [comment]
> I don't like the idea of `git add`ing a file not named meson.build, causing Meson to suddenly generate new installation rules, especially if we then have to look up additional dependencies and check which _version_ they are, even.

Sure, that's reasonable. Since you've expressed interest of getting Meson to be able to build wheels, etc. in the future, I thought this was a good first step for that, but I might have mistaken how exactly you want to achieve it.

> But if that's the case, what's the difference between copy-pasting a custom target from the meson-python docs, vs. making a meson module function?

It requires you to either have a dynamic version fetched from Meson, or to add an extra target to calculate that. On top of that, it's just more common boilerplate.

There are many similar examples of language integrations in the other modules (eg. https://mesonbuild.com/i18n-module.html#i18nitstool_join).

I... am just tired. It seems like every time I try to push anything upstream, you provide significant resistance to it, and I don't understand why. I don't know, maybe I am mistaken, but to me, it seems like you actively like to argue, often using small technicalities for that and disregarding practicality. It seems like your goal isn't really to solve the issue at hand.
Does Meson need to provide a custom target for this? No, of course not, but it is useful, and it is functionality that, as you said, you expect Meson to eventually get natively. So why make this kind of weak-ish arguments ("what's the difference between copy-pasting a custom target...") when you acknowledge the value, instead of trying to find a solution where Meson tries to bridge the gap with meson-python?

I have already gotten drained from trying to interact with you here once, and stopped contributing, since then I've been very reluctant from interacting with this repo :confused:

> Since I do expect meson to gain builtin functionality along these lines, I'd like to avoid locking us into providing multiple ways to do the same thing. And it's probably not going to be an exactly equal implementation, for example with regard to mesonpy-specific settings in pyproject.toml, or just in general the idea of pin-compatible dynamic dependencies.

Since we've started discussing this, you've used that as a justification to shut down multiple proposals, yet during the two years I have been working on this, no progress was made in Meson's side. We currently have something that works, and are proposing a significant enhancement that can work *today*, and will be useful to people *today*.

meson-python is even in the mesonbuild organization, we can coordinate... we can make sure we implement this in a way that makes sense for Meson for eg. (eg. skipping the specific settings that Meson will not want to support). Honestly, this was one of the things I was hoping to improve once meson-python joined the organization, but I guess not.

Given that there are no current plans for Meson to provide that functionality, I don't even see what's the issue of providing a method for meson-python now, and then deprecate it later when/if Meson finally implements this functionality (not saying this is necessarily the best option). If users do it via a custom target, they'll want to migrate anyway, so you're not saving churn to the users.

**Comment by eli-schwartz** [comment]
> It requires you to either have a dynamic version fetched from Meson, or to add an extra target to calculate that. On top of that, it's just more common boilerplate.

The requirement for a dynamic version fetched from Meson is there whether Meson produces the custom target internally or not. If the version is updated, Meson would have to reconfigure from scratch in order to recalculate the outputs, which means either bumping the version twice, once in meson.build and once in pyproject.toml, or doing a full reconfigure on ***all*** modifications to pyproject.toml, or just without knowing that it has to do so and going out of sync with meson-python.

But for example SciPy and scikit-image both do dynamic versions already, anyway. I have helped several other projects with porting to Meson, and from recollection, I think they all tended to have dynamic versions. Some use `python -m setuptools_scm`, some read the version from `__init__.py`. It's pretty common to want to single-source the version across the build system *and* the project source code, and usually that means either reading the version from the source code (requires meson), or configure_file() to write it *into* the source code.

(I really wish that pyproject.toml supported reading versions from a file, the way setuptools, meson, cmake, autotools all do. It could just be a VERSION.txt file, it doesn't have to be setuptools `attr:`.)

> There are many similar examples of language integrations in the other modules (eg. https://mesonbuild.com/i18n-module.html#i18nitstool_join).

Have you looked at the implementation for that? Not only isn't it a one-line custom_target, it does things that are *literally* impossible to do without a dedicated script that knows about meson's backend layout. That includes copying all compiled `*.mo` catalogs to a tempdir because the itstool program requires arbitrarily filename patterns. But the design is good (within the constraints of what itstool needs) and the function is expected to be useful as-is, forever.

It's not remotely a similar example. But what I really want to focus on is the fact that itstool_join is an unchanging API that makes sense to support for the next 10 years.

> We currently have something that works, and are proposing a significant enhancement that can work _today_, and will be useful to people _today_.

And again, it seems to me that it's a one-liner to do it with a custom_target, which does indeed work today (and requires less tight integration at the library level). So I would like to see that attempted first, rather than immediately committing to Meson's first-ever case of requiring an extras_require for functionality more significant than an optional progressbar.

I don't get why that's such a problem. :(

**Comment by FFY00** [comment]
By your own admission, you already expect Meson to get native support for this in the future, so I really don't understand the issue with at least trying to collaborate with meson-python to provide an initial version of the feature while Meson doesn't implement it itself. I've expressed willingness to try to find a way that meson-python could provide this in a way the Meson team is okay with (eg. removing features that Meson is not willing to commit to supporting at the moment), so that we can get this to work right now.

Instead, this is just another thing that gets shut down in favor of a nonexistent feature that has been theorized for over two years.

*sigh*

I'll just provide a helper directly in meson-python that distributors can use to install the missing metadata. If upstream projects want to use it in Meson as a custom target with the complexity it requires, they can do so. This is just more work for everyone else involved.

I'm not even sad about the position on this issue, it's just this noncollaborative way you provide and take feedback. I've known you for over 5 years, and over all that time you haven't managed to learn, even with all the effort people to try to help with you improve and understand. How many more projects will have to make you step away before you learn? :disappointed:

At this point, I'm just tired, I'll just go back to avoiding interacting with the Meson upstream and take deal with whatever consequences that has on my day job.

**Comment by xclaesse** [comment]
> What additional utility does this provide, though?

Not much, but we have tones of methods in modules that just wrap a simple CustomTarget. It has the advantage of being more explicit and it is also a way to get the feature documented. Feels like `python.generate_dist_info()` to invoke meson-python is nicer than the custom_target() suggested in https://github.com/mesonbuild/meson/issues/11462#issuecomment-1445421378.

I also fully expect meson-python to be someday merged within meson itself, in that case generate_dist_info() implementation can be changed without requiring everyone to change their custom_target().

Sure it means some kwargs could be added/deprecated over time if some features changes, but that's fine, we do that all the time.

That being said, as far as I'm concerned, it is not a big deal as there is nothing currently impossible. It's just syntactic sugar AFAIK.

**Comment by FFY00** [comment]
> Feels like `python.generate_dist_info()` to invoke meson-python is nicer than the custom_target() suggested in [#11462 (comment)](https://github.com/mesonbuild/meson/issues/11462#issuecomment-1445421378).

Please note that the provided example only works for projects that have a dynamic version in `pyproject.toml`, where version string is fetched from Meson. In cases where the version is specified in `pyproject.toml`, we need to either have another target to determine the `.dist-info` directory name, or set the Meson version dynamically by reading from `pyproject.toml`.

Eli even described the issues with this, so I really do not understand the opposition.

> I also fully expect meson-python to be someday merged within meson itself, in that case generate_dist_info() implementation can be changed without requiring everyone to change their custom_target().

As development is happening in Meson right now, I doubt this, given the amount of opposition on adding external dependencies for optional features I've gotten in the past. When I started writing meson-python, my goal was to implement it directly in Meson (see #9128).
Everything so far has been shutdown because it wasn't the technically optimal solution, without very little compromise, while the *technically optimal* solution never came.

To be honest, I think the best option for the community at this moment would be to try to integrate meson-python with Meson. That would allow Meson to provide features implemented by meson-python, with the compromise of having this optional dependency on meson-python. Just like Meson integrates with GNOME via a custom module, the same could be done for meson-python. This lets Meson developers focus on Meson itself, while leaving the Python packaging integration expertise to the meson-python developers.

**Comment by xclaesse** [comment]
Hm, maybe I'm confused between mesonpep517 and meson-python, they do the same thing?

> we need to either have another target to determine the `.dist-info` directory name, or set the Meson version dynamically by reading from `pyproject.toml`

If we add `python.generate_dist_info()` it shouldn't be too hard to have a `version` kwarg and if omitted read it from toml file.

**Comment by FFY00** [comment]
> Hm, maybe I'm confused between mesonpep517 and meson-python, they do the same thing?

Yes, but mesonpep517's approach is a bit limited, and I think at the moment meson-python is significantly more mature.

> If we add `python.generate_dist_info()` it shouldn't be too hard to have a `version` kwarg and if omitted read it from toml file.

This is only an issue when using a custom target, if we add something like `.generate_dist_info()` we'll have metadata already, so we know the `.dist-info` name.
