### ISSUE TITLE
cmake as backend

### ISSUE THREAD

**Issue by msink** [mesonbuild/meson#1147]
Maybe crazy idea, but - is it possible to use cmake as intermediate tool for generating backends like msvc and xcode?

This way meson can concentrate on just two backends - ninja and cmake, and let cmake handle all weird low-level details of all other backends in the world.
They just have much more manpover for this.

**Comment by ignatenkobrain** [comment]
it's almost impossible...

**Comment by jpakkane** [comment]
This has been though of before, see #668.

**Comment by nirbheek** [comment]
Going to close it for the same reasons as #668. :smile:

Also, I don't think this would reduce the work required to support VS and XCode backends at all since it's actually more complicated to support CMake syntax than the VS or XCode syntax.

It's also more likely to be buggy with. for instance, quoting of spaces and `"` in strings (see what we already have to do in the VS backend[1]) since you now have to pass through one more parser on the way to the final build system.

1. https://github.com/mesonbuild/meson/commit/d8b9b12adbd2fa04f40ea2823929acc41f0a8003
https://github.com/mesonbuild/meson/commit/2d05008956dedbfb4b6c8b690c4f025451aea587
https://github.com/mesonbuild/meson/commit/bfa25fc1d344950751c8b0302ef289de9a23a749
