### ISSUE TITLE
g++8 does not work with warning-level=everything

### ISSUE THREAD

**Issue by neheb** [mesonbuild/meson#11517]
**Describe the bug**
```
g++-8: error: unrecognized command line option ‘-Wattribute-alias=2’; did you mean ‘-Wattribute-alias’?
```

**To Reproduce**
env CXX=g++-8 meson -Dwarning-level=everything
**Expected behavior**
compilation
**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 20.04 GitHub CI
* what `meson --version`
1.0.1

ping @drobilla 

https://github.com/neheb/npupnp/actions/runs/4380043090

**Comment by drobilla** [comment]
Hm, whoops.  I didn't realize GCC changed the "value" of warnings over time.  I'll take a look.

**Comment by neheb** [comment]
Seems 7 is fine: https://github.com/neheb/npupnp/commit/9ab61b3cc2a93040767ae264a8bd26feeac9b499

**Comment by drobilla** [comment]
Seems like it was changed by 79a2c4281c7dcaa6a138d24fd037c62453a12bde before GCC 9.  Judging by the changelog, it seems this was a bit of a screw-up.  Since we don't really care about some specific warning definitely being used in some version, I think the easy solution here is to just move the warning up a bit to 9.1.

**Comment by drobilla** [comment]
Untested fix here: https://github.com/mesonbuild/meson/pull/11522
