### ISSUE TITLE
Relative prefix path

### ISSUE THREAD

**Issue by OlafvdSpek** [mesonbuild/meson#11541]
`meson.build:1:0: ERROR: prefix value 'dist-test' must be an absolute path`

Could meson resolve a relative prefix path path (`-Dprefix=dist`) relative to the current working directory if specified on the command line, like it does with build dir?

**Comment by eli-schwartz** [comment]
Expected usage of a build directory is to be relative (in virtually all cases), whereas prefix is about installation patterns and most typically is not relative to the current source directory.

So I don't think it would be safe to allow relative values here.

**Comment by xclaesse** [comment]
I think you're misusing --prefix, you probably want to install into a destdir. `meson install --destdir dist` will install into builddir/dist/.

**Comment by OlafvdSpek** [comment]
> I think you're misusing --prefix, 

Maybe I am. The prefix concept, specifying the install location at configure time, is a bit weird IMO and easy to misuse.

**Comment by eli-schwartz** [comment]
Weird and easy to misuse?

It's how literally all build systems work. In fact, it's a semantic error to specify it at install time, and if you do so then lots of software will completely fail to start, because they use compile-time C/C++ defines with the prefix in order to tell the software where to find various runtime resources.

**Comment by OlafvdSpek** [comment]
> It's how literally all build systems work.

Haven't encountered it on Windows (myself)..

> because they use compile-time C/C++ defines with the prefix in order to tell the software where to find various runtime resources.

Not saying you're wrong. 
Still saying deciding the final destination before configuring and building isn't the only choice you could make.

> Even if it were possible to specify it at install time meson would still mandate that it be an absolute path and not a relative one.

Fair enough. The request to support a relative path is to support the case where you'd like to 'install' in / near the source dir and not globally in `/usr`.

**Comment by eli-schwartz** [comment]
> Haven't encountered it on Windows (myself)..

It's how, for example, cmake works.

On Windows it may not matter so much since it's pretty common to not run installation steps, but rather produce MSI/setup.exe installer bundles directly from the build directory. Still, it's entirely possible to run "ninja install" on Windows with cmake, and install the cmake-built software to "C:/Program Files/my-project-name" by default.

CMake allows you to change it both at build time and install time, which is dangerous because it doesn't recheck the value. On the other hand, due to caching it also doesn't reliably recheck the value if you set it by re-running the configure step with a different value (that applies both to compile definitions and install locations, truly the worst of both worlds).

Depending on how well you know the exact project you're building, you may be able to get away with it -- relocatable projects do exist.

> The request to support a relative path is to support the case where you'd like to 'install' in / near the source dir and not globally in `/usr`.

I'm not entirely sure I understand the semantic intention of "install in the root of the filesystem near the source dir".

That being said, your original comment made no note of the root of the filesystem, just the source dir... So maybe you can just use `meson setup --prefix=$PWD/dist-test`? Assuming that using `meson dist` with its automatic end to end verification of producing/building/testing/installing of a dist tarball isn't sufficient.

**Comment by OlafvdSpek** [comment]
> I'm not entirely sure I understand the semantic intention of "install in the root of the filesystem near the source dir".

My bad, I meant "/" as in "or", not as in root of fs.
 
> That being said, your original comment made no note of the root of the filesystem, just the source dir... So maybe you can just use `meson setup --prefix=$PWD/dist-test`? 

That'd work, thanks!

> Assuming that using `meson dist` with its automatic end to end verification of producing/building/testing/installing of a dist tarball isn't sufficient.

I'll have a look.

**Comment by eli-schwartz** [comment]
> My bad, I meant "/" as in "or", not as in root of fs.

Ohhh... sorry, that was dumb of me. :P
