### ISSUE TITLE
1.01 fails to build gnome component: gnome-bluetooth-3.34.5

### ISSUE THREAD

**Issue by JonathanVQP** [mesonbuild/meson#11652]
I saw this issue back in the 0.60 version in previous bug reports. However, when I updated my meson to the latest git version (1.01), it appears that "function does not take positional arguments" error still remains when I tried to compile gnome-bluetooth-3.34.5. Is this still a bug?

**Comment by eli-schwartz** [comment]
The function does not take positional arguments, so, did you try updating gnome-bluetooth instead?

**Comment by JonathanVQP** [comment]
@eli-schwartz There appears to be two versions of gnome-bluetooth: 3.34.5 and 42.5. I don't get the meson error with gnome-bluetooth 42.5 but I do get it with gnome-bluetooth 3.34.5. However, Budgie control center complains that it needs gnome-bluetooth-1.0 lib from gnome-bluetooth-3.34.5 and not gnome-bluetooth-3.0 lib from gnome-bluetooth 42.5 so I am stuck with gnome-bluetooth-3.34.5 instead.

**Comment by eli-schwartz** [comment]
> There appears to be two versions of gnome-bluetooth: 3.34.5 and 42.5

There are 117 versions of gnome-bluetooth, but only the latest version -- 42.5 -- is supported by them. You aren't using a different version, so much as you are using an ***old*** one.

I don't know what the reason Budgie has for only supporting the old one, but likely because they haven't ported "yet". That's not unreasonable, but it does mean that Budgie depends on end of life software right now.

You will need to checkout gnome-bluetooth 3.34.5 and then backport https://gitlab.gnome.org/GNOME/gnome-bluetooth/-/commit/755fd758f866d3a3f7ca482942beee749f13a91e with the command:
```
git cherry-pick -x 755fd758f866d3a3f7ca482942beee749f13a91e
```

This will allow you to build gnome-bluetooth 3.34.5

Now that meson reached version 1.0, semver says we'll be preserving compatibility even if the project itself had a bug for using undocumented stuff that wasn't supposed to be accepted. But back during 0.60, that guarantee was not available. :(
