### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by verghiskoshi** [mesonbuild/meson#11650]
verghis@verghis-Latitude-E5570:~/dpdk-stable-22.11.1/build$ sudo ninja install
[sudo] password for verghis:          
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-internal__install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip

Versions of Meson newer than the one installed with dpkg, learned to catch this error and be more descriptive of the cause. However, upgrading the version with pip can't fix or upgrade the version installed by dpkg.

**Comment by verghiskoshi** [comment]
I'm using meson1.0.1 which seems to be the latest:


Releases · mesonbuild/meson
https://github.com › mesonbuild › meson › releases
Dec 23, 2022 — Latest. 1.0.1. Assets 8. meson-1.0.1-64.msi. 13.9 MB Feb 23. meson-1.0.1.pkg. 10.2 MB Feb 26. meson-1.0.1.tar.gz. 2.01 MB Feb 23.

Maybe I'm missing something?

**Comment by eli-schwartz** [comment]
How did you install it? With pip? Did you install it with *sudo* pip, or just regular pip?

Which version of Debian are you using? Bullseye doesn't have meson 1.0.1, but the error message you posted comes from /usr/lib/python3/dist-packages/mesonbuild/minstall.py which is a Debian system packages path.

**Comment by verghiskoshi** [comment]
I used regular pip3:
319  pip3 install meson ninja

Should I use sudo?

I'm not sure I understand the Debian question; I'm using Linux Mint 21.1 Vera (thought it was Cinnamon but I guess not), kernel 5.15.0-67-generic.  AFAIK Mint comes from LMDE 5 "Elsie".

I followed the instructions from http://doc.dpdk.org/guides/linux_gsg/build_dpdk.html to the letter.

Happy to answer any other questions, thanks for your help.

**Comment by eli-schwartz** [comment]
> Should I use sudo?

Very possibly, but see the link I posted.

The basic issue here is that pip install without sudo, installs meson but only for your current user. Thus when you run `sudo ninja install`, the root account cannot find meson.

What makes it worse is that you have a different version of meson installed as root, but an older version. That older version isn't binary-compatible with meson 1.0.1.

Installing with `sudo pip install meson` solves this. It also scribbles all over the package manager. On the other hand, sudo ninja install also installs to places that the system package manager "owns", so that may be okay. Alternatives include running meson.py as a git clone of the meson repo, or using the instructions on the "Getting Meson" page to create a meson.pyz -- a single-file executable for meson.

If you do use sudo pip, make sure to uninstall the Linux Mint version of meson using `apt remove meson` *first*.

> I'm not sure I understand the Debian question; I'm using Linux Mint 21.1 Vera

No big deal, Linux Mint is a derivative of Ubuntu which is in turn a derivative of Debian. So technically you're using Debian twice removed.

**Comment by verghiskoshi** [comment]
Thanks for the detailed answer.  I'll make sure I understand it properly before I proceed.
Thanks again.

**Comment by verghiskoshi** [comment]
I wound up with the following as I was worried about sudo damaging the package manager:

PATH="/usr/local/bin:$PATH"

helloworld works now.
