### ISSUE TITLE
Verbose output suppresses gcc coloring

### ISSUE THREAD

**Issue by dvdhrm** [mesonbuild/meson#1170]
Hey

Using `ninja -v` suppresses all output-coloring of gcc via `-fdiagnostics-color=always`. That is, output coloring of warnings and errors works fine, unless you specify `-v`. Not sure what is responsible, but I guess ninja tunnels all gcc output through a non-terminal device in that case. Hence, `isatty()` in gcc fails and it suppresses colors. Just a wild guess, though.

This is meson-git and ninja-1.7.2. If I should rather report that on ninja-upstream, let me know.

Thanks
David

**Comment by jpakkane** [comment]
I can replicate this. I'm guessing that this is caused by one of two things. Either a) GCC ignores `-fdiagnostics-color=always` for some reason or Ninja strips color information when run in verbose mode.

Running the compile command manually and piping it to less yields colors which would indicate that the latter is happening. In either case Meson is not invoked at all in this so you should probably file a bug in Ninja.

**Comment by dvdhrm** [comment]
Submitted upstream:
    https://github.com/ninja-build/ninja/issues/1214

It really is a ninja bug/feature. They end up stripping escape-codes.
