### ISSUE TITLE
unhandled python exception... this is a meson bug and should be reported!

### ISSUE THREAD

**Issue by slyfox1186** [mesonbuild/meson#11751]
**Describe the bug**
```
ninja: Entering directory `build'
[0/1] Installing files.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 811, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 564, in do_install
    d = self.check_installdata(pickle.load(ifile))
AttributeError: Can't get attribute 'OptionString' on <module 'mesonbuild.interpreter.primitives.string' from '/usr/lib/python3/dist-packages/mesonbuild/interpreter/primitives/string.py'>

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-internal__install 

```

**To Reproduce**
[Google-Drive](https://drive.google.com/file/d/1GFfJDTsuZ3NbJ2WPl0GG_RL-07Chsow4/view?usp=share_link)
The entire build folder with all the meson.build files inside.

**Expected behavior**
It builds the output files that is why I am doing this into the prefix path that I set in my code. It has worked before, and I did a fresh install of ubuntu and updated a ton of support libraries like I always do and this time this error happened. FYI I did a fresh install because it was not working before I did that, and I was hoping it would help.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
Same PC
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
Ubuntu 22.04.02 x86_64
* what Python version are you using e.g. 3.8.0
Python 3.10.6
* what `meson --version`
1.1.0
* what `ninja --version` if it's a Ninja build
1.10.1

**Comment by eli-schwartz** [comment]
Ubuntu 22.04 ships with meson 0.61.2 in /usr/lib/python3/dist-packages, if you pip install meson then it will install meson 1.1.0 as a user install that isn't available when running `sudo ninja install`.

There's nothing we can do about this because it is just how pip works. But you can use meson via the instructions on our homepage for creating a "zipapp" instead of using pip.

The easiest solution if possible is to just us whichever version of meson is shipped with Ubuntu 22.04. You can also `sudo pip install meson` but that could pitentiacause issues and clashes with the system version.

Versions of meson more recent than the one provided by Ubuntu, learned how to detect this error and report a more useful error message.
