### ISSUE TITLE
libhttpseverywhere fails to build on Meson master

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1178]
The fix for #858 caused this. This breaks jhbuild because Epiphany uses libhttpseverywhere. 

The problem is that we have no way to install secondary files generated by Valac (#892, #891 ), so libhttpseverywhere has a hack to work around it that doesn't work anymore because we check that the file passed to `install_data` exists at configure time.

This same hack is used by almost all Vala projects which is a major problem because there is no workaround for this. We need to fix #892 and #891 so that people have an actual way to do this stuff.

**Comment by arteymix** [comment]
Maybe adding a bunch of `install_vala_<out>` is not that evil after all.

While `install_data` would be more consistent with installing stuff in `${prefix}`, it also poses serious the issue with knowing in advance the generated file name.

I would advocate the one-target-one-output model whenever possible.

**Comment by nirbheek** [comment]
The generated filename will always have to be known in advance regardless of what mechanism we use, and at least with Vala it is not difficult to know that at all.

What I liked about the [`mylib.vala_vapi()` syntax](https://github.com/mesonbuild/meson/issues/891#issuecomment-260003211) was that it also allowed other functions to consume that file, such as tests, custom targets, or even other build targets. If we add `install_vala_*` kwargs, there is still no way to refer to the C header file generated by valac when creating a vala library.

**Comment by arteymix** [comment]
@nirbheek that would definitely be the solution, but we would have to make `install_data` work with generated files

For your concerns of having `install_data` capable of installing the primary target, I think we could address this by never exposing its file object. You would only get a high-level build target, which is fine because of all the fuss it would involve to manipulate in other targets.

We could use `extract_vala_vapi`, `extract_vala_gir` and the like (as we already have `extract_objects`). Have some generic `extract_<language>_<output>` definition (why not `extract_c_objects` instead?) for target that produce multiple outputs. This pattern would potentially cover other compilers.

**Comment by arteymix** [comment]
By the way I love the idea of reusing the generated header or GIR in other targets. This would seriously make Meson incredibly friendly for Vala users.

**Comment by nirbheek** [comment]
I've filed a workaround bug for libhttpseverywhere, so we can potentially ignore this regression for this release: https://bugzilla.gnome.org/show_bug.cgi?id=776177

**Comment by grindhold** [comment]
@nirbheek thanks for your patch. i merged it just now.

**Comment by nirbheek** [comment]
Great, we will get this fixed for 0.38.0 so we can get rid of those hacks :)

**Comment by nirbheek** [comment]
Fixed: https://bugzilla.gnome.org/show_bug.cgi?id=780521
