### ISSUE TITLE
Python 3.7 EOL / move to python 3.8

### ISSUE THREAD

**Issue by amitdo** [mesonbuild/meson#11808]
Python 3.7 was released in June 27, 2018.

It will reach EOL next month. So maybe you want to remove the support for this version in meson sometime in the next 6 months.

**Comment by xclaesse** [comment]
IMHO, it does not matter much if it's EOL, what matters is what we gain from using Python3.8? What are the new APIs and syntaxes that can improve Meson code?

**Comment by eli-schwartz** [comment]
I am the person that did this change for python 3.6 -> 3.7, so I was looking into it for 3.7 -> 3.8 as well.

My thoughts on the matter:
- we shall not under any circumstances ever bump the metadata requirements or the startup error checking, in an untruthful manner -- so if meson runs under 3.7 (and we currently test it extensively under CI, so we know it does) then we shall continue to annotate the metadata to truthfully report that it does so
- upgrading to a new minimum version of python means starting to use features that require that new minimum
- having looked at the whatsnew for python 3.8, I don't feel strongly tempted by anything in order to use it for meson specifically. I think mainly what it allows is:
  - f-strings with `f'{foo=}'`, but this is almost entirely useful for debugging locally, so meson doesn't need it
  - walrus operator, which I simply do not find appealing. Also it doesn't actually typically provide any new functionality, it just allows you to slightly rewrite the exact same code. I have seen one or two examples of things that can't be done without it, but those were very contorted code golfing exercises that I'd reject in a review as deceptive

If we compare this to the 3.7 upgrade, there were some extremely useful things we took advantage of there. `__future__` annotations is one. Dataclasses is another. importlib.resources (replacing a custom compiler that converted data files into inline string variables in a .py file) is a third.

I think that by the time the question of upgrading to a 3.9 minimum comes around, I'll be a lot more tempted to upgrade. And I'm desperately looking forward to the very day that 3.9 is EOL so I can upgrade to 3.10 and get KW_ONLY in dataclasses. That alone is going to be a lifesaver.

Are there any killer features of python 3.8 that people would like to use? All suggestions are welcome.

**Comment by amitdo** [comment]
https://docs.python.org/3/whatsnew/3.8.html

**Comment by eli-schwartz** [comment]
Thanks, but I already said I looked at that and didn't find anything appealing. I was asking what *you* consider a killer feature for use in meson.

**Comment by eli-schwartz** [comment]
Without anything other than a link I've already read... Marking this for potential future closing.

**Comment by amitdo** [comment]
IIRC, in the past you (the Meson team) upgraded the Python version not long after the version became EOL. That why I open this issue.

I didn't contribute **code** to this project, so I don't want to try to convince you or other devs to drop 3.7.

**Comment by eli-schwartz** [comment]
Okay, thanks for clarifying. :)

If anyone else comes across this ticket -- I'm still interested in hearing if anyone feels that upgrading the minimum version of python would enable using any specific features that help them write better code for meson. Upgrading is absolutely still an option, if someone can champion it as something that will help them code better on meson.

**Comment by joukewitteveen** [comment]
`shlex.join` could replace `' '.join([shlex.quote(x) for x in ...])`, although it may be clearer if we aliased it inside `mesonlib` [anyway](https://github.com/mesonbuild/meson/pull/12807#issuecomment-1925503594).

**Comment by eli-schwartz** [comment]
@amitdo Just want to follow up on this, and thank you for opening up this ticket. Despite ultimately being closed as not planned, yes. :)

It's been in the back of my mind ever since, and was a major part of my motivation to open the tracking ticket linked above, as well as pending documentation updates at #14325 which will add our support policy and upgrade approach to the documentation website.

**Comment by bonzini** [comment]
For what it's worth, 3.8 would mostly allow getting rid of typing_extensions, and thus would allow to use Literal and TypedDict for validation purposes.

**Comment by dcbaker** [comment]
I'd *really* like to move to 3.10 in October when 3.9 reaches EOL, the switch statement in particular would be pretty nice. so if not before then, in October I'm planning to push for that
