### ISSUE TITLE
hdf5.py fails with exception if the project is not set up for C

### ISSUE THREAD

**Issue by radistmorse** [mesonbuild/meson#11925]
**Describe the bug**
what it says in the title. If you have, e.g. a c++ project, trying to call
```dependency('hdf5', language: 'cpp', method: 'config-tool')```
will cause an exception
```
<...>
  File "/usr/lib/python3.11/site-packages/mesonbuild/dependencies/hdf5.py", line 119, in __init__
    compiler = environment.coredata.compilers[for_machine][language]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'c'
```
hdf5.py always tries to configure ```c``` language, which is a problem whan it's not set in the project

**To Reproduce**
```
project('test', 'cpp')
dependency('hdf5', language: 'cpp', method: 'config-tool')
```

**Expected behavior**
no exception. If C is always needed for HDF5 - make a special error for this case.

**system parameters**
meson 1.0.1
ninja 1.11.1
fedora 38

**Comment by dcbaker** [comment]
That shouldn't be happenning, if you're setting language it should be using c++ to try to find hdf5, that means somewhere along the line the `langauge` keyword is getting dropped between the interpreter and the actual dependency

I had initially thought this is a good first issue because it was trying to use a language it should have but that language wasn't present. That bug is there, and if someone wanted a good first issue we should raise a nice error if someone tries to add this dependency without the requested language.

**Comment by dcbaker** [comment]
Okay, yeah. It seems that C is required, it's added as a sub-dependency.

We could go a couple of ways here. We can just nicely error out in this case which would be easy. Or, we could add a C compiler for the target machine for you and go from there. The second would be more user friendly, but a lot more work to get right (especially when cross compiling).

If someone wanted to fix this, you'd basically want to add a check to make sure that both 'c' and language if are in the compilers for the current machine, and otherwise set the dependency to not-found and return.

**Comment by radistmorse** [comment]
Why do we even care about the compiler there? We only need the list of libraries. Moreover, the expected env for the custom C linker is ```HDF5_CLINKER``` not ```HDF5_CCLINKER``` (see https://github.com/HDFGroup/hdf5/blob/develop/bin/h5cc.in#L97), so it never even worked.

**Comment by dcbaker** [comment]
the `config-tool` method wraps around the `h5cc`, `h5c++`, and `h5fc` programs, which themselves wrap a compiler invocation. For them to work we need an appropriate compiler. if you use the `pkg-config` method then you don't have this problem, it's just a text file with a list of libraries, include directories, and compiler flags to add

**Comment by radistmorse** [comment]
That's not how I understood the code. The tools are called with ```-show``` (see https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/hdf5.py#L131) which means that we are interested only in the list of flags and libs. We extract the list, store it in our internal structures, and forget about these tools. The actual compilation command has nothing to do with these tools anymore.

To use the pkg-config method you need the ```.pc``` file that HDF5 upstream doesn't provide.

**Comment by radistmorse** [comment]
I just removed the sub-dependency on C libs, and the project built and run without issues. All the libs were linked. The configuration tool from HDF5 links to the C libs directly (see https://github.com/HDFGroup/hdf5/blob/develop/c%2B%2B/src/h5c%2B%2B.in#L315) without the need for sub-dependencies. So where did the information that C is needed as sub-dependency even come from? I couldn't find anything about it on the HDF5 official sources.
