### ISSUE TITLE
Snap package ready and working

### ISSUE THREAD

**Issue by soumyaDghosh** [mesonbuild/meson#12124]
Hi, I have made a snap package for `meson` which works perfectly, but needs to have classic confinement. So, it's better that the upstream creates an account and takes it to the store. This way it'll be much better. Also, it's a universal package, working in any distro. I will be there to help maintain this snap if upstream wants.

**Comment by xclaesse** [comment]
What benefits does it have that justify the extra workload on Meson maintainers?

**Comment by eli-schwartz** [comment]
I see two problems with this:
1. There are many appstores out there, and usually any given individual is familiar with at *most* one or two, and often none. In the open source world, it's fairly traditional to publish source code and have appstore maintainers handle integration -- this is how apt/dpkg works on Ubuntu, as well as rpm, portage, pacman, xbps, and many more. Snap is just one more example. And no one on the core meson team is a snap store maintainer, so we aren't the best people to do this.
2. snap is bad for the ecosystem and bad for OSS. I strongly dislike Ubuntu's efforts to create a walled garden that doesn't follow proper OSS governance. If one wished to have cross-distro per-package appstores, flatpak is the way to go.

**Comment by soumyaDghosh** [comment]
> What benefits does it have that justify the extra workload on Meson maintainers?

First replying to this:

1. Meson team will not have to bother with updates. If someone is not using latest/stable meson and that causing the end packager issues.
2. There can be multiple channels to support multiple types, and also multiple architectures. Like: `amd64`, `arm64`, `armhf`, `ppc64el`, `riscv64`, `s390x`.
3. I am not sure if this help the upstream, but this will help the Ubuntu team. And other teams, as they can now ship same meson with every distro, regardless of being `22.04 LTS` or `23.04`.
4. As meson is used by many snaps, building them will be much better and easy also.
5. There is not extra work needed.




> I see two problems with this:
> 
>     1. There are many appstores out there, and usually any given individual is familiar with at _most_ one or two, and often none. In the open source world, it's fairly traditional to publish source code and have appstore maintainers handle integration -- this is how apt/dpkg works on Ubuntu, as well as rpm, portage, pacman, xbps, and many more. Snap is just one more example. And no one on the core meson team is a snap store maintainer, so we aren't the best people to do this.
> 

This is not entirely clear to me, but what I can say is, I can maintain it and help the team for the same. 

>     2. snap is bad for the ecosystem and bad for OSS. I strongly dislike Ubuntu's efforts to create a walled garden that doesn't follow proper OSS governance. If one wished to have cross-distro per-package appstores, flatpak is the way to go.

I completely accept this, but the point you cannot make a flatpak for meson, but for snap, a big yes.

**Comment by eli-schwartz** [comment]
> Meson team will not have to bother with updates. If someone is not using latest/stable meson and that causing the end packager issues.

But we already don't bother with updates. :) If a user is using an old version of meson, which we ask about in the issue template, we can just tell them "try updating".

Since many, many, many meson users are on Windows, snaps can't really affect that one way or the other.

> There can be multiple channels to support multiple types, and also multiple architectures. Like: `amd64`, `arm64`, `armhf`, `ppc64el`, `riscv64`, `s390x`.

Meson has no types and no architectures. In Ubuntu dpkg terms, it is an "all" architecture package. It is one-size-fits-all.

Note that `pip install` also supports the concept of an "any" built package or one that is specific to amd64/armhf/s390x etc. The "any" built wheel for meson, however, can be installed on Windows and macOS too, with just a single binary package.

> I am not sure if this help the upstream, but this will help the Ubuntu team.
> As meson is used by many snaps, building them will be much better and easy also.

This sounds like reasons for Ubuntu to want a snap, not for us to want a snap.

> There is no extra work needed.

So... I am additionally concerned by things like this: https://github.com/pdfarranger/pdfarranger/pull/930#issuecomment-1666537500

It sounds very much like the followup to adding snap support to the meson repo would be a request to become an org member with push access, which is a security concern as it sidesteps the usual process for becoming a trusted community member.

There is absolutely work needed! It feels a bit dishonest to say otherwise. At a minimum, it's work to review pull requests. And it's probably also additional CI jobs to test that snaps keep on building, additional management work to handle release credentials, and a disruption to development if we cannot merge PRs because the snap breaks after a build refactoring and the CI goes red.

Of course, we already have self-elected to maintain some credentials for the documentation website and the canonical PyPI release website. And CI can go red for a few different reasons and we have to stop everything and figure out what went wrong and fix it.

But those are for things we get personal benefit from. So investing in it makes sense. This is very different from the snap situation where we don't benefit at all.

It makes much more sense for snaps to be maintained by whoever wants them, separately, as part of Ubuntu.

**Comment by soumyaDghosh** [comment]
> So... I am additionally concerned by things like this: https://github.com/pdfarranger/pdfarranger/pull/930#issuecomment-1666537500

A kind request to not go personal. That's a desktop snap, which I am full aware that I can handle. And not a way to do such things. Also, I'm not the only one to help. Actually, in the snap forum, admins suggested me to ask this and try to make the snap upstream.

https://forum.snapcraft.io/t/suggestions-for-meson-and-ninja-snap/35826/11

And if the CI goes red, it'll disrupt pypi too. Because the snap also uses pip.

**Comment by soumyaDghosh** [comment]
@xclaesse I have linked the forum post. You can check that out and ask the admins. I'm none to answer this. But, I personally can do that.

If you want an answer which is opinionated by me, then I guess just like cups and pipewire, they want to have this project an official snap, which they can rely on, to create the next projects.

**Comment by eli-schwartz** [comment]
> A kind request to not go personal. That's a desktop snap, which I am full aware that I can handle. And not a way to do such things. Also, I'm not the only one to help. Actually, in the snap forum, admins suggested me to ask this and try to make the snap upstream.

I am not getting personal. I am talking about general operational security as a function of community. There are 8.1 billion humans on earth and at least 8 billion of them do not have maintainer privileges. The reason for this is not because they are suspected to be bad people.

Every software project in existence has to manage a balance somehow, of establishing a community and vetting new maintainers based on e.g. reputation and contribution history. Where this breaks down is when new maintainers are onboarded and given privileged security roles without any form of community management.

This is a procedural failure of the project in question, not of the new maintainer. But I think it's a procedural failure that says something about how Ubuntu snaps work.

**Comment by soumyaDghosh** [comment]
> This is a procedural failure of the project in question, not of the new maintainer. But I think it's a procedural failure that says something about how Ubuntu snaps work.

Not at all. This is my procedure, because the first I made, is now more or less popular, somehow, that project took this approach. https://github.com/NickvisionApps

Anyway, as you said, I'll try to maintain it then, on my own. Hope that if any issues comeup, that I can't fix, I'll get a little help here. Thanks.
