### ISSUE TITLE
dependency named 'intl' can't use pkg-config?

### ISSUE THREAD

**Issue by cellularmitosis** [mesonbuild/meson#12166]
It seems meson is special-casing the dependency name 'intl' and refusing to use pkg-config with it, even if you explicitly set that as the method.

i.e.

```
libintl = dependency('intl', required: false, method: 'pkg-config')
```

produces this error:

```
meson.build:2094:0: ERROR: Unsupported detection method: pkg-config, allowed methods are auto, builtin and system
```

but simply using a different name causes it to try to use pkg-config:

```
libintl2 = dependency('intl2', required: false, method: 'pkg-config')
```

```
Run-time dependency intl2 found: NO (tried pkgconfig)
```

It appears there is no way to use a gettext installation which lives in /opt.

Version info:

```
$ meson --version
1.0.0
```

EDIT: just updated to 1.2.1, same issue.

```
$ meson --version
1.2.1
```

**Comment by eli-schwartz** [comment]
> It seems meson is special-casing the dependency name 'intl' and refusing to use pkg-config with it, even if you explicitly set that as the method.

> It appears there is no way to use a gettext installation which lives in /opt.

The libintl author claims that pkg-config violates the spirit of Free/Libre and Open Source Software, and considers that he cannot introduce these text files because it would result in gettext violating the GPL license.

> Here is a quote of him explaining why:

> As long as pkg-config is designed to make things more efficient for the distro builder while at the same time removing freedoms from the end user [1], we should not add more pkg-config files in GNU, IMHO.
> 
> Bruno
>
> [1] https://gitlab.com/ghwiki/gnow-how/-/wikis/Discussion-about-pkg-config

And here's another quote from him:

> The .pc files invite people to use the current pkg.m4 (rather than the gettext.m4 from the GNU gettext package).
>
> While gettext.m4 makes it easy to use to use a libintl that was installed by the user with e.g. --prefix=$HOME/installed-gettext, pkg.m4 makes it hard and frustrating. The net effect is that users struggle with that, and after two or three failures abandon and say "oh well, let me just use what my distro vendor provided".
> 
> Whereas the idea of Free Software is not only that it *technically possible* to modify the source code and build and use that modified source code, but also that, as a user, you are *invited* to do so.

And if you go read Bruno's personal Wiki (with the careful disclaimer: "The GNU Hackers Wiki contains technical information from GNU Hackers for GNU Hackers. It does not officially represent the GNU project.") you will see his pièce de résistance:

> When users have installed libraries in their own locations (e.g. under $HOME), the .pc file will not be found by default. Users need to adjust the PKG_CONFIG_PATH environment variable.

(At the bottom of the wiki page, he talks about how pkg-config "doesn't work well with cross-compilation". I did manage to inform him of pkgconf's support for personality.d/ files.)

So there you have it. Allowing people to use pkg-config means they won't use gettext.m4, and by extension, that they won't use GNU autotools as their build system. And that's a huge no-no, because the idea of Free Software is that you are "invited" to modify and use your modifications.

Do you feel invited? Are you getting that warm and fuzzy feeling inside, by being told by FSF members that anyone using a build system that isn't GNU autoconf is an enemy of the free software movement engaged in a malicious attempt to violate the rights of users by denying them the ability to know that it's possible to compile a custom copy of gettext and point gettext.m4 at it?

I don't.

But, unfortunately, gettext upstream doesn't have pkg-config files, and meson makes the assumption that it doesn't have to fork out and run pkg-config to try to find something that (it is believed) cannot ever be found. Instead it goes straight to the "system" dependency type, which searches for `-lintl` and `#include <libintl.h>` along your `$CFLAGS` / `$LDFLAGS`.

**Comment by eli-schwartz** [comment]
If you have a pkg-config file for intl, how did it get up installed? Has gettext changed its policy? Did you write one yourself?

**Comment by cellularmitosis** [comment]
Yeah I saw his infamous "pkgconfig is too ill-designed" [post](https://lists.gnu.org/archive/html/bug-gettext/2012-03/msg00022.html), rolled my eyes, and just wrote my own.

```
macuser@pmacg5(leopard)$ cat /opt/gettext-0.21/lib/pkgconfig/intl.pc 
prefix=/opt/gettext-0.21
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: intl
Description: GNU internationalization (i18n) and localization (l10n) library
Version: 0.21
Libs: -L${libdir} -lintl
Cflags: -I${includedir}
```

**Comment by cellularmitosis** [comment]
Would it be possible to default to `auto, builtin and system` but still allow an explicit override for `method: 'pkg-config'`?  Then I could just make one edit to glib's meson.build file in order to get it to work.

**Comment by cellularmitosis** [comment]
Alternatively, if using CPPFLAGS and LDFLAGS for intl could be an option, I'm also happy to do that.

**Comment by cellularmitosis** [comment]
oh wait, that worked!

```
CPPFLAGS="-I/opt/gettext-0.21/include" LDFLAGS="-L/opt/gettext-0.21/lib" meson ....
```

```
Run-time dependency intl found: YES
```

Closing issue, sorry for the bother!

**Comment by eli-schwartz** [comment]
> Would it be possible to default to `auto, builtin and system` but still allow an explicit override for `method: 'pkg-config'`? Then I could just make one edit to glib's meson.build file in order to get it to work.

The current implementation of mesonbuild.dependencies.factory.DependencyFactory doesn't support anything other than setting priority ordering. I *think* it would be simple enough to change, basically `process_method_kw()` controls which methods we'll actually try so perhaps tweaking that so that it respected, idk, a `self.nondefault_methods`, match `method: 'pkg-config'` in kwargs and allow more methods?

> Alternatively, if using CPPFLAGS and LDFLAGS for intl could be an option, I'm also happy to do that.

This should work too though. Since the "system" dependency lookup uses `cc.has_header()` and `cc.find_library()` under the hood, and those methods are supposed to respect -I / -L flags, C(PP)?FLAGS and LDFLAGS should cause it to be picked up.

**Comment by cellularmitosis** [comment]
Thanks for your quick responses btw!

**Comment by ferdnyc** [comment]
@eli-schwartz 

> So there you have it. Allowing people to use pkg-config means they won't use gettext.m4, and by extension, that they won't use GNU autotools as their build system. And that's a huge no-no, because the idea of Free Software is that you are "invited" to modify and use your modifications.
> 
> Do you feel invited? Are you getting that warm and fuzzy feeling inside, by being told by FSF members that anyone using a build system that isn't GNU autoconf is an enemy of the free software movement engaged in a malicious attempt to violate the rights of users by denying them the ability to know that it's possible to compile a custom copy of gettext and point gettext.m4 at it?

The really nutty thing is, Haible has no real love for autoconf either, and biasing projects towards _its_ use really isn't the motivator for his anti-pkg-config stance. He just really hates pkg-config.

In [this libunistring bug](https://savannah.gnu.org/bugs/?53717), he even recognizes that autoconf is dropping precipitously in its "marketshare" among build systems, and because the request is from a user looking to integrate libunicode into a CMake project, he determines:

> Then, what we need is good support for locating libunistring in CMake.
> [...]
> Therefore, I'm looking for a solution that involves CMake but does not involve pkg-config.

As @cellularmitosis said (paraphrasing): :roll_eyes:

**Comment by eli-schwartz** [comment]
Wow. I'm somewhat lost for words.
