### ISSUE TITLE
qt5.compile_moc ignores include paths from dependencies

### ISSUE THREAD

**Issue by mardy** [mesonbuild/meson#12182]
**Describe the bug**
Passing the `dependency` parameter to `qt5.compile_moc` does not bring in all the include paths specified in the dependency.

**To Reproduce**
[mesontest.tar.gz](https://github.com/mesonbuild/meson/files/12482449/mesontest.tar.gz)

Results in a failed build:
```
[1/4] Generating 'program.p/moc_includer.cpp'.
FAILED: program.p/moc_includer.cpp 
/usr/lib/x86_64-linux-gnu/qt5/bin/moc --output-dep-file -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 ../includer.h -o program.p/moc_includer.cpp
../includer.h:11: Parse error at "IFACE_NAME"
[2/4] Compiling C++ object program.p/main.cpp.o
ninja: build stopped: subcommand failed.
```

Note that the directory `subdir` is missing from the list of includes passed to `moc`.

**Expected behavior**
The include path added to the `subdir_dep` in `subdir/meson.build` should be added to the list of include paths when invoking the moc.

**system parameters**
* native build
* Ubuntu 22.04
* Python 3.10.12
* meson 0.61.2
* ninja 1.10.1

**Comment by mardy** [comment]
Occurs with meson 0.63.3 too.

**Comment by tristan957** [comment]
Can you test with master?

@bruchar1 is this something you could help with?

**Comment by bruchar1** [comment]
At first sight, it seems that the qt module gets the compile args from the dependencies, but for internal dependencies, compile args do no include include dirs, as the include dirs are stored in a different member, and are usually resolved by the backend.

The fix is probably to add the include dirs to compile args, in the `_compile_moc_impl` function of the qt module. I wonder if this problem exists elsewhere in the code? But qt seems the only module to use Generator object, so the answer is probably no.
