### ISSUE TITLE
wrong shared library 7.9, want 7.10 on OpenBSD

### ISSUE THREAD

**Issue by kernigh** [mesonbuild/meson#12195]
**Describe the bug**
Given versions x.9 and x.10 of a shared library on OpenBSD, Meson finds the wrong one. It picks x.9, but I want x.10.

**To Reproduce**
Meson has a test to find shared libraries on OpenBSD, so I added a failing case,

```diff
diff --git a/unittests/internaltests.py b/unittests/internaltests.py
index 56d36117a..37cbbc3bd 100644
--- a/unittests/internaltests.py
+++ b/unittests/internaltests.py
@@ -549,11 +549,13 @@ class InternalTests(unittest.TestCase):
         if platform != 'openbsd':
             return
         with tempfile.TemporaryDirectory() as tmpdir:
-            for i in ['libfoo.so.6.0', 'libfoo.so.5.0', 'libfoo.so.54.0', 'libfoo.so.66a.0b', 'libfoo.so.70.0.so.1']:
+            for i in ['libfoo.so.6.0', 'libfoo.so.5.0', 'libfoo.so.54.0', 'libfoo.so.66a.0b', 'libfoo.so.70.0.so.1', 'libbar.so.7.10', 'libbar.so.7.9']:
                 libpath = Path(tmpdir) / i
                 libpath.write_text('', encoding='utf-8')
             found = cc._find_library_real('foo', env, [tmpdir], '', LibType.PREFER_SHARED, lib_prefix_warning=True)
             self.assertEqual(os.path.basename(found[0]), 'libfoo.so.54.0')
+            found = cc._find_library_real('bar', env, [tmpdir], '', LibType.PREFER_SHARED, lib_prefix_warning=True)
+            self.assertEqual(os.path.basename(found[0]), 'libbar.so.7.10')
 
     def test_find_library_patterns(self):
         '''
```

Do `./run_unittests.py -k internaltests`, then the test fails:

```
    self.assertEqual(os.path.basename(found[0]), 'libbar.so.7.10')
AssertionError: 'libbar.so.7.9' != 'libbar.so.7.10'                             
```

**Expected behavior**
Meson should find `libbar.so.7.10` because it has a higher minor version number than `libbar.so.7.9`. The code in mesonbuild/compilers/mixins/clike.py _sort_shlibs_openbsd is comparing floats 7.9 > 7.10. I want to compare tuples (7, 9) < (7, 10), but I don't have Python code to make the tuples.

**system parameters**
* OpenBSD 7.3-current, Python 3.10.12, Meson 025bcc0 (master on Sep 1, 2023)

**Comment by eli-schwartz** [comment]
Is it required to be a two-component version?

**Comment by kernigh** [comment]
Yes, shared libraries are named [libfoo.so.major.minor](https://www.openbsd.org/faq/ports/specialtopics.html#SharedLibs), always with 2 components (major and minor). That's why meson's _get_patterns has `{}.so.[0-9]*.[0-9]*`

**Comment by eli-schwartz** [comment]
I think this should do the trick: https://github.com/eli-schwartz/meson/commit/5b85fadb0223c9fa64e6f4a0bf52dc3064bd9a6f

**Comment by kernigh** [comment]
Yes, your diff works for me. Given `dependency('libdrm')` and `dependency('libdrm_amdgpu')`, meson was finding libdrm.so.7.9 and libdrm_amdgpu.so.1.9; but your diff finds libdrm.so.7.12 and libdrm_amdgpu.so.1.12

The old code in _sort_shlibs_openbsd to "Validate file" by doing `float(ret[1])` now seems wrong. Strings like `'3e33'` and `'inf'` are valid floats but can't become tuples of integers. I created libdrm.so.3e33 but meson ignored it. I suspect that the glob in _get_trials_from_pattern can't match libdrm.so.3e33, so _sort_shlibs_openbsd never sees 3e33.

**Comment by landryb** [comment]
some context on  what lead to this discovery:
on openbsd, base libs versions are regularly updated when symbols are added/removed, and 'old' libs are kept around if one doesnt remove them (useful to keep potential old binaries still linked against them to run).

i stumbled upon that when building xwayland, which requires a particular symbol from libdrm:
```
ld: error: undefined symbol: drmGetDeviceFromDevId
```
the symbol was present in libdrm 7.11 and libdrm 7.12, but not in libdrm 7.8 and 7.9 (which were still around, even if from 2020..) - after inspecting the ld line, meson/ninja was trying to link with libdrm 7.9, instead of (expectingly) the 'latest' libdrm 7.12.

**Comment by eli-schwartz** [comment]
> some context on what lead to this discovery:
on openbsd, base libs versions are regularly updated when symbols are added/removed, and 'old' libs are kept around if one doesnt remove them (useful to keep potential old binaries still linked against them to run).

This has nothing to do with openbsd, the same thing occurs here on Linux, and also on BSDs other than openbsd, such as FreeBSD.

(Gentoo has a very nice setup for keeping old libs only if something still refers to them, and automatically removing the old libs once they aren't needed as part of rebuilding whichever package needed them. Other package managers working at the binary level usually have to package the libs separately and treat them as normal dependencies.)

The difference is that openbsd is very much unique in not including an unversioned soname symlink pointing to the new library, whereby this symlink is then used when looking up a library name. This was originally reported by @kernigh, in fact, back in 2018 -- that's how we ended up with the current openbsd specific code to filter and sort versioned sonames in order to detect, for ourselves, which one is the default to link against.

No meson developers use openbsd, plus we don't have any CI for it, so we're entirely reliant on users reporting issues. Thanks for the report. :)

**Comment by Xayeu** [comment]
> **Mô tả lỗi** Với phiên bản x.9 và x.10 của thư viện chia sẻ trên OpenBSD, Meson tìm sai. Nó chọn x.9, nhưng tôi muốn x.10.
> 
> **Để Reproduce** Meson có test tìm thư viện dùng chung trên OpenBSD nên mình thêm vào một trường hợp bị lỗi,
> 
> ```diff
> diff --git a/unittests/internaltests.py b/unittests/internaltests.py
> index 56d36117a..37cbbc3bd 100644
> --- a/unittests/internaltests.py
> +++ b/unittests/internaltests.py
> @@ -549,11 +549,13 @@ class InternalTests(unittest.TestCase):
>          if platform != 'openbsd':
>              return
>          with tempfile.TemporaryDirectory() as tmpdir:
> -            for i in ['libfoo.so.6.0', 'libfoo.so.5.0', 'libfoo.so.54.0', 'libfoo.so.66a.0b', 'libfoo.so.70.0.so.1']:
> +            for i in ['libfoo.so.6.0', 'libfoo.so.5.0', 'libfoo.so.54.0', 'libfoo.so.66a.0b', 'libfoo.so.70.0.so.1', 'libbar.so.7.10', 'libbar.so.7.9']:
>                  libpath = Path(tmpdir) / i
>                  libpath.write_text('', encoding='utf-8')
>              found = cc._find_library_real('foo', env, [tmpdir], '', LibType.PREFER_SHARED, lib_prefix_warning=True)
>              self.assertEqual(os.path.basename(found[0]), 'libfoo.so.54.0')
> +            found = cc._find_library_real('bar', env, [tmpdir], '', LibType.PREFER_SHARED, lib_prefix_warning=True)
> +            self.assertEqual(os.path.basename(found[0]), 'libbar.so.7.10')
>  
>      def test_find_library_patterns(self):
>          '''
> ```
> 
> Do `./run_unittests.py -k internaltests`, thì bài kiểm tra thất bại:
> 
> ```
>     self.assertEqual(os.path.basename(found[0]), 'libbar.so.7.10')
> AssertionError: 'libbar.so.7.9' != 'libbar.so.7.10'                             
> ```
> 
> **Hành vi dự kiến**​​Meson nên tìm `libbar.so.7.10`vì nó có số phiên bản phụ cao hơn `libbar.so.7.9`. Mã trong mesonbuild/compilers/mixins/clike.py _sort_shlibs_openbsd đang so sánh số float 7.9 > 7.10. Tôi muốn so sánh các bộ dữ liệu (7, 9) < (7, 10), nhưng tôi không có mã Python để tạo các bộ dữ liệu.
> 
> **hệ thống tham số toán học**
> 
> * OpenBSD 7.3-current, Python 3.10.12, Meson [025bcc0](https://github.com/mesonbuild/meson/commit/025bcc0d9d1f7ebdc3ba483ef77bc515327364bf) (chính thức vào ngày 1 tháng 9 năm 2023)

Tuỳ thuộc người sử dụng giữa lặp lại 2 thành phần theo tôi hiểu + -  nhờ mọi người truy xuất thêm cho hoàn chỉnh nhé.thank
