### ISSUE TITLE
DOC: regenerate the release notes for 1.2.2

### ISSUE THREAD

**Issue by mattip** [mesonbuild/meson#12311]
I was curious what is new with the (very) recent 1.2.2 release, but didn't see anything in the [release notes](https://mesonbuild.com/Release-notes.html). Is there a way to regenerate that?

**Comment by eli-schwartz** [comment]
The release notes are based on snippet files to document new features. Anything significant enough to warrant release notes for a new feature is usually not eligible for backporting.

What you're probably interested in is the list of fixed bugs -- and that's the heart of the issue here, because...

... historically meson hasn't included release notes with a "bugs fixed" section. So, correspondingly, there's no release notes to regenerate for the point release.

I'm not sure what people think about starting to do this -- other than that I haven't really thought about the topic myself! However, we do keep a GitHub milestone for each point release that records each PR merged to master that was nominated for backporting. It's quite accurate as the scripts which produce the point release branch actually use the GitHub API, process the list of PRs targeted for the milestone, and backport the contents of each milestoned PR.

The titles of the PRs are usually elucidative.

**Comment by mattip** [comment]
OK, so I should look at [the 1.2.2 milestone](https://github.com/mesonbuild/meson/pulls?q=milestone%3A1.2.2+). Thanks, that is helpful. Feel free to close if you think this is not something others would be interested in.

**Comment by xclaesse** [comment]
> OK, so I should look at [the 1.2.2 milestone](https://github.com/mesonbuild/meson/pulls?q=milestone%3A1.2.2+).

exactly.
