### ISSUE TITLE
extracting from wrap archives should detect case-sensitivity issues

### ISSUE THREAD

**Issue by pobrn** [mesonbuild/meson#12344]
**Describe the bug**

The source archive for a wrap might depend on the case-sensitivity of the file system to work. Meson currently:

* experiences data loss on extraction for regular files (since only one will be kept);
* might fail with an obscure `OSError` if symbolic links are present;
* (probably other failures are possible)

**To Reproduce**

See mesonbuild/wrapdb#1051. Try to build it on a case-insensitive file system. (Or just check windows/mac CI logs.)

**Expected behavior**

Meson should detect this scenario and fail with a clear error message.

**system parameters**
* meson version: 1.2.2

**Comment by eli-schwartz** [comment]
But liburing is also not actually even supposed to be downloaded or installed on non-Linux operating systems, so it makes mostly perfect sense that it is using technology that is linux-specific in the tarball.

This is technically a wrapdb "bug" because the wrapdb has had issues in the past where people ignored platform-specific errors when merging (not contributing, *merging*) wraps and silencing errors by misusing the "project source code is intended only for linux" config setting to mean "don't build and test on xxx platform because the upstream build system works fine on that platform, but the wrap is buggy".

I'm unsure what should be done here from meson's side of things.

**Comment by eli-schwartz** [comment]
> That's true, but I don't think the core issue is linux-specific. It's true that linux platforms usually use case-sensitive filesystems, but that can also be changed on linux for certain filesystems.

Nearly all people anywhere do not care about this, and a couple people are trying to do it as a "because we can, to prove we can" kind of thing. It's nuts to actually use one.



> I don't see it that way. The issue has nothing to do with the wrap itself. This happens way before that code is even parsed and executed. This happens as the result of the [`subproject()` call](https://github.com/mesonbuild/wrapdb/blob/5cfaa1c9f7a0a7154ba826c2b809a6710ec1591b/meson.build#L9) downloading and extracting the source, there is nothing the wrap can do to prevent that (as far as I know).

If the wrap gets downloaded by `subproject()` then it will also get executed, and this will fail. I would consider it highly surprising if a project does `subproject('liburing')` on Windows. :)

> the `sanity_checks.py` from wrapdb needs to have an option that will prevent even running `meson setup -D wraps=...` for certain wraps; or

We had that, but again, people were reviewing PRs for cross-platform projects that were failing due to meson.build files that mishandled compiling on Windows, and handling this by using that option as a "quick hack to get CI to pass". Then those wraps rotted forever because they claimed to be for source code which wasn't written to target the Windows API, so CI never ran.

This is why we no longer rely on people marking wraps as "don't even run `meson setup`", and instead go double-check by running it and asserting that it fails.

> something that addresses this issues needs to be added to meson, and the `sanity_checks.py` from wrapdb needs to be extended to recognize this error ([just like it does for others](https://github.com/mesonbuild/wrapdb/blob/5cfaa1c9f7a0a7154ba826c2b809a6710ec1591b/tools/sanity_checks.py#L404)).

The obvious immediate answer is to just merge liburing with failing CI.

But see my linked PR.

**Comment by eli-schwartz** [comment]
> That's perfectly fine by me. I thought that would make the CI fail from that point on, but it appears that is not the case.

No. CI will only run on the current wrap by design. There's a separate mega-CI build that runs on a schedule instead of on PRs, and tests every possible wrap -- but that just checks for regressions and doesn't cross-verify that liburing "should fail on Windows", it just skips over it as it expects to not build on Windows and the mega-build is only interested in wraps that passed with older versions of meson and fail with an updated meson from git master.
