### ISSUE TITLE
meson < 1.2.x is broken for macOS 14.0 Sonoma (clang 15.0)

### ISSUE THREAD

**Issue by franramirez688** [mesonbuild/meson#12399]
**Describe the bug**

After upgrading my macOS to Sonoma version and clang 15.0, meson started to fail with:

```
The Meson build system
Version: 1.1.0
Source dir: /Users/myuser/myfolder/meson/tutorial
Build dir: /Users/myuser/myfolder/meson/tutorial/builddir
Build type: native build
Project name: tutorial
Project version: undefined

meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)


A full log can be found at /Users/myuser/myfolder/meson/tutorial/builddir/meson-logs/meson-log.txt
```

Issues likely related: https://github.com/mesonbuild/meson/issues/12159

**To Reproduce**

It can be easily reproduced with the meson tutorial.

My folder structure:
```
.\
 | - main.c
 | - meson.build
```

**main.c**
```c
#include <stdio.h>

//
// main is where all program execution starts
//
int main(int argc, char **argv) {
  printf("Hello there.\n");
  return 0;
}
```

**meson.build**
```
project('tutorial', 'c')
executable('demo', 'main.c')
```

Running this in your command prompt, I got this error:

```
$ meson setup builddir

The Meson build system
Version: 1.1.0
Source dir: /Users/user/myfolder/meson/tutorial
Build dir: /Users/user/myfolder/meson/tutorial/builddir
Build type: native build
Project name: tutorial
Project version: undefined

meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)

A full log can be found at /Users/myuser/myfolder/meson/tutorial/builddir/meson-logs/meson-log.txt
```

It's true that upgrading meson to 1.2.x, the problem is solved:

```
tutorial git:(develop) ✗ meson setup builddir

The Meson build system
Version: 1.2.0
Source dir: /Users/myuser/myfolder/meson/tutorial
Build dir: /Users/myuser/myfolder/meson/tutorial/builddir
Build type: native build
Project name: tutorial
Project version: undefined
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.0.40.1)")
C linker for the host machine: cc ld64 1015.7
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.0 at /usr/local/bin/ninja
➜  tutorial git:(develop) ✗ cd builddir
➜  builddir git:(develop) ✗ meson compile
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/local/bin/ninja
[2/2] Linking target demo
ld: warning: -undefined error is deprecated
```

Curiously, it worked, but having a look at the meson-logs.txt, the error is still there (but not raising any exception):

```
-----------
Detecting linker via: `cc -Wl,--version` -> 1
stderr:
ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-----------
-----------
Detecting Apple linker via: `cc -Wl,-v` -> 1
stderr:
@(#)PROGRAM:ld  PROJECT:dyld-1015.7
BUILD 16:59:22 Oct  1 2023
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
will use ld-classic for: armv6 armv7 armv7s arm64_32 i386 armv6m armv7k armv7m armv7em
LTO support using: LLVM version 15.0.0 (static support for 29, runtime is 29)
TAPI support using: Apple TAPI version 15.0.0 (tapi-1500.0.12.3)
Library search paths:
	/usr/local/lib
Framework search paths:
ld: Undefined symbols:
  _main, referenced from:
      <initial-undefines>
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-----------
```

**Expected behavior**
-

**system parameters**
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
  * macOS 14.0 Sonoma
  * clang and xcode versions
```bash
$ clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ /usr/bin/xcodebuild -version

Xcode 15.0.1
Build version 15A507
```
* what Python version are you using e.g. 3.8.0
Python 3.9.18
* what `meson --version`
tested with Meson 1.0.1 and Meson 1.1.0
* what `ninja --version` if it's a Ninja build
ninja-1.11.0

**Comment by Maijestro** [comment]
Hello I have exactly the same problems as described above. Compiling from the git master sources of Qemu is no longer possible under MacOs Sonoma 14.1 with Homebrew and Xcode 15. I have already submitted a ticket and described the problem.  So I refer to it again and ask for help.

https://gitlab.com/qemu-project/qemu/-/issues/1939

Meson 1.2.3 was installed via Homebrew 

./configure
Using './build' as the directory for build output
python determined to be '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3'
python version: Python 3.10.8
mkvenv: Creating non-isolated virtual environment at 'pyvenv'
mkvenv: checking for tomli>=1.2.0
mkvenv: installing tomli>=1.2.0
mkvenv: checking for meson>=0.63.0
mkvenv: installing meson==0.63.3
mkvenv: checking for sphinx>=1.6
mkvenv: checking for sphinx_rtd_theme>=0.5

'sphinx==5.3.0' not found:
 • Python package 'sphinx' was not found nor installed.
 • mkvenv was configured to operate offline and did not check PyPI.


Sphinx not found/usable, disabling docs.
Disabling PIE due to missing toolchain support
The Meson build system
Version: 0.63.3
Source dir: /Users/reneengel/qemu
Build dir: /Users/reneengel/qemu/build
Build type: native build
Project name: qemu
Project version: 8.1.50

../meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
stdout: 
stderr: ld: unknown options: --version 
clang: error: linker command failed with exit code 1 (use -v to see invocation)


A full log can be found at /Users/reneengel/qemu/build/meson-logs/meson-log.txt

ERROR: meson setup failed

**Comment by Maijestro** [comment]
This is not very helpful, is there a solution to the problem ?

**Comment by tristan957** [comment]
> Meson 1.2.3 was installed via Homebrew

You aren't using this version, so the solution is to use a version of Meson in the 1.2.x series. Please read what I am saying.

**Comment by Maijestro** [comment]
And how do I use Meson in the 1.2.x series? I'm sorry but I have no idea how I can help myself. Everything worked without problems before MacOs Sonoma and there were no problems with Meson.

**Comment by tristan957** [comment]
You have to install it, which you said you did, but you don't use it for some reason. I cannot give you an answer as to why you choose to use an old version.

**Comment by Maijestro** [comment]
I didn't choose an old version, I already said the last current version of Meson was installed via Homebrew, the problem seems to be with Qemu, Qemu seems to be using a very old Meson version 0.63.3 which is no longer compatible shines. So I think I'm in the wrong thread here and I should report the bug in the Qemu bug tracker.

**Comment by tristan957** [comment]
You installed it, but didn't use it. There is no bug. Please read the log output that I already quoted to you.

**Comment by Maijestro** [comment]
I'm quite new to Git and I'm not a programmer either and it's very difficult to understand things. Where can I find the log output?

You should be patient with me and if there is something to solve, please give me clear, understandable instructions so that I understand how to use it.

You wrote that Meason 1.2.x was installed, but it is not used, but I don't understand why it is not used, as I have never had such problems under MacOs.

**Comment by tristan957** [comment]
Running `which meson` will tell you where the Meson you are using is from. Somehow you have installed a really old Meson into what is probably /usr, probably with pip. So you uninstall it. Then the version you installed with homebrew will take precedence.

**Comment by eli-schwartz** [comment]
It appears that qemu is completely bypassing the good version of meson you installed, and installs a second, older copy to use.

This can be ascertained from the build logs, because meson always prints the following header:
```
The Meson build system
Version: __________
```

In this case the meson build log header is in the middle of the qemu build system's own log. So it's not as obvious to read as it could be.

---


The qemu configure script may have an option to select a different meson instead of the one it bundles, iirc.

**Comment by eli-schwartz** [comment]
@bonzini

**Comment by eli-schwartz** [comment]
You can also see:

```
mkvenv: installing meson==0.63.3
```

**Comment by Maijestro** [comment]
> Running `which meson` will tell you where the Meson you are using is from. Somehow you have installed a really old Meson into what is probably /usr, probably with pip. So you uninstall it. Then the version you installed with homebrew will take precedence.

"which meson" gives me that in the terminal as output

% which meson
/opt/homebrew/bin/meson

**Comment by tristan957** [comment]
That confirms what Eli said then. QEMU is really doing some funky stuff there.

**Comment by bonzini** [comment]
Yes, QEMU finds Meson (and sphinx) based on the Python executable in the PATH. Because find_program uses the Python version that was used to run Meson, this is the only way to have one and only one version of Python for the whole build. His system Python didn't have a meson wheel installed. 

Having up to deal with up to three different pythons (the first python3 in the PATH for executable scripts found with find_program; Python used by the first meson in the PATH for non-executable scripts found with find_program; Python used by the first sphinx-build in the PATH for Sphinx extensions) was harder to debug than the situation that the reporter found himself in.

@Maijestro, does `which python3` point to homebrew or to the system Python? If the late, can you modify the PATH?
If not, my suggestion is to point the PYTHON environment variable to the homebrew interpreter. I think CMake and Autotools will use it too.

**Comment by bartekpacia** [comment]
I'm also experiencing this problem. I'm very new to QEMU. I just did `git clone git@gitlab.com:qemu-project/qemu.git` and then `./configure --target-list=aarch64-softmmu`.

My machine is MacBook Air M1, macOS Sonoma (14.1.1), latest Xcode 15.0.1.

<details><summary>Logs</summary>

```
$ ./configure --target-list=aarch64-softmmu
Using './build' as the directory for build output
python determined to be '/Users/bartek/.pyenv/shims/python3'
python version: Python 3.11.1
mkvenv: Creating non-isolated virtual environment at 'pyvenv'
mkvenv: checking for meson>=0.63.0
mkvenv: installing meson==0.63.3
mkvenv: checking for sphinx>=1.6
mkvenv: checking for sphinx_rtd_theme>=0.5

'sphinx==5.3.0' not found:
 • Python package 'sphinx' was not found nor installed.
 • mkvenv was configured to operate offline and did not check PyPI.


Sphinx not found/usable, disabling docs.
Disabling PIE due to missing toolchain support
The Meson build system
Version: 0.63.3
Source dir: /Users/bartek/dev/random/qemu
Build dir: /Users/bartek/dev/random/qemu/build
Build type: native build
Project name: qemu
Project version: 8.1.90

../meson.build:1:0: ERROR: Unable to detect linker for compiler `cc -Wl,--version`
stdout:
stderr: ld: unknown options: --version
clang: error: linker command failed with exit code 1 (use -v to see invocation)


A full log can be found at /Users/bartek/dev/random/qemu/build/meson-logs/meson-log.txt

ERROR: meson setup failed
```

</details>

I hope this info will be useful to somebody more experienced. And thank you for maintaining this project.

**Comment by bonzini** [comment]
It's already fixed in Meson. :)

**Comment by bartekpacia** [comment]
Right, this issue was one of first that showed up in search results. Thank you for the fix!

So I guess now it's a problem on QEMU's `configure` script side to pick up the right Meson version, and not some ancient 0.63.3?

**Comment by eli-schwartz** [comment]
> No, QEMU is doing the right thing. Meson is essentially a Python package that is installed by Homebrew instead of e.g. pip, and the installation of Meson must match the Python interpreter used for anything else in the build (especially building documentation).

Uhhhh, what?

(Spoiler: QEMU is doing the wrong thing.)

**Comment by bonzini** [comment]
> Uhhhh, what?

I agree it's funky but it is better than all the alternatives. Especially if you consider that:

* some distros (RHEL, SLES) ship /usr/bin/sphinx-build using a 3.6 Python interpreter, and building docs needs a newer one

* some distros (homebrew) write a shell script to the meson binary in the path, therefore, given a "meson" binary, there is no way to find which python interpreter it is using (at least not without running it)

* some distros (bsd ports) provide packages for multiple versions of Python

* some distros do not have new-enough system packages for meson, or perhaps the users want to install it using pip instead of system packages

There's so many things that can go wrong that it's better for QEMU to only accept consistent configurations and fail early for everything else.

Also consider that QEMU contains programs (such as firmware and tests) for 10+ different targets, which is way beyond Meson's abilities (even target_machine is half-assed and IMO should be removed). All tests needed to configure and build the emulators are done in Meson, but that is not the only work needed to build the full QEMU distribution.

**Comment by eli-schwartz** [comment]
The point is that it simply does not matter which version of python is in the shebang for the file described by `meson_command=$(command -v meson)`, because no matter what you actually do with python software in your `meson.build` files you can just specify your own very freely.

There's nothing stopping you from using a system meson and then enforcing the python version used by all qemu stuff totally independently from meson. In fact, since you invoke meson from a configure shell script it's even easier than usual, as one of the primary configuration points for meson is the use of a machine file and you can hardcode one into your configure shell script.

**Comment by bonzini** [comment]
Sure, however:

1) that would require putting the path to python explicitly in all the custom targets and generators; meson's find_program (and hence custom targets and generators) does have a preference towards invoking them with the same interpreter that was used to run meson itself, which it uses if the argument is a non-executable Python script

2) this would indeed avoid possible confusion with respect to meson, but it would not do so for sphinx-build and other tools. And it is even more important to have a consistent environment because sphinx-build does run Python code supplied by the user. Therefore I don't see a reason to special-case meson.

**Comment by eli-schwartz** [comment]
> Sure, however:

Well, at least we agree that it was incorrect to say meson doesn't work unless internally used python matches the python from build tools. ;)

> 1) that would require putting the path to python explicitly in all the custom targets and generators; meson's find_program (and hence custom targets and generators) does have a preference towards invoking them with the same interpreter that was used to run meson itself, which it uses if the argument is a non-executable Python script

It has a contextually relevant preference: meson (but not muon) knows that there is always *a* python available, even if it's not the preferred one, so it can use that as a fallback in situations that would otherwise result in a fatal error. Looking for "python3" will only use mesonlib.python_command if it cannot otherwise find a python3 on $PATH.

Put the path to Python in $PATH, rely on either `find_program('python3')` or `#!/usr/bin/env python3` to detect that, and you're golden.

Although meson has yet another heuristic for scripts that aren't executable, I think this is arguably a bug and mostly exists because of Windows anyway. Ideally I'd like to unify the heuristic so that scripts which aren't executable and scripts run as find_program('python3'), run the same way.

> 2) this would indeed avoid possible confusion with respect to meson, but it would not do so for sphinx-build and other tools. And it is even more important to have a consistent environment because sphinx-build does run Python code supplied by the user. Therefore I don't see a reason to special-case meson.

The reason to special case meson is because meson interacts heavily with the build and host platforms, and especially the build one. As this very bug report demonstrates, sometimes build platforms change and meson has to adapt to that -- and the platform can ship an updated meson or backport patches, which qemu doesn't see with its pinned version.

**Comment by bonzini** [comment]
> qemu doesn't see with its pinned version

The bundled version is only a fallback. It's intended to be used with old distros not new one. The reason why this fails is the combination of Sonoma needing a very new Meson, *and* Homebrew's peculiarity that the Python interpreter in its "cellar" [is not used by default except by other Homebrew packages](https://docs.brew.sh/FAQ#what-does-keg-only-mean).

So if anything this is an interaction between opposite designs/expectations in QEMU and Homebrew, which doesn't even extend to other environments. IME this is a common misunderstanding of how Homebrew works and leads to misery when mixing pip- and brew-installed packages.

**Comment by eli-schwartz** [comment]
But the meson command *is* available in $PATH, right?

**Comment by bonzini** [comment]
Yes, but we're going in circles. Using the meson in the path would leave the same problem that sphinx and other Python packages installed into the "keg-only" Homebrew interpreter would not be usable. And it would (at least with all current and past releases of Meson) require a change to all custom_targets and generators.

If you want to change the behavior of py.find_installation() and of non-executable Python scripts to use find_program('python3'), I wouldn't complain. But I think it might have backwards compatibility implications and I am not sure it's doable. For example in the case of Homebrew it would switch from using the keg-only Python to the system one, and any uses of "python3 -m xxx" would fail to find packages installed via Homebrew. Basically the same breakage that is affecting QEMU's configure script when it tries to detect Meson.

**Comment by eli-schwartz** [comment]
Meson has never made any guarantee that its internal fallback python impl is useful for any purpose outside of the standard library. That's why it is intended to be a last-ditch best-effort fallback when find_program() would otherwise simply... fail. I admit that that intention is inconsistently enforced.

In fact, if you try to use the `*.msi` installer for meson on Windows, or the `*.dmg` installer for meson on macOS, you'll get an *extremely* private copy of python, that being the one which PyInstaller embeds into the executable and then extracts on the fly into your tmpdir each time you launch the entrypoint executable. You cannot add additional python packages to this in any manner.

(You can build an installer for Linux too, but mostly nobody bothers. I refactored the installer packaging to make it *possible* to do linux as well, purely because I needed a way to manually test fixes for the Windows installer.)

**Comment by faithseed** [comment]
For the specific Qemu compile error, you could work around with

```
brew install meson
./configure –enable-cocoa –target-list=i386-softmmu –disable-vnc --disable-bsd-user --disable-guest-agent --python=/usr/local/bin/python3.12
```
