### ISSUE TITLE
Python module: `install_sources()` seems to lack documented functionality.

### ISSUE THREAD

**Issue by blochl** [mesonbuild/meson#12601]
**Describe the bug**
The documentation states that for `install_sources()` "All positional and keyword arguments are the same as for `install_data()`" ([link](https://mesonbuild.com/Python-module.html#install_sources)).
But in practice, it seems not to be the case, as I get the following error:
```
ERROR: python_installation.install_sources got unknown keyword arguments "install_dir", "install_mode", "rename"
```

**To Reproduce**
Example:
```meson
py_mod = import('python')
py = py_mod.find_installation()
py.install_sources(
  'myprogram.py',
  rename: 'myprogram'
  install_dir: join_paths(get_option('prefix'), get_option('bindir')),
  install_mode: 'rwxr-xr-x',
)
```

**Expected behavior**
I expect that `myprogram.py` would be installed to `/usr/local/bin` as `myprogram`, with 755 permissions.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
    * Just want to copy a file, no build involved.
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.)
    * Ubuntu 22.04.
* what Python version are you using e.g. 3.8.0
    * 3.10.12
* what `meson --version`
    * 0.61.2 (but the same is happening with 1.3.0 - tried upgrading - no change)
* what `ninja --version` if it's a Ninja build
    * 1.10.1

**Comment by rgommers** [comment]
These keywords may have been left out on purpose, because:
- `install_dir` should typically not be used, the `py.install_sources`-specific `subdir` keyword replaces it. leaving `install_dir` in place may be confusing
- `install_mode`: should not apply to anything being installed into a Python site-packages directory

`rename` I'm less sure about though, that could make sense for `install_sources` (we had a need for this in https://github.com/scipy/scipy/pull/19701, worked around by using `install_data` instead).

At a minimum this requires a doc fix indeed.
