### ISSUE TITLE
Allow dry-run installation

### ISSUE THREAD

**Issue by Nikratio** [mesonbuild/meson#1281]
It'd be great if there was a way to support a "dry run" installation. At the moment, calling `ninja -d install` isn't helpful at all, because it just shows that it would call Meson.

**Comment by nirbheek** [comment]
This is not possible to implement in Meson because Ninja doesn't actually run anything in dry-run (`-n`) mode (internally, it implements a fake class that just returns `true` without doing anything), so no Meson scripts would be called at all.

Maybe we can implement a `dry-install` Ninja target that will call all the scripts in a dry-run mode.

**Comment by mine260309** [comment]
I would like to see this function as well, e.g. I would like to see which service files are going to be installed to the system directory, without actually installing them.

**Comment by braindevices** [comment]
any progress on this? I just want see same output as `make -n install`.

**Comment by xclaesse** [comment]
Should be pretty easy to implement now that we have 'meson install' command.
