### ISSUE TITLE
[question][UNIX] Is it possible to avoid adding the `prefix` value to `DESTDIR`?

### ISSUE THREAD

**Issue by franramirez688** [mesonbuild/meson#12880]
It does not matter if I'm adding or not any `prefix` value to the `setup` step as it's always adding the default value or the given one to the DESTDIR path:

```bash
$ meson setup --help
....
options:
  -h, --help                             show this help message and exit
  --prefix PREFIX                   Installation prefix (default: /usr/local).
```

```bash
$ meson setup .  src 
The Meson build system
Version: 1.3.1
.........

  User defined options
    Native files: /Users/franchuti/develop/conan/mesonsss/test_package/build-release/conan/conan_meson_native.ini

Found ninja-1.11.0 at /usr/local/bin/ninja
```
```bash
$ DESTDIR=/my/abs/path meson install -C xxxxxx
ninja: Entering directory `xxxxxxx'
ninja: no work to do.
Installing libmylib.a to /my/abs/path/usr/local/lib
Installing src/mylib.h to /my/abs/path/usr/local/include
```
Notice that it can be used `--destdir xxxx` if the meson version is >= 0.57.

As you can see the installation path is composed by:

```
{DESTDIR}{prefix}{libdir}
```

My **meson.build**:

```python
project('mylib ', 'cpp')
library('mylib', 'src/mylib.cpp', install: true)
install_headers('src/mylib.h')
```

Is there no other way to keep the prefix empty?

Related issue: https://github.com/mesonbuild/meson/issues/2535

## Workaround

I'm passing `--prefix "/"` in the setup process, and it seems to work fine. Tested on macOS and Linux.

For the record, Windows seems to not define any prefix by default, so it'd be enough to use:
```bash
set "DESTDIR=/my/abs/path" && meson install -C xxxxxx
```

**Comment by eli-schwartz** [comment]
This appears to be a case of mistaken identity.

Prefix is never added to DESTDIR. It is added by default to `install_dir: 'xxx'`.

The purpose of install_dir is to be known at compile time, frequently compiled as `'-DPREFIX='+join_paths(get_option('prefix'), get_option('datadir'))` into the source code of the software, so that the program can be made aware of the path relationship between different types of installed files. Not all software needs this functionality but a tremendous amount for.

DESTDIR primarily exists for the sake of Linux distros and other UNIXes. Its purpose is to allow installing the software to a different location from the one it will be used in, and linux distros use that to install the software into a temporary directory and then tarball up that directory into an installer format such as .deb or .rpm or .pkg.tar.zst or .gpkg.tar or .apk or .xbps. It is also useful for cases such as cross compilation e.g. in yocto/buildroot where the files are installed into an emulated sysroot and later the entire directory is turned into a flashable operating system image.

> Related issue: #2535

Note that this issue is not related. #2535 was a report that the "DESTDIR" and "prefix" functionalities were both acting correctly and designed correctly but that the default value of "libdir" was incorrect during cross compilation.

**Comment by eli-schwartz** [comment]
What is your overall objective that led you to explore the possibilities of DESTDIR?

**Comment by franramirez688** [comment]
In a nutshell, I want to compile my sources in my build folder and install them in another completely different one. Why? I'm part of the Conan team, and we use the build folder to configure/compile the libraries/applications, and then, install the binaries, headers, etc. into the package one which is completely different.

At compilation time, we don't know the package folder, so we are doing something like:

```
# Compilation process (no --prefix is passed)
$ meson setup ....
$ meson compile .....
# Installation process (now, we already know the install dir so we pass the --prefix)
$ meson setup ........  --prefix /my/package/folder --reconfigure
$ meson install ......
```
That's the reason why I'm trying to use the DESTDIR variable to avoid such reconfiguration:
```
# Compilation process (avoid using meson setting default one)
$ meson setup ...... --prefix "/"
$ meson compile ......
# Installation process (no need to reconfigure anything)
$ DESTDIR=/my/package/folder meson install .......
```
I hope it's clearer now.

**Comment by bruchar1** [comment]
I think using `prefix=/` and DESTDIR pointing to package folder really is what you want in the context of conan, since you install all your files relative to the root (i.e. prefix) of the package folder (i.e. DESTDIR). And you probably need to define `prefix=/` on Windows as well. `prefix` makes sense when you are installing files directly on a system (e.g. in `/usr/local`); in the context of conan, your final destination is dynamically computed by conan.
