### ISSUE TITLE
[Question] What is the purpose of subproject.found() and how to check for non-existent subproject?

### ISSUE THREAD

**Issue by fukanchik** [mesonbuild/meson#12883]
Meson version: 0.61.2.

I have the following minimal buildfile:
```
project('xxx', 'c')

non_existent_proj = subproject('non-existent')
if non_existent_proj.found()
 message('FOUND')
else
 message('NOT FOUND')
endif
```

In case of a missing subproject I am expecting message "NOT FOUND", however I am getting just an error:
```
meson.build:3:0: ERROR: Neither a subproject directory nor a non-existent.wrap file was found.
```
This is not what `found()`'s function name suggests.

I'm not sure if this is a bug or feature, hence marking it as a question.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Reference-manual_functions.html#subproject_required

By default a subproject must be found and failing to find it is an immediate error, which happens before you can get far enough in the build file to execute .found() -- hence if you did get that far, it is always going to equal "true".

However you can designate a subproject as optional. The standard reason for this is because it's an optional feature and the subproject may have requirements that cannot be met, so the subproject errors out. But with `required: false` that converts to a warning that "the subproject failed to configure", and checking .found() is how you detect this from meson.build.

**Comment by fukanchik** [comment]
Ok, thanks for the help.
