### ISSUE TITLE
Question: How to set a default number of jobs (meson compile -j <num>)?

### ISSUE THREAD

**Issue by gabeblack** [mesonbuild/meson#12911]
Our meson project uses a cross file to configure the build to use `distcc` to distribute the build to a build farm. The build farm obviously has many cores, but where meson is actually being invoked, there are very few cores. 

I tried looking at the code and it appears there isn't a project setting, cross-file option, environment variable, or any way to configure the default number of jobs to use to compile the project. The project is very, very, large so using a large number for "meson compile -j<num>" is very much desired. 

Is there a way to configure a default value for the number of jobs to use that will exceed the number of cores where meson is being run?

I know it is trivial to ask the dev to pass in `-j <num>` to the command line, but it would be nice if a value could be configured by default.

**Comment by eli-schwartz** [comment]
> I know it is trivial to ask the dev to pass in `-j <num>` to the command line, but it would be nice if a value could be configured by default.

If it is so trivial, why not do it?

> I tried looking at the code and it appears there isn't a project setting, cross-file option, environment variable, or any way to configure the default number of jobs

It can't be a project setting, because projects shouldn't be dictating how many cores a user has.

Environment variables are the right thing to do here, really. In particular, GNU Make has `$MAKEFLAGS`, and samurai (the c99 rewrite of ninja) has `$SAMUFLAGS`.

Ninja should really respect $NINJAFLAGS. It's been asked a tremendous number of times, but the ninja developers thus far haven't accepted one...

**Comment by xclaesse** [comment]
Not that I suggested a while ago to add MESONFLAGS to make it backend independent: https://github.com/mesonbuild/meson/pull/9163

**Comment by eli-schwartz** [comment]
> I read the thread. I agree with @xclaesse that `meson compile` should be the interface used (and that is what I gathered from the meson documentation).

The meson documentation is disputed. It gives you a narrow, single sided view of things, and frequently has outright broken because it was factually incorrect to believe that `meson compile` supported doing the thing the documentation claimed.

To be perfectly clear: `meson compile` was originally created as a wrapper abstraction around msbuild and xcodebuild, which are non-default backends -- the default, simple, straightforward, universal interface is ninja. The interface of `meson compile` is actually pretty simple, because what it does is: "translate foreign idioms back to ninja compatible semantics".

Ninja doesn't support specifying in a file (definitely not inside `build.ninja`) how many jobs to use.

You don't want to specify this anywhere, anyways, because there's an open PR to ninja that adds GNU Make jobserver support, which *must* be used when active, and therefore having meson set -j is wrong.

So we are now up to a whole bunch of ways to set the number of jobs in a meson based project:
- ninja -j8
- meson compile -j8
- export SAMUFLAGS=-j8; samu
- make -j8 # launches ninja-kitware-fork internally


None of these are going away, period, end of story. Not only would it break backwards compat to do so, it's also physically impossible for meson to remove any but the second method even if it wanted to.

All you want to do is add another way to do it.

**Comment by gabeblack** [comment]
> The meson documentation is disputed. It gives you a narrow, single sided view of things, and frequently has outright broken because it was factually incorrect to believe that meson compile supported doing the thing the documentation claimed.

Asserting that one shouldn't believe documentation as a reason that they shouldn't do what the documentation says doesn't seem well grounded. I think following documentation is a PRO. If the documentation is wrong; then it should be fixed.

> So we are now up to a whole bunch of ways to set the number of jobs in a meson based project:
> 
> ninja -j8
> meson compile -j8
> export SAMUFLAGS=-j8; samu
> make -j8 # launches ninja-kitware-fork internally

Don't forget hacking the system to present a fake number of cores! Only one of the above bullet points is through meson. Yes, one can always bypass underlying build frameworks and go one layer down. One can invoke ninja directly. Or invoke Make. Or invoke the thing that make invokes., Or invoke the compiler directly, etc. etc. Just because you can do something to accomplish the same goal, doesn't mean you should. I don't think we should be recommending that people bypass meson and go directly to the backend, even if today the interface intends to mimic the default ninja backend.

The major appeal for meson for me was "making build systems not suck". If I have to know what backend meson is using under the hood and then learn the documentation for that backend -- well, that sucks. I have ported a lot of projects/subprojects over to meson in our company in the last year and this is the first that I've heard that I should be using ninja instead of meson. TBH, I don't think we should even require to know what's under the hood much less open the hood and control things from there. Doing so seems I think violates the 'configuration in one place' design goal. Furthermore, it "locks" you in to that backend.

> None of these are going away, period, end of story. Not only would it break backwards compat to do so, it's also physically impossible for meson to remove any but the second method even if it wanted to.

If someone bypasses running `meson compile` and invokes `ninja` or `samu` or `make` or whatever directly, then it is on them to reap the results of bypassing meson. 

> All you want to do is add another way to do it.

Yes. That is true. And if it isn't a high-enough priority to make it configurable, then that IMO is a totally valid reason. Especially since there _is_ already a way to do it. IMO, having an existing (meson) way to specify the number of jobs is probably argument enough not to do it. 

Anyway, I'm going to close the question, as my question is answered, and I appreciate the quick response as always and the additional dialog :-)

**Comment by eli-schwartz** [comment]
> Asserting that one shouldn't believe documentation as a reason that they shouldn't do what the documentation says doesn't seem well grounded. I think following documentation is a PRO. If the documentation is wrong; then it should be fixed.

I think it's a tremendous mistake that people have been given the impression they are "doing it wrong" to use `ninja`. Which is what the current documentation suggests.

Unfortunately, writing docs is hard, and status quos tend to win, especially when a change sneaks in under the radar.

The reality is that `meson compile` exists as a convenience mechanism for people to choose, if they choose to use it. No more, no less. 

> If I have to know what backend meson is using under the hood and then learn the documentation for that backend -- well, that sucks. I have ported a lot of projects/subprojects over to meson in our company in the last year and this is the first that I've heard that I should be using ninja instead of meson. TBH, I don't think we should even require to know what's under the hood much less open the hood and control things from there.

And you're entirely right! For you.

Again, that's why `meson compile ` was created, so that people don't *have* to care about the backend if they don't *want* to, because there's a oneshot command that covers the basic use and simply "builds the project by default".

That doesn't mean the tool doesn't exist underneath. It just means you're opting to not particularly care as long as you can tell it "stop asking me questions. Just build already".

IMHO this is kind of the opposite of wanting to fine-tune your control with things like job accounting and load averages.

> If someone bypasses running `meson compile` and invokes `ninja` or `samu` or `make` or whatever directly, then it is on them to reap the results of bypassing meson.

There are no results to reap. If you prefer running `meson compile` because you don't have to know what the command runner is, that's fine and you're welcome to do so. But that doesn't mean other people have to do the same. Nor that we should fork the UX to the point where meson behaves radically differently depending on whether you use an optional wrapper.
