### ISSUE TITLE
`meson setup --reconfigure` handling of builtin options is broken in git master

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/meson#12920]
Builtin options are not handled correctly when specified on the `meson setup --reconfigure` command line.

**To Reproduce**

```console
$ cat > meson.build <<EOF
projet('foo')
EOF 
$ meson setup build
$ meson setup build --reconfigure -Db_ndebug=true
The Meson build system
Version: 1.4.0.rc1
Source dir: /private/tmp/test-meson
Build dir: /private/tmp/test-meson/build
Build type: native build

meson.build:1:0: ERROR: Unknown options: "b_ndebug"

A full log can be found at /private/tmp/test-meson/build/meson-logs/meson-log.txt
```

**Comment by dnicolodi** [comment]
The bug is introduced by #12697 20c9f3e621581b2ed9a1c6872b86c4dc9390aa6b

**Comment by dnicolodi** [comment]
The issue is caused by 20c9f3e621581b2ed9a1c6872b86c4dc9390aa6b #12697 (which is a bit hilarious, given the commit message).

**Comment by bruchar1** [comment]
You are right. The problem is more complex than I thought. I think I have a better fix, but I need to test it before submitting it.

If you simply revert the mentioned commit, it doesn't fail, but the option it not reconfigured, despite the displayed message. I think the problem also applies to compiler options (in fact, base options are a kind of compiler options). And I'm not sure how to handle this in the case there are no compiler at all. It seems that in a project having no compilers, setting a base option does not set the option at all in the internal coredata.
