### ISSUE TITLE
Does meson support any IDE backend on Linux at the moment?

### ISSUE THREAD

**Issue by adamryczkowski** [mesonbuild/meson#1300]
Like Eclipse? QT Designer? Code::blocks?

All I see is Visual Studio for Windows and Xcode for Mac.

**Comment by ignatenkobrain** [comment]
I think at this point, GNOME Builder only.. (but I'm not sure)

**Comment by TingPing** [comment]
Yup, Builder support should be decent and eventually it should get more advanced. If somebody wants to make plugins for other IDEs it is fairly easy: https://github.com/mesonbuild/meson/wiki/IDE-integration

**Comment by agauniyal** [comment]
I once [asked](https://github.com/cppit/jucipp/issues/250#issuecomment-240589087) of support for meson in jucipp IDE and they delivered it pretty quickly. So there's one more.

**Comment by nirbheek** [comment]
The reason why we have our own backends for XCode and Visual Studio is because it is extremely unlikely (almost impossible) that the upstream projects will add support for Meson. XCode lives in its own little garden and pretends nothing else exists, and we're not big enough for Visual Studio to care about us.

However, it makes much more sense for IDEs to add support for Meson in their own codebase because it allows for much better integration. Some projects are doing that, but it's not up to us what they do. :)
