### ISSUE TITLE
[feature] Add a builtin option to install targets by default

### ISSUE THREAD

**Issue by Freed-Wu** [mesonbuild/meson#13116]
https://mesonbuild.com/Installing.html

> By default Meson will not install anything. Build targets can be installed by tagging them as installable in the definition.

Can we add a builtin option to install targets by default?

TIA!

**Comment by eli-schwartz** [comment]
That doesn't feel like it makes much sense. Whether a target makes sense to install or not is a project choice, not a choice of the person performing the build. It would be silly to install internal static libraries used purely as common object libraries for multiple binaries. It would also be silly to install code generators written in C/C++.

It would be outright impossible to install custom_target outputs because:
- many are transitive outputs that are only used as inputs for other targets
- they don't have anywhere meaningful to install them, not even "stick them in bindir" like executables do

**Comment by eli-schwartz** [comment]
I'm unaware of any prior art in other build systems for doing this, either.
