### ISSUE TITLE
meson does not run build scripts for "Cargo wraps" (Rust crates)

### ISSUE THREAD

**Issue by decathorpe** [mesonbuild/meson#13144]
**Describe the bug**

Rust crates can use a build script (by convention, `build.rs` in the project's root directory, but this can be configured in Cargo.toml) to look at the build environment and forward compiler flags based on it - usually for conditional compilation (like `-DHAVE_LIBFOO_1_1_0` for C / C++ projects).

Currently, meson does not run these build scripts, so this "configure" step is missing when building wrapped Rust crates as dependencies.

This has started to impact mesa builds in Fedora since we updated the proc-macro2 crate to the latest version:

- https://bugzilla.redhat.com/show_bug.cgi?id=2277018
- https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28923

The proc-macro2 crate introduced support for new Rust syntax that will be stabilized in Rust 1.79. The build script disables this functionality when building with Rust < 1.79. But since meson doesn't run the build script, the crate fails to compile with Rust 1.77: https://github.com/dtolnay/proc-macro2/blob/master/build.rs

**To Reproduce**

Try building any Rust crate dependency with a build script.
The build script is not run, cfg flags are not passed as required.

**Expected behavior**

Meson could compile and run the build script, collect output (lines in the form of `cargo:rustc-cfg=foo`), and pass `--cfg=foo` when building the crate accordingly.

Without this, building Rust crates with meson will either fail or produce invalid results for any crate that uses a build script.

**system parameters**

* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? No
* what operating system? Fedora Linux (any version)
* what Python version are you using? Python 3.12 (also Python 3.11)
* what `meson --version`? 1.4.0
* what `ninja --version` if it's a Ninja build? 1.11.1

**Comment by eli-schwartz** [comment]
> Rust crates can use a build script (by convention, `build.rs` in the project's root directory, but this can be configured in Cargo.toml) to look at the build environment and forward compiler flags based on it - usually for conditional compilation (like `-DHAVE_LIBFOO_1_1_0` for C / C++ projects).

Instead of compiling a rust program that echoes compiler flags to stdout after running the rust version of `if rustc.version().version_compare('>=1.79.0')`, just do this in meson.build

Meson can't run build.rs scripts because:
- it can't deliver crate dependencies for them
- virtually all use cases are either:
  - duplicating the work of build system if statements to add compile flags
  - actually compiling dependencies, which violates meson's hard guarantees
- compiling programs at setup time is a user disservice, especially if it's in a language known far and wide for being quite slow. Running `meson setup` should be as fast as possible.

The crate support already allows you to drop in your own overlaid meson.build file for injecting custom logic such as adding project flags. This is the expected and idiomatic way to handle more complex crates in meson. Especially for a very simple build.rs, the meson port should be extremely easy to do.

**Comment by decathorpe** [comment]
Ok, so you consider this a bug in how mesa uses meson to build proc-macro2, because they didn't rebuild the build.rs logic in an additional meson.build file?

**Comment by dcbaker** [comment]
@decathorpe I'm both a Mesa and Meson developer, and I've spent some time thinking about this problem. I started working on [a crate](https://github.com/dcbaker/toml-describe) to make this simpler.

But yeah, if we're not replicating the logic in meson.build we're doing it wrong.

**Comment by decathorpe** [comment]
Thanks for confirming. Just wanted to make sure, since people started complaining *to me* that I broke mesa when I updated proc-macro2 crate in Fedora a few days ago :)

**Comment by dcbaker** [comment]
@decathorpe feel free to ping me on stuff like this around mesa, I'm dcbaker most places, but I'm dbaker at the fdo gitlab

**Comment by decathorpe** [comment]
The mesa package replaces the wrapped / vendored Rust crate sources with versions that are packaged for Fedora. The mechanism for doing that is a bit brittle (as we see here), but we didn't want to build mesa from different sources than other Rust applications in Fedora.

**Comment by dcbaker** [comment]
If you're going to do that, you're going to need to update the meson definitions in Mesa as well.
