### ISSUE TITLE
Issue with Debian distro instllation for 1.5.0 release of Meson via pip install command

### ISSUE THREAD

**Issue by dreamer-coding** [mesonbuild/meson#13432]
**Describe the bug**
I was running my tests and the Debian Docker image complained about 1.5.0 being unavailable, I had not specified any versions of Meson for the test to use.

**To Reproduce**
Run pip install command for meson on a given Debian system.

![Screenshot 2024-07-15 092523](https://github.com/user-attachments/assets/b4005228-27de-40c3-a3d2-0f166ce1c6a4)

**Expected behavior**
I expect this to simply install Meson and not fire any issues during general use or even for CI test cases.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)?
* what operating system Raspberry Pi
* what Python 3.12.0
* what `meson 1.5.0`
* what `ninja 1.11.0` if it's a Ninja build

**Comment by eli-schwartz** [comment]
Please, as a general rule of thumb, provide a copy-paste of the terminal output inside of code backticks -- not screenshots of text, which can be hard to read.

It looks like this isn't actually saying meson 1.5.0 is unavailable, rather, pip installed meson successfully but https://github.com/pypa/setuptools/ generated a broken script.

Note also that it's impossible for you to have used Python 3.12.0 and gotten that error, since `importlib.metadata` is part of the python standard library.
