### ISSUE TITLE
pkg-config caching does not consider native/cross

### ISSUE THREAD

**Issue by fooishbar** [mesonbuild/meson#1366]
pkg-config appears to cache pkg-config files with no regard as to whether they're native or not. Using Wayland from here:
https://git.collabora.com/cgit/user/daniels/wayland.git/log/?h=wip/2016-11/meson

When cross-compiling, we build the scanner twice: once natively and once cross. The libxml-2.0 dependency will be cached, and the values will be reused. I tested this by changing the libxml-2.0.pc in the cross chroot to contain total nonsense, none of which propagated to the build as it was just using the cached native dependency.

**Comment by nirbheek** [comment]
This is a pretty serious bug, but the fix should be simple. It's a regression from a previous version of Meson, so I think this should go into the bugfix release.

Also, I noticed that it's a common use-case to build an executable both native (for use as a generator) and cross (for installation). We should add built-in support for that so that we create two targets: one cross and one native, when someone passes `native: 'both'` (or something like that). Maybe do it implicitly when an installable executable is `native: true`? Does anyone ever want to install a native executable into a cross prefix?

**Comment by msink** [comment]
I do not understand at all why this kwarg is needed.
For example:
```
threads = dependency('threads')
zlib = dependency('zlib', native: false)
zlib_native = dependency('zlib', native: true)

type_generator = executable('type_generator',
  ...
  dependencies: [threads, zlib_native],
  native: true)

libavian = static_library('avian',
  sources: [
    ...
    generated_code,
  ],
  ....
  dependencies: [threads, zlib],
)
```

Why meson could not deduce native or not dependency is needed, like this:
```
threads = dependency('threads')
zlib = dependency('zlib')

type_generator = executable('type_generator',
  ...
  dependencies: [threads, zlib],
  native: true)

libavian = static_library('avian',
  ....
  dependencies: [threads, zlib],
)
```

**Comment by nirbheek** [comment]
1) It is not always obvious from the context whether you want the native or the cross version of a dependency; for example if you use it in a custom target or to fetch a variable.

2) This complicates parsing/evaluation since you now have to "lazy" evaluate it based on later usage. This would involve significant parser rework for no real gain.

3) Makes it non-obvious what is intended while reading the build file.

4) The interaction with subprojects and declared dependencies is even stranger; for instance what do you do if a dependency is only added as part of a `declare_dependency()` and not used anywhere inside the project, and is meant to be used by an outer project?

**Comment by jpakkane** [comment]
> We should add built-in support for that so that we create two targets: one cross and one native, when someone passes native: 'both'

There can be only one executable with a given name, cross targets are not separately namespaced. They might also need different dependencies etc so it is not quite as simple.
