### ISSUE TITLE
git rebase

### ISSUE THREAD

**Issue by spaette** [mesonbuild/meson#13672]
Possibly this is considered as bloat.

docs/markdown/Contributing.md

```diff
 be resolved. The basic rule for this is very simple: keep your pull
 request up to date using rebase _only_.
 
+- `git clone -q https://github.com/username/meson.git && cd meson`
+
+- `git remote add upstream https://github.com/mesonbuild/meson.git`
+
+- `git fetch -q upstream && git rebase upstream/master`
+
+- `git push -f origin master`
+
 Do not merge head back to your branch. Any merge commits in your pull
 request make it not acceptable for merging into master and you must
 remove them.
```

above hypothetical (added lines) applicable where 

a forked repo's master <kbd>default</kbd> branch has had changes committed thereto

adjustments could be made either to the commands or the .md file's surrounding text

dealing with a branch conflict

into `mesonbuild:master` from `username:master`

a merge conflict isn't resolved via syncing a fork with upstream

```
$ sed -n '21,30p' meson/docs/markdown/Contributing.md
## Keeping pull requests up to date

It is possible that while your pull request is being reviewed, other
changes are committed to master that cause merge conflicts that must
be resolved. The basic rule for this is very simple: keep your pull
request up to date using rebase _only_.

Do not merge head back to your branch. Any merge commits in your pull
request make it not acceptable for merging into master and you must
remove them.
$ 
```

<hr>

@dcbaker 

a few more typo fixes are in `#13677`

**Comment by SirNate0** [comment]
It seems odd to me that the user would be using their master branch for the proposed changes. Perhaps change to `pr-branch` instead of `master`. It also isn't clear that the first one/two bullet points are suggestions for how to initially set up the repository, while the remaining are about how to go about doing the rebase. Perhaps just remove the first bullet, and add a comment to the last line that you are pushing to your github fork of meson. If the user doesn't know how to clone a repository then he/she probably won't be able to handle doing the rebase, so the first line is only useful in conveying that `origin` is referring to `https://github.com/username/meson.git`. (Further, this should probably be the SSH url and not the HTTPS one, i.e. `git@github.com:username/meson.git`, as HTTPS pushing is [hard to set up](https://stackoverflow.com/questions/76717441/is-it-possible-to-git-push-with-https-protocol))

---

Hope this saves someone a minute in discerning what they are, but the typos are specifically spelling issues:

- `executable` has `t` and `u` flipped: `exectuable`
- `returning` is missing the `r`: `retuning`
- `series` is missing the final `s`: `serie`

**Comment by spaette** [comment]
rendered as shell output 

```diff
  be resolved. The basic rule for this is very simple: keep your pull
  request up to date using rebase _only_.
   
+ ```console
+ $ cd /tmp/meson # clone of forked repo
+ $ git remote add upstream https://github.com/mesonbuild/meson.git
+ $ git fetch -q upstream
+ $ git rebase upstream/master
+ Successfully rebased and updated refs/heads/master.
+ $
+ ```
+
  Do not merge head back to your branch. Any merge commits in your pull
  request make it not acceptable for merging into master and you must
  remove them.
```

**Comment by spaette** [comment]
@eli-schwartz 

Would you have an opinion on the pertinence of the .md file's section?

Rebasing is occasionally mentioned in PRs' comments, but maybe the section "Keeping pull requests up to date" is factually a legacy of the time when the Meson documention was on a Wiki, and therefore could simply be deleted.

**Comment by spaette** [comment]
> simply be deleted

Deleting the section seems the best way forward.

<hr>

The GitHub website has some time ago implemented a button to click for rebasing.

I don't have info on what results using that button when certain file changes need to be reverted for a rebase.

The above scenario is clear in a command line interface as terminal output is returned specifying the offending files.
