### ISSUE TITLE
gnome.genmarshal() incorrectly splits the Python path if it contains spaces

### ISSUE THREAD

**Issue by danyeaw** [mesonbuild/meson#13804]
**Describe the bug**
If Python is installed in a location with a space in the path, then calling `gnome.genmarshal()` fails.

For example, create a virtualenv at C:\Program Files (x86)\venv, then try to compile gdk-pixbuf. It gives an output like:

```
[1/156] Generating glib marshaller header gdk-pixbuf/gdk-pixbuf-marshal_h
FAILED: gdk-pixbuf/gdk-pixbuf-marshal.h 
"C:\Program" "Files (x86)/venv/Scripts/python.exe" "C:/gtk-build/gtk/x64/release/bin/../bin/glib-genmarshal" "--quiet" "--prefix" "_gdk_pixbuf_marshal" "--output" "gdk-pixbuf/gdk-pixbuf-marshal.h" "--header" "../gdk-pixbuf/gdk-pixbuf-marshal.list" "--pragma-once"
CreateProcess failed: The system cannot find the file specified.
```

See that `Program Files (x86)` was split, which causes the command to fail.

This is actually a common thing to happen with GitHub Actions, because pipx is installed to C:\Program Files (x86)\pipx.

**To Reproduce**
Build gdk-pixbuf with spaces in the Python path

**Expected behavior**

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.) Windows 11
* what Python version are you using e.g. 3.8.0  3.12.7
* what `meson --version` 1.5.2
* what `ninja --version` if it's a Ninja build  1.12.1

**Comment by dcbaker** [comment]
@nirbheek, @xclaesse there was another issue recently kinda like this, is this a duplicate?

**Comment by lb90** [comment]
I have incurred into this as well. Interestingly, installing Python into a directory without spaces is not sufficient to work around the issue. `glib-genmarshal` hardcodes the full path to python.exe in its shebang:

```python
#!C:\Program Files\Python311\python.exe

# pylint: disable=too-many-lines, missing-docstring, invalid-name

# This file is part of GLib
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import re
import sys
```

 So what really matters is the Python that was used to build GLib

**Comment by lb90** [comment]
The shebang is read in [ExternalProgram._shebang_to_cmd](https://github.com/mesonbuild/meson/blob/4ac3e7d356cfc1a6a290cd6961f01c11510c0618/mesonbuild/programs.py#L173), however it cannot just quote the string, because it may contain arguments. That's stated in the comment at line 183:

```
# In a shebang, everything before the first space is assumed to
# be the command to run and everything after the first space is
# the single argument to pass to that command. So we must split
# exactly once.
```

So quoting should be applied when writing the shebang

**Comment by lb90** [comment]
Writing of the shebang is done by GLib: https://gitlab.gnome.org/GNOME/glib/-/commit/013980d8

**Comment by lb90** [comment]
Are shebangs supposed to be shell quoted or not? If that's the case, perhaps Meson could use `shlex.split`

That said, we can fix this in Glib

**Comment by danyeaw** [comment]
I think this should be fixed in GLib, closing it here.

**Comment by eli-schwartz** [comment]
> Are shebangs supposed to be shell quoted or not? If that's the case, perhaps Meson could use `shlex.split`
> 
> That said, we can fix this in Glib

Nope, posix shebangs don't support paths with spaces in the names at all. You're simply not allowed to do it -- you have to write a shebang pointing to an interpreter that doesn't have a space, such as `#!/bin/sh`, and then have that file be a polyglot script that parses as valid shell and also valid Python, which then runs the properly quoted path to Python as a *shell command* passing $0 as the argument to python.

Shebangs on Windows are a confusing concept in general since Windows doesn't use them and from meson's perspective they are a convenience to try to "fix" up scripts that were designed for posix systems. Making them behave different from the posix systems they are trying to emulate would be even more confusing.

**Comment by danyeaw** [comment]
I updated https://gitlab.gnome.org/GNOME/glib/-/issues/3331 with a new proposal based on a lot of feedback I received on my merge request. Please provide any feedback to that proposal, thanks!
