### ISSUE TITLE
gnome: compile_resources: can't take custom_target or configure_file as input XML

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#1380]
If I generate a gresources.xml file with a python script and a custom_target, and then pass the custom_target as input file to compile_resources(), I get:

```
  File "/usr/share/meson/mesonbuild/interpreter.py", line 982, in method_call
    value = fn(state, args, kwargs)
  File "/usr/share/meson/mesonbuild/modules/gnome.py", line 108, in compile_resources
    raise RuntimeError('Unreachable code.')
```
(This is what's done in Gtk+ fwiw).

**Comment by nirbheek** [comment]
The reason why this happens is because we need access to the xml file to generate dependencies with `--generate-dependencies` during configure time. We could maybe skip dependency generation in this case with a warning?

The best thing to do is to use `configure_file()` to generate the xml file. Also we should not show a traceback here. An error message would be better.
