### ISSUE TITLE
could'nt compile Glib

### ISSUE THREAD

**Issue by Mondo67244** [mesonbuild/meson#14010]
Found ninja-1.10.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C '/home/me/Téléchargements/libadwaita/glib-2.76.5/build'
ninja: Entering directory `/home/me/Téléchargements/libadwaita/glib-2.76.5/build'
[1393/1393] Linking target gio/tests/gdbus-test-codegen-min-required-2-64
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 797, in run
    b = build.load(opts.wd)
  File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2868, in load
    obj = pickle.load(f)
ModuleNotFoundError: No module named 'mesonbuild.options'

ERROR: Unhandled python exception

**Comment by eli-schwartz** [comment]
Hi, this indicates that you tried to setup a build directory using meson 1.5.0 installed manually, and then ran ninja from a different context that has the default Debian / Ubuntu version of meson installed, which is much older. It crashed because the Debian version is ***too old*** and doesn't have the protections against mismatched versions that newer versions have.

You cannot switch meson versions without reconfiguring. Newer versions of meson have a dedicated error message to say that you are using an incompatible version of meson.

**Comment by Mondo67244** [comment]
thank you!
