### ISSUE TITLE
[Feature Request] Get value of a feature option

### ISSUE THREAD

**Issue by synalice** [mesonbuild/meson#14038]
Currently, there is no way to get a value, passed to a [feature option](https://mesonbuild.com/Build-options.html#features). Available [methods](https://mesonbuild.com/Reference-manual_returned_feature.html) of a feature object only allow you to query whenever a given feature is `enabled`, `disabled` or `auto`. If a pass any other "4-th" type of value to this option, there is no way to get it.

In my case, I am rewriting an old autotools project where options can be of 4 types (`enabled`, `disabled`, `auto` and `builtin`) (see [line 116](https://git.kernel.org/pub/scm/network/connman/connman.git/tree/configure.ac#n116)).

Am I missing something or is string option type my only... option? (no pun intended)

**Comment by dcbaker** [comment]
It depends what you want to do.

You could use a `combo` option, (which feature is basically a special type of), but you loose the ability to pass the option to various functions that special case `features`. that would be:

```meson
option('opt', type : 'combo', choices : ['enabled', 'disabled', 'auto', 'builtin'])
```

If `builtin` could be mapped back to one of the other options, then you could use the `deprecated` keyword to make the feature map `builtin` to something else, like enabled.

**Comment by eli-schwartz** [comment]
> Currently, there is no way to get a value, passed to a [feature option](https://mesonbuild.com/Build-options.html#features). Available [methods](https://mesonbuild.com/Reference-manual_returned_feature.html) of a feature object only allow you to query whenever a given feature is `enabled`, `disabled` or `auto`. If a pass any other "4-th" type of value to this option, there is no way to get it.

It's a bit "worse" since you actually aren't allowed to pass a 4-th type of value at all. ;) It's a restricted-values option.

> In my case, I am rewriting an old autotools project where options can be of 4 types (`enabled`, `disabled`, `auto` and `builtin`) (see [line 116](https://git.kernel.org/pub/scm/network/connman/connman.git/tree/configure.ac#n116)).

Looking at that project now, I don't see that it cleanly maps onto a meson feature option. Feature options are intended for the case where you want to either enable or disable a feature, with a third possibility of "check if the feature can be enabled, and automatically enable it if possible". It is typically used in cases where an external dependency is required for the feature to be built, and then:
- specifying =enabled will fail the build if the dependency is not installed
- specifying =disabled will simply ignore the dependency whether it is installed or not
- specifying =auto will try to be helpful and pick a good option for the user, depending on whether the dependency is installed or not

In configure.ac build systems, this is usually referred to as `--with-FOO={yes|no|check}`, and meson's "auto" maps to the configure.ac soft-convention "check" (because, it literally means to check something else and then decide whether to act like yes, or act like no).

You're *not* expected to query the type at all, though it is possible to query if you have unusually advanced needs. The point of a feature option is that you can pass the option value itself to a dependency lookup, which then does very clever things that are hard to otherwise replicate.

What connman is doing is very different, it doesn't seem to have any use for hh2serial-gps to be "auto"detected. The functionality has no dependencies and is either always built, or never built, but the "builtin" value causes it to be built, while linked directly into the main program versus being split out as a dlopen plugin. 

> Am I missing something or is string option type my only... option? (no pun intended)

I would suggest using a combo option here and providing 3 options just like configure.ac had -- "enabled" / "yes", "disabled" / "no", and "builtin". Alternatively, you could add a second option instead, e.g.

```
meson setup builddir/ -Dhh2serial-gps=true -Dhh2serial-gps-builtin=true
```
