### ISSUE TITLE
Meson can not install anything

### ISSUE THREAD

**Issue by LucasSom** [mesonbuild/meson#14047]
Trying to install libHSL I run `sudo meson install -C builddir` (after `meson init --build` on an empty directory, `meson setup builddir` and `meson compile -C builddir`) and I get this error:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 146, in run
        return options.run_func(options)
      File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 797, in run
        b = build.load(opts.wd)
      File "/usr/lib/python3/dist-packages/mesonbuild/build.py", line 2868, in load
        obj = pickle.load(f)
    ModuleNotFoundError: No module named 'mesonbuild.options'

    ERROR: Unhandled python exception

        This is a Meson bug and should be reported!

This was run in `Ubuntu 22.04` with `Python 3.10.12`, `meson 1.6.1` and `ninja 1.10.1`.

**Comment by eli-schwartz** [comment]
> Trying to install libHSL I run `sudo meson install -C builddir` (after `meson init --build` on an empty directory, `meson setup builddir` and `meson compile -C builddir`) and I get this error:

> This was run in `Ubuntu 22.04` with `Python 3.10.12`, `meson 1.6.1` and `ninja 1.10.1`.


You have pip installed a new version of meson 1.6.1, since Ubuntu 22.04 ships with meson 0.61.2; this meson version is installed to your user account, not available as root. When you ran `sudo meson install`, it tried to find a root-installed meson program, and could have failed entirely but as it happens you had an older version installed too.

The older version is pretty old. Versions that are newer than the Ubuntu LTS version include special checks for this scenario -- instead of crashing with a traceback, they emit a clear error message saying:

> ERROR: Build directory has been generated with Meson version 1.5.0, which is incompatible with the current version 1.6.0. Consider reconfiguring the directory with "meson setup --reconfigure".
 
or similar. But we can't backport better error handling into the version that comes shipped with Ubuntu LTS. :(

There is some suggested remediation here: https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip
