### ISSUE TITLE
Tell meson to only use ccache if available when specified via CC/CXX

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#1471]
I know that meson will automatically use `ccache` if you call it by itself like `meson build`. But if you want to specify a different compiler you would call meson like this: 

```
CC=clang meson build
``` 

But in this case, `ccache` won't automatically get used.

You can rewrite it like this:

```
CC="ccache clang" meson build
```

But then if `ccache` isn't installed on the machine, the build breaks (I'm assuming).

Is there, or should there be a way to tell meson to use `ccache` if it's available even if you specify the compiler in the `env`?

**Comment by jpakkane** [comment]
Existing unix behaviour is that if `CC` is specified then that, and only that, is used for compilation. Many processes depend on this and there would probably be several angry people if we did something different.

**Comment by rhd** [comment]
Command line option, maybe? --use-ccache-if-available.

**Comment by rhd** [comment]
With that said, if you have `ccache` installed, the only way to get meson to **not** use it is to specify `CC` and/or `CXX`?

Anyway, thanks for responding so quickly - one reason I really like meson - the support from the devs is great.

Feel free to close this issue.

**Comment by TingPing** [comment]
Is using `CC="ccache clang"` really a problem beyond perhaps not being documented?

**Comment by rhd** [comment]
The only issue with`CC="ccache clang"` is that the build will fail if `ccache` isn't installed.

I know that meson detects `ccache` in the default case, I thought it might be nice to detect it when `CC` is specified on the command line.

**Comment by fabio-porcedda** [comment]
If a option like " --use-ccache-if-available" is added, it could be used even for cross compiling for the same reason.

**Comment by RJVB** [comment]
I know this is old - but this only became an issue for me now

> The only issue with`CC="ccache clang"` is that the build will fail if `ccache` isn't installed.

This should in fact be a non-issue. Env. variables are supposed to be set by the user, and if they're set through a wrapper script then that wrapper script could very well check first if ccache is available.

A more annoying issue that I've already encountered (though not with meson) is when some subprocess tries to execute `$CC` or `$CXX` as a single command. Evidently most people won't have an executable called "ccache clang"... 

Personally I like CMake's solution here: provide hooks for the user to specify compiler *launchers*.  This allows to avoid the aforementioned issue, allows any kind of launcher (remember distcc?) but also allows CMake to invoke the compilers without the launcher in cases where it knows that is possible and possibly better.
(caveat emptor: I haven't checked if this approach has already been discussed ad nauseam, I just like it)

**Comment by CarloWood** [comment]
Pretty ridiculous that this was never addressed.
It is exactly as RJVB says: CXX is set to the executable (in your PATH, or specify the full path). If it contains spaces then interpreting those as a command/argument separator is simply a bug. And of course I need to set CC and CXX in order to pick which compiler I want to use. If the result of that is that meson sudden doesn't use ccache anymore then that is clearly broken behavior, ESPECIALLY if then the devs refuse (doing nothing for 8 years is refusing) to add a simple and logical command line option as proposed above.

**Comment by dcbaker** [comment]
Internally we attempt to differentiate launchers like ccache and sccache and not use them when possible. We also attempt to parse `CC` using a shell compatible split (depending on the shell).

**Comment by RJVB** [comment]
> Internally we attempt to differentiate launchers like ccache and sccache and not use them when possible.

And that's supposed to make it clearer for the end user exactly what will happen?

> We also attempt to parse `CC` using a shell compatible split (depending on the shell).

That seems to be at odds with this claim : https://github.com/mesonbuild/meson/issues/1471#issuecomment-286548094 which clearly implies that `$CC` and `$CXX` (and equivalents) are to be used "as is".

**Comment by bonzini** [comment]
> clearly implies that $CC and $CXX (and equivalents) are to be used "as is".

Splitting arguments is needed since other build systems allow `CC='gcc -m32'` for example.

**Comment by eli-schwartz** [comment]
> That seems to be at odds with this claim : [#1471 (comment)](https://github.com/mesonbuild/meson/issues/1471#issuecomment-286548094) which clearly implies that `$CC` and `$CXX` (and equivalents) are to be used "as is".

The comment in question said "that and only that" should be used, not "it should be used as-is".

The defined semantics of $CC as used by I believe all build systems ever, is that it is shell code to be interpolated into a command line including that it shall undergo word spliting, thus it is actually mandatory to use a shell-compatible split and that is how you "use that, and only that".

**Comment by eli-schwartz** [comment]
Also see https://mesonbuild.com/Reference-tables.html#compiler-and-linker-selection-variables and particularly note the changes since 1.3.0

See https://github.com/mesonbuild/meson/issues/11128 and the associated pull request. It fixes the case where it was unintuitive to use 

```
CC='C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe'
```

which is in general the only case where you actually want to represent executable files with spaces inside them.

It also notes in the docs how to quote the contents of CC so that it is parsed correctly as an array containing a command with spaces plus args after another space as well as observing that machine files sidestep the problem entirely.
