### ISSUE TITLE
LLVM dependency

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#1611]
LLVM has it's own special tool for configuration, `llvm-config`. It would be nice for `dependency` to wrap llvm config.

I'm planning to write such a class (tomorrow at this point), but I wanted to make sure that there was interest and no one had already done so and just never created a PR.

**Comment by TingPing** [comment]
I can say I have a use for it: https://github.com/GNOME/gnome-builder/blob/master/plugins/clang/meson.build#L29-L53

**Comment by dcbaker** [comment]
llvm-config returns different values for --cflags and --cxxflags, including the std. Does meson have a way to represent this?

**Comment by jpakkane** [comment]
Not at the moment. But I looked at what the commands output and the results are just plain terrible. As an example for C++ it returns `-std=c++0x` and then a few arguments later `-std=c++11`. It also has arguments such as `-Wall` `-O2` and `-g` and `-DNDEBUG`. A dependency provider should never, ever produce any of these (or some of the other flags there), it will screw up everything else. Behaving in this way is understandable if you are just using it for quick Makefile invocations but not as a part of a modern build system.

As an example GNUStep does the same thing and we filter out all of the troublesome flags. I guess we could do the same here but I'd prefer first filing a bug against LLVM to:

 - ship standard pkg-config files
 - if that is not possible, fix the output of `llvm-config` to get rid of those garbage arguments (because then what probably remains is the same for C and C++)

**Comment by dcbaker** [comment]
there is a bug for package config, it's been opened and ignored since 2011 https://bugs.llvm.org//show_bug.cgi?id=9405 (their ssl certificate is broken)

here's the difference between the --cflags and --cxxflags:
-std=c++11 -Wno-maybe-uninitialized -Wcast-qual -Wdelete-non-virtual-dtor -fno-exceptions -fvisibility-inlines-hidden

I don't disagree that it would be great if LLVM would ship a package-config file, or if they would fix llvm-config to not return garabage, but we're still going to need to support old versions of llvm that are still broken for some time.

I think that we should pobably just filter out everything except the -f arguments from both the c and c++ flags and return those combined?

**Comment by dcbaker** [comment]
Okay, combining C and C++ flags gives warnings (at least with GCC and clang), but I do have a patch that mostly works.

**Comment by jpakkane** [comment]
File a MR and we'll go from there.
