### ISSUE TITLE
Build RPATHs should not be overrideable with LD_LIBRARY_PATH, affects OSes using DT_RUNPATH such as FreeBSD and Debian

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#1635]
Due to #1519. Should we revert or is there a fix?

**Comment by nirbheek** [comment]
FWICT, the problem is in the order in which the runtime linker searches for libraries (from the manpage):

> If a shared object dependency does not contain a slash, then it is searched for in the following order:
>
> * (ELF only) Using the directories specified in the `DT_RPATH` dynamic section attribute of the binary if present and `DT_RUNPATH` attribute does not exist. Use of `DT_RPATH` is deprecated.
>
> * Using the environment variable `LD_LIBRARY_PATH` (unless the executable is being run in secure-execution mode; see below).  in which case it is ignored.
>
> * (ELF only) Using the directories specified in the `DT_RUNPATH` dynamic section attribute of the binary if present.

On some systems, including Debian Sid, setting `-Wl,-rpath` sets `DT_RUNPATH` instead of `DT_RPATH`, so `LD_LIBRARY_PATH` is searched first.

The only reliable fix is for `mesontest.py` to append the relevant test directories at the beginning of the `LD_LIBRARY_PATH` env variable. It is going to be a very rare use-case for someone to want to not use the libraries they just built when running the test program that they just built.

However, we can decide that this is too invasive a change right now, and just skip the test for this release.

**Comment by nirbheek** [comment]
Continued from https://github.com/mesonbuild/meson/issues/2881:

> FreeBSD configures its clang to pass --enable-new-dtags to the linker by default, so RPATH gets converted to RUNPATH. If Debian is doing the same thing, this issue should also affect Debian users.

It does, and that's what the bug is about. We could disable it, but the way we rewrite rpaths on install means we will also set the install rpath with the old dtags, which breaks Debian and FreeBSD policy.

So the best solution would be to use the old dtags for build rpaths, and the new dtags (or whatever the default is for the linker) for install rpaths. Should be doable.

**Comment by fooishbar** [comment]
> Now we have meson devenv (https://github.com/mesonbuild/meson/pull/8393), so users can manually workaround the issue by building and testing in the meson devenv environment. That is, users can run meson devenv ninja instead of ninja, and run meson devenv meson test instead of meson test.

We can, but `meson devenv -C build-x86-64 meson test` is deeply unsatisfying UX ... it's surfacing a really arcane implementation detail (`LD_LIBRARY_PATH` vs. `RUNPATH` vs. `RPATH`) as a first-class thing that users should have to care about. It's not predictable either: sometimes `meson test -C build-x86-64` will work, and sometimes you'll get inexplicable errors.

Can we please just do this, as suggested by @nirbheek?
> The only reliable fix is for mesontest.py to append the relevant test directories at the beginning of the LD_LIBRARY_PATH env variable. It is going to be a very rare use-case for someone to want to not use the libraries they just built when running the test program that they just built.

FWIW, my usecase is that I build and install Wayland (the library) and libweston+Weston into `~/prefix/wayland`. I need to have `~/prefix/wayland/lib` in `$LD_LIBRARY_PATH`, because otherwise I can't resolve the newer symbols it has (or test the newer behaviour it exposes). But if I do, the tests all break, because they link to `libweston.so.$n` from there instead of from the build directory.
