### ISSUE TITLE
pulling subprojects fails if the build directory is outside the source directory

### ISSUE THREAD

**Issue by hussamT** [mesonbuild/meson#1679]
I am using meson 0.40.0
To reproduce,
git clone git://git.gnome.org/nautilus
mkdir build
cd build
meson --prefix=/usr --buildtype=debug --sysconfdir=/etc --libexecdir=/usr/lib/ -Denable-gtk-doc=false -Denable-exif=true -Denable-xmp=true -Denable-selinux=false ../nautilus

This results in the following error:

Meson encountered an error in file meson.build, line 107, column 0:
Subproject directory 'subprojects/libgd' does not exist and cannot be downloaded:
No libgd.wrap found for 'subprojects/libgd'

The directory subprojects/libgd exists but is empty.

Next I tried:
cd nautilus
mkdir build
cd build
meson --prefix=/usr --buildtype=debug --sysconfdir=/etc --libexecdir=/usr/lib/ -Denable-gtk-doc=false -Denable-exif=true -Denable-xmp=true -Denable-selinux=false ../
said:
Submodule path 'subprojects/libgd' not initialized
 Maybe you want to use 'update --init'?

A Gnome developer suggested I file a bug report here.
Thank you.

**Comment by ernestask** [comment]
This describes two related issues:

- submodules aren’t initialized on checkout, can be fixed by adding `--init` to the command line [here](https://github.com/mesonbuild/meson/blob/7dc747ea54480c452b913e4bfe682ec67061c9bf/mesonbuild/wrap/wrap.py#L162), as the error so kindly suggests
- [Meson doesn’t try to update submodules outside the repo](https://github.com/mesonbuild/meson/blob/7dc747ea54480c452b913e4bfe682ec67061c9bf/mesonbuild/wrap/wrap.py#L152)

**Comment by nirbheek** [comment]
Let's fix this and get it into 0.40.1. This bug makes submodule subprojects unusable in many cases.
