### ISSUE TITLE
RFE: allow installation of individual targets

### ISSUE THREAD

**Issue by floppym** [mesonbuild/meson#1682]
This idea was briefly discussed in IRC. It would be nice if we could install individual targets.

Use cases:
- Development/testing of a plugin-in or library as part of a larger project. The install step copies the plug-in to the right place.
- Distro building/packaging of sub-components of a large project. For example, Gentoo Linux build scripts (aka ebuilds) optionally build libraries as both 32-bit and 64-bit for binary compatibility with proprietary software.

Patching meson.build to accommodate these use cases via package options is not generally sustainable.

**Comment by nirbheek** [comment]
It would also be useful to have meta-targets like `install-libs` and `install-bins`.

**Comment by jpakkane** [comment]
Just like with tests we should probably not add a gazillion top level targets but instead provide a tool such as `mesontest` to do nonstandard installs.

**Comment by nirbheek** [comment]
Now that we have a single entry point for all `meson*` commands, we can add a new one called `meson install` that takes target names as input.

This would also mean that any target with the `install_dir:` kwarg, or any build target (since they have default paths for installation) can be installed, regardless of whether `install: true` is passed since that only sets whether it is installed by default.

**Comment by williamh** [comment]
What is the latest status on this?

Thanks much,

William

**Comment by le-jzr** [comment]
This is also important for me. Any progress?

**Comment by jpakkane** [comment]
There is a `meson install` and it has an option `--only-changed`, which should provide for most use cases for this (you can't specify individual targets, though).

**Comment by le-jzr** [comment]
My use case is to only build and install libraries, which is much faster than building and installing all targets, and sufficient for some needs.

**Comment by lucmann** [comment]
it is nice that meson compile has been capable of compiling individual target. #7181 and I've tested that with meson 0.55.0.  But After the specific individual target is built, if I run `meson install -C build` (even though `--only-changed` added), it starts to compile the rest of targets.  

is there any progress on this feature for meson install?

**Comment by eli-schwartz** [comment]
This was implemented in #9110 as `install_tag: 'libfoo'` on installable targets, with default tags for general categories as described in detail at https://mesonbuild.com/Installing.html#installation-tags

e.g. for a distro that splits out development headers vs. runtime stuff, you can do:

```
DESTDIR="$staging/libfoo" meson install --tags runtime,man,i18n
DESTDIR="$staging/libfoo-dev" meson install --tags devel
DESTDIR="$staging/libfoo-doc" meson install --tags doc
```

For even more custom splitting up, the upstream project will need to carefully tag the components for later distro use.

**Comment by Hi-Angel** [comment]
@eli-schwartz what about `meson.add_install_script`, was tag added there as well?

**Comment by eli-schwartz** [comment]
It's listed as a valid kwarg for `meson.add_install_script()`, here: https://mesonbuild.com/Reference-manual.html#meson-object

:)

**Comment by Hi-Angel** [comment]
> This is listed as closed, but my reading is that it was assumed that tag-based sets of install targets would satisfy the need and that target-specific installation will not be implemented. Is that right?

This questions sounds a bit vague, so I'll try to answer as I understand it.

I presume, a "target" is a result of `executable()`, `library()`, etc. In this case, installing per-target *(without using tags)* would be too inflexible, because often there's more files that come with the target, like configs, documentation, etc.

The tag-based installation is an evolution on that approach, which allows you to build the exact list of files that you want to be installed along with an `executable`.

**Comment by Hi-Angel** [comment]
With that said, I think it could be useful in cases where `install_tag:` is omitted to default it to the name of the `executable()` or `library()`, so a user could install the target files individually without having to assign a tag explicitly. I think like it intuitively would feel like correct.

**Comment by detly** [comment]
> This questions sounds a bit vague, so I'll try to answer as I understand it.

Sorry, I was stuck in the terminology of GNU make when I wrote this. Yes, I meant installing individual executables defined with `executable()`. (And possibly `library()` but that need hasn't come up for me.)

My current situation is: I sometimes have `meson.build` files that predate the tag feature, and an embedded target where space is at a premium, and executables that are not marked `install : true` in `meson.build` that I want on the device (eg. debugging utilities).

I am currently happy to just copy the individual files I need during the image build (which is the custom anyway on eg. OpenWrt). My main motivation for asking was because I'd been fruitlessly searching to see if this feature existed, and wanted to know if I could stop searching.

> With that said, I think it could be useful in cases where install_tag: is omitted to default it to the name of the executable() or library()

Even though I asked this, I don't know that I'd actually suggest this - frequently projects will use the same name for the project as a whole, the executable itself, the executable and files that need to accompany it for distribution, etc. So it would not be obvious what `meson install -C build foo` would do for a project named `foo`, and if the `foo` project implemented install-tags for the first time after this default behaviour had landed, it might have to deal with a surprising, backwards-incompatible change in behaviour.

**Comment by eli-schwartz** [comment]
4. The default install tag for an executable is "runtime", which conveniently distinguishes itself from "devel" for static libraries and headers and stuff... changing that to the executable name would be a regression in functionality that people are actively relying on.

**Comment by xclaesse** [comment]
@detly I'm not sure to understand exactly your use-case, but projects often have a main executables and a few extra debug/devel tools that are not required for normal usage. In that case the main exe should have `runtime` tag and debug/devel exe should have `bin` or `bin-devel` tag, according to https://mesonbuild.com/Installing.html#installation-tags. If you really need to cherry-pick individual executables, IMHO the best is still to install everything into a DESTDIR then copy only the file you want.
