### ISSUE TITLE
provide more helpful error message if find_program() fails due to locale issues

### ISSUE THREAD

**Issue by mbiebl** [mesonbuild/meson#1703]
I just ran into 
https://github.com/systemd/systemd/issues/5855

```
$ export LANG=C
$ meson build
...
Program tools/make-man-index.py found: YES (/home/michael/git/systemd/tools/make-man-index.py)
Program tools/xml_helper.py found: NO

Meson encountered an error in file meson.build, line 2253, column 0:
Program "tools/xml_helper.py" not found.
```
tools/xml_helper.py isn't marked as executable and contains non-ASCII characters.

While it can be argued, that running with a non-UTF locale is not supported, the error message was rather misleading. Maybe meson could provide a more specific error message, like

"program found but not marked as executable and autodetection failed"

**Comment by nirbheek** [comment]
The "not marked as executable" part will be fixed by https://github.com/mesonbuild/meson/pull/1747/

However, for the locale problem, we already print a warning message at the top:

```
WARNING: You are using 'ANSI_X3.4-1968' which is not a a Unicode-compatible locale.
WARNING: You might see errors if you use UTF-8 strings as filenames, as strings, or as file contents.
WARNING: Please switch to a UTF-8 locale for your platform.
```

I'm not sure if it's possible for us to inspect every location where we or some code we call inside the stdlib parses files and fails if the locale is not UTF-8-compatible.

**Comment by inigomartinez** [comment]
I often find myself doing the following:

```
  foo_dep = dependency('foo', required: false)
  assert(foo_dep.found(), 'foo is required. please install it or disable the feature')
```

Or the same when searching programs:

```
  foo = find_program('foo', required: false)
  assert(foo.found(), 'foo is required. please install it or disable the feature')
```

Custom messages are usually nice to have, because they allow you to present better error messages to the user, particularly messages that can be helpful. It would be nice to have a parameter with the error message in case of failure. Something like:

` foo_dep = dependency('foo', error: 'foo is required. please install it or disable the feature')`
` foo = find_program('foo', error: 'foo is required. please install it or disable the feature')`

**Comment by eli-schwartz** [comment]
As far as I can tell, this works fine now.

We do have CI that checks for CPython's own EncodingWarning emitted when an encoding isn't specified while opening files for reading. So as of (very) recently, python upstream does now provide tools to "inspect every location where we or some code we call inside the stdlib parses files and fails if the locale is not UTF-8-compatible."

Yay!

**Comment by eli-schwartz** [comment]
> Custom messages are usually nice to have,

This has nothing to do with the reported issue. Custom messages aren't what was asked for here and wouldn't help cases like systemd.
