### ISSUE TITLE
Add name_suffix option to cross-files

### ISSUE THREAD

**Issue by noverby** [mesonbuild/meson#1802]
For cross-compiling to platforms such as Emscripten, it would be useful to be able to define name_suffix for all targets. 

Cross-file example:
```
[binaries]
c = '/opt/emsdk-portable/emscripten/1.37.9/emcc'
cpp = '/opt/emsdk-portable/emscripten/1.37.9/em++'
ar = '/opt/emsdk-portable/emscripten/1.37.9/emar'

[properties]
root = '/opt/emsdk-portable/emscripten/1.37.9/system'
c_args = ['-s', 'WASM=1', '-O2']
c_link_args = ['-s', 'WASM=1','-O2']
cpp_args = ['-s', 'WASM=1','-O2']
cpp_link_args = ['-s', 'WASM=1','-O2']
name_suffix='js'

[host_machine]
system = 'emscripten'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
```

**Comment by jpakkane** [comment]
Seems useful. It should have options for each type separately, though. (exe, shared lib, static lib, module)

**Comment by zajo** [comment]
I wanted to open this as an issue, happy to see there already is one opened. :)

This is very important for Emscripten support, because `em++` and `emcc` lack a command line option to specify the format of the output; they use the suffix of the specified output file name to determine what kind of code to generate.

Another relevant note: when `name_suffix` in cross files is implemented, please make sure that the sanity-check compilations Meson launches when setting up the build directory also use the specified suffix. Currently, you'll notice emscripten cross files in various Meson projects have `exe_wrapper` line that specifies `node` as the wrapper, but it is commented-out. The reason is that if it isn't commented out, meson fails because it tries to use `node` with non-js sanity-check files it generates. Of course once the build dir is setup, the user has to uncomment `exe_wrapper` so that he can run unit tests, which works as long as `executable` targets specify `name_suffix:'js'`.

**Comment by jfinkhaeuser** [comment]
What's the status of this? I ran into this exact issue, see a PR is open for half a year, but nothing much happened since then?

**Comment by nirbheek** [comment]
The pull request is missing tests, that's blocking it from getting merged. Would you like to finish that up?

**Comment by jfinkhaeuser** [comment]
Since the tests seem to include setting up the CI for e.g. emscripten compilation, I'm not sure if you really want that.

**Comment by nirbheek** [comment]
You don't have to setup emscripten compilation to test that. Those options apply to all compilations, and testing that they apply to C cross-compilation is enough.

**Comment by jfinkhaeuser** [comment]
If that's enough, ok. Just not today :)
