### ISSUE TITLE
cc.has_header_symbol() does not work for struct definitions

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#1975]
```meson
# Always succeeds
cc.has_header_symbol('linux/fs.h', 'struct file_clone_range')

# Always fails
cc.has_header_symbol('linux/fs.h', 'file_clone_range')
```

This is because our check evaluates to:

```c
struct file_clone_range;
```

Which is just a prototype definition.

**Comment by Salamandar** [comment]
Meson should issue a warning when the symbol starts with struct.

**Comment by Salamandar** [comment]
https://cmake.org/cmake/help/v3.0/module/CheckSymbolExists.html
> If the symbol is a type or enum value it will not be recognized

CMake checks symbols ( = function, macro, variable) apart from types. Maybe Meson should do the same as it seems buggy to merge the two.

**Comment by pm215** [comment]
If I understand correctly, you can use cc.has_type() to test for the presence of "struct foo", eg
```
cc.has_type('struct iovec', prefix: '#include <sys/uio.h>')
```

Question: is there any valid use for passing a string with spaces in it to cc.has_header_symbol()? If not, would it be worth making that a syntax error or at least a warning, to catch accidental attempts to use it on "struct something" ? (The generated code for has_header_symbol() clearly doesn't envisage being passed multiple words, because it will generate "#ifndef struct foo", which is bogus syntax and  provokes compiler warnings during compilation of the test case.)

**Comment by nirbheek** [comment]
> If I understand correctly, you can use cc.has_type() to test for the presence of "struct foo", eg

Yes, this issue is obsolete now. I'll close it.

> If not, would it be worth making that a syntax error or at least a warning, to catch accidental attempts to use it on "struct something" ?

Absolutely, yes. Could you open a PR that does that and CC me on it?

**Comment by pm215** [comment]
I'm not sufficiently familiar with meson's internals to submit a pullreq, I'm afraid.

**Comment by eli-schwartz** [comment]
That's okay, we can offer advice. :)

You can find the base implementation in mesonbuild/compilers/compilers.py and overridden implementations in compilers/c.py and compilers/cop.py and compilers/cuda.py

Check for `def has_header_symbol` :D
