### ISSUE TITLE
stable v0.41.2 FTBS budgie-desktop git

### ISSUE THREAD

**Issue by fossfreedom** [mesonbuild/meson#2096]
Hi,

  budgie desktop will be looking to release git master at some point soon.  However, it currently only builds with v0.40.1 meson.

All subsequent meson versions including master fail to build - the issue is being tracked here: 

 - https://github.com/budgie-desktop/budgie-desktop/issues/1044

Ubuntu 17.10, Debian Buster/Sid and Arch are specific distros that I'm aware of that have pulled in the latest meson and hence cannot build budgie desktop directly at the moment.

**Please can we have some guidance why our FTBS occurs?**

Notes:

If I've done the git bisect on the 0.41.2 branch correctly, the likely commit causing this issue is commit ae9b23832e3ef4064e5735265ce7008794ab0491

While bisecting I had also to apply the commit described in this previous meson issue: https://github.com/mesonbuild/meson/issues/1969

As Ikey has mentioned in the linked issue - we are definitely linking the libraries correctly - as I said, it works with v0.40.1

**Comment by nirbheek** [comment]
I can see the problem. Basically, the `-Wl,--start/end-group` modifiers are only surrounding the static archives and not the dynamic libraries, so the linker is not recursively checking the dynamic libraries for symbols needed by the static libraries.

The fix is simple (writing a test case is harder), but I only wish this had been reported before we made the stable release :D

I will talk about a workaround you can use on https://github.com/budgie-desktop/budgie-desktop/issues/1044.

**Comment by jpakkane** [comment]
Can you test if the referenced PR fixes the issue for you?

**Comment by fossfreedom** [comment]
yes thanks.  Tested on both Debian Sid and Ubuntu 17.10.  

Cheers.
