### ISSUE TITLE
find_library and dependency do not work properly in Windows MinGW

### ISSUE THREAD

**Issue by Phitherek** [mesonbuild/meson#21]
I' ve got the project structure - src and include directories and additionally build directory for Meson. I generate all the library files within the meson.build in src directory, install headers in meson.build in include directory and get this all together with root meson.build. When I try to define the external dependencies or even the dependencies I built within different library project earlier with Meson, where on Linux they work perfectly, on Windows MinGW find_library cannot detect the .a static library files I installed earlier into the /lib directory (in MSYS) and dependency cannot even find the MSYS version of pkg-config. I think this should be fixed somehow.

**Comment by johan-boule** [comment]
Keep in mind that the original goal of MSYS is to be able to build softwares with the autotools (autoconf, automake, libtool) by providing the minimal set of unix programs these tools rely on.
I, for one, remember having hacked up a horrendous 'file' shell script to mimic what the original 'file' program does on unix, but only handled the cases needed by libtool, i.e. converting filename patterns like lib*.dll.a, *.dll, lib*.a to their corresponding file types. Earnie Boyd thought it was good enough for the purpose of MSYS, which was : making libtool happy, and he chose to include that crappy script, despite someone else saying he had success with the GNUWin32 port of the real file program. I guess you get the spirit : don't rely on MSYS outside of its scope.

Anything beyond running the autotools is kind of out of the scope of the MSYS project and better solved using Cygwin.

If you consider that Meson only depends on python (and pkg-config if you wish), there should IMO be no advantage running it through the MSYS version of python port rather than directly on the native version of python : you just need to tell meson to use mingw as the compiler.

**Comment by jpakkane** [comment]
You can set a custom path for find_library so this should be enough to get going. If there are more specific needs please open new bugs.
