### ISSUE TITLE
version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by 1a1a11a** [mesonbuild/meson#2102]
I have learning meson and use it to compile my project, it compiles fine, however, when I try to run the binary, it has the following error 
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./test)` 

Here is the dependency about glib 
`glib_dep = dependency('glib-2.0', version: '>=2.40')` 

Do I miss something? 

BTW, the project compiles, links and runs fine with cmake.

**Comment by jpakkane** [comment]
Can you post a link to the full project?

(GLIBCXX is different from glib, btw. The former is the C++ standard library and the latter is the GLib plain C library.)

**Comment by 1a1a11a** [comment]
I don't have a public full project url yet, but I can provide any information needed. The original code is in C, I recently added some C++ modules. The meson.build is like this: 

`
glib_dep = dependency('glib-2.0', version: '>=2.40')
thread_dep = dependency('threads')

cc = meson.get_compiler('c')
m_dep = cc.find_library('m', required : true)


src = ['test.c']
src_utils = [...]

inc_headers = include_directories('headers') 


lib_utils = static_library('utils', sources:src_utils, dependencies: [glib_dep, thread_dep, m_dep], include_directories: [inc_headers])

executable('test', sources:[src], link_with: [lib_utils], 
	dependencies: [glib_dep, thread_dep, m_dep], include_directories: [inc_headers])
`

**Comment by jpakkane** [comment]
It's hard to debug this issue  based on this information alone. However what is most likely happening is that somehow C and C++ linking gets mixed. Either you accidentally link all C code with the C++ linker or the other way around. The versioning would indicate that there are C++ shared libraries that are linked with a newer version of stdlibc++ than you are currently running. That could be caused by prebuilt binaries that are built on a machine with a newer C++ library version.

**Comment by 1a1a11a** [comment]
wow, you are awesome! I have figured out with your help! I exported the wrong path of new libstc++.so, so it uses the system level (old) libstc++.so, which caused the problem. Thank you very much!
