### ISSUE TITLE
pip module install a meson.py executable instead of just meson

### ISSUE THREAD

**Issue by aruiz** [mesonbuild/meson#2203]
when doing pip install on windows, the command line tool name is "meson.py" instead of "meson" like for example pip install ninja provides a "ninja" command line tool name

**Comment by jpakkane** [comment]
That's just how Windows + Python works. It is unavoidable. This is documented (somewhere), sometimes the executable name is `meson`, sometimes it is `meson.py`.

The MSI installer package version will be `meson.exe`.

**Comment by aruiz** [comment]
How does ninja do it then? I do get a ninja.exe with pip install ninja

**Comment by jpakkane** [comment]
Ninja is not a Python program so I don't really understand why pip even has that available. It is probably a binary wheel because it is implemented in C++. Plain Python scripts can not be binary wheels, they come as scripts AFAIK.

However if you want to use Meson on Windows it would be useful if you could try the MSI version. You need to build it yourself, though:

 - install WiX
 - use pip to install cx_freeze
 - checkout #2195
 - run `python msi\createmsi.py`
 - report problems in the above mentioned PR

**Comment by nirbheek** [comment]
If you install Python 3 with the right options, it will install a helper that will associate with `*.py` scripts and you will be able to run `meson.py` in `cmd.exe` without specifying the full path as if it were an exe. That's why all executable Python scripts on Windows end in `.py`

**Comment by lazka** [comment]
`pip install meson` installs a meson.exe nowadays so I think this can be closed.

**Comment by nirbheek** [comment]
Yes, this was fixed already.
