### ISSUE TITLE
0.42.0 is giving a backtrace: TypeError: can't pickle _thread.lock objects

### ISSUE THREAD

**Issue by wberrier** [mesonbuild/meson#2211]
that didn't happen with 0.41.2...

```
Traceback (most recent call last):
  File "/home/wberrier/wa/git/meson/mesonbuild/mesonmain.py", line 338, in run
    app.generate()
  File "/home/wberrier/wa/git/meson/mesonbuild/mesonmain.py", line 186, in generate
    pickle.dump(b, f)
TypeError: can't pickle _thread.lock objects
```

Ideas?

**Comment by jpakkane** [comment]
Do you have link to the repository where this happens?

**Comment by wberrier** [comment]
Sorry, it's not a public repository.  Is there something I can dig/investigate?

**Comment by jpakkane** [comment]
What happens is that Meson stores the state of the project in a dump file for later use (and regeneration). One of the things that gets store are the original keyword arguments that were passed to construction functions. These may contain pointers to non-build state such as Holders and, in this case, the interpreter object itself.

There is a cleanup function for these that was added since we found out that this leakage was happening. Most probably it has some bug that causes an interpreter object to be pickled. To ensure that bad objects are not accepted, every interpreter object has an object that can not be pickled so it breaks (you can grep for `unpicklable_object` to find these).

**Comment by nirbheek** [comment]
Is there any progress on this?

**Comment by nirbheek** [comment]
I can reproduce this with glib. Investigating.

**Comment by nirbheek** [comment]
The problem seems to be with pickling `Target` and `TargetHolder` objects. The following code is responsible for the error in glib:

```meson
   tmpsample_xml = custom_target('tmpsample.xml',
      output : 'tmpsample.xml',
      build_by_default : true, # hack around meson bug, see PR #1335
      command : [ gtester, '-k', '--quiet', '-o', '@OUTPUT@',
                  '--test-arg=--gtester-selftest', gtester])

    test('gtester-xmllint-check', xmllint,
      args : ['--noout', tmpsample_xml],
      env : test_env)
```

Specifically, `args : ['--noout', tmpsample_xml]`. Replacing `tmpsample_xml` (`CustomTargetHolder`) with `gtester` (`Executable`) gives the same error.

**Comment by nirbheek** [comment]
Turns out this one is caused by https://github.com/mesonbuild/meson/pull/2236. The original is some other problem.

**Comment by nirbheek** [comment]
@wberrier because of how useless the traceback error message is, you will have to debug this manually. in `pickle.dump(b, f)`, the `b` is a `class Build:` object. You can iterate over every property of that class and `pickle.dump()` each separately till you figure out which one is causing the error, then do the same recursively till you figure out what object is causing it.

**Comment by wberrier** [comment]
[meson_link_with_failures.zip](https://github.com/mesonbuild/meson/files/1289095/meson_link_with_failures.zip)

@nirbheek Agreed, too bad `pickle` doesn't give better backtraces...

In any case, the object that is giving trouble (and it looks like there are multiple ones), is:

    b.targets['namehidden@exe'].kwargs['dependencies'][0].libraries[0][0]

which is a `StaticLibraryHolder`, which is a `BuildTargetHolder`, which has `self.interpreter`.

I have a list of static libraries in my project via `static_library()` and am passing that list to `declare_dependency()` under the `link_with()` keyword.

...

Found it!

Turns out that when declaring a dependency, if you pass a doubly wrapped list to `link_with`, this error crops up.  But, if you just pass a list to `link_with`, this error doesn't show up.

See attached `meson.build`.

ie:
    libs = []
    libs += static_library(...)
    #dep = declare_dependency(link_with : libs) # works
    dep = declare_dependency(link_with : [libs]) # broken! with the pickle backtrace...

Where to go from here?

**Comment by jpakkane** [comment]
Presumably when unpacking that we do 

    if hasattr(foo, 'held_object'):
        foo = foo.held_object

and we should do

    while hasattr(foo, 'held_object'):
        foo = foo.held_object
