### ISSUE TITLE
Cross compilation presets

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/meson#2283]
I'm not sure this is a good idea, maybe Meson could be shipped with cross compilation presets on Linux distributions. For example on Fedora, there are mingw, arm(linux/none) compilers, etc.
So while calling meson like this:
```
meson srcdir builddir --cross-file mingw32
```
Meson could look into two path, the current one and and a global one like /etc/meson.d/.
That may help new comers.
The difficulties I see here are:
 - who provides this files Meson or the distribution?
 - when installing with pip 

One other solution would be to share them on github.

**Comment by nirbheek** [comment]
I think it's a great idea, but with some changes:

New option `--cross-preset fedora-mingw64`, and we ship the presets with Meson. Initially, we can add presets for Fedora, Ubuntu, Debian and people can contribute more.

I myself have found it annoying to use cross info files because I have to copy the same file into every project.

**Comment by lieff** [comment]
+1, need this feature.

**Comment by shevegen** [comment]
It should be shipped with Meson rather than any distribution per se because the latter may lead to fragmentation; the (bigger) distributions could already modify the code at will in their own internal repos if, for any reason, they would have to change the defaults. By having meson do this, smaller distributions can also refer/use to it. You also only need to provide the simplest and most logical path in my opinion, not every corner case.

**Comment by jpakkane** [comment]
The next package release of Debian will ship with a Debian specific cross file generator. For details [see this link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859177).

We can extend that to other cases after it has seen some use and we know what it should actually do.

**Comment by textshell** [comment]
I think it would be great if the toolchains could ship the meson files (i.e. there is a specific directory for such files).
Also a place in say `~/.config` for user specific crossfiles would be nice.
I think presets could address some needs not served by a cross file generator (e.g. microcontroller style embedded projects where a toolchain could be used in quite different ways).

**Comment by dcbaker** [comment]
I have a few reasons that distros rather than meson should ship the cross files.
1) compilers don't necessarily have the sames names for the same tools on different distros
2) distros can ensure that the dependencies for those cross files are actually installed if the cross file is installed
3) distros can update their cross files if the names/paths change and ensure that calling `meson build --cross-file fedora-x64` works on fedora 27 where gcc is multi arch, or gcc-x64 if a special cross compiler is needed. meson the project cannot guarantee that works, espcially when meson is installed from pip, and I think it's better to err on the side of not providing broken things.

**Comment by lieff** [comment]
1. This is also reason why it must be maintained by distros+meson, not per-user files.
2. Yes, but cmake for example contain many cross-distros scripts to make life easier. It's too much work for one distro or cmake. Distros polish what cmake already provides.
3. Custom distro name is great too, but more or less standard cross-distros names like --cross-file mingw32 should be provided.
