### ISSUE TITLE
ninja dist should respect gitattributes export-ignore

### ISSUE THREAD

**Issue by jbicha** [mesonbuild/meson#2287]
Quoting from the [manpage](https://manpages.debian.org/unstable/git-man/gitattributes.5.en.html#Creating_an_archive) for gitattribute

`Files and directories with the attribute `export-ignore` won’t be added to archive files.`

It would be great if `ninja dist` would respect that and not include files with that attribute in the tarball it generates.

**Comment by Kekun** [comment]
I have zero idea what dist is exactly doing, but something like this *should* work:
```
git = find_program ('git')
cleandist = custom_target (
  'cleandist',
  output : '@0@-@1@.tar.xz'.format(meson.project_name(), meson.project_version()),
  input : '.git',
  command : [
    git, 'archive',
    '--prefix', '@0@-@1@'.format(meson.project_name(), meson.project_version()),
    '--output', '@OUTPUT@',
    'HEAD'
  ],
  install : true,
  install_dir : 'cleandist'
)
```

Also, I definitely need this feature too. :)

**Comment by nirbheek** [comment]
All the logic for `ninja dist` is contained in [mesonbuild/scripts/dist.py](https://github.com/mesonbuild/meson/blob/master/mesonbuild/scripts/dist.py), so if you want to take a crack at it, it should be easier than maintaining your own script :)

**Comment by sjohannes** [comment]
The difficult part here is that `git archive` doesn't support submodules, so you can't simply replace the current `clone → submodule update → tar` sequence with it. Perhaps it's something to bug the Git maintainers about.

**Comment by onkarshinde** [comment]
The issue is in function del_gitfiles. This deletes the .gitattributes file as well, essentially defeating its purpose when using command `git archive`.

**Comment by textshell** [comment]
From talking about this on irc. Meson does not use git archive at all (because meson needs to support submodules)

There is `git check-attr` which could be used to implement it nevertheless:
The code would need to walk the file tree feed all files to git check-attr via stdin and interpret the output...

check-attr has a batch mode where it acts like a filter in a pipe, so it's not spawning heavy, but i don't have an idea how much slower this would make disting.

**Comment by onkarshinde** [comment]
Can it not be implemented with some if/else logic?
```
if (project_contains_submodules) then
use_tar_program_as_we_currently_do
else
use_git_archive
```
Or could it be implemented behind a configuration flag such that if flag is set to true then we use git archive.
Are there any statistics about how many projects are using meson as build system and also have submodules? If there are then that will provide help in making this decision.

**Comment by jpakkane** [comment]
If anywhere this option should go as the command line option to `meson dist´, just like all complex things to testing are options to `meson test`

**Comment by nirbheek** [comment]
Isn't this a project-specific option, so you'd want a way to set it in the project description somehow? Perhaps in the `project()` call at the top of the build file? Like, if you wrote a `.gitattributes` file you probably don't want to *not* use that for dist by accident.

**Comment by textshell** [comment]
I think we really should try to get this to work without an option though. I think the outline i posted above is workable and should not be tons of work. Not a project for a meson+python beginner likely though. If i didn't miss some complication is mostly fiddeling with subprocess to allow for streaming through a command.

**Comment by nirbheek** [comment]
I would even argue that we should probably *always* do this, because why else would you set that option in `.gitattributes` at all?

**Comment by onkarshinde** [comment]
[meson_dist_using_git_archive.txt](https://github.com/mesonbuild/meson/files/2395585/meson_dist_using_git_archive.txt)

Please find attached a crude patch that implements the if/else logic I mentioned in my comment above. Please excuse the file extension as github does not allow uploading files with extension .diff or .patch.

I have briefly tested this on my project and the result is as expected and ignores the files having export-ignore in the .gitattributes file.
There is one limitation. Since git archive does not support tar.xz by default (not until you set some config values) I had use tar.gz as the output format. Either we can use this approach or go with tar.xz but update documentation that this requires setting tar.tar.xz.command.

**Comment by eli-schwartz** [comment]
I have linked a PR which should fix this.

It uses git-archive while still supporting submodules. :D
