### ISSUE TITLE
xcodebackend still references meson_test.py

### ISSUE THREAD

**Issue by LukeShu** [mesonbuild/meson#2362]
The [xcode backend](https://github.com/mesonbuild/meson/blob/5cec8fc43a9341dbd4eb50f95a743bb6d6d2e416/mesonbuild/backend/xcodebackend.py#L569) still has a reference to the `meson_test.py` script, which existed until c7ddce163.  This needs to be updated to `meson test`, but I'm not sure what's involved, since I'm not familiar with `meson_test.py`'s usage, so I figure it would be more productive to report it to someone who was :)

I also figure that that means that bit of code isn't hit by the test suite, and that could probably stand to be fixed.

**Comment by nirbheek** [comment]
The xcode backend is in advanced stages of decay because no one uses it and no one wants to maintain it. As a result, it is also not a part of our CI and hence it keeps getting worse.

Would you like to work on it? The first step would be to figure out which tests pass on it, ensure minimum workability, then enable those tests on the CI so we at least don't regress constantly, and people are forced to take care of the backend.

**Comment by LukeShu** [comment]
I actually only stumbled across while reading the code; I didn't hit it, I'm not even a mac user.  I saw "meson_test.py" and thought "I don't think that file exists."

However, if I get a chance, I'll use a friend's macbook to get it going on CI :-)

**Comment by drsog** [comment]
I have a fix, but am looking to get the CI running.  Currently looking for a ticket that covers it...

**Comment by jpakkane** [comment]
Yeah, we don't currently run CI with the Xcode backend because it is too broken.

**Comment by drsog** [comment]
Thanks Jussi.
I'd like to help, but there are a few thinks making it difficult - or rather, I will be very noisy asking lots of questions.  I have been going through the issues as best I can but many are not labelled as macos.  I am unable to attach labels. If I could do that I could collect up the issues as a program of work.  I may not be able to address everything, but at least the size of the problem would be known.

From what I can see, I don't think its a huge amount of work - but I think that comes from a position of naivety.

My rabbit hole is getting deeper though.  I've got fixes for some bugs, but I can not pull request till I understand the existing CI faults on master, so I know I am not introducing more bugs.
FYI, when running --backend=ninja, master has only 2 failed tests, but there are other tests throwing stderr logs that should be being picked up. 
I would like to raise issues for each of these and label then as macos.  So can you make it so my github user 'drsog' can label tickets?

Thanks,

Sean

**Comment by drsog** [comment]
The fix is more than simply re-naming the file reference. meson/mesonbuild/script/meson_test.py became meson/mesontest.py which is now meson/meson test.
The arguments have changed too.
Implementing call in xcode as  (example)
'/usr/local/opt/python3/bin/python3.6' '/Users/drsog/Local/git/meson/meson.py' test --no-rebuild -C '/Users/drsog/Local/git/meson/b q5o7j7tv/' runtest

**Comment by drsog** [comment]
Sorry, I'm polluting this ticket a little. A bit of user error and uncertainty in process.  Promise to get better.

1. Labelling: only available to members and due to GITHUB permission structure, I do not qualify. Solution: Comment tickets with, for macos example: 'LabelAs: macos', then a member can easily search with '-label:macos in:comments "LabelAs macos"' and bulk label.  Note, this ticket already has the macos label and will not be selected (hence I can use it as an example :-)

2. While manually testing I found that the --no-rebuild may be a problem. When backend=xcode, it does not compile when building or testing. 
To be clear, behaviour of ninja (for consistency), the workflow is meson configure, ninja build, meson or ninja test. If I have this wrong in any way, let me know.
Only ninja build compiles, but by default, ninja only, meson test will build - hence the --no-rebuild flag.  No rebuild = true is the default for xcode (and VS?).  Hence, the compile stage is ill-defined.

**Comment by nacho4d** [comment]
Hello...  Is there anywhere I can get some guides on how/where to start?
Meson looks like a good tool it just needs a bit more love from macos community. I am glad to help but if there is a mentor or somebody I can ask things on how to start it would be great :)

**Comment by nacho4d** [comment]
unfortunately that is the true. Fortunately I use Xcode everyday and have an idea of things.

Also there are various implementations in various languages that already tackled that challenge like this [mod-project in python](https://github.com/kronenthaler/mod-pbxproj/) or this [XcodeGen in swift](https://github.com/yonaskolb/XcodeGen)
Could we use any of these to make our life easier?

**Comment by jpakkane** [comment]
Probably not. First of all we can't depend on any external code, only stuff that exists in Python standard library (and obviously not Swift) and second of all the format is the smallest problem, the bigger is mapping Meson's internal view of the world to xcode.

A potentially more lucrative approach would be to look at GN. FWICT it generates a shim XCodeProject that only calls into Ninja. That is not as smooth of an experience but it might be easier to implement.

**Comment by nirbheek** [comment]
Another thing you might find helpful is that you probably want to start with `test cases/common/1 trivial` and then keep going up the test list till everything at least configures correctly. The reference point is the `ninjabackend.py` file.

**Comment by nacho4d** [comment]
@jpakkane Thank for the pointers. I understand now policy of meson. 
@nirbheek Thanks for the tests. I just did a quick fix in my local repo and xcode is working for some of my projects again :) I will definetely check `test cases/common/1 trivial`  and try to submit a fix soon.

FWIW, I was reading the swift code from  [swift package manager](https://github.com/apple/swift-package-manager/blob/b3427a5146592bb2bf86c2f0181b0a8ea8c431c0/Sources/Xcodeproj/generate().swift) and I think this is the best reference we can find to generate correct Xcode projects. 

At least, it looks generated Xcode is trying to reference CoreData.framework? I think this is one of the reasons failing. (CoreData is one of the defaults linked frameworks but not needed in meson projects since it is a library specially for iOS/macOS, not cross-platform)

**Comment by nacho4d** [comment]
@jpakkane @nirbheek 
Here is my PR, I checked with some trivial tests and Xcode works OK again. Can you look at this please?
https://github.com/mesonbuild/meson/pull/4220

I would like to start more tests and maybe work with a CI to make sure it is maintained and does not break but that would be in another PR. I found various things in Xcode that need updates.

(About CoreData.framework, I was wrong, nobody it trying to use that 😃 )

**Comment by eli-schwartz** [comment]
Fixed in #3199
