### ISSUE TITLE
Dependencies on python modules

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#2377]
For mesa I need to check if the mako module is installed (and of the proper version) for the python version we're using (python2 at this point :/ ).

I'm interested in adding the feature to meson, but I want to know whether the preferred implementation would be to writing a dependency type (maybe that took a python prog as an argument?), or to add a method to the python module (obviously for the latter we'd need a python2 module).

**Comment by nirbheek** [comment]
The Autotools build looks for python2, but I looked at a few scripts and they seemed to be compatible with both python2 and python3? Maybe the ones that aren't can be ported to be Py2/Py3 compatible? They don't seem to be doing anything special that would prevent that.

I think for the Meson build it makes sense to require Python3 since that's what Meson is also written in. That will make your job easier because then you can add module searching to the python3 module.

**Comment by dcbaker** [comment]
I'm working on porting to python 3 (I know, I'm juggling 4+ major projects at a time, lol), the problem is that some of the scripts are incredibly complicated and have deep rooted python2 assumptions build into them. There's also a *lot* of code generation is mesa.

Anyway, I think that the answer i'm looking for is that add a `had_module` method to the python module would be acceptable.

**Comment by nirbheek** [comment]
`has_module` would make it more consistent with, for instance, compiler checks. But yes, we'd happily accept a python2 module if you submit one. Other people have also asked about it in the past.

**Comment by martingkelly** [comment]
Could we also link up `has_module` with the `dependency` method? It's a bit confusing/inconsistent if we end up with having to detect Python dependencies separately from dependencies for other languages (using `has_module` instead of just `dependency` possibly with `method: python`).

**Comment by dcbaker** [comment]
`has_module` makes the python depdendency feel more like a compiler object, like `c.has_library`. I haven't paid too much attention to the changes in the python module, but dependencies already have  `modules` argument, llvm and qt use that.
