### ISSUE TITLE
Meson wont update

### ISSUE THREAD

**Issue by vjr2** [mesonbuild/meson#2380]
Ok, first I installed meson version 0.37.1 but then I realised I couldnt do ninja command. So I wanted to upgrade to upper version 0.40, in my case 0.42. So I just runned the pip3 command and installed meson 0.42, but when I want to use the programm it says the version is still 0.37.1. How can I fix this? Thanks

**Comment by vjr2** [comment]
[Im on Raspbian]

**Comment by NickeZ** [comment]
Did you run `pip3 install --upgrade meson` ?

**Comment by TingPing** [comment]
Maybe `~/.local/bin` isn't in `PATH`.

**Comment by liugang** [comment]
run `which meson` to see where is old meson, uninstall it.

For example: on ubuntu:

```
sudo apt-get remove meson
```

and then reopen terminal.

pip3 whill install meson to /usr/local/bin/meson, but some machine, the `/usr/bin` is before `/usr/local/bin` in `$PATH`

**Comment by nirbheek** [comment]
Note that you should prefer using `pip3 install --user meson` to avoid needing root, and ensure `~/.local/bin` is at the front of `PATH`.

**Comment by davidwcraig** [comment]
liugang's procedure worked for me wit a similar problem. Thank you!

**Comment by TesseractA** [comment]
A note to mac users: ``pip3 uninstall meson`` only uninstalls meson in the python3's meson directory. Another directory, like that in ``/usr/local/bin/meson`` may still contain meson.

 To uninstall or update meson for quick command-line use, you should first make sure you've done ``xcode-select --install`` for more command line developer tools if you haven't already (so that there won't be any errors thrown in brew installs.) Then, you have 2 brew-related options:
1. ``brew uninstall meson`` and to reinstall it ``brew install meson`` (time consuming)
2. ``brew upgrade meson`` (less time consuming)

Hope that saves another person some time.

**Comment by SourceCodeDeleted** [comment]
My install still checked for it being in /usr/bin

I just made a symlink . 

`ln -s /home/username/.local/bin/meson /usr/bin/meson`

**Comment by michaelbadcrumble** [comment]
Would this helps?

https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/001-readme.md

**Comment by ClassRepo** [comment]
@michaelbrockus 
> Would this helps?
> https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/001-readme.md

Sadly no, as it's 404.

This appears to be a problem again. I just tried to update `meson` and it failed, then tried uninstall, and install. That failed, now I have no `meson`. Even using `SUDO` failed.

**Comment by nirbheek** [comment]
This is not a meson bug, folks. It's how pip works and after installing with `pip3 install --user` it even tells you if `~/.local/bin` is not in PATH. We even document it: https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip

Closing.

**Comment by Shadowblitz16** [comment]
@nirbheek you didn't document how to fix it though.

And why do we need to install through pip? apt makes it easily usable.
The only problem with apt is its not updated.
