### ISSUE TITLE
Qt5 module should only be run on files containing Q_OBJECT

### ISSUE THREAD

**Issue by adrianjohnson** [mesonbuild/meson#2398]
I currently get the moc warning "Note: No relevant classes found. No output generated." for every header that does not contain Q_OBJECT.

The [moc documentation](http://doc.qt.io/qt-5/moc.html) states "Whenever qmake is run, it parses the project's header files and generates make rules to invoke moc for those files that contain a Q_OBJECT macro."

Meson should do the same to prevent this warning.

**Comment by jpakkane** [comment]
We do not do this by design because it is a scalability bottleneck. It means that every time you start a compilation you _first_ have to parse the full contents of all source files that have changed (because any change may add or remove a `Q_OBJECT` definition). This works fine for small programs but complicates and slows down large builds, especially if you have other source preprocessor tools that want to do the same thing.

In Meson the user is in charge of explicitly telling which files need to be processed with moc. This is basically the same reason why source files must be specified explicitly rather than with globs.

**Comment by adrianjohnson** [comment]
It is annoying when I try to keep my builds free of warnings. Some of these headers without Q_OBJECT are included by others so I can't control the list of headers that moc is run on.

Is invoking an external executable on every changed header that much faster than first scanning the headers for Q_OBJECT? Usually, I may change only 1 or 2 headers at most before each incremental build.

**Comment by jpakkane** [comment]
This problem is further complicated by the backends we use. Ninja does not have a concept of a "pre-build scanning phase" so simulating one after the fact is difficult. MSVC might or might not support that, and even if it does I don't know how to make it do that. And then there's XCode which is ... well ... XCode.

The only place we do scanning of file contents is Fortran because that is just what you have to do to build Fortran. But it is unreliable, awful and not something you want to do if you can avoid it.

**Comment by adrianjohnson** [comment]
Maybe the best option is for moc to add an option to disable only that warning.

**Comment by jpakkane** [comment]
We don't like disabling warnings by default, but adding an option to pass extra arguments to moc so people can opt in to disabling those would be ok.

**Comment by adrianjohnson** [comment]
I found that moc has a "--no-notes" option. I checked the moc source code and the only note it generates is 
`moc.note("No relevant classes found. No output generated.");
`
If the Qt5 module provided a way to pass options to moc, using that option should silence all the noise without disabling warnings.

**Comment by adrianjohnson** [comment]
Patch to add 'moc_args' argument. With this patch I added "moc_args : '--no-notes' " to qt5.preprocess() and I no longer see the "Note: No relevant classes found. No output generated." message.

[qt5.diff.txt](https://github.com/mesonbuild/meson/files/1353907/qt5.diff.txt)
