### ISSUE TITLE
Upgraded to meson 0.43.0 and now boost program-options is not a valid boost library

### ISSUE THREAD

**Issue by gauteh** [mesonbuild/meson#2456]
```
boost   = dependency ('boost',
                        modules : [ 'thread', 'filesystem',
                                    'program_options', 'log_setup',
                                    'log', 'date_time', 'system' ])
```

error:

```
Meson encountered an error in file meson.build, line 23, column 0:
Dependency program_options not found. It is not a valid boost library.
```

the program no longer links, since it is missing a bunch of references.

Boost package list on Arch Linux: https://gist.github.com/gauteh/205bcdf30d7eda628264e4eb8f4a8bd6

**Comment by gauteh** [comment]
Note that `boost_po = cc.find_library ('boost_program_options')` succeeds.

**Comment by NickeZ** [comment]
The problem is that the boost build system `Boost.Build` or b2 has two syntaxes for how to define a library to be built and I only knew about one of them when I improved the boost support. program_options is also the only library which is defined with the alternative way.

It looks like either

```
lib boost_program_options
```

or

```
boost-lib program_options
```

in their `build/Jamfile`. https://github.com/boostorg/program_options/blob/develop/build/Jamfile.v2#L12
