### ISSUE TITLE
Updating the Visual C runtime breaks things

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#2483]
We have just started testing the `.msi` installer (0.43.0) and a user reported that the Xilinx SDK failed to start correctly after meson installer was installed.

He said:
> The SDK failed to start.  I didn't capture the exact message, but it was similar to "Visual Studio Redistributable not present".  It would auto-launch an installer, which would claim to successfully repair the redistributable, but nothing changed the next time around.

The work around [is here](https://www.xilinx.com/support/answers/69076.html) - specifically setting this in the environment `XIL_PA_NO_REDIST_CHECK = 1`.

So, can we change the installer so that it only installs the updated C runtime if it's not already present? 

This is reference to #2420

**Comment by rhd** [comment]
This seems to be a bug in the Xilinx SDK and their [official response](https://forums.xilinx.com/t5/Installation-and-Licensing/Vivado-Xilinx-SDK-Error-Incorrect-Visual-C-Version/m-p/774709#M18480) is to set that environment variable.

The question is, should meson update the runtime if it's already installed?

**Comment by jpakkane** [comment]
The way we install the vc redistributable is [the way officially recommended by WiX](http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html). That is to say point an XML snippet to an opaque binary blob of data and have it do its thing. I only changed INSTALLDIR to TARGETDIR (or the other way around) because that is the actual install dir we use.

I have no idea what is the correct way of fixing this and how we should be doing it. If someone does, please file a patch.

**Comment by rhd** [comment]
@jpakkane I think you're doing the right thing. The Xilinx SDK has issues. I'm going to close this issue.

Thanks!
