### ISSUE TITLE
MSI Installer: Support upgrade

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#2485]
I just attempted to upgrade from meson `0.42.1` to `0.43` and was presented with this screen using the MSI installer

![2017-10-11 14_37_47-windows installer](https://user-images.githubusercontent.com/3422847/31468523-efdaf1d2-ae92-11e7-8c93-04b1978479cf.png)

At the very least, that error message should be a bit more clear.

Besides that - a huge :+1: for having a windows installer!

**Comment by jpakkane** [comment]
If someone knows how to do this, please file an MR. I don't have the knowledge to do that. Also, that error message comes either from WiX or Windows itself. We can't change it as far as I know.

**Comment by slurps-mad-rips** [comment]
IIRC this error occurs because the Product GUID has stayed the same throughout each msi. So, while the upgrade guid is used to show they are the same, the product guid should change from release to release. 

I believe if you change [this](https://github.com/mesonbuild/meson/blob/master/msi/createmsi.py#L41) to `self.guid = "*"`, this issue shouldn't occur in the future (Wix will generate a new Product GUID every time you run a build).
