### ISSUE TITLE
Add Boost.Python module

### ISSUE THREAD

**Issue by pamolloy** [mesonbuild/meson#2507]
Meson does not appear to currently support [Boost.Python](http://www.boost.org/doc/libs/1_65_1/libs/python/doc/html/index.html). It don't see an appropriate entry in [`BOOST_LIBS`](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies/misc.py#L764). I haven't tried to read through or run `tools/boost_names.py` yet, but will try to take a closer look later. Unfortunately, I'm not familiar with Jamfiles (see [boostorg/python/build/Jamfile](https://github.com/boostorg/python/blob/develop/build/Jamfile)). Any help would be greatly appreciated.

**Comment by pamolloy** [comment]
As is probably immediately evident the script fails because it assumes all modules contain a `Jamfile.v2`, as opposed to a `Jamfile`.

**Comment by NickeZ** [comment]
The Jamfile looks to complex to just "parse" with a regex.. Since the python module is the only one using a Jamfile and that has a library I think it is a bit overkill to write an actual parser. I'll make a pull request that simply adds libboost_python{,3} and libboost_numpy{,3}. From what I can read that is all the libraries that are defined.
