### ISSUE TITLE
Pnacl

### ISSUE THREAD

**Issue by felipellrocha** [mesonbuild/meson#257]
Hey guys.

I was trying to compile some of my stuff using pnacl (https://developer.chrome.com/native-client). I was wondering whether that would be possible with meson.

Thanks,

Felipe Rocha

**Comment by jpakkane** [comment]
I have not tested myself but if the pnacl compiler shows itself like a plain gcc/clang compiler then it should work. You need to write a cross file for this setup and then run a cross build. If pnacl requires extra compiler flags then you need to set them manually. Since I have not played with this myself it's hard to say if we could provide those automatically.

**Comment by nirbheek** [comment]
You can use almost any generator with `custom_target()`, and native support for this would be added only if someone is working on it. Closing issue.
