### ISSUE TITLE
Boost: Broken detection when cross compiling to Windows hosts

### ISSUE THREAD

**Issue by lachs0r** [mesonbuild/meson#2631]
Python system: Linux
Version: 0.43.0

When cross compiling to Windows using a mingw-w64 toolchain, the Boost dependency detection is broken and can’t find the libraries.

Problem is probably right here:
https://github.com/mesonbuild/meson/blob/e51da1a34d3ac2ed23451e05c971720c20aaa064/mesonbuild/dependencies/misc.py#L230-L233

Also, this needs more logging. Can’t even tell what it’s looking for.

**Comment by nirbheek** [comment]
@NickeZ, could you look into this and also add more debug logging with mlog.debug()?

**Comment by NickeZ** [comment]
I never tried cross compiling with boost. I probably won't set this up and try it..

**Comment by lachs0r** [comment]
> I never tried cross compiling with boost. I probably won't set this up and
> try it..

This should be quite easy with mxe.

Basically, Meson’s Boost detection assumes that Windows == MSVC, and lifting 
that assumption would most likely fix this issue.

**Comment by bredelings** [comment]
On Debian a cross build involved installing `g++-mingw-w64`, wine and `wine32`.  Building the boost dependency so that meson can try to find it might be more work.

Probably most of the occurrences of is_windows() and is_linux() need to be changed to for_windows( ) and for_darwin( ).  Specifically,
* `mesonlib.is_windows()` -> `mesonlib.for_windows(self.want_cross, self.env)`
* `mesonlib.is_osx()` -> `mesonlib.for_darwin(self.want_cross, self.env)`

Maybe we should add methods self.for_windows() and self.for_darwin() to ExternalDependency or Dependency?

**Comment by lyakhov** [comment]
I can confirm the issue exists on Fedora 27 cross-compiling using mingw32 -- and using precompiled boost packages (mingw32-boost, mingw32-boost-static). 

Hopefully, there is a workaround, as mentioned at https://unix.stackexchange.com/questions/408963/meson-doesnt-find-the-boost-libraries:
```cxx = meson.get_compiler('cpp')
    boost_dep = [
        cxx.find_library('boost_system'),
        cxx.find_library('ws2_32')
    ]
```
(that is particular case for boost asio using Windows sockets for TCP)

**Comment by bredelings** [comment]
See also #2990

**Comment by bredelings** [comment]
@lachs0r I think this is fixed now in current master.  Can you try it out?

**Comment by lachs0r** [comment]
Sorry about the late response. Seems to work now. Thanks!
