### ISSUE TITLE
Sailfish OS SDK support

### ISSUE THREAD

**Issue by clix9** [mesonbuild/meson#265]
Are there plans to make Meson available for the Sailfish OS SDK?

And if there are, are there plans to add SDL2 build files (btw. SDL2 is broken on Jolla Devices, I thought I would bring this particularly to the attention of @jpakkane)

**Comment by jpakkane** [comment]
The packages provided by Sailfish OS SDK are mostly defined by Mer and Nemo projects. They both aim to be minimal distros and only allow new packages if there is actual use. I can do the packaging if there is is sufficient demand for it. In the mean time you can use Meson by installing Python 3 and Ninja in the sb2 targets and putting Meson in path.

SDL2 has been working on Jolla devices for a while assuming you do graphics with OpenGL ES 2 yourself. SDL_Renderer has been broken but that has been fixed in 1.1.7 or 1.1.9, please try again.

Since this is not really a bug in Meson, I'm closing this. Please file a new bug in Mer bugzilla for the packaging.

Thanks,
