### ISSUE TITLE
Support rspfile in ninja backend

### ISSUE THREAD

**Issue by jimon** [mesonbuild/meson#271]
On windows there is a command line limit, so longer calls from ninja with just fail with "CreateProcess: The parameter is incorrect."

To reproduce it just do :

     project('app', 'cpp')
     executable('app', 'test1.cpp', 'test2.cpp', ... , 'test1000.cpp')

And generate build.ninja file. In this case backend will generate one link build command with all 1000 object files. And total length of this command will be longer that maximum command line length on windows.

To fix it you need to use [rspfile in ninja](http://martine.github.io/ninja/manual.html#ref_rule)

**Comment by jimon** [comment]
Awesome ! :+1:

**Comment by nico** [comment]
We were talking about this issue elsewhere; I wanted to chime in on the fix here:

Re meson#271:

```
>>> len('test1.cpp') * 1000
9000
```

It sounds like meson sends link commands through the shell which has a limit of 8k. If you don't send links through the shell, the limit is 32k.

Also, the example here is combining compile and link of 1000 cpp files in one invocation. In practice, it's more likely to have 1000 compile actions taking cc -> o and then one link taking 1000 o files.

Writing rsp files on Windows is expensive. If you unconditionally use them for every compile, each compile will be a bit slower. In chromium, with a distributed build system that makes the actual compile fast, stopping to use rsp files for compiles made the build 50% or so faster (https://bugs.chromium.org/p/chromium/issues/detail?id=796021#c7) since rspfiles are written serially by ninja but the compiles run in parallel.

So I'd recommend that you don't use rspfiles by default for compiles (for links it's ok since there are way fewer of them). I don't know if meson makes a compile/link distinction and if that's feasible to implement; but I thought I should mention it.
