### ISSUE TITLE
Why all subproject should be inside a directory?

### ISSUE THREAD

**Issue by jvanz** [mesonbuild/meson#2766]
Hi guys,

I'm starting to build more complex build using meson and I'm loving it. I'm sure this is one of, if not the best, build system out there. But I have a doubt and possible a suggestion...

Why we need to always put the subproject within a folder? Why the `subproject` call cannot receive the path as argument? My suggestion is remove the need of a specific directory to subprojects. 

Thanks!

**Comment by jpakkane** [comment]
There are several reasons.

First of all, to maintain any sort of sanity, the system must prevent going inside other subprojects with `subdir` or variations thereof. Having the subprojects in well defined places makes this easy. If subprojects could be anywhere at all, it would be a lot harder.

Second of all it is extremely important that end users can easily see what subprojects any project has. Because they are in one, and only one, place, reviewing them becomes easy.

This is also a question of convention. Since all Meson projects have the same layout w.r.t subprojects, switching between projects becomes easier. You don't have to spend time on a new project traipsing through the source tree looking for subprojects. They are always in the same place.

Finally if you can have subprojects anywhere, this increases the possibility of having many different (possibly incompatible) versions of a dependency in your source tree. Then changing some code (such as changing the order you traverse directories) may cause a completely different version of the subproject to be used by accident.

**Comment by nirbheek** [comment]
We should probably add this to the FAQ somewhere. :)

**Comment by tyszja** [comment]
This issue is already closed but I just came across this limitation and would like to share my thoughts even if no one reads it or care.
I really like how meson works in general but hate the idea of build system forcing your project's folder structure to the form your build system maintainers consider 'the correct one'. You know what suits your project needs better than they do. This may stop people from migrating from other build systems. (another reason - imagine every git blame pointing you to a commit which moved the whole thing to 'subprojects' folder so that your new build systems could work. And you should not blame git for it's 'blame' implementation - it works this way since the dark ages).

The subprojects and dependency system seams a bit rigid to me. You are even forced to keep a flat, one level deep structure inside 'subprojects' without any sensible grouping folders like 'subprojects/vendor/vendorlibXYZ/', 'subprojects/myown_lib_using_vendorlibXYZ'. Going further - there is no nested dependency solving when your app depends on subproject_libA, which depends on subproject_libB. Manually adding all dependencies in the master 'meson.build' is not nice at all. I initially thought that the purpose of subprojects and dependency systems was to solve this problem by letting subprojects manage their dependencies on their own (this makes even more sense if they are stored on different git repos) - I was wrong though.

Cheers.

**Comment by jpakkane** [comment]
> this makes even more sense if they are stored on different git repos

If each dependency is in its own Git repo, then combining them together with [a wrap-git file](http://mesonbuild.com/Wrap-dependency-system-manual.html#branching-subprojects-directly-from-git).

**Comment by tyszja** [comment]
@sarum9in Nested dependencies are indeed recognised but not resolved in a 'nested' way. I still have to manage all the subprojects of my subprojects in a top level subprojects directory right? Just like in the example you linked to - the main program depends on lua and libpng but still it manages the zlib dependency for libpng in the form of zlib.wrap in it's top level subprojects folder. While I would expect the libpng.wrap to somehow handle this dependency for me (either by *.wrap file itself or the wrapper/patch pointed by the 'patch_url' variable inside the wrap file).

@jpakkane I was not aware of the git wrapper, thanks. If it resolves the nested subprojects case (e.g. by merging 'subprojects' directory of a wrapped subprojects with the top level subprojects folder) then it's even better. But if I still have to manually merge 'subprojects' folders of each fetched subproject with the master 'subprojects' folder then it's not exactly what I'm looking for. I guess I would like to trade a bit of explicity for simplicity. ;)

Regards.
