### ISSUE TITLE
Reject comparison between boolean & string (or any incompatible combinations)

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#2870]
While reviewing libdrm's meson port I found such construction (which is typo, but anyway).

`if get_option('foo') != 'false'`

To be honest, I want meson to fail hard on this... Or at least show noisy warning.

**Comment by nirbheek** [comment]
Yes, we should definitely do this for comparisons against the return value of `get_option()` (since that is strictly-typed), but I am unsure if we should do this for all variables. For instance, people might be doing something like:

```meson
libfoo_path = false
if some_condition
  libfoo_path = '/usr/local/lib'
elif some_other
  libfoo_path = '/opt/lib'
endif

if libfoo_path != false
  library('somelib')
endif
```

i.e., variables do not have strict type constraints. One way to implement this would be to set a property on the returned value of all meson functions with a list of the types it can be. Then we'd know if the comparison was never going to be satisfied because it compared against an impossible type.

**Comment by jeandet** [comment]
The point here is, I think that this should be simpler. Variables are just 'references' or 'labels' as in Python while values have a type. Then this is stated that there should be no implicit type conversion [here](http://mesonbuild.com/Syntax.html#syntax).
So I think that @ignatenkobrain you pointed a real bug, there should be an error message like 'can't compare bool and string'

**Comment by jpakkane** [comment]
> So I think that @ignatenkobrain you pointed a real bug, there should be an error message like 'can't compare bool and string'

Yes. Meson is not PHP. Implicit type conversions are bad.
