### ISSUE TITLE
How to pass include directories / CFlags to gtkdoc-scangobj ?

### ISSUE THREAD

**Issue by Salamandar** [mesonbuild/meson#2901]
I'm probably not understanding something here, but I need to pass additionnal flags to scangobj:
* `include_directories` to specific dirs of the project
* `link_with` helper/static libraries of the project

It seems that the only way to do that is to `declare_dependency` with those infos and pass this dependency to `gnome.gtkdoc`.
Isn't there an easier way ?

EDIT: That doesn't work, because `meson.source_root()` is a relative path, and the scanobj call is equivalent to:

    cd devel-docs/libgimp && gtkdoc-scangobj --cflags=... --ldflags=...
That seems to break the path to `meson.source_root() == ../.`.
Or am i missing something ?

**Comment by inigomartinez** [comment]
I'm having the same issue when porting [evince to meson](https://gitlab.gnome.org/GNOME/evince/merge_requests/80). Most of headers include [guards](https://gitlab.gnome.org/inigomartinez/evince/blob/meson/libview/ev-page-cache.h#L20) to force including just two general headers, [evince-view.h](https://gitlab.gnome.org/inigomartinez/evince/blob/meson/evince-view.h) and [evince-document.h](https://gitlab.gnome.org/inigomartinez/evince/blob/meson/evince-document.h), unless `EVINCE_COMPILATION` macro is defined.

This macro definition has to be passed as `CFLAGS` in both [libview](https://gitlab.gnome.org/inigomartinez/evince/blob/meson/help/reference/libview/Makefile.am#L111) and [shell](https://gitlab.gnome.org/inigomartinez/evince/blob/meson/help/reference/shell/Makefile.am#L103) GTK documentation generation.

Using the `scanobjs_args` parameter to include it does not work, so there doesn't seem to be any way to override the `cflags` already included by meson.

**Comment by Salamandar** [comment]
@inigomartinez i've already started and almost finished to port evince... I'll send you my work when I can if you're interested.

**Comment by 3v1n0** [comment]
I'm having the same issue, I've to say that related only to `include_directories` the problem can be fixed as you said using `declare_dependency` with something like `dependencies: [LIB_DEPS, declare_dependency(include_directories: extra_include)]`, however, this could even just be fixed by passing the `include_directories` *unducomented* parameter to `gnome.gtkdoc` (see https://github.com/mesonbuild/meson/blob/master/mesonbuild/modules/gnome.py#L888).

However, this is indeed a bug, even using `add_project_arguments(cflags, language: 'c')` doesn't work (well, I've a fixed for this case, though).

In the mean time that I'm looking at how to fix properly meson, however these [gtk-doc patches](https://gitlab.gnome.org/GNOME/gtk-doc/merge_requests/7) should allow to use a syntax such as:

```
scanobjs_args: [
     '--cflags=' + ' '.join(cflags),
     '--ldflags=' + ' '.join(libs)
  ]
```
