### ISSUE TITLE
Missing features to enable GNOME applications

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#295]
As discussed face-to-face during the Meson presentation at GUADEC, meson is currently not featureful enough for GNOME applications which rely heavily on autoconf macros to handle a lot of automation during the build process, and during post-installation.

There is currently no support for Meson in `gnome-continuous` (aka `ostree`), nor in `jhbuild` which are the 2 biggest build scripts used in GNOME.

Applications usually have post installation scripts that will only be run if the installation is done on the target system, such as compiling GSettings schemas, updating desktop databases, or updating the icon cache. For example, gnome-twitch requires you to do that by hand:
https://github.com/Ippytraxx/gnome-twitch/blob/master/README.md

Finally, a number of macros were provided by `gnome-common` and now available in the upstream `autoconf-archive` project, a number of which are listed here:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
(gtk-doc, yelp, appdata support, deprecation and warnings macros, etc.)

**Comment by jpakkane** [comment]
For the specif case of gnome-twitch, Meson allows you to run custom scripts during the install phase with `meson.add_install_script()`. Creating a simple shell script with the required steps and then running it makes those manual steps go away.

Since I don't have personal experience with desktop databases and the like I have not yet added builtin functionality for them. Some post-install steps are done by the packaging system so the app developer does not need to care. I don't know if these particular features fall into this category, though. The best approach (short of filing patches :) is to report individual bugs with as specific requirements as possible.

As for the package builders, that is a bit of a chicken and egg problem. Some tool maintainers (not speaking of jhbuild or gnome-continuous, but some other ones I've talked to) are wary of adding support for build systems that are not widely used yet. This is understandable, as they have only a limited amount of time. But on the other hand developers don't want to use build systems that are not supported by their other tools. I don't have a really good solution for this but I'll be glad to support those tool devs with integration.

**Comment by hadess** [comment]
> For the specif case of gnome-twitch, Meson allows you to run custom scripts during the install phase with meson.add_install_script(). Creating a simple shell script with the required steps and then  running it makes those manual steps go away.

Is it possible to have those not run in some cases? Installation for the purpose of placing the files in the right directories, for package building, shouldn't run those commands, but a user installing the program by hand should.

They usually just check whether DESTDIR is set, so `make DESTDIR=/my/tmp/path install` will not run the script, but `make install` would.

> Some post-install steps are done by the packaging system so the app developer does not need to care.

That's when the application will be packaged, which might not be the case.

> As for the package builders, that is a bit of a chicken and egg problem. Some tool maintainers (not speaking of jhbuild or gnome-continuous, but some other ones I've talked to) are wary of adding support for build systems that are not widely used yet.

I don't think that any patches for jhbuild, at least, would be discarded if it helps add more applications to the module set.

**Comment by jaystrictor** [comment]
> Is it possible to have those not run in some cases? Installation for the purpose of placing the files in the right directories, for package building, shouldn't run those commands, but a user installing the program by hand should.

FYI: gnome-twitch [now](https://github.com/Ippytraxx/gnome-twitch/blob/64b0a72e2f6c2dad4e392590f9b9bc26e8242a2d/meson.build#L6-L8) has a conditional start of `meson.add_install_script()`.

**Comment by TingPing** [comment]
To add to this list also it would be useful if the gnome module had support for generating c++ bindings with mm, see `mm-common`.

**Comment by mcatanzaro** [comment]
So this issue can probably be closed now, right? I think the remaining tasks are covered by #837.

**Comment by tp-m** [comment]
Yeah, let's close this. Please open new issues for specific missing features if needed.

**Comment by craigbarnes** [comment]
> For the specif case of gnome-twitch, Meson allows you to run custom scripts during the install phase with meson.add_install_script(). Creating a simple shell script with the required steps and then running it makes those manual steps go away.

@jpakkane 

When you say "during" the install phase, do you mean *after* everything has been installed or just at some unspecified point in the install phase?

The reason I ask is because I got some strange [output](https://gitlab.com/craigbarnes/showdown/-/jobs/19581894) when testing a meson build on GitLab CI. The `echo` commands from within script are shown at the start of the install phase but Meson's own "running custom install script" message is shown at the end. Is this something to do with multi-threading and output buffering?

**Comment by jpakkane** [comment]
Output buffering does some weird things but AFAICR currently Meson first installs its own things and only after that runs custom install scripts.
