### ISSUE TITLE
cpp_args aren't included with dependency

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#306]
I have a dep:
```
lib_dep = declare_dependency(
    cpp_args:['-DTHING1=-1 -DTHING2=1'],
    include_directories:include_directories('lib/include'),
)
```
and a static lib:
```
util = static_library('Util', src,
    cpp_args:['-DSOMETHINGELSE=100'],
    dependencies:[lib_dep],
    include_directories:[boost_inc],
)
```

Should the cpp_args from `lib_dep` be included in `util`?

**Comment by jpakkane** [comment]
No by design, because explicit is better than implicit. Debugging where random problematic compiler flags come from is extremely annoying (as an example CMake has 5-10 different implicit places where compiler flags can come from).

If you have a set of flags you want to use in several places either use `add_global_arguments` or store them in a variable like `common_flags` and pass that to your targets.

**Comment by rhd** [comment]
Great explanation... Thanks.

**Comment by rhd** [comment]
#423 add this feature... thanks! Use `compile_args` instead of `cpp_args`.
