### ISSUE TITLE
Feature Request: Test Groups

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#325]
Hi,

It would be really nice to somehow specify a different set of tests to run. I have some fast running and some really slow running tests and it would be really nice to somehow switch between the two.

I can somewhat do this currently by changing a flag via mesonconf, but adding a new target like `ninja test group1` or `ninja test-group1` would be more ideal.

UPDATE: 
Also, the ability to run a single test by itself would also be hepful.

**Comment by jpakkane** [comment]
Can you try mr #327 and see if it does what you expect?

Running a single test is problematic because in Ninja you can't add arguments to targets, so you would need to create a top level target for each test and that quickly becomes infeasible. However you can do this yourself easily, mesonintrospect.py can be used to extract all the information necessary to run each test. Just grab that and run it manually.
