### ISSUE TITLE
Document compiler warning_level project option

### ISSUE THREAD

**Issue by ptomato** [mesonbuild/meson#3275]
Searching for it in the documentation turns up nothing. It cost me quite a lot of source-diving to find out whether 1 or 3 was the most strict warning level.

**Comment by mwleeds** [comment]
I think this can be closed? The documentation is here: https://mesonbuild.com/Builtin-options.html#

**Comment by ptomato** [comment]
Excellent, thanks!

**Comment by le-jzr** [comment]
So, what do those levels actually mean? 3 being "the most strict" doesn't really say much, when I don't know which warnings are enabled. That would have been fine in the past, but with current version, meson actually spews warnings about "please use this vague option instead of manually using `-Wall -Wextra`", and I find that risky when it's not even documented what it's meant to mean exactly.

**Comment by philippludwig** [comment]
I agree about that. I have read the GCC manpage and have a pretty exact idea which warnings I would like to enable.

Furthermore, there should be an easy copy&paste snippet on the documentation page. If I write `warning_level(3)`, I get:

```
meson.build:2:0: ERROR: Unknown function "warning_level".
```

And I don’t find any indication on how this option is being used correctly.

Therefore, I would like to suggest that the warning `WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.` is removed.

I assume that this feature is intended as some compiler-agnostic warning setting, but when I don’t care about other compilers, just let me set my flags as I would like without printing something like this.

**Comment by eli-schwartz** [comment]
Worse is the fact that:
- warning_level 1 adds `-Wall`,
-warning_level 2 adds warning_level 1 + `-Wextra`,
- warning_level 3 adds warning_level 2 + `-Wpedantic`

But some projects want `-Wall` and `-Wpedantic`, but refuse to add `-Wextra` because it's not a stable definition. It's therefore impossible to use the meson option. So the warning is useless, as it will warn you about things you cannot change.

**Comment by smac89** [comment]
> Worse is the fact that:
> 
>     * warning_level 1 adds `-Wall`,
>       -warning_level 2 adds warning_level 1 + `-Wextra`,
> 
>     * warning_level 3 adds warning_level 2 + `-Wpedantic`
> 
> 
> But some projects want `-Wall` and `-Wpedantic`, but refuse to add `-Wextra` because it's not a stable definition. It's therefore impossible to use the meson option. So the warning is useless, as it will warn you about things you cannot change.

It would be nice if the above was documented to include the corresponding warning flags for different languages

**Comment by eli-schwartz** [comment]
I submitted #7973 to stop meson from reprimanding you if you manually add -Wpedantic, did not (currently) try to document the flags each level add though.

**Comment by eli-schwartz** [comment]
That will fail the build needlessly when users build from a git checkout.

**Comment by zippy2** [comment]
Which is acceptable, because that's usually the case for advanced users building their own package (and they probably know ho to report this back to the project in question). Majority of users use distro shipped binary packages -> no problem.

**Comment by eli-schwartz** [comment]
- It's nowhere near true to say that only advanced users build from git checkouts.
- Even advanced users cannot use their advanced knowledge to report the bug and then, having done their "duty", build the software anyway and ignore the warning. There's no option to disable -Werror hardcoded in the build files.
- Claiming the majority of users use distro shipped binary packages implies that distros actually ship all software as binary packages, but they don't. They ship lots of popular software, and some unpopular software, but there is always stuff that users need to build themselves in order to use it. This ties back into point 1.

**Comment by Consolatis** [comment]
> Worse is the fact that:
> 
> * warning_level 1 adds `-Wall`,
> * warning_level 2 adds warning_level 1 + `-Wextra`,
> * warning_level 3 adds warning_level 2 + `-Wpedantic`

Is the quoted table documented somewhere?
https://mesonbuild.com/Builtin-options.html only states `From 0 = none to everything = highest`.

On a side note: It seems neither `none` nor `highest` are the correct definitions of what that setting actually does.

**Comment by xclaesse** [comment]
Maybe we should deprecate numerical values, and have more proper names. Like `-Dwarning_level=all,pedantic`. Probably would require some approximative mapping for compilers other than gcc/clang.
