### ISSUE TITLE
Detect microsoft vc 2015 toolchain #1

### ISSUE THREAD

**Issue by RedSkotina** [mesonbuild/meson#331]
Environment variable 'CXX' not work with path that have space.
Example: 
> set
   CXX=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe
> meson build
Meson encountered an error in file meson.build, line 1, column 0:
Unknown compiler(s) "C:\Program, Files, (x86)\Microsoft, Visual, Studio, 14.0\VC
\bin\cl.exe"
i think  in https://github.com/mesonbuild/meson/blob/master/environment.py#L288
instead 
compilers = os.environ[evar].split()
must be
env_delimiter = ';' # for windows and ':' for unix
compilers = os.environ[evar].split(env_delimiter)

**Comment by jpakkane** [comment]
This is problematic because to use e.g. distcc or ccache you need to do `CC='ccache distcc gcc'`. But for VS you should always have cl in path, because vs is only guaranteed to work if launched from the VS command prompt. It sets env vars and other stuff. Simply pointing to the compiler binary will not work (or it might work some time but fail mysteriously and randomly).

**Comment by RedSkotina** [comment]
When i have cl and gcc both in path then gcc detected earlier and i cant specify microsoft compiler without CXX variable. 
Can we then have checked a variable like 'VCINSTALLDIR' (setted by vs command prompt) for take priority at VS compilator ?

**Comment by jpakkane** [comment]
If you have cl in path then you can specify it with `CXX=cl meson <options>`.

**Comment by RedSkotina** [comment]
Thanks for solution, i didn't know what we can use just name without full path.

**Comment by half2me** [comment]
Any idea why I get `Compiler cl can not compile programs.`
``` bash
$ cl --version
Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```
