### ISSUE TITLE
Allow setting LLVM_CONFIG to find $CARCH-llvm-config in 'cross' builds.

### ISSUE THREAD

**Issue by hanetzer** [mesonbuild/meson#3327]
Greets.

Gentoo needs to be able to set the llvm-config tool via the `LLVM_CONFIG` envvar
(preferably) in order to transition our mesa ebuilds to use meson instead of autotools.

**Comment by QuLogic** [comment]
I haven't tried it, but looking at `ConfigToolDependency`, it should already be supported with the `llvm-config` variable in the `binaries` section.

**Comment by hanetzer** [comment]
@QuLogic yes, I see that that is doable, but via gentoo's `meson.eclass` a cross-file is only
generated when cross compiling, and lib32 on amd64 machines is not considered a cross
compile for this purpose.

**Comment by hanetzer** [comment]
Plus `llvm-config` can already be given via 'LLVM_CONFIG' in the autotools build for mesa,
and being rather analogous to `pkg-config` and `PKG_CONFIG` in most other ways it would
make sense to have the same ability for specification.

**Comment by hanetzer** [comment]
And gratz, meson 0.48.0.dev1 breaks on mesa-18.2.0_rc3 because gen_matypes
can't be used without a exe wrapper because abi_x86_32 on amd64 is 'cross-built'.
We really need to be able to specify this now in gentoo otherwise we'll not be able to
do 32 bit builds on 64 bit systems with meson eventually.

**Comment by nirbheek** [comment]
> because gen_matypes can't be used without a exe wrapper because abi_x86_32 on amd64 is 'cross-built'.

I am a bit confused, earlier you said that x86 on amd64 is not considered cross compilation, but now it is? Regardless, if you have a cross file, you can tell Meson that an exe wrapper is not needed by setting `needs_exe_wrapper = false` in the cross file properties.

**Comment by hanetzer** [comment]
I mean, in gentoo, we currently handle buidling x86 on amd64 via a cross file,
so its treated as a cross-compilation even though it isn't, kinda. We end up with
this bug: https://bugs.gentoo.org/664222

**Comment by nirbheek** [comment]
Right, then you should definitely set `needs_exe_wrapper = false` in the cross file when building x32 or lib32 on amd64.

Also, as a status update for the original request, we're not going to add more environment variables, but we will be implementing a "--native-file" option which will be similar to the `--cross-file` option, but for native builds.

**Comment by hanetzer** [comment]
The problem here is we cannot unconditionally declare `needs_exe_wrapper = false` in our
use case, as gentoo's eclasses and ebuilds are rigged to work as native builds, lib32 builds,
and true cross-compiles, including cygwin, mingw-w64 and osx. llvm-config is a very close
anlog to pkg-config and we allow for specifying it via an env var, so it makes sense to allow
llvm-config to do the same, especially as making autotools->meson ports easier.

**Comment by devurandom** [comment]
#4254 includes a potential fix for this issue.

**Comment by eli-schwartz** [comment]
> Also, as a status update for the original request, we're not going to add more environment variables, but we will be implementing a `--native-file` option

So you are refusing to respect prior art, and then adding a feature that requires one command-line option *plus* one configuration file, per environment variable you refuse to support.

I beg you to reconsider, as this is really an inferior way of doing things.

**Comment by eli-schwartz** [comment]
And when using distribution packaging, it's extremely scalable because it's already a shell script. Which can be inlined in the existing shell script, in a way that native files cannot be (without using some truly horrid heredoc). Thus, logically, it fulfills some non-zero use case. 

(This doesn't need to scale with such fervor anyways, since projects are *supposed* to use pkg-config files, and config-tool is a workaround for these exceptional cases.)

And native files cannot be conveniently shared in a distribution build environment. The options are:
- add a single native file for each package that provides a config-tool, then add each native file to the meson command line, stacking up in at least as confusing a manner as those environment variables you hate, with the advantage that at least we would be grateful if only we were using Windows
- add a global native file for lib32 builds, which has no package to go in, and then have every lib32 package depend on some data package that just provides the native file alone, causing additional dependencies, versioning hell and bureaucracy while you try to make sure that the official distribution native file has all the tools you happen to need, and adding one which has been forgotten,
- adding the same file to the meson package, with the additional disadvantage of going through the bureaucracy of re-releasing meson itself

All this in order to... what? Refuse to support an additional option **as a matter of policy**? Did I say that I'm morally opposed to `$LLVM_CONFIG` coexisting with native files the way `$PKG_CONFIG` **already** does?

I did not say so. I responded to your policy declaration that (paraphrasing) "meson shall not implement some ridiculous environment variable, because I say so, but I shan't tell you why", and said that **meson should respect prior art** and support `$LLVM_CONFIG`, irrespective of any other consideration, since an environment variable offers a great deal of convenience.

P.S. If you really believe that environment variables are such a broken model, then I expect you to remove support for the environment variables you currently do support. i.e. `$PKG_CONFIG`. I **don't** expect riots, since pkg-config itself will take the choice out of your hands w.r.t. supporting `$PKG_CONFIG_PATH`/`$PKG_CONFIG_LIBDIR`, but I guess I wouldn't be too surprised if your vision of purity led you to aggressively purge environment variables from anywhere you see them (because clearly it's downright evil to allow anything to exist even as a fallback, that Windows developers don't know how to do).

Also please remove support for confusing, Un-Windows-like, non-stackable `CC`, `CFLAGS`, etc. environment options. We don't need to be able to unify settings across multiple build systems, only meson matters! People should set this in a native file!

**Comment by eli-schwartz** [comment]
> except that you can't easily share shell scripts between projects, whereas sharing native files is simple

By the way, sharing shell scripts between projects is just as simple, as long as your shell supports the `source` command.
