### ISSUE TITLE
pkgconfig generator: Add project/global arguments

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/meson#3334]
Arguments defined using those functions are ignored by the pc generator, but since they were needed to build the lib they should probably be pulled into pc just like any other deps:
        add_global_arguments()
        add_global_link_arguments()
        add_project_arguments()
        add_project_link_arguments()

While at it, probably consider extra_args we are adding in https://github.com/mesonbuild/meson/issues/3304

**Comment by jpakkane** [comment]
No, that can not be made reliable. Suppose there is a project that uses a project level compile option to toggle symbol visibility and imports, something like `add_project_arguments('-DBUILDING_MYLIB=1', ...)`. This must NOT under any circumstances be allowed in pc files because they will break them for _everyone_ who tries to use them.

Global arguments should never be put there, because they can come from other projects and have stuff like `-Ofast-math` or something else, which, again, must _never_ enter any pc file.

**Comment by xclaesse** [comment]
Good point.
