### ISSUE TITLE
Cannot pass Qt's include paths to qt.preprocess

### ISSUE THREAD

**Issue by SirCmpwn** [mesonbuild/meson#3470]
https://github.com/SirCmpwn/qtlayershell/blob/6315d292a72690391d207894f066a10becd1c8e6/qtlayershell/meson.build#L12-L31

**Comment by jeandet** [comment]
@SirCmpwn, maybe accepting dependency objects as argument to preprocess would make this easier.

**Comment by SirCmpwn** [comment]
>@SirCmpwn, maybe accepting dependency objects as argument to preprocess would make this easier.

Yes

**Comment by equeim** [comment]
I have run in the same issue recently. Basically if you QObject-derived class implements any Qt interface (e.g. has Q_INTERFACES(QQmlParserStatus) in declaration), MOC will fail because it can't find interface declaration. I decided to go with CMake instead because workaround for this is too ugly (well, and brcause of other issues with Qt in Meson).

**Comment by jeandet** [comment]
Covered by #3998.
