### ISSUE TITLE
Build fails when passing -Dc_args due to extra quotes

### ISSUE THREAD

**Issue by ndufresne** [mesonbuild/meson#3473]
I encountered this regression when moving of 0.45 to 0.46 today.  If I call meson with ```-Dc_args="-g -O0" ```

I get the following error at build:
```
cc -Iorc/orc@@orc-0.4@sha -Iorc -I../orc -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O2 -g -DHAVE_CONFIG_H '-g -O0' -fPIC -DORC_ENABLE_UNSTABLE_API -D_GNU_SOURCE  -MD -MQ 'orc/orc@@orc-0.4@sha/orcdebug.c.o' -MF 'orc/orc@@orc-0.4@sha/orcdebug.c.o.d' -o 'orc/orc@@orc-0.4@sha/orcdebug.c.o' -c ../orc/orcdebug.c
cc: error: unrecognized debug output level ' -O0'
```
As you can see, meson added quotes around '-g -O0'. Removing the qotes fixes it.

**Comment by xclaesse** [comment]
Oh, and doc says the proper syntax is:
```
$ meson configure -Darray_opt=foo,bar
$ meson configure "-Doption=['a,b', 'c,d']"
```

But that doesn't work neither.

**Comment by jpakkane** [comment]
Can you bisect the exact commit that broke this?

**Comment by xclaesse** [comment]
I'm pretty sure this actually never worked. It's new in 0.46.0 that -Dc_args is not ignored: https://github.com/mesonbuild/meson/pull/3203

Still, that PR has 2 flaws:
- `-Dc_args=foo -Dc_args=bar` result in `c_args=['foo', 'bar']` because it appends instead of replacing when passing that cmd line option more than once, unlike all other options.
- `-Dc_args="foo bar"` result in `c_args=['foo bar']` because it doesn't split on space, unlike `meson configure -Dc_args="foo bar"`.
