### ISSUE TITLE
0.46.0 breaks `gdbus_codegen()` in a subdirectory

### ISSUE THREAD

**Issue by TingPing** [mesonbuild/meson#3488]
I believe this is caused by https://github.com/mesonbuild/meson/commit/b2636ceef9cf838b4368583c41f5583338266eb9 or maybe https://github.com/mesonbuild/meson/commit/351b59f03adcdbf5a4efbaba2446c0e40a456ef1 which move the `--output-directory` args around. I've not tested this out yet though.

**Comment by nirbheek** [comment]
Earlier we used to use `--generate-c-code` which would output both `foo.c` and `foo.h` in the same command. We used `--output-directory` to set the 'base directory' to set the correct `#include` line for `foo.h` in `foo.c`.

Starting with 0.46.0 we started to use `--body | --header` to generate `foo.c` and `foo.h` in separate custom targets.

However, `--body` requires `--output`, and `--output` is incompatible with `--output-directory`. So this is a glib bug. CCing @inigomartinez 

We need `--output-directory subdir --output subdir/foo.c` to mean that `foo.c` should `#include "foo.h"`. The fix for Meson is to disable the codepath that uses `--body` and `--header` by upping the minimum glib version to `9999` till glib is fixed.

**Comment by nirbheek** [comment]
Upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=795802

**Comment by inigomartinez** [comment]
It's my fault.

`--output` and `--output-directory` are mutally exclusives. `--output-directory` was introduced because multiple files where going to be created, so setting the directory where the files were going to be created was necessary. However, `gdbus-codegen` is now able to create body and header files individually, so by using `--output`, the full path can be passed.

@nirbheek i closed your upstream bug, because the behaviour is correct and meson should be fixed. I'll try to fix it.

**Comment by inigomartinez** [comment]
After a chat with @nirbheek in the IRC, I have figured out what was happening, and the issue was in `glib` :disappointed:. I have send a patch though it might not be available until the next glib release.

**Comment by TingPing** [comment]
> --output and --output-directory are mutally exclusives. --output-directory was introduced because multiple files where going to be created, so setting the directory where the files were going to be created was necessary. However, gdbus-codegen is now able to create body and header files individually, so by using --output, the full path can be passed.

Just to be clear so we don't regress in another area. `--output` always worked, the problem was that it used that path to create the header include which is not what we want.

**Comment by inigomartinez** [comment]
> Just to be clear so we don't regress in another area. --output always worked, the problem was that it used that path to create the header include path which is not what we want.

It's fixed now in [upstream glib](https://gitlab.gnome.org/GNOME/glib/commit/5faac84) (Philip Withnall very kindly has also [updated stable 2.56](https://gitlab.gnome.org/GNOME/glib/commit/cd1f82d8f), so this should be fixed when using the [next glib stable release](https://github.com/mesonbuild/meson/commit/78fdf10eb757f0a235bb92110390dd742a7527d7).

**Comment by nirbheek** [comment]
@inigomartinez already fixed! https://github.com/mesonbuild/meson/issues/3531
