### ISSUE TITLE
gtkdoc: gtkdoc-check is not called as part of `meson test`

### ISSUE THREAD

**Issue by pwithnall** [mesonbuild/meson#3580]
gtk-doc provides a `gtkdoc-check` utility which runs unit tests on the generated documentation (making sure it’s complete, looking for syntax errors, etc.) Currently there’s no way to easily run this in Meson. It would be really good if it were automatically hooked up so it ran as part of `meson test`.

**Comment by pwithnall** [comment]
I think treating it like `-Werror` (in the sense that some people always want it enabled, but others don’t because it can bring in breakage outside their control) is sensible. I’d definitely want a way to be able to always have it enabled (for CI, my personal development configuration, etc.).

**Comment by pwithnall** [comment]
How would I go about adding this? Something like `test = Test(… gtkdoc-check …); build.tests.append(test)` from `gnome.py`? Not sure whether I should (or can) fiddle with the `build` object from within a module.

**Comment by xclaesse** [comment]
Note that would considerably increase build time, gtk-doc takes an eternity to build. I worked on this a few years ago for glib and I got it pass gtkdoc-check but desrt didn't want to make it part of make check because it was too slow. The solution that I never implemented was too split html generation out of gtkdoc-check because that's what takes most of the time and is useless for the tests.

As for the meson implementation, I don't think you can/should modify build.tests from a module, you should return the Test object and the interpreter will/should add it to the list.

**Comment by xclaesse** [comment]
In any case, that should definitely be part of the CI where we control the version of gtkdoc. It could be added as separate ninja target, like `ninja doc-test` ?

**Comment by pwithnall** [comment]
> It could be added as separate ninja target, like `ninja doc-test` ?

That would work for me.

**Comment by dcbaker** [comment]
I think  #5591 fixed this, so i'm going to close this, reopen if that's not the case please.
