### ISSUE TITLE
Set linker executable with environment variable

### ISSUE THREAD

**Issue by zhiayang** [mesonbuild/meson#3597]
Hello there.

So I noticed that while the compilers can be set with the environment `CC` and `CXX` and so and so, it appears that Meson doesn't support setting `LD` to change the linker.

Is there a way to do this? Versus just going into the generated `ninja.build` and changing the link command? Reason for this is that `link.exe` is just the slowest piece of trash ever, and I'm seeing if maybe trying out `lld-link` would make my life slightly better.

While we're here, are there plans to allow setting the executables directly in the configuration file, rather than using environment variables? Like maybe 3 levels; the default system compiler, then whatever you specify in the config file, and finally any environment variables?

Thanks.

**Comment by amitdo** [comment]
Clang and GCC support the `-fuse-ld=<linker>` option.

**Comment by zhiayang** [comment]
Is there something that works for MSVC? Makefiles actually work well on unix platforms so I don't use meson on those.

**Comment by nirbheek** [comment]
This does sound like a useful feature to me, particularly because of `lld`'s existence, and also because of `ld.bfd` vs `ld.gold`, even though there's usually a distro-specific way of setting that.

What do you think @jpakkane?

**Comment by jpakkane** [comment]
The main problem with this is that in Meson you can't "just point to a different linker". Someone needs to write all the code to make Meson understand how to run it. On non-Windows we have also actively avoided calling into the linker directly but instead invoke it via the compiler, because it simplifies a lot of things and there are args that you can give it to specify which linker to use.

**Comment by nirbheek** [comment]
> On non-Windows we have also actively avoided calling into the linker directly but instead invoke it via the compiler, because it simplifies a lot of things and there are args that you can give it to specify which linker to use.

The main reason why we do this with GCC and Clang is because they usually call the linker with specific default options which make, f.ex., LTO work correctly.

So the way I would imagine this working, is that we use the `-fuse-ld` option for GCC and Clang, and directly call the specified linker with MSVC.

**Comment by Hi-Angel** [comment]
`-fuse-ld=` option doesn't work for me:

```bash
$ g++ a.o -fuse-ld=clang++       
g++: error: unrecognized command line option ‘-fuse-ld=clang++’; did you mean ‘-fuse-ld=bfd’?
```

*(disclaimer: I heard clang linker is very fast, so wanted to try it out. In my tests it seems to be compatible with GCC)*.

**Comment by nirbheek** [comment]
You need to use `-fuse-ld=lld`, support for which was merged only recently in gcc: https://gcc.gnu.org/ml/gcc-patches/2018-10/msg01240.html

**Comment by Hi-Angel** [comment]
I don't have `lld` binary on my system, nor `clang*ld`, nor `llvm-lld`, Idk why. It's a clang build from SVN, not one from a repository.

**Comment by leio** [comment]
Would be nice to be able to get the LD environment variable at least. For example glib gio/tests/meson.build calls 'ld' outright for some `-r -b binary` stuff, which for 32bit non-native build will generate a 64-bit ELF and everything falls apart later, as everything else is 32-bit in that build (and despite passing a cross file, it isn't considered a cross build, rightly so, so it does go into that glib meson.build path). We already have `LD=x86_64-pc-linux-gnu-ld -m elf_i386` in that case, but this obviously doesn't get honored when `ld` is directly launched, but that's also because there's no access to `LD` env to call it with that. This isn't just for x86 though - other architectures do multilib too and have other -m values for that.

**Comment by dcbaker** [comment]
This is on my list of things to do after #5681 lands, for those interested.

**Comment by 86423355844265459587182778** [comment]
> I don't have `lld` binary on my system, nor `clang*ld`, nor `llvm-lld`, Idk why. It's a clang build from SVN, not one from a repository.

@Hi-Angel 
I guess it is needed to compile LLD separately - see https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/lld-8.0.1.src.tar.xz or https://github.com/llvm/llvm-project/tree/master/lld.

**Comment by Hi-Angel** [comment]
> > I don't have `lld` binary on my system, nor `clang*ld`, nor `llvm-lld`, Idk why. It's a clang build from SVN, not one from a repository.
>
> @Hi-Angel
> I guess it is needed to compile LLD separately - see https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/lld-8.0.1.src.tar.xz or https://github.com/llvm/llvm-project/tree/master/lld.

Thanks, that helped. FTR, in a testcase I still ended up with errors about undefined sanitizer symbols, like:

    ld.lld: error: undefined symbol: __asan_init
    >>> referenced by test.cpp:7
    >>>               a.o:(_GLOBAL__sub_I_00099_1_main)

    ld.lld: error: undefined symbol: __asan_version_mismatch_check_v8
    >>> referenced by test.cpp:7
    >>>               a.o:(_GLOBAL__sub_I_00099_1_main)

    ld.lld: error: undefined symbol: __asan_register_globals
    >>> referenced by test.cpp:7
    >>>               a.o:(_GLOBAL__sub_I_00099_1_main)

    ld.lld: error: undefined symbol: __asan_unregister_globals
    >>> referenced by test.cpp
    >>>               a.o:(_GLOBAL__sub_D_00099_0_main)
    collect2: error: ld returned 1 exit status

I worked that around by adding after the `-fuse-ld=lld` a `-Wl,-lasan`.
