### ISSUE TITLE
Remove directories with spaces from source tree

### ISSUE THREAD

**Issue by aruiz** [mesonbuild/meson#360]
Working with the meson repository on a unix shell feels quite cumbersome, find | xargs requires -print0/-0 and other tasks such as completion or creating new directories that are homogeneous become quite frustrating

"test cases", "manual tests" and the like come to mind as examples

**Comment by jpakkane** [comment]
The reason those directories have spaces in them is intentional. It ensures that Meson properly quotes all file names it handles. What you are seeing is that common unix tools have major problems dealing with file names that have special characters (particularly spaces) in them. This is unfortunately a bit cumbersome for developers (though if you use `zsh` it just works and you very seldom need to use `xargs` and the like) but it is necessary for reliability. As an example on Windows many default paths include spaces (such as `c:\documents and settings`) and Meson needs to work on them.

**Comment by aruiz** [comment]
I don't quite follow the logic here, so in order for you to ensure that meson handles spaces in directory names you scatter the project with directory names with spaces instead of adding an isolated test case/suite that handles that and informs you that such specific condition fails?

Following that reasoning every directory in the test suite should have every single character that you want to ensure that works.

meson is an open source project targetting mostly other open source projects, most open source projects target Linux or bash based UNIX systems, yes xargs and bash could work better with spaces, but nor you and I can handle that and most Linux developers simply tend to not use spaces nor other special characters in their projects.

Can I live with those directories having spaces? Yes, but I'm just saying this is going to make the life of the people who want to contribute to meson a little more difficult.

**Comment by jpakkane** [comment]
I actually considered putting the tests in a directory called `test $ \ > '" cases` or something like that but that would have been too cumbersome. Having just one test case with spaces would not work because file name handling permeates the entire code base. You would need to check that `C` works, custom targets work, run_targets work, subprojects work and so on and so on. The only reliable way is to have the space in every test.

Windows is a tier 1 supported platform and spaces are common there. They need to be supported, so that brings some pain.
