### ISSUE TITLE
Can't find `mesonbuild` on `ninja install` when meson is run uninstalled

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3647]
This was caused by https://github.com/mesonbuild/meson/pull/3393.

```python
[6/7] Installing files.
/opt/local/bin/python3: Error while finding module specification for 'mesonbuild.mesonmain' (ModuleNotFoundError: No module named 'mesonbuild')
FAILED: meson-install
/opt/local/bin/python3 -m mesonbuild.mesonmain --internal install /path/to/builddir/meson-private/install.dat
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "buildtools/run_meson.py", line 186, in <module>
    build(mcu_dir, build_dir, os.path.join('external', 'librtmp'), env)
  File "buildtools/run_meson.py", line 130, in build
    subprocess.check_call(['ninja', 'install'], cwd=build_dir, env=env)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'install']' returned non-zero exit status 1.
```

CC @martingkelly

**Comment by martingkelly** [comment]
@nirbheek there's no way uninstalled runs can work unless you set `PYTHONPATH`; Python cannot know where to find meson unless told. I would suggest we follow the approach that gstreamer does (`gst-uninstalled`) and create a small wrapper script that sets `PYTHONPATH` (relative to the `meson-uninstalled`) script for cases like this.

Without such a thing, there's really only two options:
- Set `PYTHONPATH` manually (painful).
- Go back to error-prone, hard-to-maintain heuristics that break other use cases (e.g. the Yocto SDK). By reverting this, we're breaking a different, valid use-case.

**Comment by martingkelly** [comment]
If you are agreeable to it, I will submit a PR to add this commit back along with a `meson-uninstalled` script.

**Comment by filbranden** [comment]
Commit ab599b5733539130db5c4d17c664744f4d5aacaf  (`commandrunner: make run handle python options` or e0f22b5 here) is also breaking tests for me, in particular `test_run_target_files_path` while trying to run `check_exists.py`.

The command-line I'm getting is: 

<pre>
/usr/bin/python3 "$MESONDIR/meson.py" \
    --internal commandrunner \
    "$MESONDIR/test cases/common/58 run target" /tmp/tmp255jvj15 "" \
    /usr/bin/python3 <b>"$MESONDIR/meson.py"</b> \
    "$MESONDIR/test cases/common/58 run target/check_exists.py" \
    "/tmp/tmp255jvj15/../../$MESONDIR/test cases/common/58 run target/helloprinter.c"
</pre>

I believe the part in bold is the problem, since I'd expect it to call `python3 check_exists.py` and not `python3 meson.py check_exists.py`.

Reverting ab599b5733539130db5c4d17c664744f4d5aacaf fixes the problem.

I haven't gone further in trying to diagnose the problem...

Thanks!
Filipe

**Comment by eli-schwartz** [comment]
As far as I can tell, this works fine these days.

Guessing it just accidentally didn't get closed by the above PR.
