### ISSUE TITLE
pkg-config should not generate CFlags/Include for platform-independent code

### ISSUE THREAD

**Issue by martingkelly** [mesonbuild/meson#3698]
This is a minor issue, but currently the pkg-config module generates a CFlags entry even for code that is platform-independent. This may be a slightly odd case, but I'm using pkg-config to advertise directories for data files, and my repository does not contain any native code. Nonetheless, CFlags/Include entries are being generated. Though this doesn't harm anything, it is a bit confusing from the users' perspective.

As part of this work, it would probably be good to set a property for whether or not a given project is platform-independent (which would be automatically inferred from the language). Then we would not have to duplicate a hard-coded list of languages in multiple places. If we had such a property, we might also consider changing the `lib` path for platform-independent code, as right now it will be set to `x86_64-linux-gnu` even though it is architecture-independent.

If I get the time, I will fix this myself.

**Comment by jpakkane** [comment]
It would be nice if this could be made to work automatically, but we probably can't because C++ header-only libraries installed to `/usr/local` would have no visible output flags but it would still be required.

However if someone can come up with a reliable autodetect method that does the right thing without any user code, we should totally do that.

**Comment by eli-schwartz** [comment]
I guess what you really want is the dataonly mode added in #5775?
