### ISSUE TITLE
find_program() with relative paths and same name

### ISSUE THREAD

**Issue by rhd** [mesonbuild/meson#374]
Hi Jussi,

If I have two different `meson.build` files in two different directories and each `meson.build` contains:
```
exe = find_program('./foo.sh')
```

meson doesn't actually find the 2nd `/path/to/foo.sh`.

A workaround was to do `exe = find_program(meson.current_source_dir() + '/foo.sh')` in each `meson.build` file

Not sure if this is expected behavior or not...

**Comment by jpakkane** [comment]
Meson caches the results of find_program and since you probably have `.` in your path, it finds the first one but not the second one. This is a known issue but I'm not sure how to best fix this. Having `.` in path is highly recommended against but also a very common thing to do. Maybe we should just not cache the results of `find_program`, the perf hit is probably not even measurable (except maybe on Windows).

**Comment by rhd** [comment]
I just checked - I don't have `.` in my path - so that's not issue... the scripts look for `./foo.sh`.

Not caching the results of `find_program` would work for me :)

**Comment by jpakkane** [comment]
Crap, I missed that you have the leading `./`. The behaviour is the same, though, Meson caches based on string comparison but `./foo.sh` means different things in different directories.

**Comment by rhd** [comment]
using `meson.current_source_dir()` isn't too bad of a workaround - but not caching programs seems like a reasonable thing to do. Is windows really slow at finding programs?
