### ISSUE TITLE
Document 'root' and 'sys_root' cross-compilation properties

### ISSUE THREAD

**Issue by tintou** [mesonbuild/meson#3801]
Both variables are available here:
https://github.com/mesonbuild/meson/blob/87871e7b95d4cc89627971f316bdeffebde048e5/mesonbuild/environment.py
But there is no documentation of these properties in the source and in http://mesonbuild.com/Cross-compilation.html
The only file that document them is https://github.com/mesonbuild/meson/blob/master/cross/linux-mingw-w64-64bit.txt

**Comment by ppetraki** [comment]
It's even more cryptic than that, 'root' only appears to be used for mingw. So it's safe to ignore for everything else, but it's not helpful to leave it undocumented because it's a debugging black hole where the user is setting a variable that has no effect.

10/24/19, from Meson HEAD 2b6c997e33e0864fd9bd462e913323b6711f644a

<PRE>
git grep -A4 -B4 get_root 
mesonbuild/backend/backends.py-
mesonbuild/backend/backends.py-    def get_mingw_extra_paths(self, target):
mesonbuild/backend/backends.py-        paths = OrderedSet()
mesonbuild/backend/backends.py-        # The cross bindir
mesonbuild/backend/backends.py:        root = self.environment.properties[target.for_machine].get_root()
mesonbuild/backend/backends.py-        if root:
mesonbuild/backend/backends.py-            paths.add(os.path.join(root, 'bin'))
mesonbuild/backend/backends.py-        # The toolchain bindir
mesonbuild/backend/backends.py-        sys_root = self.environment.properties[target.for_machine].get_sys_root()
--
mesonbuild/envconfig.py-
mesonbuild/envconfig.py-    def has_stdlib(self, language: str) -> bool:
mesonbuild/envconfig.py-        return language + '_stdlib' in self.properties
mesonbuild/envconfig.py-
mesonbuild/envconfig.py:    # Some of get_stdlib, get_root, get_sys_root are wider than is actually
mesonbuild/envconfig.py-    # true, but without heterogenious dict annotations it's not practical to
mesonbuild/envconfig.py-    # narrow them
mesonbuild/envconfig.py-    def get_stdlib(self, language: str) -> typing.Union[str, typing.List[str]]:
mesonbuild/envconfig.py-        return self.properties[language + '_stdlib']
mesonbuild/envconfig.py-
mesonbuild/envconfig.py:    def get_root(self) -> typing.Optional[typing.Union[str, typing.List[str]]]:
mesonbuild/envconfig.py-        return self.properties.get('root', None)
mesonbuild/envconfig.py-
mesonbuild/envconfig.py-    def get_sys_root(self) -> typing.Optional[typing.Union[str, typing.List[str]]]:
mesonbuild/envconfig.py-        return self.properties.get('sys_root', None)
</PRE>

**Comment by killdaclick** [comment]
How to use the sys_root? I need for the cross compilation and pkg-config.
