### ISSUE TITLE
find_program('python3')/python/python2 should use import('python').find_installation()

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#3856]
This will make build files cross-platform by default since python is called different things on different platforms, and people shouldn't need to know that they need to use the python module to get the right behaviour.

**Comment by Tachi107** [comment]
This was implemented in https://github.com/mesonbuild/meson/commit/067ff7eeae26eda8edc9f7f7432f551c3e373eaa, right?

**Comment by eli-schwartz** [comment]
The spirit of this issue is fulfilled: the python module find_installation does a bunch of things to find python, and find_program only does one of those things, but regardless it is sufficient for finding a suitable interpreter to run scripts.

The literal title of the issue will never be fulfilled: find_installation is used for compiling and installing python modules, is slow (costs an import) and slower as well (runs introspection scripts for sysconfig/distutils info) so we are never going to actually expose that as an implementation detail of `find_program('python3')`. :D
