### ISSUE TITLE
Library search path needs to query the linker

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#396]
The get_library_dirs() function in mesonlib hard-codes paths, and that's completely wrong. The search path for C/C++ libraries is decided by the linker. Specifically, the output of:

`gcc -Xlinker --verbose | grep SEARCH_DIR`

Gives the list of search directories in order of priority. I don't have a patch for this because I'm not sure how this ties in with the compiler detected/selected during configuration; especially cross-compilation.

**Comment by tp-m** [comment]
This is a problem even on Linux btw, for example meson fails to find libm on my powerpc/Debian box where it is in /usr/lib/powerpc-linux-gnu/.

**Comment by nirbheek** [comment]
I forgot to add; it's a problem on 64-bit Fedora itself. The default search dirs for 64-bit are: 

```
$ gcc -Xlinker --verbose | grep SEARCH_DIR
SEARCH_DIR("/usr/x86_64-redhat-linux/lib64");
SEARCH_DIR("/usr/lib64");
SEARCH_DIR("/usr/local/lib64");
SEARCH_DIR("/lib64");
SEARCH_DIR("/usr/x86_64-redhat-linux/lib");
SEARCH_DIR("/usr/local/lib");
SEARCH_DIR("/lib");
SEARCH_DIR("/usr/lib");
```

(reformatted for readability)

So, Meson always finds the 32-bit libraries first, and then fails at compile time.

**Comment by jpakkane** [comment]
For system libraries like this a better check would be to check if the compiler accepts `-llibname` because sometimes the libraries don't exist physically. As an example OSX does not have libm because it is in libc. However it is perfectly happy to accept `-lm`, it is just ignored. Time spent detecting libraries manually is usually wasted because system library path thingy is massively complicated.

It even works with MSVC, but only because on Windows the system provides no libraries whatsoever. :)

That being said people seem to want to use this so it probably should work better, though personally I would be happier if we could just get rid of it altogether (which is not really feasible).

**Comment by jpakkane** [comment]
Thinking further, maybe we should make `find_library` a method of the compiler and it could do this in the background. Then you could do this:

    libbob = cc.find_library('bob')
    libcrossbob = cc.find_library('bob')

and then the two would point to different libraries.

**Comment by nirbheek** [comment]
Yeah, I think `cc.find_library()` makes the most sense; would tie in with the language too. For instance finding Mono/C# libraries. I was actually surprised while reading the API reference in the very beginning that `find_library` was not already compiler-specific. I just assumed there was some magic there to take care of that. :)
