### ISSUE TITLE
pkgconfig: implement 'descriptive_name' as an option.

### ISSUE THREAD

**Issue by hanetzer** [mesonbuild/meson#3968]
As it currently stands, the name parameter of pkg.generate is both the filename
on disk + .pc and the 'Name' field inside the pkgconfig file itself. Some projects
have a more human name inside that field, and perhaps they'd avoid porting to
meson if they can't get exactly what they had before working.

**Comment by eli-schwartz** [comment]
Since the original 2014 implementation of the pkgconfig generator (back when it was a top-level `pkgconfig_gen()` function) in commit 0384ca71f712554f3adfe21a16280d0b10969e5d, this has taken two kwargs:
- name
- filebase

If filebase isn't specified, it defaults to name. People who need the functionality described here should just use both kwargs in combination.
