### ISSUE TITLE
Build definition not regenerated after meson configure

### ISSUE THREAD

**Issue by yshui** [mesonbuild/meson#3992]
If `meson configure` is run immediately after `meson setup`, the build definition will be not automatically regenerated when I run `ninja -C <builddir>`.

Adding a `sleep 1` between setup and configure in my script fix this problem for me.

**Comment by nirbheek** [comment]
What version of Ninja are you using?

**Comment by yshui** [comment]
@nirbheek 1.8.2

**Comment by nirbheek** [comment]
And which operating system is this and what filesystem?

**Comment by yshui** [comment]
@nirbheek tested on Ubuntu 16.04.4 LTS with ext4, and Void Linux with btrfs.

**Comment by nirbheek** [comment]
Strange, this Ninja bug was fixed and released with 1.8: https://github.com/ninja-build/ninja/issues/371

The other known bug is with filesystems that don't support sub-1s timestamps at all, such as HFS+. It is surprising that this happens with ext4 and btrfs.

Can you try this Ninja binary? https://nirbheek.in/files/binaries/ninja/linux-amd64/ninja

**Comment by yshui** [comment]
@nirbheek That ninja binary fixes the problem. Perhaps it's how ninja is built? Is there some configure flag needed to be set for sub-1s timestamp?

**Comment by nirbheek** [comment]
Ah, my mistake, I thought 1.8 had the fix but it was made before the pull request was merged. You should ask your distro to ship the patches from https://github.com/ninja-build/ninja/pull/1219 to fix this. It's not a meson bug. :)

**Comment by yshui** [comment]
@nirbheek That fix is not in any released version yet! This is annoying :/

**Comment by nirbheek** [comment]
Unfortunately yes. Thankfully this is why we have distros!

**Comment by FrancisRussell** [comment]
I'm unsure how that is relevant.

Distros typically aim to package released versions as these are considered supported and stable and attempt to minimize their patch set to security and build-related issues. Until a release is made containing these fixes, they're unlikely to make it many distributions. A significant upstream patch set combined with a long interval since the last release increases the chance a package will be removed from a distribution entirely as it is considered an indication that the software is no longer maintained.

**Comment by vcunat** [comment]
As a person who tends to update hundreds of different packages in a distribution, finding a generally recommended combination of patches seems off-putting.  I'd expect upstream knows that combination best and that's why maintenance/bugfix releases are made (or at least maintenance branches).  Having each distro doing the work again seems inefficient, too.

**Comment by vcunat** [comment]
Right, I'm sorry.

**Comment by yshui** [comment]
@QuLogic The point is meson probably shouldn't rely on an un-released version of ninja, and then say it's distributions' job to provide patched packages.

I think the right person to push ninja for new releases is meson developers, rather than us.

**Comment by nirbheek** [comment]
Well, we've been asking them for a release but we don't have a magic hotline to the Ninja developers. The more people that complain to them about it, the better.
