### ISSUE TITLE
pkgconfig module should allow nullification of some default variables.

### ISSUE THREAD

**Issue by hanetzer** [mesonbuild/meson#4011]
Not all projects require the prefix, libdir, and includedir variables in their pkgconfig files.
In addition, it should be possbile to remove the `Cflags: -I${includedir}` line either entirely
or in order to have your own variables there, minus the `-I${includedir}` addition.
For example's sake, this is the entireity of the xorg-libinput.pc file:
```
sdkdir=/usr/include/xorg

Name: xorg-libinput
Description: X.Org libinput input driver.
Version: 0.28.0
Cflags: -I${sdkdir}
```

**Comment by jpakkane** [comment]
Something like this might be added but for this particular case it is not necessary. Using the builtin pkg-config generator is easy and it even works better than writing the file manually. That sample file is not relocatable, that is, if you install it somewhere else (say, to '/usr/local` for whatever reason) then you need to change `sdkdir` manually.

The pkg-config file creator takes care of all that automatically. Basically you only need to add a keyword argument `subdirs: 'xorg'` and the rest will take care of itself.

**Comment by hanetzer** [comment]
@jpakkane that may be so, but I'm trying to 1:1 port this and for whatever reason,
sdkdir is what they use.

**Comment by fooishbar** [comment]
One reason to have this is for architecture-independent pkg-config files in projects which also have architecture-dependent outputs.

For example, Weston installs libweston-N.pc which contains compiled DSOs and architecture-dependent includes. It also installs libweston-protocols-N.pc, which only contains architecture-independent XML files. Debian would like to package libweston-protocols as an architecture-independent package, but it's complaining because it includes architecture-dependent paths, particularly `libdir`.

**Comment by xclaesse** [comment]
The easy answer is you can use configure_file() for those less common cases. But I agree we could add a keyword argument to pkg.generate() that will prevent it from adding such common fields in the case people really want to control exactly what gets written.

**Comment by ppaalanen** [comment]
I do think a way to create architecture-independent pkg-config files would be good to have.

FYI, this is the Weston issue: https://gitlab.freedesktop.org/wayland/weston/issues/269

At least wayland-protocols will have the same problem once converted to Meson since does not install any binaries, even if the Weston issue was resolved somehow else.

**Comment by nirbheek** [comment]
> I do think a way to create architecture-independent pkg-config files would be good to have.

I suggested a kwarg for this in https://github.com/mesonbuild/meson/pull/5775#issuecomment-520297783.
