### ISSUE TITLE
Don't assume that Python 3 is `python3` inside Meson

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#403]
I purposely checked for `python3` first and then `python` in that test because on some platforms (OS X and Windows for instance), Python 3 is installed as `python` and there is no `python3` available.

**Comment by nirbheek** [comment]
Alternatively, we could have a function called `find_python` that gives us the Python 3 being used by Meson.

**Comment by jpakkane** [comment]
The fact that Python 3 is available as python3 is hardcoded in many parts of the code base including a bunch of tests. If we're going to fix this then it should go in all places at once.

**Comment by nioncode** [comment]
Running `grep -P -r '(?<!env )python3'` will revail all usages of explicit python3 usages that are not caused by `#!/usr/bin/env python3` shebang lines.

The prominent usages are:
- `find_program('python3')`
- `dependency('python3')`

Is this something meson should take care of? It is easy to create symlinks from `python` to `python3` or to copy the binary itself.
All those usages are only in `meson.build` files of test cases, which are of no real interest for the average user. If you want to run the tests, you must of course have a working `python3` binary.

Possible ways for fixing `find_program`:
A. Generic:
  - first try to find the executable as specified
  - chop any numbers from the end and try again -> this might not give the correct version, if only `python2` is installed as `python` and there is no python3 installed at all

B. `python3` specific:
  - first try to find the executable as specified
  - fall back to `python` and parse `python --version` if it starts with `Python 3`

I am not even sure if `dependency` needs changes or if this just works as it is now.

**Comment by nirbheek** [comment]
This is fixed now that we have `import('python3').find_python()`.
