### ISSUE TITLE
Meson regen is broken for vs2010 backend

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#418]
I'm currently fixing everything related to the REGEN project in the vs2010 backend, which is broken on several levels.
I already debugged and fixed a bunch of stuff today, but before preparing my Pull Request, I'd like to get some feedback on how meson wants to handle the regeneration of project files:

1. Currently, meson does its own checks if the solution needs to be regenerated (only for vs2010 though). Additionally, it uses the VS system of declaring input & output files and let VS decide, if meson must be called to regenerate the solution.
Is there any reason why meson does its own additional checks and does not just rely on VS?

2. The timestamp of the dependencies are always wrong, because they are written in `Vs2010Backend.generate`, which is too early, because meson dumps its data into `coredata.dat` afterwards, which then has a newer timestamp and causes the REGEN project to always be called. I introduced a new method for each backend `generate_finished()`, which touches the needed timestamp files on vs2010 (does nothing on all other backends) so that they have a newer timestamp. Is this the right approach? We could also dump `coredata` prior to calling `backend.generate()` as the backend does not modify it. This seems to be nicer.

3. Is the dependency on `coredata.dat` even correct? Assuming this file only changes if any `meson.build` file has changed, is it not enough to use these as dependencies?

**Comment by nioncode** [comment]
Also: what should happen if the project is cleaned / rebuilt from scratch (without deleting the build directory)? Should the solution files be regenerated or should this not matter at all?
If they should not be recreated, it would require the user to manually delete the build directory and call meson again if he wants to force the regeneration of the project files. However, it should only be necessary to regenerate the project files if any dependency has changed, which is handled automatically. Therefore, I'd vote for not regenerating the project files on rebuilds / only regenerate if a dependency like `meson.build` has changed.

**Comment by jpakkane** [comment]
The vs2010 backend has not had as much love as the Ninja one. I basically hacked it together mostly by stealing what CMake does. If you find oddities in it, the reason for that may very well be that I had no idea what I was doing. Thank you for looking into this and fixing it, if you find anything weird do not fear in cutting stuff out. The important thing is that the "user visible" behaviour is the same as with Ninja. That is, building "all" rebuilds everything, running "test" runs "all" before running tests, if build definitions are changed then the system regenerates automatically and so on.

1) The regen behaviour is how CMake does it. I don't know the internals of VS well enough to say how these two

2) the latter seems nicer because it does not need new functions

3) coredata.dat also changes when you alter project configuration with `mesonconf`, such as changing build type, compiler flags and so on. When this happens the build needs to be regenerated.

**Comment by nioncode** [comment]
Fixed by #419.
