### ISSUE TITLE
Only create required subdir targets

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#420]
When using a library from a subproject, meson will not only create build targets for the library, but also for all other targets defined in the subproject.

It is not uncommon for a project to define the library and multiple example or test applications, which as a user of the library I don't want to build when I just want to link against the library.
Building all those unnecessary targets can get quite time consuming.

meson should therefore only import the targets of a subproject that are required to fulfill the `declare_dependency` - `dependency` contract.

**Comment by nioncode** [comment]
On further thought I think the current behavior is fine and when actually compiling the project, the user should make sure to only call `ninja prog`, i.e. not using the `all` target.
However, it would be nice to have an additional phony target that would build every target (including dependencies) that is defined by the current project and not by a subproject.

This would keep the current behavior of building everything by default, but give a more granular option for users that don't want to build the entire project tree.

**Comment by jpakkane** [comment]
We need to build all targets so that `ninja test` can run all tests of all subprojects (if you don't run them, you don't know if the code actually works).

The problem of sample code etc is better solved by establishing some core guidelines, namely that projects should check `meson.is_subproject()` and, if it is true, skip building sample code, developer tools and the like.

**Comment by nioncode** [comment]
I agree for subdir targets, but shouldn't subprojects be treated as an external project, which can be assumed to have already been tested by the original developer, so there is no need for me to build and run all test targets?

Also, I am not a friend of the idea that every project should think about whether it might be included as a subdir or subproject and then do different things based on `meson.is_subproject()`. There should be fast defaults that can be overwritten. Something like:
```
if meson.is_subproject():
    only build targets that are used as dependencies in superproject
else:
    build all targets
```

Is this feasable for meson? Otherwise, each project developer must take care of this for each new project.

**Comment by jpakkane** [comment]
The tests must be built and run. You might be running on a compiler/platform/other that the main developer has not tested. You might have extra compiler flags that the developer has not tested. There might be a bug in the build setup and it does not work as a subproject. Running tests is the only way to be sure. That is why they exist. (If you want to only run top level tests, you can do `ninja test-`, the syntax for that might change in the future.)

Just because some target is not used in the superproject does not mean it is not needed to make the whole thing work. Case in point: shared modules (plugins) loaded at runtime.

A project can not be used as a subdir, only subproject. This does mean some work for library developers but that is just a part of providing a good experience, like shipping pkg-config files and the like. In practice it will probably look like something this:

    if not meson.is_subproject()
      subdir('samplecode')
      subdir('devtools')
      subdir(...)
    endif

**Comment by nioncode** [comment]
Accepted :)
