### ISSUE TITLE
data/meson.build:78:0: ERROR: Native dependency 'glib-2.0' not found

### ISSUE THREAD

**Issue by h5yi199qrp** [mesonbuild/meson#4264]
Im trying to build this: https://github.com/GabMus/razerCommander/
```
Build started at 2018-09-25T16:27:17.128629
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/lucas/Downloads/razerCommander-master
Build dir: /home/lucas/Downloads/razerCommander-master/builddir
Build type: native build
Project name: razercommander
Build machine cpu family: x86_64
Build machine cpu: x86_64
Configuring org.gabmus.razercommander.desktop using configuration
Configuring org.gabmus.razercommander.service using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'

data/meson.build:78:0: ERROR: Native dependency 'glib-2.0' not found
```
How can I Fix this?

**Comment by h5yi199qrp** [comment]
my OS: 
Linux lucas-B85M-DS3H 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tp-m** [comment]
Try: `sudo apt-get install libglib2.0-dev`

**Comment by h5yi199qrp** [comment]
Thanks! It worked. 

But that program cannot recognize my hardware, I've a different error when trying to install another app from openrazer, I'll post it in a diferent issue. 

Thanks a lot for your help though.

**Comment by faizanahemad** [comment]
On `yum` package manager based systems using `sudo yum -y install "glib*"` worked

**Comment by giuliohome** [comment]
On my Fedora:  `sudo dnf in glib2-devel` was needed

**Comment by All3xJ** [comment]
> On my Fedora: `sudo dnf in glib2-devel` was needed

same for me. I don't know why this is not in dependencies.

**Comment by eli-schwartz** [comment]
Dependencies of what? This is entirely dependent on the application you're trying to build -- and that application will declare which libraries, such as glib, it depends on, usually in e.g. the README.md file for that application.

It's nothing to do with Meson.

**Comment by giuliohome** [comment]
yeah the idea is that you get an error ("revealed" by meson, not fault of meson) like 

`data/meson.build:78:0: ERROR: Native dependency 'glib-2.0' not found`

and you google it because you don't know what to install (guessing can be more difficult than in this simple case) with your package manager (e.g. dnf in Fedora): I'll write my tip below (*) and you land here.

In the meantime you'll find a guru suggesting you to build with flatpak, but you don't surrender...

(*) so if your error is  'glib-2.0' or 'something', try

```bash
dnf repoquery --provides --archlist=x86_64 '*/glib-2.0'`
```

or `'*/something'`

**Comment by QuLogic** [comment]
> `dnf repoquery --provides --archlist=x86_64 '*/glib-2.0'`

This search is a bit lucky, in that the `glib2-devel` package happens to contain a directory `glib-2.0` that matches. But Meson is looking for a pkgconfig file here (unless it's one of the [dependencies with special handling](https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality)), which may or may not correlate with directories like this. It's also running a query to output the provides of the package (`--provides`) that matches the path, instead of asking what package _provides the file_ (`--whatprovides`).

So for a pkgconfig file, you should try for `*/glib-2.0.pc`. But on Fedora, there are many convenient virtual provides; one useful one here is for pkgconfig: `pkgconfig(glib-2.0)`.

So either:
```
$ dnf repoquery --whatprovides --archlist=x86_64 '*/glib-2.0.pc'
```
or
```
$ dnf repoquery --whatprovides '--archlist=x86_64 pkgconfig(glib-2.0)'
```

**Comment by giuliohome** [comment]
Cool.
```bash
dnf repoquery --archlist=x86_64 --whatprovides '*/glib-2.0.pc'
```
or even better
```bash
dnf repoquery --archlist=x86_64  --whatprovides 'pkgconfig(glib-2.0)'
```
I assume that would work great also for the many other cases I met building projects like gnome-calendar or endeavour (but at the moment I don't recall the list...)  
Thank you

**Comment by airtonix** [comment]
remember: if you're using some kind of python version manager and you've already installed python, remove it and reinstall it again.

```
asdf plugin add python
asdf local python latest

asdf install python

# get error about missing bits. 

sudo dnf install lzma-sdk-devel sqlite-devel bzip2-devel ncurses-devel readline-devel glib-devel

asdf uninstall python
asdf install python
```

**Comment by eli-schwartz** [comment]
What does python have to do with this? This ticket is about system software such as glib, not python and definitely not some broken "version manager". And definitely not about trying to correctly install python using the broken "version manager" while compiling ***python*** against system versions of unrelated software.

Was this comment generated by ChatGPT?

**Comment by memorycancel** [comment]
`centos 7`

`sudo dnf innstall glib2-devel` works
