### ISSUE TITLE
Add add_postconf_script to wiki

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#430]
Add it at least to the reference manual, below the meson object:

**meson object**

- `add_postconf_script` will run the executable given as an argument after all project files have been generated. The script will receive the source directory and build directory as parameters, followed by any additional arguments that are added to the command.

**Comment by jpakkane** [comment]
I have not done that because I realized that the current approach is wrong. Currently you this:

    meson.add_postconf_script('postconf.py', '5', '33')

But Meson calls the script by putting build dir and source dir between `postconf.py` and `5`. This is extremely confusing and counter-intuitive. Other invocations do not change arguments but instead pass these in environment variables that the scripts can use as they choose. We should probably change this to work the same way.

**Comment by nioncode** [comment]
Done. Updated text:

- `add_postconf_script` will run the executable given as an argument after all project files have been generated. This script will have the environment variables `MESON_SOURCE_ROOT` and `MESON_BUILD_ROOT` set. All additional arguments are passed as parameters.

**Comment by jpakkane** [comment]
Wiki updated. Thanks.
