### ISSUE TITLE
Allow `wrap` checkout placed in build directory

### ISSUE THREAD

**Issue by becm** [mesonbuild/meson#4447]
The target directory for `wrap` type subproject downloads/checkouts could (optionally) be placed into `<builddir>/meson-wrap`, to restrict  `meson` write actions to a non-source-tree location.

If the `wrap promote` operation is limited to the build directory, an alternative build could use a different [`subproject` selection](https://mesonbuild.com/Using-wraptool.html#promoting-dependencies) while using the same source tree.
Complete cleanup after partially failed  `meson setup` would be reduced to `<buildir>` removal.
Privilege separation/limit on network checkout/`git` processes to restrict write access to `<builddir>` may become a long term objective.

With introduction of `wrap promote` and the new limitation on [`directory` name](https://github.com/mesonbuild/meson/pull/4428), the subproject location should be source tree layout agnostic enough to now handle this without further limits on `wrap` files.

I'd suggest a project config option (or wrap operation argument).
Per `subproject()` override via argument may be needed for *special occasions* (to be evaluated).
The `wrap promote` copy operation may be a good first step to see benefits to maybe even make this a default: A CMS would then not need to explicitly set to ignore the additional directories created in the top level `subproject` folder.

**Comment by detly** [comment]
This would also be useful on Gitlab's CI (and I assume Github's). For example, if I split my CI pipeline into:

- "pre"build ie. `meson setup build`
- build ie. `meson compile -C build`

...then the `build` directory can be carried over from the first stage to the second stage with everything intact. Otherwise it has to be repopulated for every stage, or every subproject's directory under `subprojects` has to be listed as an artefact to carry over.

**Comment by eli-schwartz** [comment]
>  Privilege separation/limit on network checkout/`git` processes to restrict write access to `<builddir>` may become a long term objective.

What's the objective of "privilege separation" here? What privileges are you separating?

For network requests: once downloaded for the first time, all tarball files get stored in subprojects/packagecache/ which can be preserved as a cache (including in CI) and will be unpacked from there rather than using the network.

>  Complete cleanup after partially failed `meson setup` would be reduced to `<buildir>` removal.

There isn't much point in removing the extracted subprojects, other than cache busting. For this, there is `meson subprojects purge --include-cache`.

...

On the other hand, extracting to the builddir/ seems entirely way too dangerous, because the builddir is only supposed to contain *generated* files and you definitely don't want to overlay the subproject and the subproject's output files in the same location -- that would be a very fancy form of "in-tree builds".

**Comment by eli-schwartz** [comment]
@detly Shouldn't CI runs be doing the second step using the same booted image and same filesystem tree (project source code, builddir/, etc.) as the first step?

**Comment by detly** [comment]
@eli-schwartz Only if both steps are in the same job. It's fairly common for people to split two-stage build systems (meson, premake, cmake) into separate jobs for the generation and compilation steps, so that your reporting/display has that level of granularity.

> all tarball files get stored in subprojects/packagecache/ which can be preserved as a cache (including in CI) and will be unpacked from there rather than using the network

Sure, my only point (and it's relatively minor) was that spelling this out for every CI config is annoying and error prone.

**Comment by eli-schwartz** [comment]
So you boot up two VMs and copy files back and forth between them, solely because you can display them separately that way?

That seems quite... unfortunate, and wasteful. I'm not super familiar with gitlab CI, but you get reporting/display on the granularity of individual steps within one job, if you look at the jobs from https://builds.sr.ht/~sircmpwn

The github API does let you see details per step, but the summary PR/commit status doesn't expose this... `gh run view 1194912694` for example shows:

```
X option-deprecated linux #9184 · 1194912694
Triggered via pull_request about 14 hours ago

JOBS
X Arch Linux in 19m44s (ID 3497807714)
  ✓ Set up job
  ✓ Initialize containers
  ✓ Run actions/checkout@v2
  X Run tests
  ✓ Upload coverage report
  ✓ Post Run actions/checkout@v2
  ✓ Stop containers
  ✓ Complete job
✓ CUDA (on Arch) in 9m23s (ID 3497807771)
✓ Fedora in 23m34s (ID 3497807811)
✓ OpenSUSE in 21m53s (ID 3497807858)
✓ Ubuntu Bionic in 27m56s (ID 3497807891)
✓ Ubuntu Rolling (gcc, g++) in 20m5s (ID 3497807992)
✓ Ubuntu Rolling (--unity=on -Ddefault_library=static, --no-unittests, gcc, g++) in 17m54s (ID 3497808041)
✓ Ubuntu Rolling (-Ddefault_library=both, --no-unittests, gcc, g++) in 20m20s (ID 3497808089)
✓ Ubuntu Rolling (clang, clang++) in 29m14s (ID 3497808139)
✓ Ubuntu Rolling (--unity=on, --no-unittests, clang, clang++) in 22m41s (ID 3497808190)
✓ Ubuntu Rolling (--cross ubuntu-armhf.json --cross linux-mingw-w64-64bit.json, 0, gcc, g++) in 17m58s (ID 3497808244)
✓ Ubuntu Rolling (--cross ubuntu-armhf.json --cross linux-mingw-w64-64bit.json, --unity=on, gcc, g++) in 16m24s (ID 3497808304)
```

**Comment by detly** [comment]
@eli-schwartz Each "job" in Gitlab's CI is run in a clean docker instance (typically, of course it can be configured differently). Here's [CMake as an example](https://gitlab.kitware.com/cmake/cmake/-/pipelines/245370). Each green tick is a "job". The whole thing is a "pipeline". Each job is run on a clean slate (usually).

It's done that way so that you can be sure about dependencies and required state between stages of a build (or deployment). And yes, you can drill down into stdout if you want details for a monolithic job, but if a build config is complex or fiddly enough that generation is a common failure point, it makes sense to separate it from the compilation step and elevate it to a distinct job so that it gets its own tick or cross in the pipeline overview.

At any rate, it's not an issue for us any more, we've mostly sorted out our build configs enough that they don't fail at all.

**Comment by becm** [comment]
@eli-schwartz the current `wrap` approach puts data in the source directory, so it does do *in-tree* builds **now**.
Since `wrap` checkouts **are** generated artifacts for a build setup and should **not** be located in the *actual* project source tree.

The build directory already has predefined specific directories for other `meson` functionality.

References via `meson` project setup should be agnostic to the actual location of the checkout of a `wrap` subproject, it is already possible to override the location via `directory` attribute inside a `wrap` file.

**Comment by eli-schwartz** [comment]
> It's done that way so that you can be sure about dependencies and required state between stages of a build (or deployment).

None of that explains to my mind, the need for running each stage in a clean docker VM. :p And I don't know what dependencies means here, unless you're trying to uninstall software used during configuration, once they are "no longer needed" for the build?

> if a build config is complex or fiddly enough that generation is a common failure point, it makes sense to separate it from the compilation step and elevate it to a distinct job so that it gets its own tick or cross in the pipeline overview.

Yes, that's precisely what sourcehut does on the display frontend, without making it a distinct VM job on the runner backend.

> @eli-schwartz the current `wrap` approach puts data in the source directory, so it does do _in-tree_ builds **now**.
> Since `wrap` checkouts **are** generated artifacts for a build setup they should **not** be located in the _actual_ project source tree.

This is subjective wording which I completely 100% disagree with, so I guess we will have to agree to disagree. You're not convincing me (or, I don't think, the other meson maintainers) that wrap checkouts violate the out-of-tree builds policy, nor that source code (shared across builddir/ configurations) is "generated build artifacts".

> References via `meson` project setup should be agnostic to the actual location of the checkout of a `wrap` subproject, it is already possible to override the location via `directory` attribute inside a `wrap` file.

No, it is not. You cannot override anything, it isn't an "override". It's a "name", and it's not allowed to contain directory components. It just happens to default to the {name}.wrap filename.

You have zero control over the actual location of the checkout of a wrap subproject, it *must* be a single-level deep subdirectory of the source code subprojects directory.

**Comment by becm** [comment]
@eli-schwartz ah, I was not familiar with the added *name-only* restrictions for `subproject` directories.
Up to `meson 0.42` a relative directory was allowed and working as expected.
So I assumed the added checks in later versions were not necessarily a technical limitation.

**Comment by eli-schwartz** [comment]
> With introduction of` wrap promote` and the new limitation on `directory` name, the subproject location should be source tree layout agnostic enough to now handle this without further limits on wrap files.

This is the limitation I'm talking about here. As mentioned there it was never intentionally supported.

**Comment by becm** [comment]
Oh, so it seems I *was* familiar and *forgot* about this change…
The point I tried to make (in 2018) was it is now **easier** to change subproject folder locations.
A location change should no longer impact any *allowed* setting in project or wrap configs.

Wraped subprojects could just be in `<builddir>/meson-wrap/<name>` instead of `<srcdir>/subprojects/<name>`.

**Comment by detly** [comment]
> None of that explains to my mind, the need for running each stage in a clean docker VM.

I thought that was the whole point of Docker, to run parts of the build procedure in a clean environment so you can be sure you've accounted for all requirements.

> And I don't know what dependencies means here, unless you're trying to uninstall software used during configuration, once they are "no longer needed" for the build?

Yes, exactly (except not uninstall, just proceed without in a clean Docker image).

**Comment by eli-schwartz** [comment]
And I thought the whole point of docker was to run the entire process end to end, in one go... While ensuring you've accounted for all dependencies.

(Of course this same problem is solved by any other VM technology, I'm personally partial to systemd-nspawn.)

The part I don't understand is your intention to remove build dependencies that are supposedly only needed for configuring, and not compiling.

I see no point to this, I've never heard of anyone else doing it, and I don't understand why meson should change and remove reatrictions to accommodate this use case if I don't understand the point of the use case (but maybe another meson developer understands the use case better?)

So maybe it would help if you explained the practical benefits of doing this? You have set up a build VM with stuff you've carefully selected that you need in order to build. This includes:
- meson itself
- libfoo-dev style packages for all system dependencies
- any programs you are running in a run_command, run_target, custom_target, etc.
- compilers and other build toolchain support
- other???

Which of these things do you want to remove? You cannot remove
- meson, it's used during build as well as configure (to implement `meson --internal ...` commands and wrapped commands due to env or capture or feed build rules)
- libfoo-dev which included the configure time .pc files, because it also has the build time headers
- compiler toolchain
- run_target or custom_target generator programs

You can remove run_command programs, because those are only run if you edit meson.build and have to rerun configure. Probably not applicable to CI... But we do encourage reducing reliance on run_command stuff! e.g. don't use sed, we have string manipulation methods. Don't use cat, we have fs.read()

And things that aren't used by meson at all. But why do you want to do this? You have carefully selected them because you need them for the overarching build process, and they must be installed at some point...  but no third-party users are going to uninstall them halfway through, they are documented "configure and build" requirements, and I don't understand the motivation for "docker lets you account for all build requirements so I can make sure this is only needed for run_command() during configure, and not during build". What does this prove?

If this is about non meson related stuff, like lint tools or external test suites not invoked via meson, I don't think you need to prove via docker that they don't rely on running meson. But if you want to anyway, then once you've finished with meson it should not matter if you remove stuff that meson cares about... just operate solely on the copied over builddir/ 

Alternatively, add a stage that uninstalls the tools you just installed without booting a new VM. It will be faster anyway.

**Comment by eli-schwartz** [comment]
Whatever the conclusion here, meson *needs* to download by default to the source directory, which survives unscathed across `meson setup --wipe` and which is the *only* correct choice for the average user that doesn't have rather unusual needs. We cannot make this highly common use case delete the downloaded subproject(s) and redownload everything.

Also meson dist and meson subprojects update need to download there for pre-caching and uploading release tarballs. It's a complete non-starter to make either of those rely on a configured builddir.
