### ISSUE TITLE
Regression: gtkdoc-scangob quoting is broken

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/meson#4452]
This is [Debian tracker issue #911697](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911697). The problem in a nutshell is that if you do this:

```meson
compile_args: [ '-DG_LOG_DOMAIN="dbind"' ]
```

Then it will be expanded in the scangobj command to this:

```
'"'"'-DG_LOG_DOMAIN="dbind"'"'"'
```

Git bisection says that the commit that broke this was bb9f6062 by @lantw44.

To test the issue you need to pass `-Denable_docs=true` to the configure step.

**Comment by lantw44** [comment]
This cannot be a regression because the commit isn't backported to 0.48 branch. Ccommit bb9f60624b27041805ca87a48f9a4196afb84ccc is specifically made to fix gtk-doc build for at-spi2-core, so it is expected to see broken gtk-doc build in Debian sid because it uses meson 0.48.1. I think the correct fix for Debian is to cherry-pick commit bb9f60624b27041805ca87a48f9a4196afb84ccc to their meson package.

Note that there are commits on gtk-doc on master branch which broke it after I submitted the fix to meson: https://gitlab.gnome.org/GNOME/gtk-doc/merge_requests/7. I reverted broken commits and it should now work again: https://gitlab.gnome.org/GNOME/gtk-doc/merge_requests/14. Since these broken versions only affect a few commits and they are never released, this recent breakage should not affect Debian.

By the way, since there is no common flag to enable gtk-doc in all projects, such as `--enable-gtk-doc` in autotools, I end up passing `-Dgtk_doc=true -Ddisable_gtkdoc=false -Ddoc=true -Ddocbook=true -Ddocs=true -Ddocumentation=true -Denable-doc=true -Denable-gtk-doc=true -Denable_docs=true -Denable_gtk_doc=true -Dgtk-doc=true -Dwith_docs=true -Dgtk-doc=true` to all projects in order to test gtk-doc build for all GNOME modules.

**Comment by nirbheek** [comment]
> -Dgtk_doc=true -Ddisable_gtkdoc=false -Ddoc=true -Ddocbook=true -Ddocs=true -Ddocumentation=true -Denable-doc=true -Denable-gtk-doc=true -Denable_docs=true -Denable_gtk_doc=true -Dgtk-doc=true -Dwith_docs=true -Dgtk-doc=true

That's something that you should submit patches for in each upstream project. The GNOME goal specifically says that everyone should use `-Dgtk_doc`, preferable as Feature Options and not boolean.

**Comment by jpakkane** [comment]
> I think the correct fix for Debian is to cherry-pick commit bb9f606 to their meson package.

Or, alternatively, put it in 0.48.2?

I need to verify that it fixes the issue first, though.

**Comment by lantw44** [comment]
> That's something that you should submit patches for in each upstream project. The [GNOME goal](https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting) specifically says that everyone should use `-Dgtk_doc`, preferably as Feature Options and not boolean.

I remember I read this on the mailing list, and some projects have moved to `-Dgtk_doc=true` after the name is suggested. However, there are still many projects using different option names, and sometimes projects porting to meson invent their own names. Yes, it really needs work to fix the current situation.

> Or, alternatively, put it in 0.48.2?

Yes, it will be better.

**Comment by jpakkane** [comment]
I received confirmation that the patch fixes the issue on Debian. @nirbheek can you put that in 0.48.2? And further, do we need anything more to release 0.48.2? This issue is the last one remaining on the milestone.

**Comment by nirbheek** [comment]
> @nirbheek can you put that in 0.48.2? And further, do we need anything more to release 0.48.2? This issue is the last one remaining on the milestone.

I've added it to the milestone, and I'll prepare 0.48 tomorrow. Nothing else is on the list afaik, so we should be good to go.

**Comment by jpakkane** [comment]
Excellent. Good work, everyone.

**Comment by nirbheek** [comment]
@jpakkane I've updated the 0.48 branch with all the patches in the 0.48.2 milestone. However, the aforementioned gtkdoc-scanobj patch did not apply cleanly, so I had to edit it a bit. I think we should verify that the branch does indeed fix the issue on Debian before releasing 0.48.2

**Comment by jpakkane** [comment]
Verification request has been sent.

**Comment by jpakkane** [comment]
Released. Packaging also done and will enter Debian as soon as pitti gets around to uploading it.
