### ISSUE TITLE
ninja on Windows: test case 86 broken

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#459]
Test case 86 fails for ninja on Windows.

The test creates a `static_library` and a `shared_library` from the same source file while giving both the same output name `name`.
Because all targets share the same output directory, this will create the following output files:

Static Library:
- build/name.lib

Shared Library:
- build/name.lib (import library)
- build/name.dll (runtime library)

Whichever library gets built last will overwrite the `name.lib` from the other library, which makes the test executable randomly break either for the static or the shared library.

Is there a reason why all targets share the same output directory? The issue should not come up if each target has a unique output directory.
Or should meson just disallow duplicate target names in the same `subdir`?

**Comment by jpakkane** [comment]
The real problem here is that on Windows the ninja backend does not put both .lib and .dll to the rule output list. That should be enough to trigger the dupe detector. We could put them in different directories but that would not work when using --layout=flat. I guess we can say that that one is a "don't do that then" kind of a thing.

**Comment by nioncode** [comment]
So, should we disallow targets with the same name? I think cmake does this as well.

**Comment by jpakkane** [comment]
Originally they were disallowed but it turns out lots of people want to create a library and an executable with the same name (i.e. they have a plain C api in `libfrob.so` and a cli executable `frob`). Similarly people may want to provide both shared and static libraries of the same name in one go.

**Comment by nirbheek** [comment]
My proposal for solving the static vs import library collision is to always use `libfoo.a` for static libraries. I thought about this for quite some time and this was the only thing that made sense to me.

1. `libfoo.lib` sounds nice at first glance but GCC cannot find it via `-lfoo` syntax, so that breaks linking with MinGW.

2. MSVC always needs the filename of the library that you're linking to, so it doesn't matter what we name it as long as it is recognizable and consistent.

3. We need to transform the output of `pkg-config` in static-library MSVC mode from `-Lpath -lfoo` to `/LIBPATH:path libfoo.a` or similar. Hence we need it to always be predictable (we can't do a library search ourselves).

I'm halfway-through implementing this as part of #417.

**Comment by nioncode** [comment]
This will make shipping the static library to customers that expect a *.lib file a bit harder, though.
On the other hand, it will be simple for the deployment script to just rename the static library file to whatever is needed, so I vote for this approach.

**Comment by nirbheek** [comment]
I will note that you can also use your own naming with the `name_prefix` and `name_suffix` arguments to `static_library`.

**Comment by jpakkane** [comment]
Fixed for now by moving the static lib in a different directory.
