### ISSUE TITLE
Passing both --buildtype=debug{,optimized} and --debug results in no debug CFLAGS

### ISSUE THREAD

**Issue by perror** [mesonbuild/meson#4686]
I recently noticed that using the options `--buildtype=debug --debug` with `gcc` on a gnulinke platform was not triggering the usual debug options (aka `-g`). This issue refer to [glib merge request #566](https://gitlab.gnome.org/GNOME/glib/merge_requests/566).

It seems that the default flags for debug are defined as _empty_... I suggest the following patch (but it might be not enough to cover all, I noticed a lot of empty `debug` and `debugoptimized` options which are not filled properly in these templates.

```
diff --git a/mesonbuild/compilers/compilers.py b/mesonbuild/compilers/compilers.py
index 2a5c9763..0aa8080a 100644
--- a/mesonbuild/compilers/compilers.py
+++ b/mesonbuild/compilers/compilers.py
@@ -127,7 +127,7 @@ def is_library(fname):
     return suffix in lib_suffixes
 
 gnulike_buildtype_args = {'plain': [],
-                          'debug': [],
+                          'debug': ['-O0', '-g'],
                           'debugoptimized': [],
                           'release': [],
                           'minsize': [],

```

Let me know if you want me to fill all the defaults which I believe not to be properly filled (obviously, the `debugoptimized` is the second that comes in mind).

**Comment by nirbheek** [comment]
The code there is a bit confusing, but `-g` is added [lower down](https://github.com/mesonbuild/meson/blob/master/mesonbuild/compilers/compilers.py#L333):

```python
clike_debug_args = {False: [],
                    True: ['-g']}
```

What version of meson are you using, what are you testing, what do you expect, and what do you observe?

**Comment by nirbheek** [comment]
Verified, passing `--buildtype=debug` or `debugoptimized` and `--debug` leads to no debug flags being set.

**Comment by copelnug** [comment]
Actually, the problem is simply with `--debug`. It seems the problem is in the coredata.py file where the functions `get_builtin_option_action` and  `get_builtin_option_default` use the third ([2]) field of the built-in options. 

While reading those function, it become apparent that `debug` being `True` by default create a design problem. This has a couple of impacts:
1. The implementation of `get_builtin_option_action` will do the opposite of what the option name suggest (putting `False` at debug).
2. Even if it did what was suggested by the name, it would be redundant.
3. If it did what was suggested by the name, there would be no way to disable that option (except the special case of buildtype).

## Impact
The problem seems to concern three options and make them behave strangely at setup:
1. debug
2. stdsplit
3. errorlogs

## Possible solutions:
1. Reverse the name of those options (no-debug) but it will be ugly in the `meson configure` display.
2. Make those options false by default but it would break backward compatibility and limit all value to a default of false.
3. Change the way boolean options work: Accept `--Option` (True), `--Option=True` and `--Option=False`
