### ISSUE TITLE
custom_target vs2010 and ninja works different

### ISSUE THREAD

**Issue by zpgaal** [mesonbuild/meson#470]
Custom_target generates its output in different places for ninja and vs2010.
The working directory for ninja is the build-dir, the meson was configured for, for vs it is the subfolder. 
I'd prefer the ninja version as it correlates to the default include_directories of targets.

A small sample is attached:
[bug.zip](https://github.com/mesonbuild/meson/files/183981/bug.zip)

```
meson build_vs --backend vs2010
meson build_ninja
```

for ninja the current working dir of the custom target: bug\build_ninja
for vs2010: bug\build_vs\subdir\subdir2

**Edit**
Thus for ninja no include_directory have to be added for the generated headers for a shared_lib in 
subdir/subdir2 as it is added the the include directories automatically.
For vs the private_include_dir should be added, which seems strange.

**Comment by nirbheek** [comment]
I just ran into this myself, and I think there's no way to fix this. One should always add explicit `include_directories : ` for each target and not rely on the directory from which the compiler is invoked which would always be backend-specific. The same problem will exist for XCode as well, I think.

I recommend closing this issue.

**Comment by nirbheek** [comment]
There were a bunch of places where the include directories weren't being added properly, but I've fixed those now. As for implicitly adding the build root to the include path, I don't think we should do that since people coming to Ninja from VS will have the opposite concern: the directory where the build file resides will not be implicitly searched by the compiler when you use Ninja.

All include directories should always be added explicitly in the build files.
