### ISSUE TITLE
Meson doesn't automatically call ldconfig

### ISSUE THREAD

**Issue by superm1** [mesonbuild/meson#4737]
We received an issue in fwupd (https://github.com/hughsie/fwupd/issues/914) that indicated that an application wasn't working properly after installed.

The issue ended up being that libraries were installed into `/usr/local/lib/$(triplet)` which was referred to in a file in  `/etc/ld.so.conf.d` however since `ldconfig` wasn't run `/etc/ld.so.cache` wasn't refreshed and the application was failing to run.

So I wanted to see what thoughts were on setting default behavior of `ninja install` to call `ldconfig`, but let distros such as those using deb or rpm with delayed callbacks turn this behavior off.

**Comment by mjog** [comment]
Kind of doesn't matter since Fedora doesn't even include /usr/local in its ld.so.conf: https://bugzilla.redhat.com/show_bug.cgi?id=144967

This would be a good argument for either meson changing the default prefix to /usr, or Fedora unbreaking its default install.

**Comment by superm1** [comment]
At least Debian and Ubuntu do that aspect correctly.

Of course there is always the option of parsing `ld.so.conf` and adding the prefix to it when found missing like that Fedora case too.

**Comment by jpakkane** [comment]
We are _not_ touching system global configuration files.

**Comment by superm1** [comment]
OK well what about showing a warning during install time?  It's easy enough to grep if $prefix is in `/etc/ld.so.conf.d/*` or `/etc/ld.so.conf`.  If it's not there at least people will know that it's going to be broken without fumbling around google.

And if it is there call `ldconfig` so the cache is refreshed and stuff just works.

**Comment by jpakkane** [comment]
Calling ldconfig after install is something we could do. Are there any downsides to calling it even if there is no need? We might consider calling other such tools too, such as icon cache refreshers. I think there's a bug open about those.

In any case patches welcome.

**Comment by superm1** [comment]
The main downside is that packaging systems will take longer to run `ninja install` for a command that does nothing for them.
Generally they need to run this on the user's machine, not the build machine and they use a so called "delayed trigger" for this action to avoid it happening.

So if calling `ldconfig` automatically is added then it might need to be configurable to allow turning it off to keep packagers happy.  Maybe an easy way to do this is if `DESTDIR` is set to not call any refresher type stuff.

**Comment by pinchartl** [comment]
We've experienced the same issue with libcamera recently, as reported by Raspberry Pi users in https://github.com/raspberrypi/libcamera-apps/pull/58.

I like the suggestion of making the `ldconfig` call dependent on `DESTDIR`, but the `prefix` could also point to a destination in the user's `$HOME`. Maybe the decision  should be based on whether elevated privileges need to be requested to run `meson install` ? We could also possibly check if the destination is covered by one of the `/etc/ld.so.conf` entries.

**Comment by haxworx** [comment]
ldconfig behaves differently on varying platforms. Triggering a call to ldconfig breaks the universe on OpenBSD. Does everything have to be hidden away? If a user is building from source, surely it can't pain them too much to learn to run ldconfig manually on a Linux machine?

**Comment by eli-schwartz** [comment]
This is tracked by #9592 and obviously this was only implemented because no one *expected* that it would break the universe on the BSDs. Sadly, we don't actually have any CI running on any BSD (I am in the process of fixing that! I don't want stuff like this to happen again.)

Also, based on the FreeBSD bug report my understanding is it's fundamentally a BSD bug (what a terrible footgun! adding the "verbose" flag to ldconfig causes it to switch modes and produce different effective results). FreeBSD is fixing that.

Fortunately, completely removing it is unnecessary. We can just implement both behaviors, which means using `-m` on the BSDs.

**Comment by eli-schwartz** [comment]
So far, implementing this has:
- broken the world on *BSD in #9592 
- broken NixOS cross compile in #9707
- showed messy and confusing errors in #9241

It is generally slow on Linux if you don't need it, and we cannot solve that, in order to find out whether we need to run it we need to run it and then grep the output to find out if we should have run it at which point it is too late. And not only that: "you don't need it" is better defined as "using it doesn't do anything, the library still isn't in the cache" -- for cases where you install to some prefix not in the ld.so.conf lookup.

It's a topic of discussion in the NixOS issue, whether this functionality should be removed or made opt-in.

**Comment by haxworx** [comment]
I think it's a nice idea but probably a bit too much. My suggestion would be to remove it, it's another hidden layer, that, in my opinion isn't necessary.
