### ISSUE TITLE
Missing `libselinux` dependency on Arch

### ISSUE THREAD

**Issue by I60R** [mesonbuild/meson#4798]
swaywm/wlroots#1477 provides more context

**Comment by xclaesse** [comment]
The problem is `restore_selinux_contexts()` in minstall.py does `subprocess.check_call(['selinuxenabled'])` but `selinuxenabled` is not installed. Meson catch the FileNotFoundError exception but for some reason your python 3.7 seems to raise NotADirectoryError that we don't catch.

It is weird that python 3.7 changed that exception, but I guess we should catch it too.
