### ISSUE TITLE
Support building both shared and static libraries at the same time

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#484]
The `default_library` option should also accept `both` as a valid option which would cause all `library()` invocations to emit build commands to build both static and shared libraries in the same build.

Autotools already does this when you pass `--enable-shared --enable-static` to `configure`.

**Comment by jpakkane** [comment]
What is the use case for this? Why would you want both?

AFAICR Autotools does this by compiling everything with -fpic and using the obj files directly. We don't do that so our compile time would double. It would also cause some other wacky bits (what is the return value of this and how would you use only one of them to link to a target) but those are probably fixable with some effort.

**Comment by nirbheek** [comment]
If you're building for yourself (perhaps because you're compiling a library for use with an executable), you want either static or shared. However, if you're building for binary distribution either because you're a Linux distribution or you're distributing binaries as a software project, you want to distribute both static and shared libraries because the end-users might want either of those two.

For instance, Linux distros ship the static libraries with the devel files, and in GStreamer, Cerbero creates tarballs with both shared and static libraries since people often tell us that they want to link to some gstreamer and its dependencies statically and others dynamically.  Especially people writing applications for embedded.

In fact one use-case that libtool makes impossible that we have to work-around manually in Cerbero by writing our own linker commands is to link to some libraries statically and others dynamically. There is no reason why that should be as hard as it is. It would be quite nice if Meson supported it out of the box. :)

Why can't we also build everything with `-fPIC` and just `ar` the object files to create the static library?

**Comment by nioncode** [comment]
Can't you just use two build trees?

**Comment by nirbheek** [comment]
Of course we could do that, but then you re-generate all the arch-independent stuff such as gtk-doc files, data files, headers, pkg-config files, and so on, and then install them again too. Seems awfully redundant especially since it's technically possible to generate shared and static libraries from the same object files.

Speaking of which, pkg-config files have `Requires.Private` which is a list of dependency libraries to link to when you're linking statically to this library statically. The whole infrastructure is really setup assuming that you'll be providing both static and shared libraries in one go. :)

**Comment by jpakkane** [comment]
> people often tell us that they want to link to some gstreamer and its dependencies statically and others dynamically.

The Grand Vision is that this should be doable with per project options. By default build shared, toggle one switch to get static and if you want mixed then something like:

    meson . builddir -Dboblib:libtype=static

> Why can't we also build everything with -fPIC and just ar the object files to create the static library?

Because `-fPIC` has a runtime performance penalty. You can create a static library out of a shared one with `mylib.extract_all_objects()` if you want to.

> Speaking of which, pkg-config files have Requires.Private which is a list of dependency libraries to link to when you're linking statically to this library statically. The whole infrastructure is really setup assuming that you'll be providing both static and shared libraries in one go. :)

Except that it does not work if you want to link only some parts statically. I tested this and even if you pass `--static` to pkg-config, it outputs flags that link the shared version. In order to get static linking you need to pass `--static` to gcc, which links _everything_ statically. (I did not spend a ton of time on this, it might be possible with some permutation of flags.)

The bigger issue is that only dependencies built with Autotools and libtool ship both shared and static libraries. Libraries built with CMake (for example [this one](http://packages.ubuntu.com/wily/libcolumbus1-dev) do not. If you have even a single dep of that kind you can't use pkg-config for it.

Debian's documentation on this does explain that static libraries should go in `-dev` packages but never do they mention _why_ you would want to use those. In fact most of the docs flat out say that you should not use static versions ever, which makes sense.

**Comment by nirbheek** [comment]
> > people often tell us that they want to link to some gstreamer and its dependencies statically and others dynamically.

> The Grand Vision is that this should be doable with per project options. By default build shared, toggle one switch to get static and if you want mixed then something like:
> `meson . builddir -Dboblib:libtype=static`

Makes sense, but the use-case I'm thinking about here are consumers of our binaries who are using them in their own applications with their own (often horrific) build systems. This is more common than you'd think (or hope)! For them, we need to ship both static and shared libraries.

> > Why can't we also build everything with -fPIC and just ar the object files to create the static library?

> Because -fPIC has a runtime performance penalty. You can create a static library out of a shared one with mylib.extract_all_objects() if you want to.

I'm not sure if the function lookup penalty is a major factor these days. Most code that would be affected by that tries to inline the functions. If people really care, they have the option to do a static-only build. I think mentioning this caveat about potential performance problems in the documentation would suffice.

> > Speaking of which, pkg-config files have Requires.Private which is a list of dependency libraries to link to when you're linking statically to this library statically. The whole infrastructure is really setup assuming that you'll be providing both static and shared libraries in one go. :)

> Except that it does not work if you want to link only some parts statically. I tested this and even if you pass --static to pkg-config, it outputs flags that link the shared version. In order to get static linking you need to pass --static to gcc, which links everything statically. (I did not spend a ton of time on this, it might be possible with some permutation of flags.)

`-lfoo` in the pkg-config output can refer to either static or shared libraries. pkg-config leaves it up to the compiler to resolve it to a path. The `--static` option in pkg-config is meant to only list the extra dependencies you need for static linking. It is upto you to tell the linker that you want to link to these libraries statically since the mechanism for doing that is linker-dependent.

I experimented with this a lot a year ago because we needed it for the [OpenWebRTC project](https://github.com/EricssonResearch/openwebrtc/). If you have both shared and static libraries available, `gcc -lfoo` will always prefer the shared library unless you specify something like `-Wl,--whole-archive -lfoo -lbar -Wl,--no-whole-archive -lbaz`. Then `foo` and `bar` will be linked statically into whatever you create (library or executable) IIRC and `baz` will be linked dynamically.  We use this in Cerbero/GStreamer and Cerbero/OpenWebRTC to build such "fat" shared libraries.

`libtool` is completely useless because it will *always* use the shared library if it is available while generating a shared library. The only way time it will prefer static libraries is if you pass `-static-libtool-libs` while linking an executable. It was really frustrating to have to bypass `libtool` wherever we wanted to do this.

> The bigger issue is that only dependencies built with Autotools and libtool ship both shared and static libraries. Libraries built with CMake (for example this one do not. If you have even a single dep of that kind you can't use pkg-config for it.

This is not entirely true. There are projects that use `make` + shell scripts as a build system that can (and do) build both shared and static libraries. Example: zlib, icu, openssl, libvpx.

> Debian's documentation on this does explain that static libraries should go in -dev packages but never do they mention why you would want to use those. In fact most of the docs flat out say that you should not use static versions ever, which makes sense.

AIUI, that documentation and advice has been carried over from decades ago when the entire ecosystem was migrating from static libraries being the norm to shared libraries being the better idea. libtool enshrined that as well and none of these have updated themselves to the current world where people want to ship things other than Linux distros.

Today, however, people want to ship on Windows, embedded Linux, iOS/Android, and so on. The benefits of shared libraries are clear and people use them wherever they can. However, most such applications out find it easier to use a mixture of shared and static libraries. For instance, people build a single shared libmultimedia.so with all the dependencies and gstreamer plugins linked statically inside it, and then link to it dynamically. Others build separate libmultimedia.so and libmultimedia-codecs.so, and so on.

**Comment by jpakkane** [comment]
> I'm not sure if the function lookup penalty is a major factor these days. 

The penalty comes from other places, too. But regardless we need to support two different setups, static libraries without fpic and those with fpic. Both are used in the wild.

> For instance, people build a single shared libmultimedia.so with all the dependencies and gstreamer plugins linked statically inside it, and then link to it dynamically.

This is interesting because it actually is a use case rather than just talking about shared/static in the abstract. So the real requirement is something like this: "for project X and some portion of its subprojects, build a single .so that merges all those libraries into one". In Gst's case this might also mean compiling the libraries with different flags (AFAICR you need a define to statically link gst plugins so they all get unique names or something).

This raises obvious follow up questions.

- Is there a technical reason for this or is it merely convenience/habit/workflow thing
- is it actually, really needed or would these people throw up a massive revolt if they had to ship multiple dlls rather than one
- is libmultimedia.so just an aggregation or will it contain also some custom code (i.e. their own API functions for controlling it)

**Comment by bluca** [comment]
Hi, as a distro maintainer and user :+1: for allowing to optionally build both static and shared libraries. Not having this option means I'll have to rebuild twice all the libraries I maintain in Debian that switch to Meson, which will be much slower than any performance penalty building both in one go might present I'm afraid.

Thanks!

**Comment by nirbheek** [comment]
Since April 2016, lots of things have changed:

1. We always build objects with -fPIC even when they're for static libraries.
2. gstreamer no longer needs special handling for static plugins

The basic implementation would now be rather simple: `extract_all_objects()` and link it again. There are still some questions though, such as what would be the return value of `library()` in this case, etc.

**Comment by xclaesse** [comment]
There is also the question about shared_module() that glib-networking uses. I'm working on making static build of gio modules, but shared_module() only build shared library. Do we want both_module() too ?

**Comment by nirbheek** [comment]
I want @jpakkane to comment on this before we spend too much time on this. He has in the past [been skeptical](https://github.com/mesonbuild/meson/issues/484#issuecomment-204695375) about the usefulness of this (which I disagreed with, and still do).

**Comment by kaimast** [comment]
I have a similar issue. 

I want to build a python bindings and c++ bindings for my project and both are treated as shared libraries by meson. Thus, they cannot have the same name.
However, I would like to avoid having rename my Python or C++ bindings because of this. Why is there this limitation in the first place?

**Comment by mqudsi** [comment]
Thanks for this.
