### ISSUE TITLE
Support \ (backslash) in compiler arguments added by build files

### ISSUE THREAD

**Issue by nirbheek** [mesonbuild/meson#489]
Since Meson has the requirement that compiler arguments passed manually via build files cannot contain `\`, this means it is impossible to pass `cargs` to functions inside build paths that contain paths on Windows because Python by default (`os.path`) uses `\\` as the path separator.

However, MSVC (and most Windows utilities) accept `/` as the path separator, so things like `meson.current_source_dir()` and so on should return paths separated by `/` instead of `\\` so that those can be passed as `cargs`.

If there is agreement on this, I'll submit patches that use `pathlib.PurePath.as_posix()` to convert Windows paths to POSIX paths before returning them.

**Comment by jpakkane** [comment]
It turns out that it is possible to write Ninja files with a backslash in them that work reliably (which is not what the comment in the code says, oops). The proper fix would be to fix the quoting so we can stop caring about this. There are a gazillion ways backslash paths can enter the system and trying to fix them all leads to whack-a-mole.

**Comment by nirbheek** [comment]
Are you looking into this already or should I try my hand at it? :)

**Comment by nirbheek** [comment]
So it looks like `\\` is a valid character in Ninja paths as long as the path doesn't **end** in a `\\` since that would cause it to become `\\"` which breaks. Do we ever create a path that ends with `\\`? We might need to add guards around that or users will see errors when they run Ninja.
