### ISSUE TITLE
Unable to use custom_command for tools that only output to stdout

### ISSUE THREAD

**Issue by ssssam** [mesonbuild/meson#512]
Hi!
I had a look at writing Meson build rules for GNU Awk, just as a way of trying Meson on a random oldskool project.

The first hurdle I've hit is that I need to call `sed` as part of the build process, but `sed` will only output to stdout. There's no 'redirect output to a file' option. I think that means I can't use 'generate' or 'custom_target' for this, which is sad. I could work around it by adding a shell script to the repo that wraps `sed`, but that also seems sad.

The relevant part of gawk's Makefile.am looks like this:

```
awkgram.c: awkgram.y
	$(YACC) $(AM_YFLAGS) $(YFLAGS) $<
	sed 's/parse error/syntax error/g' < y.tab.c | awk -f $(srcdir)/bisonfix.awk awkgram > $*.c && rm y.tab.c
```

So I can do something like this...

```
awkgram_messages_fix = custom_target('awkgram.y messages fix',
    input: 'awkgram.c',
    output: 'awkgram.messages-fixed.c',
    command: ['sed', 's/parser error/syntax error/g', 'awkgram.c'])
```

...only it does nothing, because the output goes to stdout, and is then ignored. Do you have any thoughts on how custom_target() or generate() could be extended to capture the process' stdout and write that to a file?

**Comment by jpakkane** [comment]
The recommended way to do this is to write the functionality in a small Python script and ditch Awk & co. This has several advantages:

- functionality is separated from its usage
- the script is runnable on its own, which makes it testable and debuggable
- on Windows shell pipelines do not work (requiring people to install cygwin/something else is _not_ an option)
- performance is usually better, sometimes by a lot

Since Meson is (currently) implemented in Python 3, it is always guaranteed to be available when compiling. This makes it possible to compile the code on non-unix platforms, which have traditionally been a huge pain in the rear for Make/Autotools based toolchains.

**Comment by ssssam** [comment]
Well, GNU Awk itself is unlikely to ditch Awk :-)

Writing a Python script is fine for me. In this case the script will be several lines compared to 1 line of `sed`, but should be clearer :-)

**Comment by QuLogic** [comment]
As an example of where this might be useful, both `glib-mkenums` and `glib-genmarshal` output to stdout and one would normally want the output in some file.

**Comment by nirbheek** [comment]
There are plans to add support for both those to the `gnome` module since the usage is very common.

**Comment by jpakkane** [comment]
There is also [this Bugzilla entry](https://bugzilla.gnome.org/show_bug.cgi?id=770175) to add `-o` args to those two binaries in glib.

**Comment by fickludd** [comment]
In case anyone else stumbles in here, there is nowadays a `capture` option in `custom_target` which solves exactly this problem. https://mesonbuild.com/Reference-manual.html#custom_target
