### ISSUE TITLE
[RFE] target to get archive

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#53]
I want to have something like `make dist` in meson which will make tarball with sources

**Comment by jpakkane** [comment]
This is the way Meson does releases:

https://github.com/jpakkane/meson/blob/master/create_release.sh

It is a lot simpler than with autotools, because in Meson (and CMake and almost anything else) a tarball is exactly the same as a git checkout. It's just put in a named directory. Specifying the same in Meson would probably take about the same amount of code (but would require a fair abount of code in Meson itself).

**Comment by ignatenkobrain** [comment]
but in cases when we're not using git?

**Comment by ignatenkobrain** [comment]
don't see any problems with using sh script or something like this, so closing.

**Comment by aruiz** [comment]
The fact that meson treats a dist as a git checkout is quite a problem in certain cases.

For example, one of the selling points of Vala is that you can dist the generated C files, imposing no requirements on a specific vala compiler for distributions.

**Comment by ignatenkobrain** [comment]
@aruiz makes sense

**Comment by jpakkane** [comment]
Could you elaborate on why you'd want to distribute the intermediary files. One would imagine that distributions specifically want the original Vala sources so they can compile them with their own Vala compiler with exactly the compiler flags they require. Going a bit further, it could even be argued that the generated C files are equivalent to object files and not "the original source" which means their use should be prohibited (in an ultra-extreme interpretation they should even be removed from foobar-1.0.orig.tar.gz:s just like .o files or the like).

**Comment by aruiz** [comment]
The point is not to enforce any specific vala compiler. Until vala reaches 1.0, different vala compilers might produce different C code which might impact API/ABI at times, by distributing the C code you can generally ensure that you're distributing the same resulting API/ABI code. The other thing is thta a C compiler is generally available whereas the specific vala compiler that one uses might not be. Vala tarballs distribute both .c/.h and .vala files.

**Comment by jpakkane** [comment]
Let me write out some technical background on why this is a bit problematic. One of the core design choices of Meson was that for any source tree you must be able to create an arbitrary amount of build trees. Typical examples include having a normal tree with debug enabled and optimization disabled, then one with optimizations for performance evaluation, one build with asan, one with tsan, one with Clang instead of GCC, one for testing cross compilation and so on.

All these build configuration *must* be usable at the same time and *must not* ever interfere with each other. The obvious outcome of this is that all generated state, including sources, *must* be stored in the build directory.

Unfortunately this is fundamentally incompatible with wanting to ship generated intermediary files. It completely breaks the source/build separation. There does not seem to be a simple solution that would permit both of these.

One possible (but not very clean) solution would be to create a packer script that would take a git checkout, configure and build it, copy the sources to src dir and then alter the meson.build files to use the c files rather than vala. I have been considering for a while to create a helper script to manipulate Meson files programmatically. The idea is that we would implement stuff like "add file X to target Y" once and then all IDEs could use those rather than coding text manipulation from scratch.

The obvious downside of this is that once this is done you can only compile the C version. Which is probably not sufficient for all use cases.

**Comment by hughsie** [comment]
Another case to consider is "make distcheck" which is a really good way for maintainers to check "have I included everything in the tarball to make his build without a git tree". This is super useful if you you only want to require some arcane build dependency for people compiling with git, and then distros building from tarballs can just use the generated files.

**Comment by hughsie** [comment]
A common one is https://github.com/hughsie/colord/blob/master/man/Makefile.am -- i.e. we don't require the package-using user to have docbook2man installed, but use it if it's available

**Comment by jpakkane** [comment]
Out of curiosity, what percentage of your developer base does this affect? That is, what percentage

1) are compiling from source
2) are on a platform without any kind of package manager (even Homebrew or the like)
3) want manpages

Also, what platforms are these people running on?

Thanks,

**Comment by hughsie** [comment]
So for the docbook2man issue it's really not a big deal; we just require people building from tarball to have the same deps as people building from git. If that's the case then it's probably important to document and tell people converting to meson *how* to generate a tarball when they are porting their project. Given that 99% of my not-in-git-but-disted files are things like configure, Makefile.in and Makefile I think it's not a huge problem for me. For vala however, a solution needs to be found.

**Comment by jpakkane** [comment]
If you are coming to Guadec we can have a chat there.

**Comment by aruiz** [comment]
I will, I have to say I'm kind of sympathetic to the idea of ditching the dist step and basically relying on git checkout. But there are situations where it really simplifies the build environment setup for the people who just want to "wget && make && make install".

Let's have a chat at GUADEC.

**Comment by jpakkane** [comment]
At the guadec hallway track we came to the conclusion that it is ok to require a Vala compiler when building with Meson rather than shipping with generated C source.

**Comment by arteymix** [comment]
It would be great to have a dist command (and distcheck) that archive the code along with the target build system setup so that we can ship the sources without Meson as a dependency.

If we ever target a configure/Makefile build, it could help a big deal the end-user.
