### ISSUE TITLE
compiler.has_function() partially broken on Windows

### ISSUE THREAD

**Issue by nioncode** [mesonbuild/meson#530]
As mentioned in #490, on my Windows 7 machine with VS2010 + VS2015, compiler.has_function() is broken, test case 43 fails.

I am debugging this now to see if I can find anything.

**Comment by nioncode** [comment]
Setting the VS2010 tools at the beginning of the PATH works.
So everything works fine when the 2010 tools are used, but with vs2015 things break.

**Comment by nirbheek** [comment]
How are you testing this? Visual Studio installs `cmd.exe` shortcuts that run the appropriate `vcvarsall.bat` file to set the environment. Are you using those?

**Comment by nioncode** [comment]
Yes, I am using the `Developer Command Prompt for VS2015`.

When I manually call `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x64` it works fine. However, when I use `x86` (which seems to be the default the command prompt uses), it breaks again with:
> error LNK2001: unresolved external symbol _printf

**Comment by nirbheek** [comment]
I can also reproduce this. How strange. I was always testing with the 64-bit one (MSVC installs shortcuts for both).

**Comment by nirbheek** [comment]
I see the issue. `printf` is now an inline function in the header, so it's not provided by the standard library at all. They probably messed up and made the change only in the 32-bit toolchain. So `has_function` is actually behaving as expected.

Perhaps we should find a way to detect inline implementations of C library functions in the headers since it turns out this is quite common with MSVC.

```
The printf and scanf functions are now defined inline: In order to support the two wide string format and conversion specifier modes, the definitions of all of the printf and scanf functions have been moved inline into <stdio.h>, <conio.h>, and other CRT headers. This is a breaking change for any programs that declared these functions locally without including the appropriate CRT headers. The “fix” is to include the appropriate CRT headers.
```

https://blogs.msdn.microsoft.com/vcblog/2014/06/18/c-runtime-crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1/

**Comment by nioncode** [comment]
Do you have any idea how to implement this?

**Comment by nirbheek** [comment]
I have an idea; trying to implement it now.

**Comment by nirbheek** [comment]
There's no way to attach patches, so I've filed a pull request. GitHub has such a weird (broken) workflow.

**Comment by nioncode** [comment]
#537 broke it again.
