### ISSUE TITLE
Introspection API: missing info about `install_subdir`

### ISSUE THREAD

**Issue by TheQwertiest** [mesonbuild/meson#5556]
`meson-info/intro-installed.json` does not contain any information about files/directories installed via `install_subdir`.

PS: `meson-logs/install-log.txt` contains such info, so it probably could be used as a reference.

**Comment by mensinda** [comment]
I am not sure how we should handle this, because the complete file list is not known for subdirs at configure time. It is only when `meson install` is executed that the directories are scanned.

The install data known at configure time only stores the source and destination directory. Adding this to the introspection output would be trivial, however, this would not contain the content of the directory.

Do you need the full install information, or would the source and destination directory be enough?

**Comment by TheQwertiest** [comment]
> would the source and destination directory be enough?

Folder itself would be enough for my case, and, IMO, it would be the correct behaviour as well: `install_subdir` means "install everything that is there and I don't care what it is".

**Comment by mensinda** [comment]
Should be fixed with #5577.

**Comment by TheQwertiest** [comment]
Thanks! I will try to test it later today (or tomorrow).
