### ISSUE TITLE
Allow partial install

### ISSUE THREAD

**Issue by Jehan** [mesonbuild/meson#5632]
It seems that currently meson does not allow partial installation when relevant. Typically our usage case is GIMP (a contributor proposes us a port of our build system). GIMP is not a single binary: it relies on several internal libraries (libgimp, libgimpbase, libgimpwidgets, etc. 9 of them, used both by the core GIMP executable and by plug-ins), a lot of data files, and we have a lot of plug-ins too.

2 use cases I think of where no partial install is very bad:

1) Say we make a one-liner change in one of the `libgimp*` ⇒ bam, full rebuild of the whole repository is triggered (since nearly all binaries in GIMP use them). If there is API/ABI change, you want this. If you do a release build, you want this too of course (we'd do the build from scratch anyway, of course). But for development, if no API/ABI break happens, we just want to build/install the library and restart GIMP. With our current build system, this is quick with a `cd libgimp && make && make install`. Like less than one second and done we can already test. With meson, we can rebuild only the library which is a ninja target, but apparently a `ninja install` cannot work on selected targets, and since the install triggers also the full build: we are stuck at triggering full builds at every test fix. This is a lot of wasted development time.

2) When we fix plug-ins, they are runtime-loaded, so we don't even need to restart GIMP after a fix. What we were doing with our current build system is: leave GIMP opened and just rebuild/reinstall the faulty plug-in after a fix (since plug-ins are very small binary, this is basically instant). Unfortunately while we can rebuild just the plug-in target, the install is full (~10 seconds) with meson, and it reinstalls everything, which is not wanted (yeah the GIMP process is in memory even if the binary is replaced, still it's definitely uncool).

So what if we could like: `ninja install <target>` same as we can already `ninja <target>`?
If the target is not an independent installable one (like a `.o` file), of course nothing happens. But if it is, it would install this target only (and not trigger any other rebuild that the one on this target if needed).

**Comment by xclaesse** [comment]
Note that `ninja install` is just a dummy ninja rule that invokes `meson install`. If you run instead `meson install --only-changed --no-rebuild` it could be fast enough?

Another possibility is to run GIMP uninstalled, libraries in the builddir have all kind of rpath set to be usable from there without requiring installation.

**Comment by Jehan** [comment]
> If you run instead meson install --only-changed --no-rebuild it could be fast enough?

I just tried, it is still very slow. 😢

> Another possibility is to run GIMP uninstalled, libraries in the builddir have all kind of rpath set to be usable from there without requiring installation.

We can do this. I actually run the main binary like this (it does not need to be installed), but not for libraries/data/plug-ins. Now we could add some environment variables or whatnot to use repo-build (not installed) files instead of installed ones, but this would be a complex workaround (there are a lot of data; and plug-ins are in many subdirs and we have several dozens in the core app; libs also are each in their own dir, and so on) for basically something which should be dealt by the build system.

Not even mentioning that in meson, it would be a generic features which would work for every project out there, whereas if we implement this with GIMP environment variables (or similar techniques), it is GIMP only.

Note that I am not asking that it is implemented just now (though if it could, would be awesome!), but maybe at some point, if it could be in your roadmap for some day, would be good too. 🙂

In any case, if we accept the meson patch, we will keep both build system for a while, I think, as a test period. But I could see this issue as kind of a deal break on the long run (I do partial install like nearly every single day, and when I do this, it may be 20 times in a row since I don't necessarily get the right fix immediately; in the end, this may be more important that speed of full build which we don't need to do often). :-/

**Comment by jpakkane** [comment]
The way Meson is set up is that `ninja <command>` always does the most common operation in a reliable way. Then there is a corresponding `meson <command>` command that you can run manually that can take extra arguments, has explicit options to do things that are unsafe but potentially faster and so on.

In this particular case we could add something like `meson install --only-target foobar` or something similar. However

> I just tried, it is still very slow.

The best solution here is if we could make this operation fast. Obviously for humongous projects it can't be fast but the operation should be almost instantaneous for up to 1000 files or so. All it does is some file operations, and Python is not _that_ slow. Can you try it again and report where it seems to be spending its time?

An alternative (and slightly crazy) option would be to have something like `meson install --symlink` which does not actually install the files, only creates symlinks that point back to the files in the build dir. There is obvious breakage potential (which is why it would require an explicit command line argument) but it _should_ work.

**Comment by xclaesse** [comment]
Note that if you use `install_subdir()` with large files, it could be faster with Meson >= 0.49, because of https://github.com/mesonbuild/meson/pull/4537. Which version are you using?

About using uninstalled files, fwiw GStreamer project has a script setuping the env for that:
https://gitlab.freedesktop.org/gstreamer/gst-build/blob/master/gst-uninstalled.py

I personally don't like having to install stuff into a prefix while developping, but I agree it's not always easy to achieve.

**Comment by Jehan** [comment]
> The way Meson is set up is that ninja <command> always does the most common operation in a reliable way. Then there is a corresponding meson <command> command that you can run manually that can take extra arguments, has explicit options to do things that are unsafe but potentially faster and so on.

That's fair. Good to know.

> In this particular case we could add something like meson install --only-target foobar or something similar.

This would be perfect (even better if there could also be a short one-letter option like `meson install -o foobar `). :-D

> Can you try it again and report where it seems to be spending its time?

So it mostly works (i.e. it apparently does not reinstall most files), but I notice that it still installs some data files and all the `.mo` (built localization files) even though the po files are untouched. I asked the contributors to look at why it does this on the merge request.

Also I notice it gets stuck for maybe 3 or 4 seconds at this:

```
[…]
Preserving existing file /home/jehan/.local/share/crossroad/roads/native/gimp-meson/lib64/pkgconfig/gimpui-3.0.pc
Failed to restore SELinux context of installed files...
Standard output:

Standard error:
restorecon: SELinux: Could not get canonical path for  restorecon: No such file or directory.

Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=gimp30'
```

So apparently it tries to regenerate all the mo files (not just install them), even despite the `--only-changed --no-rebuild` options.

Also the SELinux/restorecon error just before is weird (though it does not look to get stuck at this line). Not sure if it is linked to the gettext files as well or something else (which somehow ties this report to my other one #5631 because without install verbose mode telling what line it is running before doing something, it feels like guess-work to debug meson files!).

Anyway all in all, it takes about 10 seconds (timed with `time` command) to run this install command, which is about 50 times too long. :P

> An alternative (and slightly crazy) option would be to have something like meson install --symlink which does not actually install the files, only creates symlinks that point back to the files in the build dir.

Never thought of this. Obviously only a dev option, but would be quite an interesting one as this would just make the `meson install` step useless (hence save a lot of time). You run it once, then you just rebuild files. However fast a `meson install` would be, this would always be faster (no command to type at all). Why not!

>  it could be faster with Meson >= 0.49, because of #4537. Which version are you using?

Meson 0.50.0.

> I personally don't like having to install stuff into a prefix while developping, but I agree it's not always easy to achieve.

As we are discussing on our small tricks 😉…
I have my own tools to create development environment at will. It creates a prefix for me (I don't even need to know or care about the actual path) as well as all environment variables and tweak all the tools as necessary. That allows me to install any application in its own small prefix in a whim, but also get rid of the whole thing in a single command. Also that allows me to have several built branches of a same project (I have like 3 or 4 branches of GIMP built on various prefixes) and to develop lower level libraries like glib without breaking other apps or even the desktop which keep using the stable versions.

So of course, if I were to install stuff in some unique prefix set up for my whole system, where it can break things and stuff, I'd agree. But the way I do it, I have no problem installing software in prefixes. 😛 I think it is even better because you test the application as it is really supposed to be and you can check exactly what gets installed and where. Here for the small off-topic. :-)

**Comment by xclaesse** [comment]
About mo generation, many gettext project have an option to disable translation: https://gitlab.gnome.org/GNOME/glib/blob/master/meson_options.txt#L87

It is especially useful when doing build on Windows/msvc where it's hard to have gettext dependency, but you could use that to save time on dev builds too. The reason it rebuild mo files is because meson doesn't know the exact dependency list for them, so just assume they always have to be rebuilt. Same thing with gtkdoc.

**Comment by Jehan** [comment]
> About mo generation, many gettext project have an option to disable translation:

Well I definitely don't want to disable translation. This is a core feature of GIMP (which is translated in 80 languages so far!), we need it, both for releases as for development (we regularly have to debug translation-related bugs). Making an option for this seems very counter-productive.

> The reason it rebuild mo files is because meson doesn't know the exact dependency list for them, so just assume they always have to be rebuilt. Same thing with gtkdoc.

Hmmm… ok. We have the files [POTFILES.in](https://www.gnu.org/software/gettext/manual/html_node/po_002fPOTFILES_002ein.html) which list exactly the source files which contain translated strings. Can't meson use this standard gettext information? All paths in this file are to be considered the dependency list, hence no need to rebuild anything when neither the source, nor the translations (.po) files are changed.

**Comment by xclaesse** [comment]
I guess meson could learn how to parse the POTFILES, but currently it doesn't do that. Would be nice optimization.

**Comment by eli-schwartz** [comment]
This is more generally described by #7007

**Comment by eli-schwartz** [comment]
#7007 is getting solved by #9110 

Looking back at the locale files discussion... POTFILES.in seems pretty offtopic here, because that's used for generating .pot files, not building .mo files... and regenerating the .pot sources is and shall only be done manually by the developer checking in new translations via `ninja foo-pot`.

But that being said, the actual .mo files are now (since 487d45c1e5bfff0fbdb4747841db6a0b5b124af9) built by ninja compile rules and directly installed by `meson install` builtin file copying and are NOT handled by running a custom install script `/usr/bin/meson --internal gettext`. This means, among other things, that ninja is now in charge, as it should have been from the very beginning, for deciding when they are out of date and need to be rebuilt.

**Comment by eli-schwartz** [comment]
Since I think between these two solutions and `--only-changed`, this issue is solved?

**Comment by Jehan** [comment]
Thanks for these everyone! Not tested any of these changes yet, but I guess I will soon and it will be hopefully good (otherwise I can open new reports and bother you again! 😛).
