### ISSUE TITLE
Support llvm-cov

### ISSUE THREAD

**Issue by TheAifam5** [mesonbuild/meson#5652]
Hey!
Based on that line in the tests: https://github.com/mesonbuild/meson/blob/cd12a6fc391782fc9101f71e7bef56590358f06c/run_unittests.py#L4978
I think meson does not support the `llvm-cov` yet. I couldn't find similar issue to this, so looks like this feature is forgotten.

By any chance, is that still possible to implement?

Regards,
TheAifam5

**Comment by jfinkhaeuser** [comment]
Just came across the same. Generally, the `b_coverage` flag is not handled properly with clang:

- Adding `--coverage` is only useful at link-time, not compile-time.
- Some guides suggest adding `-fprofile-arcs` and `-ftest-coverage` is necessary at compile-time
- Then use `llvm-cov` instead of gcovr

**Comment by eli-schwartz** [comment]
This got fixed in #7196
