### ISSUE TITLE
import('cmake') fails with ERROR:  Module "cmake" does not exist

### ISSUE THREAD

**Issue by smohantty** [mesonbuild/meson#5684]
Meson Version : 0.49

**Meson Build File Snippet:**

    cmake_bin = find_program('cmake', required: false)

    if cmake_bin.found()
                  cmake = import('cmake')
                  cmake.write_basic_package_version_file(
                                      version: meson.project_version(),
                                       name: 'rlottie',
                                      )

**Error Log:**

Found pkg-config: /bin/pkg-config (0.28)
Found CMake: NO (version of /bin/cmake is 2.8.12.2 but version >=3.4 is required)
Dependency elementary found: NO (tried pkgconfig and cmake)
Has header "elementary-1/efl_ui_animation_view.h" : NO
Program cmake found: YES (/bin/cmake)

meson.build:58:8: ERROR:  Module "cmake" does not exist

Looks like Meson Expects the Cmake version to be >= 3.4 ,  
How to handle the case when CMake version is lower than what Meson expects ?

**Comment by mensinda** [comment]
There are two different errors:

The first one is related to a `dependency('elementary', required: false)` call:
```
Found pkg-config: /bin/pkg-config (0.28)
Found CMake: NO (version of /bin/cmake is 2.8.12.2 but version >=3.4 is required)
Dependency elementary found: NO (tried pkgconfig and cmake)
```

Since 0.49.0, meson can use the CMake dependency ecosystem to find dependencies. However, CMake 3.4 is the minimum required version (The oldest Ubuntu LTS (16.04) has CMake 3.5). This is completely separate from the CMake module (`import('cmake')`). The reason why this code fails here is that the CMake meson module was added in meson 0.50.0. There are no hard requirements for the CMake version for your use case (as far as I can tell).

To fix this error, you would have to check the meson version or specify a minimum meson version in the `project` function.

**Comment by mensinda** [comment]
Did checking for the minimum meson version solve the issue?

**Comment by mensinda** [comment]
@jpakkane I think this issue can be closed since the author did not reply.
