### ISSUE TITLE
Can't install application binary, when same binary is being executed

### ISSUE THREAD

**Issue by tobimensch** [mesonbuild/meson#578]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/EGG-INFO/scripts/meson.py", line 24, in <module>
    sys.exit(mesonmain.run(thisfile, sys.argv[1:]))
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 220, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/mesonbuild/mesonmain.py", line 210, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 235, in run
    do_install(datafilename)
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 39, in do_install
    install_targets(d)
  File "/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/mesonbuild/scripts/meson_install.py", line 196, in install_targets
    shutil.copyfile(fname, outname)
  File "/usr/lib64/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 26] Text file busy: '/usr/local/bin/aqemu'
FAILED: '/usr/bin/python3' '/usr/lib/python3.5/site-packages/meson-0.32.0.dev1-py3.5.egg/EGG-INFO/scripts/meson.py' '--internal' 'install' '~/apps/bin/pj_aqemu/build/meson/meson-private/install.dat'
ninja: build stopped: subcommand failed.

I can't remember having that problem with any other build system or system update tool. For example I can remember upgrading my complete system multiple times with dnf on Fedora, while simultaniously using my desktop. And also I'm doing regular system updates, without ever running into this.

Doing the same with cmake && make install also works just fine. And I remember it working with autotools as well.

At first it might seem like a bad idea to overwrite the binary of a program that is running, but in reality the binary is already in memory, so there should never be any actual conflict.

Kind regards.

**Comment by jbmonroe** [comment]
In Windows this isn't a thing, because Windows executables may load resources on demand from the binary file on disk, and they get swapped out of memory and reloaded all the time.  An executable is write-locked on the hard drive while it's running in order to facilitate this.  Perhaps that doesn't happen in Linux systems, but it seems to me that providing more commands to allow stop-and-resume loading of binaries wouldn't be a bad thing--I just wouldn't want Meson to assume that the entire universe works such that executing binaries are writable.

**Comment by nirbheek** [comment]
The solution to this is to simply remove the file first.

**Comment by tobimensch** [comment]
@nirbheek 
Thanks for that perfect solution! Now there's no excuse anymore to fix this.

**Comment by nirbheek** [comment]
`ninja` doesn't handle installation. It leaves that to whatever is wrapping it; in this case Meson. So that's where it needs to be fixed. I'm sure a PR for this will pop up soon.

Honestly, I'd almost be inclined to say that this is a bug in Python's `shutil.copyfile`. It should handle this case on Linux. But we have to work around it anyway.

**Comment by nirbheek** [comment]
Also, just to clarify, this will change nothing on Windows. You cannot unlink files that are write-locked there. I'm not sure if we can "schedule" installations to happen when the program exits (which usually happens on shutdown) since that gets into setup-file territory.

However, we should definitely output a friendly error message in that case.

**Comment by tobimensch** [comment]
@nirbheek 

:-)

Seems like hte shutil.copyfile is causing a lot of headaches for poor Meson developers from what I can tell.

Thanks for answering this so well. To be honest I can't be bothered about Windows, as I'm using it next to never. I think a warning/error messages would be sufficient there.
