### ISSUE TITLE
library() creates `pie executable` instead of `shared object` on gcc-8

### ISSUE THREAD

**Issue by matt-deboer** [mesonbuild/meson#5841]
Meson version: 0.51.1 (installed via pip3 install meson)

I've noticed that with gcc-8 (default on ubuntu 19.04 is gcc 8.3.1) the `library` function (and shared_library() as well) creates `pie executable` objects where I expect a `shared object` to be created.
This does not happen with gcc-7 (ubuntu 18.04 defaults is gcc 7.4.0).

Here is an example Dockerfile that demonstrates the behavior (just toggle between `bionic` and `disco` ubuntu images to see the difference). This is a build of the Aravis library which uses meson:
```
FROM ubuntu:disco

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
 && apt-get install -y \
    build-essential \
    git \
    ninja-build \
    cmake \
    libgirepository1.0-dev \
    gettext \
    libxml2-dev \
    python3-pip \
    libusb-1.0.0-dev \
 && pip3 install meson \
 && git clone -c advice.detachedHead=false  --quiet --single-branch --branch master --depth 1 https://github.com/AravisProject/aravis.git /opt/aravis \
 && cd /opt/aravis \
 && meson -Dviewer=false -Dgst-plugin=false -Ddocumentation=false -Dpacket-socket=false build \
 && ninja -v -C build \
 && file build/src/libaravis-0.8.so.0.7.0
```
As far as I can tell, the lines which create the shared object are identical for each version of gcc, it's just that in one case I get a `shared object` and in the other, a `pie executable`. 

I haven't yet found why gcc-8 would not create a shared object when passed the `-shared` flag...(while gcc-7 would)

**Comment by matt-deboer** [comment]
It looks like gcc-9 works as expected (just switch the FROM tag to `ubuntu:eoan` in Dockerfile above to test), so it's an issue specific to gcc-8

**Comment by jpakkane** [comment]
I have no idea what could be causing this. The only thing could be that you are getting a symbol called `main` in there somehow with GCC 8. But if you get different output with the exact same compiler invocation commands, then it would indicate that the bug is not in Meson.

**Comment by matt-deboer** [comment]
Yeah, I just conducted another experiment where I installed gcc-9 into ubuntu disco (which defaults to gcc-8), and it also produces the executable, so there must be an issue with one of the project's dependencies (the versions provided by ubuntu disco) sneaking in a 'main' symbol. I'll look for that. Thanks.

**Comment by matt-deboer** [comment]
Just to follow up, it turns out the issue was caused by `/lib/x86_64-linux-gnu/libc-2.29.so` on ubuntu 19.04...it shows as a `pie executable`; whereas the same file on ubuntu 19.10 shows as `shared object`...bizarre.

**Comment by eli-schwartz** [comment]
The `file` command in version... 5.37 if I remember correctly, learned to correctly tell the difference between a PIE-enabled executable and a PIE-enabled shared library.

This has nothing to do with meson, and nothing to do with gcc. Download the Ubuntu .deb files for libc6 for the respective Ubuntu releases (libc6_2.29-0ubuntu2_amd64.deb  and libc6_2.29-0ubuntu3_amd64.deb), extract them, and run the `file` command on each one in turn. They will both report the same thing... depending on your version of the file command, they will both claim to be shared objects, or they will both claim to be executables. Needless to say, "but the file command says it's an executable" doesn't actually *make* it an executable.

...

Consider this to be a reminder that software is complex, and you should not go around saying you know where the problem is (gcc) without having thoroughly tested every possible difference between your environments. ;) Your reproduction toolchain included the file command -- you showed it in your test command line -- and ultimately, you should be looking at the two produced files from different environments, and then comparing them in the same environment.
