### ISSUE TITLE
Support architecture idependent library path

### ISSUE THREAD

**Issue by 3v1n0** [mesonbuild/meson#5933]
Meson's default `libdir` points to an architecture dependent path.

This is fine for most of the cases, but there are cases where we might want to install arch independent libraries (python, perl, js, ....) to to (say) `/usr/lib/${module_name}/` so that packagers can put it into arch-independent binaries.

While this can be manually be defined, you then also need to provide a meson option to override it by command line, while it would be better to have a standard option for such case.

**Comment by ssssam** [comment]
For reference, this issue came out of: https://gitlab.gnome.org/GNOME/tracker/merge_requests/140

**Comment by eli-schwartz** [comment]
What does that even mean. Isn't a libdir by definition arch-dependent?

js seems like a perfect situation in which to install to the datadir.

Python has a single site-packages directory which mixes both .py files and compiled .so extensions in a single module bundle. I guess theoretically you could have an extra sys.path entry for pure python modules, but that seems like a lot of complexity to deviate from upstream python for utterly no gain. Does anyone actually do this?

Perl fundamentally already stores compiled .so extensions in the vendorarch directory, and .pm interpreted modules in the vendorlib directory -- on my archlinux system, vendorarch is in the libdir and vendorlib is in the datadir -- so if you're trying to do something different you're wrong.

**Comment by jpakkane** [comment]
AFAIK Python packages should be installed to the system Python dir. We [do have helpers for these in the Python module](https://mesonbuild.com/Python-module.html). Are they sufficient for you or do you need something completely different?

**Comment by ssssam** [comment]
Thanks for the response. The use case is to install a 'private' Python module, which I chose to put inside $libdir rather than $pythonsitepackagesdir because i don't consider it part of the Python ecosystem, rather something specific to my package.

This is already something the gobject-introspection package does, with the `/usr/lib64/gobject-introspection/giscanner`. I figured I would copy this model with my 'trackertestutils' Python module, but it has caused some problems when packaging the library for Debian.

We worked around this by making the install path of the Python module configurable, but I suggested that it would be better if Meson supported whatever Debian needed upstream. Unfortunately I don't understand enough about packaging to know exactly what that is ... or whether it would actually be better if we installed our package-specific Python code into the system Python dir.

**Comment by eli-schwartz** [comment]
> but it has caused some problems when packaging the library for Debian.

Can you be a bit less vague? Pretend that some people don't use Debian. (I don't!)
Even if I used Debian, how should I know whether "caused some problems" is a file conflict error or a "best practices packaging guidance" error, or what have you.

**Comment by ssssam** [comment]
I'm being vague because @3v1n0 knows much more than me here. Maybe he can fill in details :-)

**Comment by eli-schwartz** [comment]
@3v1n0 ping?

**Comment by eli-schwartz** [comment]
Still waiting for an explanation of what the actual issue is...

Closing due to lack of response. Feel free to reply with more information and ask for the ticket to be re-opened.
