### ISSUE TITLE
Why install phase is not done by ninja?

### ISSUE THREAD

**Issue by dnohales** [mesonbuild/meson#596]
The install phase in Meson looks a bit tricky. Meson creates the `install.dat` file so it can be parsed by an internal Meson install script, and Ninja delegates everything in that script. Why not just create Ninja build statement for each file to install (and also for executing the custom post-install commands)? we could benefit of it dependency management to not install a file two times in the same install destination if it's not changed, so in theory, it'd be more performant.

The install related code could be simplified as well and it could be more clear. The current approach of serializing arrays to then deserializing in the internal scripts looks a bit ugly (mainly when you see how we use hardcoded integers indices when dealing with the deserialized arrays).

This is just a question since I'm trying to understand why this bit of Meson is done like that. Maybe this could be improved (of course I could work in a PR).

**Comment by nirbheek** [comment]
Just to clarify, you're asking why the list of files to be installed (source dir + filename → output dir + filename) + filename aliases + permissions + rewriting of build rpath + setting of install rpath + stripping + DESTDIR support (and more) aren't embedded in Ninja rules that pass these as arguments to an install script, instead of `install.dat`?

Jussi will have to answer in detail, but IMO passing all that data as arguments is very error-prone and clumsy. You're basically serializing to command-line arguments and then deserializing by argument parsing; which means you probably have to account for shell quoting too. Having an `install.dat` (which is just a Python pickle) is a much simpler way of passing data to an install script. 

By spawning the install script just once, you also reduce the overhead of `execv` which is quite significant on some platforms such as Windows, and also don't spawn the Python interpreter repeatedly, which is a major slowdown on all platforms if done for each file.

In the process you might lose some dependency management, but I don't know if that's a real problem. The only way you know for sure that the built file has changed compared to the installed one is by doing a checksum of both, and at that point it's faster to just always install it. This is different from dependency management inside the build tree because that is entirely under your control.

The only exception I can think of is CoW filesystems with snapshots where you have a strong incentive to not overwrite a file if it is identical, but that's something to implement when there's a feature request for it. Although even then the filesystem should ideally detect this scenario and do online dedup.

**Comment by jpakkane** [comment]
What Nirbheek said. In addition there are many backends and it is a lot simpler to have them all call the same script rather than every one of them reimplementing the same functionality.

Implementing this in Ninja is not much fun either. On Windows we must work without a unix shell, that is, using only Windows' `cmd.exe`. Simply copying files reliably with it is tedious, implementing all the other bits would be a maintenance nightmare.
