### ISSUE TITLE
ninja: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by esodan** [mesonbuild/meson#6137]
At local this is not an issue, but on Continuous integration at GitLab, there is a repetitive issue.

The output can be seen at: https://gitlab.gnome.org/esodan/gvls/-/jobs/491030

I was unable to reproduce the issue locally.

**Comment by jpakkane** [comment]
This is almost certainly a bug in Ninja rather than Meson. You should probably report it to Ninja upstream.

If you can build a custom version of Ninja with address sanitizer (and/or undefined behaviour sanitizer) enabled and use that in your CI build machine, you could probably get a lot more accurate log information to help debug the issue.

**Comment by esodan** [comment]
Moving to https://github.com/ninja-build/ninja/issues/960
