### ISSUE TITLE
Cannot pass object generators nor files to add_install_script

### ISSUE THREAD

**Issue by nacho** [mesonbuild/meson#6175]
If I try to pass an object generated by a generator or if I try to pass a file to meson.add_install_script I get the following error:
ERROR: add_install_script args must be strings

**Comment by zackw** [comment]
+1 I just tripped over this myself.  In my case, I have all of my build scripts in a scripts/ subdirectory, and meson.build in that directory sets variables for files() objects for each, for instance

```
S_install_symlink = files('install-symlink')[0]
```

Then in another subdirectory's meson.build I had

```
  if INSTALL_SHARED_LIB
    meson.add_install_script(S_install_symlink, get_option('libdir'),
                             'libcrypt.so', 'libxcrypt.so')
  endif
```

and this blows up with

```
lib/meson.build:208:10: ERROR: add_install_script args must be strings
```

and this in the logfile:

```
Element not a string: [<File: scripts/install-symlink (not built)>, 'lib/x86_64-linux-gnu', 'libcrypt.so', 'libxcrypt.so']
```

This is particularly annoying because there's no documented way to turn a File object back into a string from the meson.build language.  (In fact, File objects don't seem to be documented at all!) The Python-level File object (mesonlib.File) has an absolute_path method but it's not callable from the meson.build language.

Anyway, it seems like add_install_script should accept the same kinds of positional arguments that run_command does.

**Comment by zackw** [comment]
Another thing that doesn't work but really should:

```
pymod = import('python')
python = pymod.find_installation('python3')
meson.add_install_script(python, 'install-hook.py')
```

-> 

```
Element not a string: [<Holder: <ExternalProgram 'python3' -> ['/usr/bin/python3']>>, 'install-hook.py']
```

**Comment by alex-tee** [comment]
+1

can't pass the result of a configure_file() to meson.add_install_script() and can't see a reason to not allow that

i pass `meson.build_root () / .... / 'my_script.sh'` instead which is pretty much the same thing, but weird

**Comment by dcbaker** [comment]
I have a patch for this in a branch, I'll clean it up and send it out.
