### ISSUE TITLE
.system() == "android" is missing in the reference table of operating system names

### ISSUE THREAD

**Issue by alexandre-janniaux** [mesonbuild/meson#6233]
In the following document:

https://mesonbuild.com/Reference-tables.html#operating-system-names

If I understand the code correctly, Android should be added as Meson takes it into account and sometimes does special handling for it, like `pie` (see the few case in `git grep android`).

**Comment by sztomi** [comment]
This is still missing.

**Comment by jpakkane** [comment]
This is problematic because we have traditionally only specified this for platforms that we do native compilation on and get the value via Python's stdlib. Android is different in that you are always cross compiling to it (as far as I can tell at least) and for cross files the system can be anything the user want it to be. If we call it `android` and later Google starts calling it something different (`googleos` or `aosp` or whatever) that will cause problems.

**Comment by tp-m** [comment]
Maybe we can just document it as a convention subject to change?

It's what most people use in their cross files right now and surely it's useful to make sure that people who write `meson.build` files all use the same identifier here?

**Comment by alexandre-janniaux** [comment]
Hi,

>  If we call it android and later Google starts calling it something different (googleos or aosp or whatever) that will cause problems.

Given that android is in the triplet naming, it shouldn't be an issue or else it would break much more than just meson. Google has not really the history of renaming things, but instead replacing them and it would seem unlikely that they try to change such brand.

I have much more insight on such buildsystem issues since I have opened this one, and imho more interesting questions are:
 
+ does meson really have something to do in case the target is android?
+ should it be done in meson or an outside wrapper?

A lot of things can be removed from the inner logic in meson and pushed into crossfiles instead, which I see much saner than trying to workaround target differences. However, it probably also means that this issue should be transformed into a documentation issue.
