### ISSUE TITLE
Python extension_module does not install in site_packages

### ISSUE THREAD

**Issue by gerion0** [mesonbuild/meson#6331]
In the *python* module documentation is claimed that `extension_module` install per default in `site_packages`:
> `subdir`: By default, meson will install the extension module in the relevant top-level location for the python installation, eg `/usr/lib/site-packages`. When subdir is passed to this method, it will be appended to that location. This keyword argument is mutually exclusive with `install_dir`

However, this does not work. When set `install: true` the modules are installed to `$prefix/lib64` on my system.

One workaround is to specify the target like:
```
py3_mod = import('python')
py3_inst = py3_mod.find_installation('python3')

foo = py3_inst.extension_module('foo',
    <source_target>,
    install: true,
    subdir: get_option('prefix') + py3_inst.get_path('purelib'),
    dependencies: [py3_inst.dependency()]
)
```
It would be nice, if the subdir is set autotically to the `site-packages` folder.

This bug is btw similar to #2859. However, this talks about the now deprecated *python3* module.

**Comment by spanezz** [comment]
Same here, except since I build a C module, I need to use `install_dir: py3_inst.get_path('platlib')`

**Comment by eli-schwartz** [comment]
`subdir` is supposed to be a subdirectory of get_install_dir() a.k.a. site-packages, not an absolute path, which will set the default install_dir. The code is broken because it accidentally only sets the `install_dir` to `join_paths(get_install_dir(), subdir)`, if a subdir is passed... otherwise it sets no site-packages at all. A trivial backwards-compatible no-op that tricks the meson code into *thinking* you passed a subdir, and then sets the install_dir to the correct default, is `subdir: ''` which then becomes `join_paths(get_install_dir(), '')` and the '' is simply ignored.

A proper fix for this should be available in the next version of meson; see linked PR.
