### ISSUE TITLE
Running --benchmarks and --tests on build script does not work

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6339]
**Describe the bug**
It seems that after Running --benchmarks and --tests on build script is not working and I get the following.
```console
Michaels-MBP:15-intro-scan mike$ meson introspect --tests meson.build 
No command specified
```
Here you see some values are missing like the programming language.

**To Reproduce**
```meson
project('prog', 'cpp', meson_version: '>=0.52.1')

exe = executable('exe', 'main.cc', install: true)

test('Run test exe', exe)
```

**Expected behavior**
As the user, I expected to not have missing values for benchmarks and tests so Meson-UI does not crash due to missing values in the introspection dialog after project setup without building.

**system parameters**
* Plain native build (for the same computer)?
* MacOS Catalina
* Python 3.8.0
* Meson `0.52.1`
* Ninja `1.9.0.git.kitware.dyndep-1.jobserver-1`

**Comment by mensinda** [comment]
Benchmark and test introspection is not implemented for the `meson.build` API. It is only available with a configured build directory.

Currently only `--buildoptions`, `--dependencies`, `--projectinfo` and `--targets` can be used without a build directory. Generally, the meson introspection API can be thought of as two different APIs: One for a configured build directory, and one for providing basic information before a build directory is created. They have two completely different backends internally for creating the introspection output. Specifically, the `meson.build` API is far more limited. Both APIs should be handled separately.

If possible, a configured build directory should *always* be preferred, because it provides more accurate information.

Are the tests and benchmark information in Meson-UI required without a configured build directory? If not, I would suggest fixing Meson-UI so that it does not crash if values are missing or the introspection information is not available.

If there is a valid use case for test introspection information without a build directory, I will consider implementing it.

**Comment by michaelbadcrumble** [comment]
What about in my app Meson-ui a command line plugin for Meson build system, simply to get values from the build script before setup dialog, this feature would allow me to provide values straight from the build script instead of assuming default values.

Test and benchmark are kinda important.  Can also benefit others when taking advantage of Meson build system provided data, more of a short hand.

**Comment by mensinda** [comment]
I am not sure what you are trying to do, but instead of writing a plugin (for which there is no precedent in meson) I would recommend implementing this feature directly. This would be a lot easier for both projects (no need to maintain a plugin API and overall less code to maintain).

To be clear, I am not agains adding test and introspection support to the `meson.build` API. It is just that it is not a trivial thing to implement (patches are welcome). See [mintro.py](https://github.com/mesonbuild/meson/blob/master/mesonbuild/mintro.py) and [ast/introspection.py](https://github.com/mesonbuild/meson/blob/master/mesonbuild/ast/introspection.py) for a starting point.

**Comment by michaelbadcrumble** [comment]
I would love to implement this feature but I’m not sure if Meson wants a build GUI in the project. 

So this is currently available separate from the Meson as a standalone build GUI with one dependency PyQt5 that would be replaced with Tkinter as soon as possible to finally drop the dependency graph.

https://github.com/michaelbadcrumble/meson-ui

**Comment by mensinda** [comment]
I thought you were talking about adding the introspection support for tests and benchmarks as a plugin :)

**Comment by michaelbadcrumble** [comment]
Oh god no that would not make since.

**Comment by mensinda** [comment]
Now the question is, do you really need to know the tests and benchmarks without a configured build directory? If yes, then the API will also be severely limited, similar to `--targets` as explained in #6338.

The only information that the API *might* provide is the name of the test. All other values would probably be dummy values (including `cmd`). Here is an example where the introspection API guess the wrong test name:

```meson
if true
  tname = 'foo'
else
  tname = 'bar'
endif

test(tname, ...)
```

Here, `tname` will be evaluated as `bar` if no build dir is present and as `foo` with build directory. This is because no meson code is executed for introspection, and all branches of an `if` are walked once unconditionally. This limitation also applies to `--targets` by the way.

**Comment by michaelbadcrumble** [comment]
I would only require the data for when the user try's to view introspection data without building the project.

I can work with limited API if required.  However I just found this `—force-object` as a handy solution for Meson 0.50.0 to the current version.

**Comment by mensinda** [comment]
I don't think that showing test introspection data (and to some extent even targets) without a build directory is helpful for the user. For once, the output may be wrong (see the previous discussion). It will also be incomplete (basically only the test name for `--tests`).

So, I would recommend to only show the projecinfo, dependencies and buildoption introspection for an unconfigured project. All other introspection sections should require a configured build directory.

I would close this issue for now, unless the introspection output is really required (here, useful to the end-user). If not, we can always reopen this issue if required.

I am also considering to make calls to `--tests`, etc. a hard error without a build directory, to avoid confusion in the future. So you should only use those options in the right context and be aware that the output format may differ in different contexts.

**Comment by michaelbadcrumble** [comment]
Ok but I’m using the `--force-object` option to return an empty data structure, and with that I’m outputting nothing in both tests and benchmarks.
