### ISSUE TITLE
AttributeError: 'CustomTargetIndex' object has no attribute 'is_internal'

### ISSUE THREAD

**Issue by yshui** [mesonbuild/meson#6365]
**Describe the bug**
meson crashes with the error in the title

**To Reproduce**
```meson
project('bug', 'c')
t = custom_target('dummy', output: [ 'libdummy.a' ], command: [ 'echo', 'dummy' ])
dep = declare_dependency(link_with: t[0])

l = static_library('l', 'src/empty.c', dependencies: dep, install: true)
```

**system parameters**
* ArchLinux
* Python: 3.8.0
* meson: 0.52.1

**Comment by yshui** [comment]
Same thing happens for 'CustomTarget' object too

**Comment by xclaesse** [comment]
Sounds like a regression I introduced in 0.52, can you please try the fix I made in https://github.com/mesonbuild/meson/pull/6366?

**Comment by yshui** [comment]
@xclaesse I am not sure if #6366 is the right solution. Seems like it will have the problem 484b721 tried to fix. i.e. if a static library is linking with a custom target that is not installed, things won't work.

**Comment by yshui** [comment]
Maybe we should produce an error `if isinstance(self, StaticLibrary) and isinstance(t, (CustomTarget, CustomTargetIndex)) and not t.need_install`?

**Comment by yshui** [comment]
BTW, #6366 also doesn't fix the CustomTargetIndex case

**Comment by andreimaximov** [comment]
+1 this is a blocker (without awful hacks) for linking static libraries generated by external build systems (eg. make) via custom targets. @yshui are you still working on https://github.com/mesonbuild/meson/pull/6367? If not I can pick up where you left off.

**Comment by yshui** [comment]
@andreimaximov please go ahead.

**Comment by Sahnvour** [comment]
I'm also blocked by this, @andreimaximov have you made progress on this by any chance ?

**Comment by andreimaximov** [comment]
@Sahnvour I haven't had a chance to spend much time on this. It seems like implementing `is_internal` for `CustomTarget` and `CustomTargetIndex` is the way to go but I stopped when I hit this:

https://github.com/mesonbuild/meson/blob/e5fabce1f32ffe918a96acd026c0e258f6d682b8/mesonbuild/build.py#L1154-L1159

Say we have...

1. static-lib-custom-target A, not installed
2. static-lib B, links in A, installed

It seems like B would need a way to get all the object files out of A because A is not installed and should be considered internal. I might be totally wrong though... maybe @xclaesse can pitch in.

**Comment by Jairard** [comment]
Hello,
this is also a blocker for me 😭 
@andreimaximov  @xclaesse did you have some time to work on this ?
Thank you !
