### ISSUE TITLE
Document meson specific meaning of the `LD` environment variable

### ISSUE THREAD

**Issue by textshell** [mesonbuild/meson#6413]
According to an IRC discussion today, meson uses the environment variable `LD` to specify the linker to use. This differs from at least how autotools use this variable. Thus we need to document this.

There is mention of a similar feature for cross files, but even if this internally boils down to be exactly the same, we need to document this outside of the cross compiler specific documentation to be clear and discoverable.

**Comment by dcbaker** [comment]
To add to this, in a cross or native file you can specify:

```ini
cc = 'clang'
ld = 'lld'
```

And meson knows that clang sets the linker by adding `-fuse-ld=lld`, or with an msvc like compiler (in which ninja invokes the linker directly)

```ini
cc = 'clang-cl'
ld = 'lld-link'
```

And meson will do the correct thing and invoke lld-link.exe instead of link.exe

the environment variable $LD can be used in place of the ld field in the cross/native file.

**Comment by dcbaker** [comment]
Since we don't have the LD environment variable anymore I'm going to close this.
