### ISSUE TITLE
Linking library doesn't seem to work as expected

### ISSUE THREAD

**Issue by DJSchaffner** [mesonbuild/meson#6593]
DISCLAIMER:
This might not be a bug, but theres not many places to find help for meson so i try here

**Describe the bug**
When i manually compile my project and link against my 2 external libraries (GLFW3 and FreeType) it works fine, but linking them with meson produces errors in the project using my library, saying there are unresolved external symbols (from those 2 libraries)  

The compilation of the library project works fine, but i get an error linking against the resulting library in a child project.

**To Reproduce**
```
project('mylib', ['cpp', 'c'], default_options : ['cpp_std=c++17'])

mylib_src = files([ # LIST OF SOURCES # ])

mylib_hdr = files([ # LIST OF HEADERS # ])

cpp = meson.get_compiler('cpp')
dir_base = meson.current_source_dir()
dir_lib = join_paths(dir_base, 'lib')

mylib_inc = include_directories('include', 'src')
lib_freetype = cpp.find_library('freetype', dirs: dir_lib, required: true)
lib_glfw = cpp.find_library('glfw3', dirs: dir_lib, required: true)

library('mylib', name_prefix: '', name_suffix : 'lib', 
        sources: mylib_src, 
        dependencies: [lib_freetype, lib_glfw],
        include_directories: mylib_inc)
```

In my 'child project' i link against the resulting library file same as i do here with freetype/glfw

Here is how i did it 'by hand' in a simple version:  
`lib.exe /OUT:build/lib/mylib.lib # list of obj files # lib/glfw3.lib lib/freetype.lib`

**Expected behavior**
It should compile and run in both projects just fine.

**system parameters**
Regular release installed using 'meson-0.53.1-64.msi' from release section
Windows 10 64 Bit
Python 3.8.0
Meson 0.53.1
Ninja 1.9.0

**Comment by chrisdoherty4** [comment]
Have you got a specific example? Generally speaking, your meson looks fine.

**Comment by DJSchaffner** [comment]
I will make a small example project and post it as soon as i get around to it.

**Comment by DJSchaffner** [comment]
I set up a basic test repo using just freetype (because i use it in my other project and was easier to set up than glfw but this should apply to other libaries as well)  
[Repo](https://github.com/DJSchaffner/meson_link_test)  

I didnt add any special settings after the meson setup so you should be able to recompile this just using  
`meson build` and then `ninja -C build` from their respective base directiories.  
For easier setup i already added thee compiled library file and header to the test project.

**Comment by chrisdoherty4** [comment]
I think I can see what's happening.

You're building your library as a static library (which is just a collection of object files). When you use the static library downstream in some other project you need to make sure you include it, along with any headers you've defined, _and it's dependencies_. 

Specifically to your example project, you need to specify the FreeType library that _mylib_ depends on on when building the myproject executable so that the final executable can resolve the FreeType symbols it includes from the mylib static library.

The 'wrap' system in Meson can help you wrap up your external dependency (mylib) appropriately for consumption by some other project. Alternatively, just build the external dependency as part of your project (myproject).

A side note, you shouldn't need to specify prefixes and extensions for Windows. Meson will handle that for you.

**Comment by DJSchaffner** [comment]
Alright, thanks for helping me. I will try it tomorrow and report back.

> A side note, you shouldn't need to specify prefixes and extensions for Windows. Meson will handle that for you.

When I didn't set those, meson would just build the library with a suffix 'lib' and as extension it chose '.a'. That's why I added it. So unless I missed a configuration step, it didn't seem to chose the correct one.

**Comment by DJSchaffner** [comment]
I'm sorry to bother you with this but i can't really get it to work.  
In the end i want `mylib` to be a standalone library which i can link against `myproject` without `myproject` ever having to worry about what `mylib` uses as dependency and i also don't really want to use `mylib` as a subproject, but just as a regular library.  
This should be possible, given that it's so easy to set it up by manually linking the external dependency with compiled object files

I updated the repo with my newest attempt

Would you mind setting my example up in such a way that it works?

**Comment by chrisdoherty4** [comment]
You're end goal of providing a dependency transparently to a consumer is a good model to have.

Let's step back a minute and think about how you would consume FreeType on Linux. Generally, when you want to use some third party library, you would install it in your environment (often installing a -dev package). With respect to FreeType that library is libfreetype6-dev. The -dev package, in a general case, will install header files and the associated libraries. The -dev package in turn may specify dependencies packages that also need installing such as the [libfreetype6-dev](https://packages.ubuntu.com/bionic/libfreetype6-dev) that has 4 dependencies one of which is zlib1g-dev.

The point I'm illustrating is that the library you depend on is delivered to you in a package (in the Ubuntu case as a deb) which installs headers and libraries at paths known to the toolchain so that you can use `#include` directives in your source code and link against the library itself. On Windows, you might simply download an installer that installs the freetype developer files and libraries.

The packages I'm referring to (Linux or Windows installer) are constructed by maintainers. In your example you're essentially looking to produce a mylib package (the external dependency) that declares its dependencies in a transparent way so that myproject can use mylib without needing to explicitly know what mylib's dependencies are.

In Meson, we declare our dependencies in a consuming project using the [dependency](https://mesonbuild.com/Reference-manual.html#dependency) call which will attempt to find the dependency on the system using pkg-config before attempting to build it as a [subproject](https://mesonbuild.com/Subprojects.html). If the dependency call falls back to building it as a subproject, the subproject should declare the dependency with the [declare_dependency](https://mesonbuild.com/Reference-manual.html#declare_dependency) call that also declares the dependencies of the dependency. Your subproject can be constructed of meson code you write yourself that does the declare_dependency calls or a [wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) file that pulls already written meson code along with any files etc.

For example, the freetype wrap includes the following towards the bottom of the meson file:
```
freetype_dep = declare_dependency(link_with: libfreetype,
  include_directories : incbase,
  dependencies: deps
)
```

The key component of this to recognize is the fact that the freetype dependency above is declared with it's own dependencies (the `dependencies: deps` line). In constrast, your code doesn't use any dependency management, you merely search for a library using `lib_mylib = cpp.find_library('mylib', dirs: dir_lib, required: true)` and try to use it but mylib actually has a dependency on a freetype library. This results in link lines to the effect of:

```
link.exe /OUT:myproject.exe /lmylib.lib
```
instead of
```
link.exe /out:myproject.exe /lmylib.lib /lfreetype.lib
```

So, to conclude, you need to change things up a little bit:
1. Build and package your mylib dependency in such a way that it can be consumed by a downstream project. There's a best [practice and tips](https://mesonbuild.com/Wrap-best-practices-and-tips.html) page to help with this.
2. Consume the dependency properly using the `dependency` call rather than just finding the library at some path.

**Comment by chrisdoherty4** [comment]
I've taken a look at your project again and it looks like you're heading along the right lines with the freetype declaration. I can see you want to use a pre-built version of freetype.lib, which is fine, but you need to ensure the freetype library is available to myproject as well because when you link against mylib.lib it requires freetype.lib. 

The contents of freetype.lib are not included in the mylib.lib hence the symbol resolution error.

**Comment by DJSchaffner** [comment]
Thank you for your detailed explanation!  
After reading this i feel like maybe i was approaching this the wrong way all along, since from what i understand everything would involve either installing `freetype` publicly on the machine, or having it as an extra library i will have to ship together with my library.  
However what i did before was create a library from the source files of `mylib` and then create another library that would basically bundle mylib and freetype together so ultimately you would only have to include this bundle.  

The compilation process would be something like this:  
`cl -Isubprojects/freetype/include "src/mylib.cpp" -c`  
`lib /OUT:mylib_pre.lib mylib.obj`
`lib /OUT:mylib.lib .\mylib_pre.lib .\subprojects\freetype\freetype.lib`  
This would result in a bundled library and work like i want it. From what i read producing a dynamic library might also solve my problem since as i understand it, it will consume the static library. However, i have not played around with that, so i might be wrong.  

Is what i do here replicatable with `meson`?  
Or is what i did there complete nonsense and i should consider doing what you suggested, and use a public or seperately shipped version of `freetype`?

**Comment by chrisdoherty4** [comment]
On Windows it's pretty normal to ship dependencies with the code itself. I think that stems from the fact Windows doesn't, traditionally, have a package management system so there's no easy way to deliver packages that express their dependencies and so forth.

In your case, you might want to ship a pre-built freetype library with your mylib project so that the consumers of mylib have the dependency available. Ideally you want to provide some meson code that you can slap into the subprojects directory with your mylib deliverable (and the freetype library) that makes the `declare_dependency` call and specifies both mylib, and the freetype lib required for linking.

Turning your mylib project into a shared library will only solve the issue if you build it against a static version of freetype. In that case, the linker will open the static freetype library and include in the mylib shared library all the shared objects that resolve symbols in the mylib library. You'll need to ensure the freetype library was built using `-fPIC` else the assembler won't be able to call functions properly.

Building mylib as a shared library against a freetype shared library is another option but will be run-time considerations that you'll need to address.

**Comment by DJSchaffner** [comment]
Alright, thanks alot for the explanation.  
Since the shared library doesn't want to be found when i search for it using `find_library` the same way i do it with the static one, i will probably end up trying to figure out what you suggested, which is shipping the external libraries together with mylib.  

Let's see how that turns out :)

**Comment by DJSchaffner** [comment]
After some trial and error i got my test setup to compile and run fine.  
I updated the repo with it to the newest working version if you would like to take a look and have suggestions for improvements or changes.  

For now i will probably move this concept over to my actual library and implement it there.

Thanks again for guiding me!

**Comment by bruchar1** [comment]
I think we can close this issue (cc @tristan957 )
