### ISSUE TITLE
How can I get test results via introspection?

### ISSUE THREAD

**Issue by michaelbadcrumble** [mesonbuild/meson#6613]
Hello.
Is it possible to read in the test results from the introspection data, because it seems like its currently impossible?  I was expecting something like `result` as a key for each JSON object representing a test.

My use case would be to display the test name followed by a test result in Meson-UI.

**Comment by mensinda** [comment]
The introspection API does not provide the test results. It only shows which tests are available. There are also general problems with including test results in the introspection data:
- Which results should be included?
  - all results
  - the last result
  - the last X results
- should logs be included?
- what happens no tests were run (introspection must work as soon as there is a build directory)?

Instead of putting the result in the introspection API, I would rather extend [meson test](https://mesonbuild.com/Unit-tests.html) to include a more machine parsable reporter (assuming it does not already exist).

**Comment by michaelbadcrumble** [comment]
To answer your questions I would think that the `result` key should provide the results of the current test like with the example test object below. No need for logs to be included, since I imagine that Meson already has that handled by printing test result logs into a file named `testlogs.txt`.  If no test are found then just keep the default value of empty JSON array object.

```JSON
[{
    "name": "name of the test",
    "workdir": null,
    "timeout": 30,
    "suite": ["example-test"],
    "is_parallel": true,
    "protocol": "exitcode",
    "result" : "passed",
    "cmd": ["command", "to", "run"],
    "env": {
        "VARIABLE1": "value 1",
        "VARIABLE2": "value 2"
    }
}]
```

Does that help?

**Comment by mensinda** [comment]
Not really, since the introspection API is completely separate from running tests.

> If no test are found then just keep the default value of empty JSON array object.

The introspection data is solely generated from configuring the project and *not* from `ninja test` or `meson test`. Tests are not dynamically found at runtime. That means that the complete test introspection data for *all* tests are always available after the configure step. They only show how the test was *defined* in the `meson.build` and thus the test result is unknown since no tests were executed at that point.

When `ninja test` is run, meson loads the test definitions stored somewhere in `meson-private` and executes the tests. The introspection data is not (and arguably should not) be touched in this step.

So, instead of somehow hacking the test results into the introspection data, I would rather improve `meson test` (with a JSON reporter, etc.). It does not make sense architecturally to store the test result in the already existing introspection structure.

**Comment by michaelbadcrumble** [comment]
That actually sounds good. JSON is pretty reliable anyway.

**Comment by jpakkane** [comment]
> assuming it does not already exist

It does. The output of tests is written to `meson-logs/testlog.json`, but note that it is not actually JSON but "streamable JSON" where the result of any single test is written in a single line. The point of this is that you can load test results as tests are being run.

The design was perhaps not the greatest in the world. We can change it if something better comes along.

**Comment by michaelbadcrumble** [comment]
This has what I’m looking for thanks.

**Comment by michaelbadcrumble** [comment]
Never mind, Meson-UI progress bar is probably not that important of a feature.

Again thanks.
