### ISSUE TITLE
The "compiler as linker" problems

### ISSUE THREAD

**Issue by ur4t** [mesonbuild/meson#6639]
Related #6633 https://github.com/mesonbuild/meson/pull/6634#issuecomment-586817866 #6638 

Having read source codes and done some tests, I've found Meson is using compilers as linkers when not in msvc compatible mode. I've pointed the origin of problems in #6634 with comments.

Personally I think the "clang-cl/msvc" style is the right way. Compilers should just be compilers, and linking should be done by linkers. Maybe we can fix the problem, with a thoroughly refactoring. But it is so hard to avoid breakages.

**Comment by dcbaker** [comment]
Unfortunately GCC, clang, all of the d compilers, rust, swift, etc don't share that point of view. They assume up and down that you are going to invoke the linker through the compiler. We could do another massive refactor, but I'm not sure we'd really eliminate any bugs, and we're going to be breaking the assumptions of every developer used to working with autotools and cmake, that anything passed to the c compiler is passed verbatim to the link command. Often the compiler hides certain complexities of differences between the linker for you (apples ld64 takes different options than gnu ld, for example, but GCC hides that).

What I think you're really running into is the corner cases of a massive refactor I did to break the assumption that Linker X and Compiler Y always go together, ie GCC is *always&* used with ld.bfd, cl.exe is *always* used with link.exe. Before that it was impossible to use clang with link.exe because our clang representation was hardcoded to assume gnu style ld.

**Comment by nirbheek** [comment]
Sounds like we should not pass CFLAGS to the linker when the linker is not the same as the compiler? Or am I missing something.

**Comment by ur4t** [comment]
> 
> 
> Unfortunately GCC, clang, all of the d compilers, rust, swift, etc don't share that point of view. They assume up and down that you are going to invoke the linker through the compiler. We could do another massive refactor, but I'm not sure we'd really eliminate any bugs, and we're going to be breaking the assumptions of every developer used to working with autotools and cmake, that anything passed to the c compiler is passed verbatim to the link command. Often the compiler hides certain complexities of differences between the linker for you (apples ld64 takes different options than gnu ld, for example, but GCC hides that).
> 
> What I think you're really running into is the corner cases of a massive refactor I did to break the assumption that Linker X and Compiler Y always go together, ie GCC is _always&_ used with ld.bfd, cl.exe is _always_ used with link.exe. Before that it was impossible to use clang with link.exe because our clang representation was hardcoded to assume gnu style ld.

> 
> 
> Sounds like we should not pass CFLAGS to the linker when the linker is not the same as the compiler? F.ex., when the user explicitly sets the linker to a different binary. Or am I missing something?
> 
> PS: setting the linker is very undocumented right now. F.ex., you have to pass `gold` and not `ld.gold`.

Thanks for your kindly explanation. Seems that I'm using meson on the bleeding edge. 

Actually clang executable 9.0.0 pre-built binaries targeting msvc, which I downloaded from llvm.org, are using gnu style arguments and _automatically_ invoke link.exe with arguments translated to ms style. I'm also confused about why clang invokes link.exe but not lld-link.exe, or lld-link.exe is just a translation layer towards link.exe?

I'll close these issues #6633 #6639.

**Comment by ur4t** [comment]
@dcbaker @nirbheek Please tag these issues for searching in the future.
