### ISSUE TITLE
meson will fail when use the Chinese version of VS2017

### ISSUE THREAD

**Issue by scholarzry** [mesonbuild/meson#6757]
**Describe the bug**
1. install  VS2017 with zh_cn
2. make a meson.build 
3.  exec  meson  build . when will show:
        meson.build:1:0: ERROR: Failed to detect MSVC compiler target architecture: 'cl /?' output is
���� x64 �� Microsoft (R) C/C++ �Ż������� 19.16.27035 ��

**To Reproduce**
" cl /?"  output :   
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27035 版

there is a bug  in environment.py:

                cl_signature = lookat.split('\n')[0]
                match = re.search('.*(x86|x64|ARM|ARM64)$', cl_signature)
       
  This expression may fail in a non-english version.

**Expected behavior**
 match = re.search('.*(x86|x64|ARM|ARM64)', cl_signature)

**system parameters**

**Comment by lb90** [comment]
The thing here is that the arch string is not at the end of the line. On the other hand, we cannot just use

`re.search('.*(x86|x64|ARM|ARM64)')`

See here for the explanation why: https://github.com/mesonbuild/meson/commit/a107eab2949cf9750ed88a634118b31666c16c7a. In short, ARM64 could match with ARM.

To make it work we could either:

* Swap ARM with ARM64 in the RE definition: `re.search('.*(x86|x64|ARM64|ARM)')` so that ARM64 is searched before ARM. While this seems to work I would not rely on that
* Look for a following space char (' ') or end of line ('$'): `re.search('.*(x86|x64|ARM|ARM64)( .*|$)')`.

**Comment by scholarzry** [comment]
I tested this expression in V2017.It works correctly
