### ISSUE TITLE
[RFC]migrate to curly bracket syntax

### ISSUE THREAD

**Issue by pynixwang** [mesonbuild/meson#6950]
```
if (x) {
  xxx
} elif (y) {
  yyy
} else {
  zzz
}

foreach(item: collection) {
   balabala
}
```

`endif`  `endforeach` is very ugly

**Comment by xclaesse** [comment]
This is not going to happen without stronger arguments than "very ugly" which is entirely a personal taste. Are there parser issues that cannot be solved?

**Comment by xclaesse** [comment]
btw, I think the point of not using {} is to emphasis that Meson does not have variable scope, unlike C-like languages.

```meson
if cond
  x = 1
endif
# x can be used here
```

**Comment by pynixwang** [comment]
@xclaesse 
I try to change the parser, it works, just current syntax "ugly"
{} not stands for scope.

**Comment by pynixwang** [comment]
it 's personal taste, but we would better do it with "common" taste

**Comment by xclaesse** [comment]
There is no such thing as common taste, we are humans we all kind of preferences. Let's be honest you are like 10 years too late to change such fundamental syntax decision, I'm sorry but this is not going to change without stronger arguments.

**Comment by lhmouse** [comment]
One reason to prefer curly braces is that many editors have a feature called 'go to matching bracket' which doesn't work with `endif`, `endforeach` etc.

And for meson it is not necessary to have scopes just because of curly braces. NGINX also has `if` etc. in its configuration files without scopes, either.

**Comment by dcbaker** [comment]
Some editors can match opening `if` with it's subordinate `elif` and `endif`, vscode does this, for example.

At this point adding curly braces to Meson as an alternative to the `if/endif` and `foreach/endforeach` wouldn't bring value, and would go against one of Meson's main design goals: make it easy to understand.

Consider the following:
```meson
if foo
  ...
endif

if foo {
}
```
In the same file there is going to be an assumption that `if/endif` and `if {}` have different meanings, because in C/C++ `if (expr) staement` and `if (expr) { statement }` do have different meanings, they change scope.

I'm going to close this as not planned, because at this point there is no value added from adding curly brace syntax.
