### ISSUE TITLE
Consider TensorFlow as a dependency object

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#7023]
How likely would it be to have Meson build automatically find `tensorflow` for cloud based applications that require the use of AI?

Repo for [TensorFlow](https://github.com/tensorflow/tensorflow)

**Comment by eli-schwartz** [comment]
Tensorflow provides these two pkg-config files on Arch Linux: tensorflow.pc tensorflow_cc.pc. So you should be able to use `dependency('tensorflow')` without issue.

What situation are you in where this does not work? Most of https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality are things which use some sort of `foo-config` file, or are otherwise not using pkg-config, or not always available via pkg-config. Are you asking for a custom lookup function for tensorflow for systems where tensorflow.pc doesn't exist? Which systems?

**Comment by michaelbadcrumble** [comment]
I was hoping for a wrap definition in WrapDB.

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/Adding-new-projects-to-wrapdb.html#how-to-contribute-a-new-wrap

Anyone can contribute one. But the assumption is someone interested will do the adding.
