### ISSUE TITLE
If there is a table of cpu_family, there should also be a table of cpu.

### ISSUE THREAD

**Issue by zeerd** [mesonbuild/meson#7037]
Hi:

For the page:

https://mesonbuild.com/Reference-tables.html#cpu-families

At least, if there is a string for cpu item , there must be a way to know which the string is. For example , a command to read it from the target board ? Or I could find it from the datesheet of the cpu manual by some keypwords? Or I can get it by the cross-compiler?

**Comment by jpakkane** [comment]
As mentioned [in the documentation](https://mesonbuild.com/Cross-compilation.html#machine-entries), cpu values are highly operating system dependent. They can be pretty much anything, especially when doing embedded work. A CPU family like RISC-V or PIC can have tens or hundreds of different individual cpu names. Because of this having a list of values for cpu is not feasible. It should be considered a freeform string that specifies the cpu "in some way".

For native builds, the cpu string is queried from the system "somehow" (in practice using Python's stdlib for that). In cross builds you get to decide yourself what value to use based on what is important for your use case.

**Comment by zeerd** [comment]
Thank you for reply.

But I am still not clear what should I fill in this cpu item when I cross-compiling a 3rd-part open source software like gstreamer.

You means , I could fill it with anything? Means the build system not need this one actually? Or I need to ask the develepor of the 3rd-part software , ex. gstreamer for this?

**Comment by dcbaker** [comment]
Right, meson doesn't read the cpu value at all, it's just something that you can inspect in the meson script language.

**Comment by zeerd** [comment]
Thank you,.

But hope you can modify the document to make this concept more clear for a newbie to meson.

**Comment by rdiez** [comment]
I am writing a generator for the cross-compilation settings file, and I was wondering that this cpu=xxx was for.

I think it should be documented that this option is not used really used by Meson. I am grateful that this issue exists, otherwise I would had kept searching the Internet and the source code.
