### ISSUE TITLE
Generated headers cannot be installed directly

### ISSUE THREAD

**Issue by QuLogic** [mesonbuild/meson#705]
As noted on IRC, a header created by a generator cannot be installed using `install_headers`, nor does the `process` method take any options for designating an install location. It can only be installed via a custom script.

**Comment by nirbheek** [comment]
Related to #891 and #892

**Comment by martin-ejdestig** [comment]
install_headers() also does not work with files().

Should I file a separate issue for that or will fixing install_headers() for generated files also make it work with files() ?

**Comment by martin-ejdestig** [comment]
Same thing with a header generated with configure_file(). install_headers() complains that arguments must be strings.

I know about install_dir to configure_file() but the use case I have in mind is this:

# meson.build in include/foo.... public headers
# files() since we are in a subdir... and configure_file() in subdir since output cannot contain path.
foo_public_headers = files(['a.h', 'b.h']) + configure_file(...)

install_headers(foo_public_headers, ...)

#meson.build in src/
foo_sources = foo_public_headers + ['a.cpp', 'b.cpp', 'c.cpp', 'c.h']

**Comment by nirbheek** [comment]
For `configure_file` you should be using the `install_dir:` keyword argument to install the generated header. This is only about `generator` targets.

**Comment by martin-ejdestig** [comment]
As I wrote above, I know `install_dir` _can_ be used for `configure_file()`. But compare this:
```
config_h = configure_file(input : 'config.h.in',
                          output : 'config.h',
                          configuration : config_h_conf,
                          install_dir : get_option('includedir') + '/' + 'foo')

public_headers = ['bar.h', 'baz.h']
sources = ['event.cpp']
sources += public_headers

lib = library('foo', sources : sources + [config_h], ...)

install_headers(public_headers, subdir : 'foo')
```

To this:
```
config_h = configure_file(input : 'config.h.in',
                          output : 'config.h',
                          configuration : config_h_conf)

public_headers = ['bar.h', 'baz.h', config_h]
sources = ['event.cpp']
sources += public_headers

lib = library('foo', sources : sources, ...)

install_headers(public_headers, subdir : 'foo')
```

- No need to call get_option('includedir').
- No need to repeat subdir headers should be installed to (or have a variable for it)
- config_h really is a public header so it makes sense to have it in public_headers

If one has say <project root>/include/foo/ where all public headers are located and <project root>/src where the rest of the source is it gets a bit more complicated since `configure_file()` must be called from a meson.build in <project root>/include/foo/ (relative paths are not allowed). If I want to "export" public_headers from <project root>/include/foo/meson.build I have to play around with a temporary list to be able to use install_headers() and then convert it to a list of `files` to append the result of `configure_file()`. Has to be file objects since I use public_headers in e.g. <project root>/meson.build or <project root>/src/meson.build.

And as I wrote in my first comment, I can create a separate issue if this won't be solved here. :)

**Comment by TingPing** [comment]
@martin-ejdestig Just a few notes: You don't need to include config_h in sources and you don't need to include other headers in sources. That eliminates some noise.

**Comment by nirbheek** [comment]
Sorry, I misread your comment. We plan to make it so that `install_data` can install secondary outputs of targets while the primary one is still installed with the `install_dir` kwarg, but things will not change for `configure_file` unless @jpakkane decides this is a good idea.

Btw, `config.h` should never be installed. It is not a public header. It is meant to be used only during compilation.

**Comment by martin-ejdestig** [comment]
@TingPing Really? I thought it was needed to make sure it was generated before it is used. Please correct me on this if I am wrong. (I have a vague memory about reading about this in the wiki but cannot find it now.)

@nirbheek Using config.h in my example was perhaps a bad choice since it is so coupled with autoconf/make-foo. But just pretend it is named something else. :) (I use a header with a #mesondefine for telling whether a library is shared or static and then do something like https://gcc.gnu.org/wiki/Visibility in it to get FOO_PUBLIC/PRIVATE defines.)

**Comment by martin-ejdestig** [comment]
@TingPing Also, does Meson not have the same problem that CMake does if headers are left out and a backend like VisualStudio is used? (Headers are not shown in IDE.)

**Comment by martin-ejdestig** [comment]
@nirbheek Do I understand you correctly that the plan is to not make install_headers() be able to install generated files? I have a bit of trouble understanding this part:

> We plan to make it so that install_data can install secondary outputs of targets while the primary one is still installed with the install_dir kwarg

**Comment by nirbheek** [comment]
> Do I understand you correctly that the plan is to not make install_headers() be able to install generated files?

As of right now, yes, that is the plan.

**Comment by TingPing** [comment]
> @TingPing Really? I thought it was needed to make sure it was generated before it is used. Please correct me on this if I am wrong. (I have a vague memory about reading about this in the wiki but cannot find it now.)

Files generated with a `custom_target()` or `generator` must be. Files generated with `configure_file()` happen at configure time (`meson`) and must always exist by time you build.

> @TingPing Also, does Meson not have the same problem that CMake does if headers are left out and a backend like VisualStudio is used? (Headers are not shown in IDE.)

Sorry I haven't used the VS backend personally.

**Comment by martin-ejdestig** [comment]
@nirbheek OK, good to know. Thanks.

**Comment by ssssam** [comment]
I've hit this issue trying to install a generated Vala header.
