### ISSUE TITLE
executable() defaults to build_by_default:true even if install:false

### ISSUE THREAD

**Issue by keszybz** [mesonbuild/meson#7106]
I'm not sure if that is intentional. For `custom_target`, the dependency between `build_by_default` and `install` is explicitly documented: "If `build_by_default` is not set, `install` will still determine its default.". For `executable`, the documentation only says: "the default value is true for all built target types", which contradicts the docs for `custom_target`. Please make `build_like_default` behave everywhere like documented for `custom_target`, i.e. default to `install`.

Obviously, I don't want to build things which are not used for anything. Right now, it is necessary to do ugly duplication of conditions:
```python
enable_foo = ...;
executable('foo',
   ...
   build_by_default : enable_foo,
   install : enable_foo)
```

**Comment by keszybz** [comment]
meson-0.54.0-1.fc32.noarch

**Comment by jpakkane** [comment]
This behaviour is the expected one. Arguably we should have made custom targets build by default as well for consistency but "it seemed like a good idea at the time"(tm) not to do that. Making executables default to not building by default is not nice, because many projects build a lot of debug and helper tools that are useful and needed during development but won't get installed.

Changing these defaults is a bit iffy, because they will lead to project build breakages and complaints. We should not do them without a really good reason.

**Comment by keszybz** [comment]
OK. Let's close this then.
