### ISSUE TITLE
No way to disable special dependency lookups, such as 'sdl2'

### ISSUE THREAD

**Issue by tliron** [mesonbuild/meson#711]
This is hardcoded, and it uses sdl2-config first. But what if I want to use my custom build of sdl2 and not the system's? There should be a way to disable these special dependency classes.

**Comment by jpakkane** [comment]
If you want to build your own SDL, the recommended way is to use a subproject [(possibly from wrapdb)](https://wrapdb.mesonbuild.com/). The other standard option is to set `PATH` and/or `PKG_CONFIG_PATH` so that your version of the deps is picked up before the system's.

**Comment by tliron** [comment]
The second option you suggest will not work. [The code looks for sdl2-config first.](https://github.com/mesonbuild/meson/blob/master/mesonbuild/dependencies.py#L1052)

I find the idea of hardcoding things like this odd. Why not let users install their own special dependency classes, or at least let them disable them? This leads to unexpected behavior, and indeed it was not easy for me to find out what was going wrong.

The first option you suggest is also not right for me, because I am already building SDL using a different build system.

Generally I find it hard to just add an existing ".so" file to Meson.

**Comment by jpakkane** [comment]
> Why not let users install their own special dependency classes, or at least let them disable them?

Because while that works fine for a single project with a single dependency, it does not scale. When you have tens of subprojects all with "just a little" of their special magic, things fail hard.

We can not support every possible way of providing dependencies, because we require things to be reliable. Thus we focus on the two ways that are reliable: "external" dependencies that provide info via pkg-config/sdl2-config/etc and "internal" dependencies that are built as subprojects.

> The first option you suggest is also not right for me, because I am already building SDL using a different build system.

This is totally fine, but then that build system should then generate pkg-config files as well as a working sdl2-config. If it does not then the dependency user needs to resort to guessing and that is not reliable.

> Generally I find it hard to just add an existing ".so" file to Meson.

That is because "just adding an .so file" is almost never enough. You need headers, possibly linker flags and the like. In many build systems you can just throw in libraries, but that usually breaks apart in interesting ways later.

**Comment by tliron** [comment]
I _am_ supplying a pkgconfig file, but Meson is ignore it because it's preferring `sdl2-config`. _That_ is non-standard behavior. And it's mysterious, too, because without delving into the Meson code I would have never have found it.

Your answers make it clear to me that Meson's philosophy is incompatible with what we want from a build system. A build system that second guesses us and introduces its own built-in solutions--and refuses to let us disable them--is dangerous. As you said, things "break apart in interesting ways" when this happens. If we can't have determinism in my build system then we're in big trouble.

We are switching our projects to [Craftr](https://github.com/craftr-build/), which shares Meson's philosophy in some ways but does not dictate the end result.

**Comment by nirbheek** [comment]
There is really no perfect solution here. The best solution is probably always preferring pkg-config files over `sdl2-config` because a custom pkg-config file can be written by a user with a custom environment, but writing an `sdl2-config` script is comparatively onerous.

**Comment by tliron** [comment]
OK, it seems that you agree that this it is a bug, but I hope you also understand that your approach would be problematic for some users. As it stands, Meson is too opinionated for some of us.

**Comment by nirbheek** [comment]
If @jpakkane didn't think there was an issue to be solved here, this issue wouldn't still be open. ;)

fwiw, if you want to "just add an so" and want to handle includes/linker flags/etc yourself, you want to look at [`cc.find_library`](https://github.com/mesonbuild/meson/wiki/Reference-manual#compiler-object).

We could do with better documentation, but generally in my experience people find that they can do everything they need to with Meson (minus bugs).

**Comment by tliron** [comment]
I wrestled with find_library and it did not work for me. In any case, I didn't understand why I needed to hack around this: my SDL is a standard build with a standard pkgconfig file.

But my problem is that you still insist that there should be hardcoded special handling for some libraries, and that it should not be disablable. If there's special handing available, that's terrific for some users. But it should be optional.

I'm glad your experience has been good with others, but I hope you listen to my criticism.

**Comment by jpakkane** [comment]
There are two clear things we could do better here.

1. better logging of where dependencies come from
2. consider whether pkg-config should have priority over sdl2-config

Originally sdl2-config was given preference because it was deemed to be "more specific". Perhaps that is not the case after all.

**Comment by tliron** [comment]
3. consider whether to disable (or better yet: opt-in) to automagickal handling of certain hardcoded dependency names

**Comment by jpakkane** [comment]
It turns out that we already print when `sdl2-config` is used. Also the `pkg-config` based checker was actually broken. Fixing.

**Comment by nirbheek** [comment]
Thinking about this more, I think it makes sense to add a mechanism (a kwarg to `dependency()`, perhaps) to disable automatic dependency checking via `sdl2-config`, `qmake-qt5`, etc and force it to only use pkg-config.

This would be particularly important when cross-compiling when you want Meson to error out if the pkg-config file is not found (because of a misconfiguration) and not inadvertantly find the system `sdl2-config` and link to the system libraries.

I'm just wondering what the best way would be. Not all `dependency()` types have a pkg-config "mode" (example: `GNUStep`, `GTest`, `WxWidgets`, etc).

**Comment by jpakkane** [comment]
Seems useful. We could start with a kwarg `method` with values `auto` and `pkgconfig`. We can then add other types if and when a need arises (I'm guessing that will never actually happen but you never know).

**Comment by tliron** [comment]
Let it not be said that I only complain. :) In case you're interested, I started working on a new build system, [Rōnin](https://github.com/tliron/ronin) (Apache licensed), that starts from a very different philosophy from Meson's.

I'm grateful for Craftr and Meson for inspiring to me to look for Python frontends to Ninja, even if I ended up taking a different path.
