### ISSUE TITLE
Support source altering tasks

### ISSUE THREAD

**Issue by ebraminio** [mesonbuild/meson#7156]
https://mesonbuild.com/Run-targets.html gives a basic example of why custom task to alter sources may is needed. I am going to extend that a bit, assume one wants to run formatter on the source everytime any of the files are changed, very similar to what IDEs do for example in golang community using `go fmt`, how one can specify a formatter task to run only when some file in the tree is changed? Apparently a `build_by_default` custom target is nearest thing meson provides for it ATM but it isn't that smooth, it can't become dependent to source file change for running tasks, and, (makes more sense in our need) apparently ninja is doing recompile needed units analysis (detecting which files needs to be recompiled) before the `build_by_default` task run thus misses those are changed.

Our issue however is really this one, https://github.com/harfbuzz/harfbuzz/pull/2357 which in short is having some tasks able to modify source files so we can put the generated files also in the tree. The real reason behind this is to make Chromium be able to embed our source easier as we can't enforce our build system there so we should put our generated files in the tree so they can use our sources without our build system. 

Using the approach, a build by default custom target, https://github.com/harfbuzz/harfbuzz/pull/2357/files#diff-9fbb37ad64805c2da3889d419806cd51R297 we can achieve most of this, but if `build_by_default` custom target could become dependent to some source file change, and if meson does the change checking after that task not before it, we can have source altering tasks the similar way we do even with our out-of-tree autotools.

And, I know there is a reason that you aren't that in favor of this, still, somehow is a blocker for us which we may are able to resolve our issue in some not supported way.

**Comment by jpakkane** [comment]
> I am going extend that a bit, assume one wants to run formatter on the source everytime it is changed, very similar to what IDEs do for example in golang community using go fmt, how one can specify a formatter task to run only when some file in the tree is changed

An alternative approach is to not do this at all, but instead have a Git commit hook that runs the formatter before committing. This way you can set it up once and it is guaranteed to work for every commit

> The real reason behind this is to make Chromium be able to embed our source easier as we can't enforce our build system there so we should put our generated files in the tree so they can use our sources without our build system.

I strongly support people's right to rewrite the build systems of projects they use to suit their personal needs. If Google wants to rewrite the build system, all the more power to them. In fact they are probably already doing it at least three times, once for Blaze, once for GN and once for Android. Nothing wrong with that. However what is _not_ cool is then increasing the maintenance burden of upstreams with the idiosyncrasies of their custom solutions. This is why we can't have nice things.

That being said, if you only want to get the generated source file in your source tree, there is a simpler way. Add a command line argument to your script that can be used to write a second copy in the source tree. Something like this (with the corresponding changes for the script):

```meson
custom_target('harfbuzz.cc',
  build_by_default: true,
  output: 'harfbuzz.cc',
  command: [find_program('gen-harfbuzzcc.py'),
            '@OUTPUT@',
            '@CURRENT_SOURCE_DIR@',
            <other changes here, see below>)
```

This should get you what you want while keeping the "unsafe" thing isolated in one place inside this script. Note that this should write the both to the build dir (it is needed for dependency tracking to work properly) and source dir.

Also, you should define all your source file arrays with `files()` instead of using string arrays. Like this:

```meson
hb_base_sources = files(
  'hb-aat-fdsc-table.hh',
  ...
  'hb-aat-layout.cc',
  ...
)
```

This will make Meson do dependency tracking properly, so all dependencies are rebuilt when source files change. It will also take care of expanding the file names automatically even when used in other subdirectories. You also don't need to add header files in the source lists. Meson only cares about actual sources. The recommended form would be something like:

```meson
hb_base_sources = files(...)
custom_target('harfbuzz.cc',
  build_by_default: true,
  output: 'harfbuzz.cc',
  input: [hb_base_sources, ...],
  command: [find_program('gen-harfbuzzcc.py'),
            '@OUTPUT@',
            '@CURRENT_SOURCE_DIR@',
            '@INPUT@'])
```

**Comment by eli-schwartz** [comment]
Is the problem here solely about release tags? Because I don't think it actually matters what build system an external consumer uses. There's a general possibility that a project might want to provide pregenerated resources, such as discussed in #2166.

In my case, it's asciidoc manpage sources compiled to troff. In the original case of the referenced issue, it was gtk-doc HTML files. In your case, it's ragel sources producing generated C.

This is all stuff you don't want to check into git, but you'd often like to save thirdparty consumers the inconvenience of installing special tools and running portions of the build simply to create output that never changes.

In autotools, you'd simply add them as EXTRA_DIST files, and their versions in-tree would be sufficient to build the software without trying to newly build them.

In meson, it's unclear how to properly dist these files, or detect that they exist and use them instead of generating them.

**Comment by ebraminio** [comment]
Glad you asked Eli, it isn't just about releases as they like to use our not released version also specially as there are not stable undergoing project in HarfBuzz that Chromium is its main user, for example with a change like [this](https://chromium-review.googlesource.com/c/chromium/src/+/2183951) they will get a revision on Chromium as this [in their build configuration](https://source.chromium.org/chromium/chromium/src/+/master:third_party/harfbuzz-ng/BUILD.gn) it is hard to enforce them to build things needed for build like hardly changed state machines should be built from ragel and hb-version.h that is generated from hb-version.h.in. Also we provide an amalgam convenience facility, called harfbuzz.cc, makes build of harfbuzz from git without any build system and one can use harfbuzz with it without any build system, for example `cd $(mktemp -d) && git clone https://github.com/harfbuzz/harfbuzz --depth=1 && cd harfbuzz && time clang -c src/harfbuzz.cc -DHB_NO_MT` is all one needs to build harfbuzz.

**Comment by ebraminio** [comment]
> Note that this should write the both to the build dir (it is needed for dependency tracking to work properly) and source dir.

This is a key point I missed the previous time I tried this, now makes sense, thank you very much!

> Also, you should define all your source file arrays with files() instead of using string arrays. Like this:

Thanks! Will apply this while trying the other tip also, it now just makes more sense.

Closing this at least for now. Thanks!
