### ISSUE TITLE
Failed to detect multilib when using clang

### ISSUE THREAD

**Issue by 12101111** [mesonbuild/meson#7169]
**Describe the bug**
When using `CC=clang -m32` on x86_64 system, the "Host machine cpu family" is "x86_64". It should be "x86"

This break building of mesa on Gentoo with clang: https://bugs.gentoo.org/723224

Related: https://github.com/mesonbuild/meson/issues/6361
**To Reproduce**
```output
❯ mkdir meson_clang_test
❯ cd meson_clang_test
❯ meson init
Using "meson_clang_test" (name of current directory) as project name.
Using "meson_clang_test" (project name) as name of executable to build.
Defaulting to generating a C language project.
Sample project created. To build it run the
following commands:

meson builddir
ninja -C builddir

❯ export CC="gcc -m32"
❯ meson gccbuild
The Meson build system
Version: 0.54.1
Source dir: /tmp/meson_clang_test
Build dir: /tmp/meson_clang_test/gccbuild
Build type: native build
Project name: meson_clang_test
Project version: 0.1
Using 'CC' from environment with value: 'gcc -m32'
Using 'CC' from environment with value: 'gcc -m32'
C compiler for the host machine: gcc -m32 (gcc 9.3.0 "gcc (Gentoo 9.3.0 p2) 9.3.0")
C linker for the host machine: gcc -m32 ld.lld 10.0.0
Host machine cpu family: x86
Host machine cpu: i686
Build targets in project: 1

Found ninja-1.10.0 at /usr/bin/ninja
❯ export CC="clang -m32"
❯ meson clangbuild
The Meson build system
Version: 0.54.1
Source dir: /tmp/meson_clang_test
Build dir: /tmp/meson_clang_test/clangbuild
Build type: native build
Project name: meson_clang_test
Project version: 0.1
Using 'CC' from environment with value: 'clang -m32'
Using 'CC' from environment with value: 'clang -m32'
C compiler for the host machine: clang -m32 (clang 10.0.0 "clang version 10.0.0 ")
C linker for the host machine: clang -m32 ld.lld 10.0.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.0 at /usr/bin/ninja
```
**Expected behavior**
Meson should detect ABI correctly:
```
Host machine cpu family: x86
Host machine cpu: i686
```

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? :native build
* what operating system: Gentoo
* what Python version are you using: 3.7.7
* what `meson --version`: 0.54.1
* what `ninja --version` if it's a Ninja build: 1.10.0

**Comment by dcbaker** [comment]
This is not a bug, this is meson working as expected. Just because you passed `-m32` to clang doesn't mean that your build machine suddenly turned into a pentium II. It's till an x86_64 machine, running an x86_64 kernel and user land. We do that detection based on uname.

What you are actually doing is a cross build, where the build machine (x86_64) happens to be able to natively run the cross binaries (x86) even though that isn't always the case. You're going to run into other issues, the pkg-config meson finds will be wrong, it's going to find the one pointing to lib64, not lib. You really do want to run x86_64 -> x86 as a cross compile, even though in autotools you could make it work treating as a build == host compile. I'm not on my gentoo machine right now, but I can post my x86_64 -> x86 cross files if that's useful to you.

**Comment by 12101111** [comment]
> We do that detection based on uname.

This doesn't explain the different behaviors of meson when using gcc or clang.

And Portage don't treat this situation as cross build but native build. 

The logic is here: https://github.com/gentoo/gentoo/blob/master/eclass/meson.eclass#L291

**Comment by mattst88** [comment]
Downstream bug: https://bugs.gentoo.org/723224

**Comment by Arfrever** [comment]
I have verified that commit 9dc3ca2c1c9fbb47e731551c6432df144f725261 (#7182) fixes this problem.

**Comment by floppym** [comment]
> And Portage don't treat this situation as cross build but native build.

We used to do a cross build, but that was changed due to a regression in meson. (https://github.com/mesonbuild/meson/issues/7041)

I guess I'll revisit this. As an enhancement, I would like to actually wire up the `[build_machine]` section we define in the native machine file. This would let us override the (possibly broken) autodetection of these values by meson.

https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/meson.eclass?id=67e30f402666ef2bd3d55174bac0754a29e93f32#n251

**Comment by dcbaker** [comment]
@floppym, @mattst88 mentioned that gentoo has problems running the meson test suite and quit running it. What needs to happen to fix that?

**Comment by floppym** [comment]
@dcbaker There are a few tests that are currently erroring, probably due to quirks in Gentoo's build environment. I would need to take the time to run the tests and triage the errors.

We tend to see new errors of this nature with every major meson release, and it gets a bit tiresome to go through the process every time.

**Comment by mattst88** [comment]
The other part I remember @floppym mentioning was that there were some tests that ran only if certain packages were installed on the system, which made comparing test results difficult.
