### ISSUE TITLE
command 'meson' not found

### ISSUE THREAD

**Issue by wpmanoj** [mesonbuild/meson#7209]
**Describe the bug**
installed with `pip3 install --user meson`
now i get Command 'meson' not found

**system**
Ubuntu 18.04 Google Cloud platform

i'm working as 'root'. Any help to Solve this issue.

**Comment by michaelbadcrumble** [comment]
I think this may help, mostly the part that explains what happens when you
add `--user` to the Python package manager install command and how to fix
that.

https://github.com/michaelbadcrumble/mesonbuild_tips/blob/master/notebook/001-readme.md

**Comment by wpmanoj** [comment]
i resolve with uninstall with pip package and reinstall without --user

`pip3 uninstall meson
pip3 install meson`

now respond to meson --version

**Comment by ranjithmkumar1992** [comment]
I am still facing this issue

**Comment by eli-schwartz** [comment]
The issue is user error. Do not use `pip install --user` if you expect meson to be invoked as root.

If you think that your issue is still not resolved, then your issue must not be the same as the original reporter.

Therefore you must ***tell*** us what your issue is. Currently we know precisely nothing about how you installed meson, therefore it is impossible to provide any help until you do.
