### ISSUE TITLE
Want --wrap-mode=forcefallback:glib,foo,bar

### ISSUE THREAD

**Issue by tp-m** [mesonbuild/meson#7218]
**Describe the bug**
Currently there is `--wrap-mode=forcefallback` but this will then apply to *all* possible fallback subprojects.

Often what people want is to only force certain fallbacks, like e.g. force to use the included glib or ffmpeg subproject but not any others.

**To Reproduce**
Can be reproduced by building [gst-build](https://gitlab.freedesktop.org/gstreamer/gst-build) with `meson --wrap-mode=force-fallback:glib` while a recent glib plus development headers are installed.

**Expected behavior**
With `meson --wrap-mode=force-fallback:glib` I would expect the build to use the glib subproject instead of the system-installed glib.

**Comment by tp-m** [comment]
**For bonus points**
Perhaps also allow `--force-fallback=glib,-openh264` to force `glib` but disallow fallbacks to be used for `openh264`

**Comment by xclaesse** [comment]
I totally agree it would be nice to have a per-subproject setting here.

I'm not really a big fan of adding complex syntax for --wrap-mode command line, just throwing ideas, what about splitting those options: `--force-fallback=glib --no-fallback=openh264` ? Seems more explicit to me.

**Comment by tp-m** [comment]
I agree, that seems much nicer!

Would you allow passing a comma-separated list like `--force-fallback=glib,libffi` ?

**Comment by xclaesse** [comment]
> Would you allow passing a comma-separated list like `--force-fallback=glib,libffi` ?

Yes that's the idea, we already have support for list options.

**Comment by MathieuDuponchelle** [comment]
@xavierclaessens , good thing you prefer a separate option because adding this to `wrap-mode` would actually have been quite a pain: meson registers wrap-mode with argparse as an argument with a fixed set of choices, I don't think it would have been possible to teach argparse to accept `forcefallback:foo,bar` as one of the choices.

I've named the option `--force-fallback-for=`, I like it a bit better than `--force-fallback`. Regarding `no-fallback` / `no-fallback-for`, it shouldn't be too difficult to implement either, but to do things right one will also probably want to perform some validation at command line parsing time, in order to make sure the same dependency isn't listed both as `no-fallback` and `force-fallback`, which would be ambiguous.

One could also not error out and instead just add / remove from one list and to the other as options are parsed (like `-W` / `-Wno` options are parsed by compilers), but I don't know how much access we have to that information at the meson level.
