### ISSUE TITLE
armclang is not detected for native aarch64 builds

### ISSUE THREAD

**Issue by andreipoe** [mesonbuild/meson#7255]
On an aarch64 host, the Arm Compiler for Linux (`armclang`) is not detected correctly:

```
> CXX=armclang++ meson build-arm
The Meson build system
Version: 0.54.2
...
Build type: native build
Using 'PKG_CONFIG_PATH' from environment with value: '...'
...
Using 'CXX' from environment with value: 'armclang++'

meson.build:1:0: ERROR: Unknown compiler(s): [['armclang++']]
```

As far as I can tell, [the Arm Compiler isn't enabled for native builds](https://github.com/mesonbuild/meson/blob/f6b0425576640e1613f64503951c7c604b868947/mesonbuild/compilers/mixins/arm.py#L132). Since, from a user-facing perspective, `armclang` behaves virtually identically to upstream `clang`, it should be easy to reuse all the defaults.

**Comment by dcbaker** [comment]
If the compiler runs on an aarc64 host that code is wrong and should be changed. You'll probably also have to add a bit of code to the environemnt.py for finding the arm linker and armclang based on their output, but it shouldn't be too much work.

**Comment by rgmiller** [comment]
I wanted to add to this discussion because I've just run into this same issue.

There are (at least) 2 different compilers who's executables are named 'armclang'.  It looks to me like Meson is attempting to support the compiler from Keil (http://www2.keil.com/mdk5/compiler/6).  However, there is another compiler produced by ARM themselves:  https://developer.arm.com/tools-and-software/server-and-hpc/compile/arm-compiler-for-linux.  This compiler is, in fact, a native AArch64 compiler.

I suspect what is really needed is a new class in compilers/mixins/arm.py  - maybe something like"ArmCompilerForLinux".  And while we're at it, rename the 'ArmclangCompiler' class to 'ArmKeilCompiler' or something like that?

**Comment by dcbaker** [comment]
Whatever way you want to paint the bikeshed :)

I'd be happy to review patches.
