### ISSUE TITLE
meson setup --wipe fails if build tree is not valid

### ISSUE THREAD

**Issue by falk-werner** [mesonbuild/meson#7261]
I observed that `meson setup --wipe` fails. if the build directory does not contain a valid build tree: 

````
> rm -rf buildir
> meson setup --wipe builddir
...
Directory does not contain a valid build tree
````

I wonder, if this is correct, since the purpose of `--wipe` is to start a clean build which is true when builddir is empty or non-existing.

**Comment by scivision** [comment]
This [--wipe logic](https://github.com/mesonbuild/meson/blame/c5d2299caca3f3ca9b8e568c6b6045aed2f00124/mesonbuild/msetup.py#L149) seems to be similar to --reconfigure. Maybe it was to not allow users to needlessly --wipe. 

I can see a stronger reason for --reconfigure failing if a build directory is not configured.
For --wipe, it seems there could be an opinion to be less strict with --wipe, that is, to not fail on --wipe even if no build directory exists.

**Comment by simonrepp** [comment]
I too ran into this (in the context of a package build script) and found the behavior unexpected.

**Comment by adiatma85** [comment]
Same issue like @simonrepp

**Comment by thebombzen** [comment]
It sounds like sane behavior would be to default `meson setup foo --wipe` to just `meson setup foo` when the directory foo doesn't exist.

**Comment by xclaesse** [comment]
I did that as part of https://github.com/mesonbuild/meson/pull/11312. It is a bit more complicated because if we want to make --wipe work regardless of whether the builddir exists or not, we also need to take into account --cross-file and verify we don't change its value. Currently --wipe --cross-file ignore the new value you passed in --cross-file, with my PR it will raise error if the value changed.

**Comment by falk-werner** [comment]
I checked the behavior with meson v1.1.1. The issue seems to be solved. Thanks a lot!
