### ISSUE TITLE
Wrong default name of wrap directory?

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#7330]
Manual says:

_Accepted configuration properties for wraps_
* _directory - name of the subproject root directory, defaults to the name of the wrap._

"name of the wrap" is it name of wrap file, yes?

But if I try to use wrap file `freertos.wrap`:
```
[wrap-file]
source_url = https://github.com/FreeRTOS/FreeRTOS-Kernel/archive/V10.3.1-kernel-only.zip
source_filename = V10.3.1-kernel-only.zip
source_hash = 887507aa5fb3c37bea6f3bf441c74c49b40683506e81bd296007b280a49795ed
```

It creates directory `subprojects/FreeRTOS-Kernel-10.3.1-kernel-only/`, not `subprojects/freertos`

* what `meson --version`
~master

**Comment by denizzzka** [comment]
addition: if I use `directory = freertos` it isn't leads to changing `FreeRTOS-Kernel-10.3.1-kernel-only` to `freertos`

`directory` wrap option is broken for `[wrap-file]`?

**Comment by xclaesse** [comment]
It is not to rename the directory created when extracting tarball, it is to tell meson what directory will be created.

**Comment by denizzzka** [comment]
> it is to tell meson what directory will be created.

But this directory isn't created.

It is created only if I add `lead_directory_missing = yes`

**Comment by denizzzka** [comment]
> It is not to rename the directory created when extracting tarball

By the way, that would be convenient: than patches would not have to be changed every time as issued new version of subproject what downloaded from the github by wrap-file.

**Comment by denizzzka** [comment]
Ok, not a bug.

And (for me) wrap-git solves this problem

**Comment by Rot127** [comment]
There is a scenario when this becomes a problem.

Meson currently doesn't allow subprojects to be compiled as `native` and `non-native` (see: https://github.com/mesonbuild/meson/issues/10947). Because of that, one has to have a copy of such a subproject for the cross build.

This works fine, if `wrap-git` is used, because it allows to clone the same project into different directories.
But `wrap-file` has no way to download/unpack the source file into different directories.
