### ISSUE TITLE
New choice in array option is ignored

### ISSUE THREAD

**Issue by pinchartl** [mesonbuild/meson#7386]
**Describe the bug**
When a new choice "newchoice" is added to an existing array option "foo", _meson configure_ will not list the new choice in the "Possible Values" column, and _meson -Dfoo=newchoice_ complains that "newchoice" is not valid.

`ERROR: Options "newchoice" are not in allowed choices: "oldchoice"`

**To Reproduce**
[choice.tar.gz](https://github.com/mesonbuild/meson/files/4839477/choice.tar.gz)

1. Run _meson build_
2. Edit meson_options.txt as follows:
```
-        choices : ['oldchoice'],
+        choices : ['oldchoice', 'newchoice'],
```
3. Run _meson configure build_. The "foo" option should report "newchoice" as a Possible Value.

**Expected behavior**
The new choice should be considered by meson as a possible value and accepted when modifying the option with -D.

**system parameters**
* Operating system: Gentoo Linux
* Python version: 3.7
* Meson version: 0.52.1 (tested the master branch as well)

**Comment by xclaesse** [comment]
You need to pass --reconfigure in that case.

**Comment by pinchartl** [comment]
I'm afraid running _meson --reconfigure_ in the build directory doesn't help (neither does _meson setup --reconfigure_).

**Comment by pinchartl** [comment]
The problem seems to be in CoreData.merge_user_options. The code handles the addition of options, as well as the modification of an option type, but not the modification of choices.

**Comment by kbingham** [comment]
Just to help for clarification, (or testing?) This is experienced when we add (or remove) support for a new pipeline in libcamera.

Currently available pipeline handlers are defined (and user selectable) by an option in meson_options.txt:
  https://git.linuxtv.org/libcamera.git/tree/meson_options.txt

```
option('pipelines',
        type : 'array',
        choices : ['ipu3', 'raspberrypi', 'rkisp1', 'simple', 'uvcvideo', 'vimc'],
        description : 'Select which pipeline handlers to include')
```

This option is later parsed under src/libcamera/pipeline/meson.build to determine which subdirs to include

https://git.linuxtv.org/libcamera.git/tree/src/libcamera/pipeline/meson.build:
```
foreach pipeline : get_option('pipelines')
    subdir(pipeline)
endforeach
```

And, I can confirm I also see the issue here that Laurent states above, that even running 'meson --reconfigure build' does not update the default options available from the choices array:
```
git diff
diff --git a/meson_options.txt b/meson_options.txt
index ea38f1553240..c51508e52f99 100644
--- a/meson_options.txt
+++ b/meson_options.txt
@@ -16,7 +16,7 @@ option('gstreamer',
 
 option('pipelines',
         type : 'array',
-        choices : ['ipu3', 'raspberrypi', 'rkisp1', 'simple', 'uvcvideo', 'vimc', 'vivid'],
+        choices : ['ipu3', 'raspberrypi', 'rkisp1', 'simple', 'uvcvideo', 'vimc', 'vivid', 'newsoc'],
         description : 'Select which pipeline handlers to include')
 
 option('qcam',
```

And the option can not be used, (either implicitly, or explicitly)
```
meson --reconfigure build -Ddocumentation=false -Dpipelines=newsoc
The Meson build system
Version: 0.54.3
Source dir: /home/libcamera/libcamera
Build dir: /home/libcamera/libcamera/build
Build type: native build

meson.build:3:0: ERROR: Options "newsoc" are not in allowed choices: "ipu3, raspberrypi, rkisp1, simple, uvcvideo, vimc, vivid"

A full log can be found at /home/libcamera/libcamera/build/meson-logs/meson-log.txt



```
