### ISSUE TITLE
Detect someway we are in --wrap-mode=nodownload

### ISSUE THREAD

**Issue by ebraminio** [mesonbuild/meson#7421]
In order to resolve https://github.com/harfbuzz/harfbuzz/issues/2551 is it possible to detect somehow `--wrap-mode=nodownload` is passed? Ideally I like to use that in https://github.com/harfbuzz/harfbuzz/blob/747f65f/meson.build#L351 with something like `and meson.is_able_to_download()`.

Understandable if is considered as invalid issue of course but that makes our default for build a bit tedious, we like to pass [`wrap_mode=nofallback`](https://github.com/harfbuzz/harfbuzz/blob/747f65f/meson.build#L6) as default option but like to get Google Benchmark for default uses also without passing [another option](https://github.com/harfbuzz/harfbuzz/pull/2548#issuecomment-654294240) ([here](https://github.com/harfbuzz/harfbuzz/blob/95b1081/perf/meson.build#L1) is its code) but like to support `--wrap-mode=nodownload` to not need for `-Dbenchmark=disabled`, contradicting needs maybe of course.

**Comment by tp-m** [comment]
```meson
if get_option('wrap_mode') == 'nodownload'
  ..
endif
```

should work?

**Comment by ebraminio** [comment]
Nice, thank you very much :)

**Comment by kusma** [comment]
Just wanted to chime in here...

Since there's also `nofallback`, which implies `nodownload` , I guess a project would have to check for both, no?

And then with options like `force-fallback-for`, seems like meson scripts might have to start parsing the option in order to figure out if the settings affects a given dependency... It really seems like some meson API for figuring this out would be good in the long run...

**Comment by eli-schwartz** [comment]
I think I'd like to know a bit more about how that would be used -- and why the built-in handling doesn't suffice.

**Comment by kusma** [comment]
> I think I'd like to know a bit more about how that would be used -- and why the built-in handling doesn't suffice.

In [my case](https://gitlab.freedesktop.org/mesa/demos/-/merge_requests/139/diffs?commit_id=70d7e7832bfcb3924d477497c9ac5a2010689bd4), I'm using the CMake module's `subproject()` function in order to wrap freeglut. But that function throws an error if the user has set the wrap-mode to `nodownload` or `nofallback`. I would like to gracefully fail to provide the dependency in that case instead.

**Comment by xclaesse** [comment]
With https://github.com/mesonbuild/meson/pull/11730 you should be able to do `dependency('freeglut', required: false, allow_fallback: true)`.

**Comment by kusma** [comment]
That sure sounds nice, but mesa-demos is probably going to have to stay on older meson versions for quite a while.

But maybe it negates the need for more meson API here...

**Comment by kusma** [comment]
> With #11730 you should be able to do `dependency('freeglut', required: false, allow_fallback: true)`.

Actually, I'm not sure that would work for me... I still need to pass `-DFREEGLUT_LIB_PRAGMAS=0` to cmake... I *suppose* I could do that with a patch, but that's IMO rather ugly, and it *kinda* defeats the point of using a cmake-wrap if I need to modify the cmake build-system at the same time...

**Comment by xclaesse** [comment]
Looks like cmake module has undocumented `required` kwarg, so `cmake.subproject(..., required: false)` should work too.

**Comment by kusma** [comment]
Actually, it's not even undocumented; the `cmake.subproject` function is documented in terms of the differences to the normal `subproject`-function, and it's defined there. So I just didn't know where to look, which is a me-problem and not a meson-problem!

Thanks for pointing me in that direction, that's exactly what I was looking for!
