### ISSUE TITLE
`meson test` with a specific test should only build what is needed for the test

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/meson#7473]
it's an usual workflow of mine to fix something and retest to see if it's fixed (using a particular test), but i have 30 tests now and i need to wait for all of them to finish linking, when i already specified the test i want to run

I think meson should be smart here and only build what's needed for the test (or suite) i specified

**Comment by alex-tee** [comment]
this is actually not a big issue. I was linking a static lib to each test so it was taking a while. using `both_libraries()` when creating a library for my shared code and doing `.get_shared_lib()` for the tests and `.get_static_lib()` for my executable seems to work fine. tests link really fast now

**Comment by bonzini** [comment]
All the information that is needed here is already available in `TestSerialisation` for use by introspection, so it should not be hard to do.

**Comment by dcbaker** [comment]
I have an opened pr for this, there's just a couple of bugs I haven't worked out yet

**Comment by bonzini** [comment]
Is that #6511? It seems a bit different, in particular one is "what to build by default" and the other one is "what to rebuild" (you can rebuild more than needed and do it by default to make things safer, but the ergonomics are worse). For a large project I don't mind building tests by default, but I don't want `meson test --suite unit` to rebuild thousands of files while I haven't even gotten the unit tests to pass for example. 

My idea for this issue was to invoke ninja with the specific targets included in `depends` and test arguments).

**Comment by dcbaker** [comment]
I guess my pr gets half there, since it changes meson test to depend on a target that builds only the tests and their dependencies.
