### ISSUE TITLE
FortranCInterface equivalent 

### ISSUE THREAD

**Issue by jeandet** [mesonbuild/meson#7704]
While trying to port/wrap SAMRAI to meson I came across this https://cmake.org/cmake/help/v3.0/module/FortranCInterface.html which is used [here](https://github.com/LLNL/SAMRAI/blob/master/cmake/CMakeConfigureFile.cmake#L4). 
@scivision I'm not sure if this makes sense to have something like this in meson?

**Comment by scivision** [comment]
I have admittedly not used this CMake functionality. This issue could be avoided by just putting `bind(C)` after the `subroutine` or `function` they're calling from C (Fortran 2003). I don't think there's any current Fortran compiler that doesn't support Fortran 2003--for several years already.

I personally would far rather see Samrai use `bind(C)`, which would allow them to simply remove a bunch of 1980's Fortran <=> C workarounds. My personal opinion is adding FortranCInterface to Meson is perpetuating a 1980's problem to today, when this problem is trivially solved by Fortran 2003 standard.

**Comment by jeandet** [comment]
@scivision , thank you for your feedback, I was quite suspicious that we would/should need to do that. Since I'm not a Fortran dev, I'm always lost with such things.

**Comment by scivision** [comment]
I'm glad you asked because there are other projects I've contributed to in the past where I might ask them to try `bind(c)`. The audience is somewhat similar to samrai at least.
.
