### ISSUE TITLE
Feature Request: dist subprojects in separate tarballs

### ISSUE THREAD

**Issue by rilian-la-te** [mesonbuild/meson#7705]
Is this possible now?

**Comment by eli-schwartz** [comment]
What's the intended use case of this? Since subprojects are distinct projects on their own, you should be able to `cd` into them, configure them standalone, and run `meson dist` on them directly.

The parent project won't get any utility out of them, though, because separate tarballs would need to be manually sideloaded to be used. And the .wrap file might be pointing to a hosted tarball already.

**Comment by xclaesse** [comment]
Since 0.57 it is possible when the subprojects is in the same git repository: https://github.com/mesonbuild/meson/pull/7907

**Comment by eli-schwartz** [comment]
Aha, and that PR was 2 months after this ticket was filed.
