### ISSUE TITLE
How to add a subproject where the meson.build is NOT in the root directory

### ISSUE THREAD

**Issue by qwertzui11** [mesonbuild/meson#8015]
**Describe the bug**

I'd like to add a subproject by git, which has it's `meson.build` inside a directory called `build`

**To Reproduce**

I have a `subprojects` directory with a `wrap-git` file in it. It clones the project fine. however then fails with the error
```
meson.build ERROR: Subproject exists but has no meson.build file
```

The error is fine, is there a way to tell the wrap-file to look for the root meson.build in another directory (of that subproject). To me it seems enforced that a `meson.build` is on the root level of the subproject.
However real-world git projects often got multiple build systems. eg how about the projects structure:
-- /README.md
-- /native/meson.build
-- /web/package.json

One large git repo vs small repos.

The other argument is, that if meson.build is only a second-citizen in that projects, it may be in a subdirectory.

the argument [`directory`](https://mesonbuild.com/Wrap-dependency-system-manual.html) does not what i expected

**Environment**
- meson `0.56.0`
- Linux

Thanks for your time!

**Comment by eli-schwartz** [comment]
The usual way to do this is by creating a [wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) that overlays the meson.build into the correct location with updated paths that do the right thing.

> To me it seems enforced that a `meson.build` is on the root level of the subproject.

Correct...

> The other argument is, that if meson.build is only a second-citizen in that projects, it may be in a subdirectory.

Then one could use a wrap to make it work out of the box. But this isn't really a sensible method in general for deploying build systems into a project.

Yes, I've seen it several times for projects which officially build using Makefiles and put alternate build systems into a contrib directory. I don't really think this is a good idea or one to be encouraged.

**Comment by qwertzui11** [comment]
It makes me sad that there are projects out there with meson support, which one can't use because the main `meson.build` is in the wrong directory.

You enforce too much, there are good reasons to not put the `meson.build` in the git root directory. May I suggest a change on that matter? :smile: 

If this won't be done you may wanna close this issue.

**Comment by deepbluev7** [comment]
Having `meson.build` in the root directory makes it easy to find it, if you use the project as a subproject or wrap. Where would you look otherwise? Requiring it there makes tooling much less error prone and is a lot less surprising to the user, since random files don't suddenly get used, even if the user can't easily find them.

**Comment by jpakkane** [comment]
Also, if the file could be somewhere else, we'd need to add configuration options so people can tell where it is. Once you have that upstream can never move their `meson.build` to any other directory since it would break all people who use it as a subproject (as the path they have defined to have the top level `meson.build` is no longer there). That just adds complexity and adds new things that can break.
