### ISSUE TITLE
Allow path segments in custom_target output

### ISSUE THREAD

**Issue by rtbo** [mesonbuild/meson#8022]
D language expects a directory structure to find source files.
If we can't specify path segments for `custom_target` output, it is virtually useless for D code generation (unless I am missing something)

consider the following (non-working):
```meson
    window_wayland_xdg_shell = custom_target('xdg_shell.d',
        input: 'resources/xdg-shell.xml',
        output: 'gfx/window/wayland/xdg_shell.d', # Error on this line
        command: [
            dub, 'run', 'wayland:scanner', '--',
            '-m', 'gfx.window.wayland.xdg_shell',
            '-i', '@INPUT@', '-o', '@OUTPUT@',
        ],
    )
```
To use the generated module (with the module name I want), the module file MUST be accessible at`prefix/gfx/window/wayland/xdg_shell.d`

The following step is to get the actual prefix within the build tree to pass it to the compiler.

**Comment by eli-schwartz** [comment]
Meson currently requires you to invoke this from a meson.build located in prefix/gfx/window/wayland/meson.build

This is a design decision, so changing it probably requires stronger reasoning than "I didn't want to do that".

**Comment by rtbo** [comment]
I see. I did miss something :smile: 
For anyone having similar issue, I changed my source tree like this:
```sh
$ tree
.
├── meson.build
├── source
│   └── gfx
│       └── window
│           ├── ...
│           ├── wayland
│           │   ├── meson.build
│           │   ├── ...
│           │   └── xdg-shell.xml
```
and have moved the custom_target call to `source/gfx/window/wayland/meson.build`.
Next I call `subdir('source/gfx/window/wayland')` from the root and that's it!
Meson even put the right import path to the compiler (may be because I'm under source, but who cares?)
Meson rocks!

**Comment by Tamaranch** [comment]
I've just encountered this error too, and had to do some research and come across this issue to convince myself that I wasn't allowed to put path segments in `custom_target` output. It's not clear from [the documentation](https://mesonbuild.com/Reference-manual_functions.html#custom_target), and in fact the opposite seems to be implied by wording like "Since 0.60.0 the name argument is optional and defaults to the basename of the first output". Why talk about basename if outputs can't contain path separators? Perhaps the documentation needs to be clarified on this point.
