### ISSUE TITLE
Vala preprocessor documentation

### ISSUE THREAD

**Issue by JerryCasiano** [mesonbuild/meson#8040]
**Describe the bug**

Following the instructions at https://mesonbuild.com/Vala.html#working-with-the-vala-preprocessor does not work as described.

**To Reproduce**

Adding add_project_arguments('-DSOME_FLAG', language: 'c') did not set that symbol for vala code, it seems vala requires a space '-D SOME_FLAG' however if we use add_project_arguments('-D SOME_FLAG', language: 'c') that results in an error probably due to it being quoted.

add_project_arguments('-D', 'SOME_FLAG', language: 'vala') seems to work as expected

**Question**

Is the version that works reliable? By this I mean is it guaranteed that those arguments will be added in that order everytime?

Should I just update the docs and submit a pull request or this actually a bug?

**system parameters**

* Fedora 33
* Python 3.9.0
* Meson 0.55.3
* Ninja 1.10.1

**Comment by astavale** [comment]
The documentation conflates the C pre-processor and the Vala pre-parser.

`add_project_arguments('-DSOME_FLAG', language: 'c')` is for the C preprocessor, so when the C files are pre-processed FUSE_USE_VERSION is replaced with 26 in the example.

For the Vala pre-parser then `add_project_arguments('-D', 'SOME_FLAG', language: 'vala')` is good. The Vala pre-parser is far more limited than the C pre-processor. It simply excludes or includes the conditional block in the source file in the parser stage of the compilation. If the block is excluded then there is no output in the generated C file for that block. There is no symbol translation, e.g. replacing FUSE_USE_VERSION with 26 in Vala code is not wanted. The pre-parser is much simpler by design.

An update to the docs would be welcome.

**Comment by JerryCasiano** [comment]
> An update to the docs would be welcome.

Done  #8044 

Thanks for the quick response.
