### ISSUE TITLE
please don't ship files ending with a tab character

### ISSUE THREAD

**Issue by doko42** [mesonbuild/meson#8041]
It looks like test cases/common/122 llvm ir and assembly/meson.build in the 0.56.0 release is a file name ending in a tab. Would it be possible to avoid that for any file shipped?  I didn't check others, but it took me a while finding out how to patch that fie.

I didn't check for other files shipped like that.

**Comment by eli-schwartz** [comment]
I can't find either the filename you refer to, or any other.

```
$ wget https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz
[...]
2020-11-28 19:34:50 (2.82 MB/s) - ‘meson-0.56.0.tar.gz’ saved [1794974/1794974]
$ bsdtar -xf meson-0.56.0.tar.gz
$ cd meson-0.56.0
$ find . -name $'*\t*'
[nothing]
$ cd "test cases/common/122 llvm ir and assembly"
$ $ printf '<%s>\n' *
<main.c>
<main.cpp>
<meson.build>
<square-aarch64.S>
<square-arm.S>
<square.ll>
<square-x86_64.S>
<square-x86.S>
<symbol-underscore.h>
$ file $'meson.build\t'
meson.build	: cannot open `meson.build\011' (No such file or directory)
$ touch $'meson.build\t'
$ file $'meson.build\t'
meson.build	: empty
$ printf '<%s>\n' *
<main.c>
<main.cpp>
<meson.build>
<meson.build	>
<square-aarch64.S>
<square-arm.S>
<square.ll>
<square-x86_64.S>
<square-x86.S>
<symbol-underscore.h>
```

**Comment by jpakkane** [comment]
Not to mention it should fail, because we try to open the file by doing, roughly `subdir + '/meson.build'` and then opening that. If the file name had a tab at the end, it would not work.

**Comment by doko42** [comment]
ok, looks like this one is not valid. this seems to be an issue with diff and/or patch.  If a file name contains a space, then some tools terminate the file name with a tab character.  Other tools like quilt generate the file name enclosed with double quotes, however this then is not recognized by dpkg.  It's easy if you know it ...

**Comment by eli-schwartz** [comment]
Sounds like the issue is more due to whatever "quilt" is... anyway, my versions of both git diff/format-patch and coreutils `diff(1)` produce output with tab characters in the .diff/.patch

This .diff output complies with the POSIX required `diff -u` format, a fairly reasonable interchange I guess... the git diff format drops the timestamp info but retains the tab itself, presumably with the rationale that known tools will interpret this as "the timestamp is null" while field splitting.

If your "quilt" tool doesn't produce POSIX formatted diffs, it should probably consider itself responsible to ensure all utilities reading the output can interpret its nonstandard output anyway. And if it turns out to be unsuitable for producing output that is correctly interpreted by e.g. `patch(1)` or dpkg, then its use should be re-evaluated.
