### ISSUE TITLE
What is the `language` keyword argument of `dependency()` supposed to do?

### ISSUE THREAD

**Issue by astavale** [mesonbuild/meson#8042]
In a Vala project I was expecting `dependency('gtk-layer-shell', language: 'c')` to only look for the `pkg-config` file for the C compilation step and not do anything for the Vala step. Instead we got an error:

```
../meson.build:3:0: ERROR: gtk-layer-shell-0 dependency does not accept "language" keyword argument
```
This project isn't currently using a Vala VAPI file, but a GIR file and those don't follow the pkg-config file name conventions, so we need to add the GIR to the Vala compiler step separately. Using the C language option seemed a good way to make Meson only search for the pkg-config file at the C compiler step. The project issue is [here](https://github.com/wmww/gtk-layer-shell/issues/5#issuecomment-733021405) if more details are needed.

**Comment by jon-turney** [comment]
AFAIK, the `language:` keyword is only significant to specialized dependency detectors which can use this information (see in [1])

[1] https://mesonbuild.com/Dependencies.html#dependencies-with-custom-lookup-functionality

**Comment by RossComputerGuy** [comment]
Using `language: 'c'` with `method: `pkg-config`' doesn't work. I think the default action for `language` is to only pull the necessary stuff to import that library for the chosen language. In a project I am working on right now, I've got a mix of Vala code and C code. Unfortunately, there's a lot of C code which cannot be converted easily to Vala due to depending on things such as egl from libglvnd and libdrm. `meson.get_compiler('c').find_library()` does not fit my case due to needing to use `pkg-config` and I do not want to write my own pkg-config handling for this.

**Comment by eli-schwartz** [comment]
Again, the purpose of `language:` is for 4 dependencies with custom lookup functionality: hdf5, mpi, netcdf, and openmp. These use different pkg-config or config-tool names for each dependency lookup.

@astavale,
If the goal is to get special handling of vala, then restricting the language is a bad approach anyway. It sounds like you just want to pass a different `--pkg` argument to vala?

@RossComputerGuy,
It sounds to me like you want to look up a dependency with pkg-config, but have vala see the C-style link arguments instead of `--pkg`?

**Comment by RossComputerGuy** [comment]
> It sounds to me like you want to look up a dependency with pkg-config, but have vala see the C-style link arguments instead of `--pkg`?

Yes, however the documentation does not make its intended use clear and should be changed so people won't get the wrong idea. The documentation for it current says

> Defines what language-specific dependency to find if it's available for multiple languages.

**Comment by jon-turney** [comment]
See also https://github.com/mesonbuild/meson/issues/3650

**Comment by jon-turney** [comment]
I think it's unspecified how .pc files are supposed to work when you might want flags to different language compiler(s).

It's usually assumed to be something 'C'-like, but I think there are some projects which supply e.g. fortran compiler flags in something-f77.pc etc., and sometimes you're just supposed to know...

**Comment by astavale** [comment]
`dependency()` is passed to each compiler stage in the build. For a Vala project this is both the Vala compiler and C compiler.

All I wanted was to control this by restricting it to one compiler stage, hence 'language: c' seemed like a good guess to have the dependency passed to the C compiler and not the Vala one. It turns out `meson.get_compiler('c').find_library()` was the meson way to do this.

To my mind `dependency()` is language specific and interpreted by each compiler slightly or completely differently, which seems fine. It's down to each build system compiler module to work how it uses the declaration. So at present `dependency()` is passed to each compiler used in the build and interpreted as per each compiler module. If the dependency is relevant to only one then other Meson functions need to be used. As I understand it now, `dependency()` is for declaring the most common use cases, the "happy paths", for most projects. If it's outside of that, then the projects structure needs to be declared in a different way.

I'm thinking this issue is documentation one.

@RossComputerGuy There was some discussion in #10738 about finding C headers outside of the standard path.

**Comment by RossComputerGuy** [comment]
> There was some discussion in https://github.com/mesonbuild/meson/issues/10738 about finding C headers outside of the standard path.

This does not work in my case, the headers include directory is given by pkg-config and using pkg-config is the best method for including packages on nixOS.

**Comment by astavale** [comment]
> This does not work in my case, the headers include directory is given by pkg-config and using pkg-config is the best method for including packages on nixOS.

Hmm, so you don't have a VAPI for this library/ies (libglvnd and libdrm)? All `dependency('x')` for Vala does is pass the name of the VAPI file to use. `valac` called by Meson only generates the C (`--ccode` with `valac`), it doesn't go on to call the C compiler / linker.

If that's so then I think you should be compiling the C as a static library and linking in to the final executable. The Vala code will also need a VAPI to use the C code for your own wrapper using the lower level libraries.

**Comment by RossComputerGuy** [comment]
I don't have vapi's because these libraries are system libraries. I'm specifically using `libdrm`, `libglvnd`, and `glesv2`. Generating bindings for these libraries isn't that easy because they don't follow the style that is liked for generating bindings. I also don't need to access these libraries in Vala so it makes sense to not need bindings for these libraries.

**Comment by tristan957** [comment]
@eli-schwartz I don't see anything actionable here. I think this can be closed.
