### ISSUE TITLE
hotdoc module generates broken "Edit on github" links

### ISSUE THREAD

**Issue by eli-schwartz** [mesonbuild/meson#8061]
- Browse to https://mesonbuild.com/Hotdoc-module.html
- Click "Edit on github"
- Be redirected to https://github.com/mesonbuild/meson//edit/master/docs/builddir/markdown/Hotdoc-module.md
- notice "builddir/" in the url

/cc @thiblahute

**Comment by thiblahute** [comment]
Ah, that broke recently, I guess in hotdoc? @MathieuDuponchelle any guess?

**Comment by MathieuDuponchelle** [comment]
checking

**Comment by MathieuDuponchelle** [comment]
This is caused by https://github.com/mesonbuild/meson/commit/b6981bd16eb0227173a85d4b26a4b060dab16998 , I'm afraid this isn't something that can be fixed directly in hotdoc. The assumption made by the edit-on-github plugin is that the source file for a page is version-controlled, that commit broke this assumption. I think the whole mechanism implemented in this commit is pretty misguided, and we could have looked for a better solution together, but things being as they are the only solution would be for the extension to accept a new page meta, that meta would specify the actual path (from the root of the repo) of the version-controlled source file.

Something like:

```
original-source: docs/markdown/foo.d
```

in the yaml front matter (naming is hard sorry). The python script used to regenerate the sources would then have the responsibility of injecting that information in the front matter, taking care of doing so correctly, ie ideally not parsing with regexes too much :D

**Comment by eli-schwartz** [comment]
> I think the whole mechanism implemented in this commit is pretty misguided, and we could have looked for a better solution together, but things being as they are

Hmm, if there is a better solution maybe we could switch to that? What are you thinking of?

**Comment by MathieuDuponchelle** [comment]
hotdoc supports sthg called transclusion: https://hotdoc.github.io/syntax-extensions.html#smart-file-inclusion-syntax . Interestingly it looks like the mechanism @TheQwertiest implemented uses the same syntax for that, presumably unknowingly, I assume this is jinja syntax.

In any case, you could switch to sthg like:

{{ cmd_help_configure_arguments.md }}

generate one markdown file per subcommand, with contents looking like:

    ```
    configure help goes here
    ```

And add an include path for hotdoc to look into

I haven't looked in details though, but I reckon this could work and not require copying everything to the build dir

**Comment by eli-schwartz** [comment]
OK, I tried implementing your solution and after a bit too much playing around to get hotdoc installed I was able to test it -- seems to work beautifully.

**Comment by TheQwertiest** [comment]
> Interestingly it looks like the mechanism @TheQwertiest implemented uses the same syntax for that, presumably unknowingly

The page you are referring to is generated dynamically in python using an actual jinjs2 package: https://github.com/mesonbuild/meson/blob/master/tools/regenerate_docs.py

**Comment by eli-schwartz** [comment]
> I assume this is jinja syntax.

Quelle surprise.

**Comment by TheQwertiest** [comment]
@eli-schwartz , can't say I agree with your changes: it now edits the file in-tree and not out-of-tree, which is not a mesonic way.

**Comment by MathieuDuponchelle** [comment]
> Quelle surprise.

hm?

**Comment by eli-schwartz** [comment]
@MathieuDuponchelle I mean to say, it's hardly surprising that "it is generated using an actual jinja2 package" if it has been previously commented "I assume this is jinja syntax". So I'm not sure what @TheQwertiest was trying to point out there.

**Comment by TheQwertiest** [comment]
> Interestingly it looks like the mechanism @TheQwertiest implemented uses the same syntax for that, **presumably unknowingly**

It was more about the *bolded* part. But perhaps I misunderstood the post, hence the confusion.

**Comment by MathieuDuponchelle** [comment]
Ah I see, I only meant you probably didn't know that that same `{{ }}` syntax could be used in hotdoc to achieve similar results :)
