### ISSUE TITLE
Make meson dist reproducible

### ISSUE THREAD

**Issue by a-vrma** [mesonbuild/meson#8093]
**Describe the bug**
When I run meson dist twice on the same tree, the checksums aren't the same, even after decompressing.

**Expected behavior**
Checksums should be the same

**system parameters**
* what Python version are you using e.g. 3.8.0: 3.9.0
* what `meson --version`: 0.56.0

See https://reproducible-builds.org/docs/archives/. Also, note that `git archive` seems to be reproducible from my testing.

**Comment by eli-schwartz** [comment]
https://docs.python.org/3/library/shutil.html#shutil.make_archive doesn't provide a method for overriding the mtime of all files, and that's the root of the problem here in dist tarballs.

In comparison git archive is usually, but not always, reproducible:
> git archive behaves differently when given a tree ID versus when given a commit ID or tag ID. In the first case the current time is used as the modification time of each file in the archive. In the latter case the commit time as recorded in the referenced commit object is used instead.

...

Note that reproducible-builds cares about archives created as part of build stages and possibly installed as artifacts... but meson dist is about *manually* / interactively creating blessed source archives where reproducibility doesn't generally matter. Fundamentally, you don't "build" a dist, you release it e.g. by attaching it to github releases alongside your signature `*.asc` and expecting everyone else to use it.

git archive is not used by meson dist, since it doesn't handle subprojects. The fact that git archive is reproducible is IMO primarily important due to the fact that github et al. use it in *automated processes* to produce default downloads for people that don't manually attach a release to a tag -- as such, it's important the archive doesn't change every time you redownload it.

Since meson dist is created manually and uploaded as an **immutable source**, it does not have this issue.

**Comment by a-vrma** [comment]
Your argument makes sense. I got the idea looking at https://github.com/LoupVaillant/Monocypher/commit/37a2589ed04436ee07b86b2097635e30d6beea07 and just thought it would be interesting if two different people could clone and run `meson dist` and get the same thing. In any case, as long as Python doesn't include that in the standard library, this issue can be closed.

**Comment by eli-schwartz** [comment]
It should be possible to do exactly what you'd do if your `tar` program is anything other than GNU tar, and use `touch` to modify file mtime. Or in the python case, `os.utime()`.

The question is whether it is worth doing. I asked on the reproducible-builds IRC, but it doesn't seem like "reproducible source code dist tarballs" have really been discussed. If there was a consensus to try making that reproducible too, I'd say sure, why not...

**Comment by woju** [comment]
FWIW this might be doable with `faketime`. I tested a simple case and it works with:
```sh
git clean -dxf
faketime -f "$(git show -s HEAD --format=%ci) i0.1" \
    sh -c 'meson build && meson dist -C build --no-tests --include-subprojects --formats=gztar'
```
This commit: woju/mesondisttest@58396025114ad9d7355c4fdedcae0425cee91af2 should result in
```
build/meson-dist/mesondisttest-1.2.3.4.tar.gz 023767205a26735ba9f4582d81ec875444453071e7807b3a0c8b7aac773c476b
```
Althought I'd prefer if faketime wasn't required in the first place, because it's a hack.
