### ISSUE TITLE
list available compilers

### ISSUE THREAD

**Issue by cheofusi** [mesonbuild/meson#8112]
Is it possbile to get a list of all the available compilers for given language?? Something like meson.get_compiler**s**('cpp')

**Comment by tristan957** [comment]
@cheofusi do you mean the compilers that are on a given system or the compilers that Meson supports?

**Comment by cheofusi** [comment]
The compilers on the build machine

**Comment by tristan957** [comment]
@eli-schwartz thoughts on this?

**Comment by eli-schwartz** [comment]
Do it from the build language DSL? I'm not sure what the use case is, since we only use whichever one we found first.

Do it from a custom command like `meson list-compilers? I guess this would be for discovery of the available options for deciding how to configure the project?

**Comment by tristan957** [comment]
I personally don't see too much value in this. A feel like someone compiling software is going to know what compilers are on their system.

**Comment by cheofusi** [comment]
Well it is handy if you're dealing with compiler specific args, so you can specify what gets passed if it's gcc, or clang, or whatever.

**Comment by xclaesse** [comment]
So you don't really need to list available compilers, just print in advance the one that will be picked by meson. I think it makes sense to know at least the value of `meson.get_compiler('c').compiler.get_argument_syntax()` I'm advance so a script can select which `-Dc_args` or which native file to pass.

**Comment by eli-schwartz** [comment]
@xclaesse,

What does this have to do with scripts? Who mentioned scripts? If you're selecting -Dc_args or native files in a script, won't the same script also select the compiler?

@cheofusi,

> Well it is handy if you're dealing with compiler specific args, so you can specify what gets passed if the chosen compiler is gcc, or clang, or whatever.

Since I assume you you just need to do it from Meson with add_project_arguments() or by building an array to pass to e.g. `executable('foo', 'foo.c', c_args: [list, of, args])`, then this already works, because:
- `cc.get_argument_syntax()` tells you whether you have a gcc-compatible or msvc-compatible compiler
- `cc.get_id()` tells you which compiler EXACTLY, you got.

And you can use one or the other of these to make sure you pass the correct flags relevant to the detected compiler.

**Comment by eli-schwartz** [comment]
Okay, I assume get_id() did the trick. :) You can consult https://mesonbuild.com/Reference-tables.html#compiler-ids to see which compilers Meson knows about -- not all of them will be installed on your machine, and you probably don't care about all of them either, but it will help you get a good idea of which ones you do care about -- and also tell you exactly what ID string to code against.
