### ISSUE TITLE
does not find dependencies

### ISSUE THREAD

**Issue by niansa** [mesonbuild/meson#8128]
**Describe the bug**
Can't configure vala projects because meson says glibc is missing even though both are installed

`Compiler stderr:`

` error: Package `glib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

`error: Package `gobject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories`

**To Reproduce**
Happens with all vala projects, even template one from gnome builder

**Expected behavior**
Configure should work

**system parameters**
* Kubuntu 20.04
* Python 3.8.5
* Meson 0.53.2
* Ninja 1.10.0

**Comment by eli-schwartz** [comment]
That is not glibc (the GNU C library), it is GLib (gnome library).

And you'll need to install gobject-introspection manually, since it is not installed by default... note you need the development libraries for it.

Look for a package from your distro providing the files /usr/share/gir-1.0/GLib-2.0.gir and /usr/share/gir-1.0/GObject-2.0.gir

**Comment by niansa** [comment]
Perfect, worked.
