### ISSUE TITLE
Support Dragon WrapDB as an alternative `meson wrap install` backend

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/meson#8167]
I was wondering if it would be possible to support a new wrap database service in Meson? The service is called Dragon WrapDB.

The database link is [here](https://github.com/dragon-wrap). There you can fine a classic wrapDB issue handler is setup and ready, along with working package(s).

The packages are structured so that I could run CI test on the upstream file which is stored in the test project `package` as a subproject dependency.

https://github.com/dragon-wrap/throwtheswitch-unity

I would like to thank the ‘Meson Build Developers’ for allowing builds that don't require a language and or compiler so it would be possible to test wrap files.

**Comment by eli-schwartz** [comment]
> The database link is [here](https://github.com/dragon-wrap).

Github isn't a wrapdb database.

Also this is just a github organization containing *one* wrap file repository created yesterday, and it's not clear why that cannot be added to https://wrapdb.mesonbuild.com/ instead.

What's the goal here? meson supports wrap files, it doesn't care where you get them from. The `meson wrap` command for searching and downloading wrap files needs to communicate with some kind of API endpoint, and "scrape a github org for repos, then check if each repo matches some heuristic structure" is not going to be the answer.

Do you want to run your own [mesonwrap webserver](https://github.com/mesonbuild/mesonwrap) and tell meson to use that instead of the baked-in domain?
e.g. `meson wrap list --wrapdb-url https://dragonwrapdb.wordpress.com/` (needs something other than Wordpress TBH).

**Comment by michaelbrockus** [comment]
On Thu, Jan 7, 2021 at 2:38 PM Eli Schwartz <notifications@github.com>
wrote:

> The database link is here <https://github.com/dragon-wrap>.
>
> Github isn't a wrapdb database.
>
> Also this is just a github organization containing *one* wrap file
> repository created yesterday, and it's not clear why that cannot be added
> to https://wrapdb.mesonbuild.com/ instead.
>
I know. It's still a bit of a working progress, and I gotta start somewhere.

> What's the goal here? meson supports wrap files, it doesn't care where you
> get them from. The meson wrap command for searching and downloading wrap
> files needs to communicate with some kind of API endpoint, and "scrape a
> github org for repos, then check if each repo matches some heuristic
> structure" is not going to be the answer.
>
The goal is to build a self replacing service, and something dedicate to
providing wrap files. Each wrap package is immediately tested to see if it
works to avoid making revisions as often as possible.

> Do you want to run your own mesonwrap webserver
> <https://github.com/mesonbuild/mesonwrap> and tell meson to use that
> instead of the baked-in domain?
> e.g. meson wrap list --wrapdb-url https://dragonwrapdb.wordpress.com/
> (needs something other than Wordpress TBH).
>
> That's just for the user experience, I'm still working on getting a server
setup to better support other wraps beyond [git-wrap] packages.

**Comment by eli-schwartz** [comment]
As far as I can tell, you haven't really tried to answer my question. What does "support Dragon WrapDB" mean to you?

- Should the `meson wrap list` tool support it?
- Should it be endorsed in the meson documentation?
- Do you want to make sure `meson setup builddir/` allows configuring projects if your Firefox browsing history reveals that you probably downloaded `foo.wrap` from the competitor rather than from https://wrapdb.mesonbuild.com/?

**Comment by michaelbrockus** [comment]
It would be nice if it could be supported in the list command but really
I'm interest in providing wrap packages as a competitor.

**Comment by eli-schwartz** [comment]
Can you please clarify what you would like the meson project to do, in order to make it easier for you to achieve your goals here.

**Comment by michaelbrockus** [comment]
Sorry. I would like to have Dragon WrapDB setup as a backup service for
Meson to get wraps from if WrapDB somehow has that issue where it was down
again.

**Comment by eli-schwartz** [comment]
OK. It will need some sort of API to determine which wraps are available, though...

**Comment by michaelbrockus** [comment]
Ok. Made a note of that, any recommendations on how I would go about that?
Secondly would a static github.io site work for storing the wraps?

**Comment by michaelbrockus** [comment]
Is this close? Kinda still trying to figure out the classic setup of the WrapDB API so I would have something ready.

https://github.com/dragon-wrap/dragon-wrap.github.io/tree/main

**Comment by michaelbrockus** [comment]
Alright got something working. Quick question about the WrapDB upstream package generator, does it work with other competitive upstream services or just WrapDB?

Here is the link for the service.

https://dragon-wrap.github.io/

**Comment by michaelbrockus** [comment]
I sadly have not enough time or resources to run a service.
