### ISSUE TITLE
Setting project version fails from git bash on Windows

### ISSUE THREAD

**Issue by lukester1975** [mesonbuild/meson#8175]
```
> meson rewrite kwargs set project / version "1.0.0"
ERROR: The ID for the function type project must be "/" not "C:/Program Files/Git/" --> aborting

ERROR: Rewriting the meson.build failed
```
(That's not the regular error message obviously; I hacked it to see what it was doing.)

Due to https://stackoverflow.com/questions/54258996/git-bash-string-parameter-with-at-start-is-being-expanded-to-a-file-path

I don't want to `MSYS_NO_PATHCONV=1` as surely it will cause other issues, and whilst passing `//` when running in git bash works, the correct command syntax then becomes dependent on the environment it is running in.

So, how about allowing `//` such that the same command will work regardless of shell? I did that here https://github.com/lukester1975/meson/tree/fix-git-bash-project-id but I would imagine it's not PR-worthy :) (plus Rewriter.md would need a note adding).

That said, maybe allowing `root` is a better alternative? I have to say I looked at the command in the docs initially and wondered by on earth there was a `/` in the command line...

I assume the same is true from other msys bashes but haven't checked.

Thanks

**Comment by mensinda** [comment]
I think we explicitly went for `/` instead of something like `root` to avoid situations where something else is called `root` in the project.

So, yes, allowing both `/` and `//` would be acceptable.

> but I would imagine it's not PR-worthy :)

Not quite but you are almost done. Just add a release note snippet, update the docs, and copy-paste a unit test for the rewriter to check that it works :)

Also, why the hell is msys doing this in the first place? Is there really no other way to turn this off?

**Comment by lukester1975** [comment]
OK sure, here's a first punt: #8183.
