### ISSUE TITLE
Allow alias_target() to depend on runtarget objects

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/meson#8353]
Right now alias_target() has a restriction to only depend on build targets. It would be nice if alias_target() could also depend on run targets.

Use case: project has both C and python files. There exists a clang-format target for C files, and a black target for python files. I want to now add a meta-target called format which runs both clang-format and black targets.

**Comment by xclaesse** [comment]
The reason nothing can depend on a run_target is ninja can only have dependencies on files, and a run_target() does not produce any output file.

But it's actually a popular request, you're not the first one to ask. I see 2 ways to work around that:
- Internally convert your RunTarget into a CustomTarget that produce a dummy file. That's pretty common in Makefile world to have .stamp files in similar situations.
- Internally instead of doing an "alias" that will somehow run the other target, we could make it a real run_target and copy the command line to execute in it.

**Comment by tristan957** [comment]
I like option 2 more I think.

**Comment by eli-schwartz** [comment]
Wait a minute... this is the same thing as #9175 from a different angle and fixed now.
