### ISSUE TITLE
configure_file called twice with network paths?

### ISSUE THREAD

**Issue by Neumann-A** [mesonbuild/meson#8375]
Original vcpkg issue: https://github.com/microsoft/vcpkg/issues/16262
Error:
```
Configuring hb-version.h with command

\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\meson.build:1:0: ERROR: Running configure command failed.

Traceback (most recent call last):
  File "\\VBoxSvr\Shared\vcpkg\buildtrees\harfbuzz\src\f4d3aa1127-a820a32874.clean\src\gen-hb-version.py", line 36, in <module>
    shutil.copyfile (OUTPUT, os.path.join (CURRENT_SOURCE_DIR, os.path.basename (OUTPUT)))
  File "shutil.py", line 241, in copyfile
shutil.SameFileError: '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h' and '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h' are the same file
```
meson code:
```
hb_version_h = configure_file(
               command: [find_program('gen-hb-version.py'), meson.project_version(), '@OUTPUT@', '@INPUT@'],
               input: 'hb-version.h.in',
               output: 'hb-version.h',
               install: true,
               install_dir: join_paths(get_option('includedir'), meson.project_name()))
```

So `<snip>\\harfbuzz\\x64-windows-static-md-dbg\\` is empty before meson is called
Meson creates the file `<snip>\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h` with `gen-hb-version.py` 
`gen-hb-version.py` -> errors if `hb-version.h` already exists and is the same. 

Conclusion:
The error shouldn't exist. Meson somehow tries/seems to run `configure_file` twice? 
(of course this could be mitigated in `gen-hb-version.py` but this seems to be a meson bug )

**Comment by dcbaker** [comment]
Does meson run configure file twice in the same invocation, or is it on the second invocation that there's a problem?

**Comment by Neumann-A** [comment]
> Does meson run configure file twice in the same invocation, or is it on the second invocation that there's a problem?

@dcbaker: vcpkg always runs with a clean working dir so it is the very first invocation

**Comment by eli-schwartz** [comment]
> The error shouldn't exist. Meson somehow tries/seems to run `configure_file` twice?

I don't understand this analysis, but it's easily falsifiable. meson logs `Configuring hb-version.h with command` two lines before running the referenced command, and the log listed at https://github.com/microsoft/vcpkg/issues/16262 only shows it being run once. Moreover, it doesn't matter how often meson runs configure_file, because it cannot produce a SameFileError anyhow.

meson, when run in command: [] mode, delegates solely to the third-party program and cannot be responsible for whatever that third-party program does. All such programs should, however, be expected to work correctly after `ninja reconfigure` which reruns the configuration process and updates any configured files.

meson itself when internally handling configuration, handles this safely.


```
shutil.SameFileError: '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h' and '\\\\VBoxSvr\\Shared\\vcpkg\\buildtrees\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h' are the same file
```

For clarity, gen-hb-version.py is running shutil.copyfile(a, b), and inside the source code to shutil itself, copyfile runs `shutil._samefile(a, b)` and if they are the same file, it raises the mentioned error. This is the only way to get that precise error.

The error states that `a` and `b` (which, as printed by the error message, have *different* paths) were detected as the same file through either:
- having the same os.stat() inode and device number on Unix or Windows (or any platform where os.path.samefile is implemented)
- having the same abspath on any other platform (?)

copyfile itself, will always create a brand new file, even when a symlink exists, unless the non-default follow_symlinks=False is set, which the harfbuzz script doesn't set. Meson doesn't set that either, when running internal configurations.

Naturally, new files cannot ever be the same st_ino && st_dev as another pre-existing file...

... so, somehow these files have the same stat values, once the first file has been created:
- `<snip>\\harfbuzz\\x64-windows-static-md-dbg\\src\\hb-version.h` (build directory)
- `<snip>\\harfbuzz\\src\\f4d3aa1127-a820a32874.clean\\src\\hb-version.h` (source directory)

I can trivially reproduce this error by making src/hb-version.h into a symlink ***to the builddir that does not exist yet***. And then configuring.

This is hardly the fault of either meson or harfbuzz.

Note: all this I have said is a total theory, you have the actual environment where this was reproduced -- I don't. So I'm just guessing here.

Anyway, this problem cannot be created by meson, and it cannot be created by harfbuzz without the user setting the scene in an... unusual... manner.
