### ISSUE TITLE
0.57.1: missing keep-going  functionality of the "meson [compile|build]"

### ISSUE THREAD

**Issue by kloczek** [mesonbuild/meson#8399]
Looks like it is some small missing bit in "meson compile" design which is equivalent of "make -k" or "ninja -k 0" switch.

**Comment by eli-schwartz** [comment]
It also doesn't support -n -d -t or -w, what's your point? Why not just use ninja directly?

meson compile only exists for the sake of Windows users because multiple backends (ninja, visual studio) can be confusing and just documenting "run `ninja`" might not work everywhere. You will always get more control by using the backend directly.

**Comment by kloczek** [comment]
> Why not just use ninja directly?

Because meson knows with what kind of backend was configured.

**Comment by kloczek** [comment]
Looks it does not need to be `meson build -k 0`.
It is about provide functionality to not stop build despite encountered errors.

**Comment by eli-schwartz** [comment]
> Because meson knows with what kind of backend was configured.

You know what kind of backend was configured too,

Unfortunately, -k is not supported by samu, which is a drop-in replacement for ninja and which meson (correctly) considers to be "the build.ninja backend". It's really not about the backend *program*, just the backend file format.

Implementing -k would mean passing -k to the build.ninja backend, which would result in a fatal samu error.

**Comment by xclaesse** [comment]
The question is wether VS backend has the same functionality, in which case we can add it to our wrapper. Otherwise you've got `--ninja-args`.

**Comment by xclaesse** [comment]
In other words, I think `meson compile` options should not be the union of feature of each backend, but rather the intersection.

**Comment by kloczek** [comment]
> Unfortunately, -k is not supported by samu, which is a drop-in replacement for ninja and which meson (correctly) considers to be "the build.ninja backend". It's really not about the backend program, just the backend file format.

That is samu problem ..

> The question is wether VS backend has the same functionality, in which case we can add it to our wrapper. Otherwise you've got --ninja-args.

Again .. you are assuming that human will be involved in processing builds (which is not the case).
If backend does not suport exactly that kind of functionality that can be skipped.

I'm pointing on some missing functionalyty which could be used by automattion (I just encountered such case on developing my distribution build infrastructure to catch not only one but all other build errors in case of initial build fail).

**Comment by eli-schwartz** [comment]
Even if the VS backend did support it, we still need to support the lowest common denominator of ninja+samu.

(I say this despite realizing no one ever tested meson compile with samu -- it is very badly broken. Nevertheless, that can, must, and will be fixed, because it is a supported `$NINJA`. We are not adding another thing which is broken but can't be fixed.)

**Comment by eli-schwartz** [comment]
@kloczek ***use ninja directly***. It solves ***all*** your problems.

**Comment by kloczek** [comment]
> @kloczek use ninja directly. It solves all your problems.

You are assuming that I'm building few packages so I can go to such level of granularity.
Issue is that I'm building thosands and as long as I'm building everytjing over rpmbuild or pkgbuild (to build IPS packages and reusing rpm spec files to building Solaris IPS packages) have on lover layer such functionality would allow me to generate additional build log to try to catch not first nut all build errors automatically).

**Comment by eli-schwartz** [comment]
You can most certainly use ninja everywhere you are currently using meson compile. You don't need "granularity" -- the only thing meson compile ***EVER*** does on platforms other than Windows or macOS, is immediately run ninja with the same arguments. `meson compile` brings nothing. No features, no bugfixes, nothing.

Except for support for Visual Studio or xcode solutions, which you cannot possibly be using on any platform supported by rpm.

**Comment by jpakkane** [comment]
> that I'm building thosands and as long as I'm building everytjing over rpmbuild or pkgbuild (to build IPS packages and reusing rpm spec files to building Solaris IPS packages)

For reference, all packages built in Debian, Fedora, SuSE and others are built with `ninja`. None of them use `meson compile`. That is by design. `meson compile` is meant to be a simple helper tool for common cases. Those who need finer control and features should use the underlying tool directly.

**Comment by kloczek** [comment]
> You can most certainly use ninja everywhere you are currently using meson compile. You don't need "granularity" 

Yes, now that is true.
However as meson by design provides layered support for backend it is possible to imagine that in the future someone will design better backend (especially on parallelisation builds) and with rpm `%meson`, `%meson_build`, `%meson_install`and `%meson_test` it would be possible instantly switch to such backend without sigle moidyfication across all rpm/IPS spec files.
This is why in my meson rpm macross I'm not using ninja but meson which knows wha kind of backend by default is used
```
[tkloczko@barrel SPECS]$ rpm -E %meson_build
/usr/bin/meson compile -C x86_64-redhat-linux-gnu -j 48 --verbose

[tkloczko@barrel SPECS]$ rpm -E %meson_install
DESTDIR=/home/tkloczko/rpmbuild/BUILDROOT/%{NAME}-%{VERSION}-%{RELEASE}.x86_64 /usr/bin/meson install -C x86_64-redhat-linux-gnu --no-rebuild

[tkloczko@barrel SPECS]$ rpm -E %meson_test
/usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
```

**Comment by kloczek** [comment]
> For reference, all packages built in Debian, Fedora, SuSE and others are built with ninja. None of them use meson compile. That is by design. meson compile is meant to be a simple helper tool for common cases. Those who need finer control and features should use the underlying tool directly.

And that kind of short term desing could be kind of problem if anything change with possibility to use some more effective meson backend. Sorry I'm not going to follow that path.

**Comment by eli-schwartz** [comment]
There's no reason to believe meson will move away from ninja. The vs and xcode backends exist because on those operating systems the OS developers provide a native build system that people sometimes need to use. That's never going to happen on linux or other more normal unixes, so there's really no point in chasing different backends.

This is all irrelevant anyway, since for your deep rpm integrations if you ever had the opportunity and desire to change the meson backend, you would do so for both %meson and %meson_build.

**Comment by eli-schwartz** [comment]
> (I say this despite realizing no one ever tested meson compile with samu -- it is very badly broken. Nevertheless, that can, must, and will be fixed, tonight, because it is a supported `$NINJA`. We are not adding another thing which is broken but can't be fixed.)

Done. #8401



> In other words, I think `meson compile` options should not be the union of feature of each backend, but rather the intersection.

I agree with @xclaesse here and I'd like to remove the `--load-average` option from meson compile since it's not really in theme here at all. After the initial introduction of meson compile (which shipped with `--load-average`), `--ninja-args` was added later on -- and per IRC discussion this is the "correct" way to pass advanced options.

Regrettably, it's harder to drop support for something than to add it, but I'd like to at a minimum have a full moratorium on adding new options, and maybe also add a deprecation warning if you do use it?
