### ISSUE TITLE
Meson.exe fails with cooperate proxy server

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/meson#8446]
**Describe the bug**
When Meson.exe (Win build of Meson) uses a wrapfile to fetch stuff, it fails. I am behind a cooperate proxy server that breaks SSL connections.

The trace of the failure:

> Run-time dependency zlib found: NO (tried pkgconfig and cmake)
> Downloading zlib source from http://zlib.net/fossils/zlib-1.2.11.tar.gz
> Traceback (most recent call last):
>   File "mesonbuild\mesonmain.py", line 132, in run
>   File "mesonbuild\msetup.py", line 275, in run
>   File "mesonbuild\msetup.py", line 183, in generate
>   File "mesonbuild\msetup.py", line 222, in _generate
>   File "mesonbuild\interpreter.py", line 4798, in run
>   File "mesonbuild\interpreterbase.py", line 641, in run
>   File "mesonbuild\interpreterbase.py", line 666, in evaluate_codeblock
>   File "mesonbuild\interpreterbase.py", line 659, in evaluate_codeblock
>   File "mesonbuild\interpreterbase.py", line 682, in evaluate_statement
>   File "mesonbuild\interpreterbase.py", line 764, in evaluate_if
>   File "mesonbuild\interpreterbase.py", line 666, in evaluate_codeblock
>   File "mesonbuild\interpreterbase.py", line 659, in evaluate_codeblock
>   File "mesonbuild\interpreterbase.py", line 674, in evaluate_statement
>   File "mesonbuild\interpreterbase.py", line 1341, in assignment
>   File "mesonbuild\interpreterbase.py", line 672, in evaluate_statement
>   File "mesonbuild\interpreterbase.py", line 1031, in function_call
>   File "mesonbuild\interpreterbase.py", line 515, in wrapped
>   File "mesonbuild\interpreterbase.py", line 229, in wrapped
>   File "mesonbuild\interpreterbase.py", line 198, in wrapped
>   File "mesonbuild\interpreter.py", line 2890, in func_subproject
>   File "mesonbuild\interpreter.py", line 2936, in do_subproject
>   File "mesonbuild\wrap\wrap.py", line 327, in resolve
>   File "mesonbuild\wrap\wrap.py", line 392, in get_file
>   File "mesonbuild\wrap\wrap.py", line 554, in get_file_internal
>   File "mesonbuild\wrap\wrap.py", line 528, in download
>   File "mesonbuild\wrap\wrap.py", line 479, in get_data
>   File "urllib\request.py", line 214, in urlopen
>   File "urllib\request.py", line 517, in open
>   File "urllib\request.py", line 534, in _open
>   File "urllib\request.py", line 494, in _call_chain
>   File "urllib\request.py", line 1371, in http_open
>   File "urllib\request.py", line 1346, in do_open
>   File "http\client.py", line 1347, in getresponse
>   File "http\client.py", line 307, in begin
>   File "http\client.py", line 268, in _read_status
>   File "socket.py", line 704, in readinto
> ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

**To Reproduce**

1. Get behind a proxy.
2. Make a meson project using a wrapfile
3. `meson setup builddir`

**Expected behavior**

1. Meson uses the Windows proxy settings.
2. If that is not possible, it allows to configure a proxy manually.
3. If that is not possible, it catches the error and issues a proper error message.

**system parameters**
* Cross-build for WinCE
* Build system is Win10
* `meson --version` yields `0.57.1` (recent MSI build from the Meson website)

**Comment by eli-schwartz** [comment]
meson is written in python, and wraps utilize python's `urllib.request` library to retrieve files over the internet.

This per default will respect https_proxy if set in the environment. Is this the case for you?

This covers at least expectation 2, but I don't know enough about Windows to know if expectation 1 is supposed to work that way out of the box.

Regarding expectation 3, what constitutes a proper error message? And how does one recognize the problem is a proxy?

(Note that your system CA certificates should be getting used by default, so if the proxy is breaking TLS, then it presumably should have installed its own signing certificate.)

**Comment by ManuelAtWork** [comment]
Thank you for looking into this.

The environment variable HTTPS_PROXY is not set on my Win10 box. It is not a typical source of proxy information on Windows OS'. Instead, [the registry appears to be reliable way to detect proxy settings](https://railsware.com/blog/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/).

The possibility to use HTTPS_PROXY should be documented, e.g. in the Wrap system's manual, to satisfy expectation 2. (Why not make it a feature instead of a side-effect of the implementation, which happens to be based on ```urllib.request```.)

Regarding the error message, I would expect something more specific. What about: "Download failed due to connection problems." Then indicate the source of the problem as good as possible: System resource/socket not obtainable? Host resolution failed? TCP handshake failed? SSL cert problem? HTTP error code? Timeout?

(Good point about CA certs. Our proxy is indeed breaking SSL and replacing certs with self-signed ones. The companies root authority is installed in the Win10 certificate store. We only have problems when programs bring their own OpenSSL instance with separate cert store.)

**Comment by eli-schwartz** [comment]
I don't regard this as a side effect of implementation. Rather, it's a benefit of using popular frameworks. For example, libcurl works the same way (yes, even on Windows) -- both will automatically respect well known environment variables provided by the user's runtime environment, but also offer language primitives for the application developer to roll their own completely from scratch implementation.

It's a standard, popular method which people tend to assume works by default, and also tend to assume should be implemented as low down the tech stack as is practical, in order to guarantee it does in fact work by default everywhere.

Conversely, I have no idea what this apparent Windows method is (and your link is bad, it links to an article which doesn't discuss this at all and talks about something else totally different.)

I guess if you like you can submit a PR to mention "yes -- meson, too, respects the universal standard".

...

As far as the error message goes, I've already said I'm not sure how the error message could be made.more specific -- it already mentions "connection error" and then provides more details -- but again, PRs welcome.

**Comment by tristan957** [comment]
@eli-schwartz seems like this should be closed.

**Comment by eli-schwartz** [comment]
Yeah, I don't know what's actionable about this either. Other than documentation changes that don't seem to be forthcoming.
