### ISSUE TITLE
Meson can't build a project with double level of subprojects.

### ISSUE THREAD

**Issue by vityafx** [mesonbuild/meson#8530]
**Describe the bug**
I am writing a meson project which uses [`vkd3d-proton`](https://github.com/HansKristian-Work/vkd3d-proton/) as a subproject.
The `vkd3d-proton` itself as a few subprojects, among which there is a [`dxil-spirv`](https://github.com/HansKristian-Work/dxil-spirv) one.

**To Reproduce**
```
project('myproj', ['c'], version: '461.09', license: 'LGPL-2.1-or-later')

lib_dl = meson.get_compiler('c').find_library('dl')
winebuild = find_program('winebuild')
wrc       = find_program('wrc')
target_arch = target_machine.cpu_family() == 'x86_64' ? '-m64' : '-m32'
libvkd3d_proj = subproject('vkd3d-proton')
libvkd3d_dep = libvkd3d_proj.get_variable('vkd3d_dep')
install_dir = get_option('libdir') / 'wine'

subdir('src')
```

It is completely irrelevant what the contents of the `src`'s `meson.build `, as we aren't even getting to building the project and are stuck with a dependency.

Now, the `dxil-spirv` builds just fine using meson, the `vkd3d-proton` projects builds just fine using meson, but when the `vkd3d-proton` project is used as a dependency to another project, this is where the things break.

This is what the error is:

```
||Executing subproject dxil-spirv method meson
||
||Project name: dxil-spirv
||Project version: 0.0
d||C++ compiler for the host machine: c++ (gcc 10.2.0 "c++ (GCC) 10.2.0")
||C++ linker for the host machine: c++ ld.bfd 2.36.1
 ||Compiler for C++ supports arguments -Wno-missing-field-initializers: YES
||Compiler for C++ supports arguments -Wno-empty-body: YES
||Compiler for C++ supports arguments -ffast-math: YES
||Compiler for C++ supports arguments -Wno-unused-parameter: YES
||Compiler for C++ supports arguments -fno-exceptions: YES
||Compiler for C++ supports arguments -fvisibility=hidden: YES
||Compiler for C++ supports arguments /wd4267: NO
||Compiler for C++ supports arguments /wd4244: NO
||Compiler for C++ supports arguments /wd4996: NO

subprojects/vkd3d-proton/subprojects/dxil-spirv/meson.build:89:0: ERROR: Sandbox violation: Tried to grab file dxil_spirv_c.cpp outside current (sub)project.

A full log can be found at /home/user/workspace/myproj/build/meson-logs/meson-log.txt
```

**Expected behavior**
The project, and all of the subprojects, all of the subprojects of the subprojects and etc, can be built just fine.
Changing all the occurrences of `files = [ 'file.c' ] to using the `files()` thing seems to work. That said, for this `dxil-spirv` project to make it work it is enough to change it from:

```
dxil_spirv_src = [
  # dxil-spirv-c
  'dxil_spirv_c.cpp',
```
to
```
dxil_spirv_src = files(
  # dxil-spirv-c
  'dxil_spirv_c.cpp',
  # ...
)
```

**system parameters**
* Build for the same computer.
* ArchLinux (latest)
* Python 3.9.2
* meson 0.57.1
* Ninja 1.10.2

**Comment by eli-schwartz** [comment]
It would help to have a description of the problem posted directly to this ticket...

**Comment by jpakkane** [comment]
In this case the problem seemed to be cause by the build setups for these projects. For example in proton, we find this:

```meson
vkd3d_external_includes = [ './subprojects/Vulkan-Headers/include', './subprojects/SPIRV-Headers/include' ]
```

This is just plain wrong and should never be done. Grabbing any files or subdirectories directly from within other subprojects is a bug. The correct way to do this is to have vk3d3-proton execute the Vulkan headers subproject and get the include directory from that via a dependency.

In Meson all subprojects to be used must be at the top level project. The reason for this is simple. Suppose you have two subprojects A and B and both of them have a dependency C. If both embed their own version this leads to weird bugs that are extremely difficult to diagnose. So in this case you'd need to have the following things (at least) in your top level subprojects dir:

- vkd3d-proton
- dxil-spirv
- SPIRV-headers
- Vulkan-headers

The build definitions also need to be changed to use subprojects properly rather than poking at their internals and hoping for the best. This is a bit of work, unfortunately, but the existing build setup is not done properly to work in this way, it is hardcoded to only work as a top level project currently.

**Comment by vityafx** [comment]
> In this case the problem seemed to be cause by the build setups for these projects. For example in proton, we find this:
> 
> ```meson
> vkd3d_external_includes = [ './subprojects/Vulkan-Headers/include', './subprojects/SPIRV-Headers/include' ]
> ```
> 
> This is just plain wrong and should never be done. Grabbing any files or subdirectories directly from within other subprojects is a bug. The correct way to do this is to have vk3d3-proton execute the Vulkan headers subproject and get the include directory from that via a dependency.
> 
> In Meson all subprojects to be used must be at the top level project. The reason for this is simple. Suppose you have two subprojects A and B and both of them have a dependency C. If both embed their own version this leads to weird bugs that are extremely difficult to diagnose. So in this case you'd need to have the following things (at least) in your top level subprojects dir:
> 
>     * vkd3d-proton
> 
>     * dxil-spirv
> 
>     * SPIRV-headers
> 
>     * Vulkan-headers
> 
> 
> The build definitions also need to be changed to use subprojects properly rather than poking at their internals and hoping for the best. This is a bit of work, unfortunately, but the existing build setup is not done properly to work in this way, it is hardcoded to only work as a top level project currently.

Thanks! I'll try improving their code base then.
