### ISSUE TITLE
install_data() doesn't accept files() object

### ISSUE THREAD

**Issue by ignatenkobrain** [mesonbuild/meson#858]
```
...
plugins = files('example-c.plugin', 'example-python.plugin')
install_data(plugins,
             install_dir : plugin_path)
...
```

```
Meson encountered an error in file libdnf/plugins/meson.build, line 3, column 0:
Arguments must be strings.
```

**Comment by TingPing** [comment]
I personally think they should accept all targets, its a bit silly that you can't pass a custom target to it.

**Comment by jpakkane** [comment]
Custom target install directives should be in the custom target definition. The design of Meson has been to put as much stuff as possible in one single place. CMake is very annoying because first you define your target and then can have an arbitrary amount of modification commands to it. We want to have everything in one place as much as possible to make things more understandable.

Install_data should accept files so we should fix that.

**Comment by nirbheek** [comment]
I looked into this, and I don't feel comfortable fixing this without also revamping how we check argument lists in all interpreter functions. It's very ad-hoc with functions and decorators spread across at least three different files with two implementations of the `flatten` function, and so on. I propose we fix this properly in the next cycle.
