### ISSUE TITLE
Add shortcut action

### ISSUE THREAD

**Issue by taozuhong** [mesonbuild/meson#8626]
**Expected behavior**
Hope meson add some shortcut for action like follow:
```
meson debug  // --> meson --buildtype=debug build  & meson compile -C build
meson plain    // --> meson --buildtype=plain build  & meson compile -C build
meson release // --> meson --buildtype=release build & meson compile -C build
```

**Comment by dcbaker** [comment]
This would be impossible for us to implement, since there are likely already people relying on `meson debug` creating a build tree. Also, you wouldn't be able to pass extra arguments to `meson setup` or `meson compile`.

Fortunately, you can easily solve this yourself (on Linux and other Unix-like systems) with a shell alias (in your bashrc or zshrc):
```sh
alias meson-debug="meson setupup build --buildtype=debug && meson compile -C build"
```

**Comment by eli-schwartz** [comment]
If we were going to implement this at all, it cannot be an operand and must be an option like `--debug`. Which exists and sets the "debug" setting, not the buildtype (which is a combination of `--debug` and `--optimization`).
