### ISSUE TITLE
Compiling and installing with failed targets.

### ISSUE THREAD

**Issue by nanthony21** [mesonbuild/meson#8632]
I have a project which produces a large number of libraries. Some of these libraries depend on 3rd party libraries which may not always be available to someone wanting to compile my project. I would like for the build process to allow some libraries to fail gracefully.

I found that I can achieve this in the compile step with `meson compile --ninja-args=-k,0`. The `-k 0` argument to ninja causes it to continue even if projects fail. However when I run `meson install --no-rebuild` the process stops immediately due to not being able to locate some of the expected libraries. Is there a way that I can get functionality similar to Ninja's `-k 0` with the install step?

**Comment by eli-schwartz** [comment]
This seems pretty nonsensical.

The point of `ninja -k0` is as a development tool, if your build has multiple errors then you don't stop at the first one but keep going to find any other errors too. Notably, the build still exits with overall failure.

But, the kind of errors it can fail on are things like compiler fatal errors (-Werror or code incompatibilities), not *missing dependencies which aren't even on the system*. Those generally lead to `meson setup` failing to configure, because meson policy is to fail fast where possible. So I'm not even sure how you'd get the error you're suggesting.

Meanwhile, your overall desire here isn't to let meson/ninja "error out but not really". You just want users to not be forced to build stuff they don't want or have installed. The solution to this is... make those third-party dependency lookups (which again, should fail fast during initial configuration) be non-fatal, via the `required: false` keyword on `dependency()` or `cc.find_library()`. Or use feature options defaulting to "auto".

Then, any component that depends on a third-party library can simply be skipped by putting it inside of `if foo_dep.found()` blocks.
The next logical step is to get rid of complicated if blocks by using https://mesonbuild.com/Disabler.html (there is a kwarg for dependency() that does this for you).

End result: if the expected libraries don't exist, ninja doesn't even generate build rules for them. You don't need -k0 since nothing is failing.

**Comment by nanthony21** [comment]
Thanks @eli-schwartz ,

That sounds like a good approach.  I'm working on migrating a large project that is currently maintained just as a large Visual Studio solution to Meson. I'm new to Meson so the correct approach isn't always obvious to me.

**Comment by eli-schwartz** [comment]
No problem, feel free to ask questions. ;)

**Comment by eli-schwartz** [comment]
I still wonder how you got meson setup to pass without the libraries available. Did you add `-l<lib>` manually to linker args? https://mesonbuild.com/Reference-manual.html#compiler-object `find_library()` is the recommended approach.

**Comment by nanthony21** [comment]
Since there are ~200 libraries to compile (each in their own subdirectory) I haven't yet gone through and added the individual dependencies to the build files.

Instead each subdirectory currently contains a python-generated `meson.build` file that includes the dependencies that are common to all projects (like Boost). For that reason the setup runs fine and it isn't until compilation that the source code tries to include headers that can't be found.

I was hoping to test out compilation and installation for the ~100 libraries that can compile without additional dependencies but it looks like before I can do that I'll need to either fix the non-working libraries or temporarily remove them from the project.
