### ISSUE TITLE
Don't warn about unused variables when compiling C code generated by the Vala compiler

### ISSUE THREAD

**Issue by eyelash** [mesonbuild/meson#864]
The Vala compiler tends to generate unused variables. So when compiling Vala code with Meson I get a lot of warnings from the C compiler that do not look nice and clutter the output.

You might argue that this is a bug of the Vala compiler but I don't think so. I agree that in hand-written code unused variables are something bad but for a compiler that outputs C code eliminating unused variables is an additional step that might not be worth it because the C compiler will eliminate them anyway.

**Comment by eyelash** [comment]
[log.txt](https://github.com/mesonbuild/meson/files/516008/log.txt)
[meson.build](https://github.com/eyelash/xi-gtk/blob/742a7fbccd723cddc4a45521e166f7f080909330/meson.build)

**Comment by TingPing** [comment]
All warnings should be ignored for output Vala code as that is up to the Vala compiler to warn about (plus its awful code full of warnings).

**Comment by arteymix** [comment]
I would rather see common warnings filtered rather than a full inhibition.

Here's what I use for Valum:

```
add_global_arguments(['-Wall',
                      '-Wno-pointer-sign',
                      '-Wno-deprecated-declarations',
                      '-Wno-unused',
                      '-Wno-incompatible-pointer-types',
                      '-Wno-discarded-qualifiers'],
                     language: 'c')
```

Then if there's some improvements for warnings in Vala, we could just remove filters based on the compiler version.

**Comment by nirbheek** [comment]
I thought about that, but realized a bunch of things:

1) We'd need to get this list for all compilers
2) The list will keep changing as compilers make more warnings the default
3) It actually makes no sense to warn about any C code issues from code generated by `valac` because the user can't do anything about it

**Comment by arteymix** [comment]
In most case, he can't, but in some cases it can indicate that a VAPI or some inline CCode annotations are incorrect.

I understand that we don't want to list warnings for all compilers.

The other approach I would suggest is to use the `warnlevel` option. Since Vala only have one level of warning, we can safely disable C warnings only for level 1 and enable them for `>2`. Thus, if the user care about extra warnings, it must be C ones.

Dropping C warnings completely would be unwise because it would remove the possibility of having them at all.
