### ISSUE TITLE
add Additional Options error

### ISSUE THREAD

**Issue by ZhouZiY** [mesonbuild/meson#8684]
**Describe the bug**
in meson.build
```
cxxflags = ['/utf-8','']
add_global_arguments(cxxflags, language : 'c')
```
and generate visual studio project 

in vcxproj
```
<AdditionalOptions>&quot;/utf-8&quot; &quot;&quot; %(AdditionalOptions)</AdditionalOptions>
```
![image](https://user-images.githubusercontent.com/16163586/115743098-ede39f80-a3c3-11eb-9e37-ad3d3f247bd2.png)

**Comment by ZhouZiY** [comment]
```
meson --version
0.57.999
```

**Comment by tristan957** [comment]
@ZhouZiY is this still an issue?

**Comment by eli-schwartz** [comment]
AFAICT, no code related to this has changed since then.

But I don't understand the bug here. Is the bug that you added the empty string as an array element, and Meson faithfully transcribed this as one of your build options? Don't do that. The empty string may, sometimes, be a valid argument depending on what came first, but it isn't a valid argument in this case, so the compiler is probably going to choke on it.
