### ISSUE TITLE
Can't get attribute OctalInt error

### ISSUE THREAD

**Issue by zedzean** [mesonbuild/meson#8695]
I am trying to install dpdk in ubuntu 20.  I used sudo apt install meson to install.  The build runs fine but the installation doesn't work. I saw a previous post where someone reinstalled meson and it worked, but it didn't work for me. I already have meson under sudo.
![image](https://user-images.githubusercontent.com/44662240/115995924-e0fcc100-a5fa-11eb-9972-edd3cf104732.png)

**Comment by localjo** [comment]
@zedzean Did you find a solution to this issue? I'm having the same problem.

**Comment by ostap-tymchenko** [comment]
im having the same issue, has anyone found a solution?

**Comment by eli-schwartz** [comment]
Duplicate of #8425

**Comment by xclaesse** [comment]
We still haven't fixed the error handling actually. When it pickle.load() installdata it should catch exception and print proper error message just like we do for coredata.load().

**Comment by eli-schwartz** [comment]
- Best discussed in one place (#8425)
- My understanding is this *can't* normally happen, since we would trigger a rebuild via coredata anyway, but users with broken installations can end up running two versions of meson simultaneously on the same builddir, and the second one is the one with the OctalInt error.

**Comment by xclaesse** [comment]
Made a fix here: https://github.com/mesonbuild/meson/pull/9507.
