### ISSUE TITLE
Installing a precompiled shared library

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [mesonbuild/meson#8830]
I have a precompiled .so file in my project that I would like to install along with my other shared libraries. At the moment, meson install creates binaries that point absolutely to the .so in the projects folders. This would allow the project folder to be deleted without breaking the install.

I currrently have a subproject with the .so that I need with
```
project('ilasmat', 'c')

pkg = import('pkgconfig')
c = meson.get_compiler('c')
# dep_mat = c.find_library('ILasMatInterface', dirs : meson.current_source_dir())
dep_mat = declare_dependency(
    dependencies: c.find_library('ILasMatInterface', dirs : meson.current_source_dir())
)
install_data('ILasMatInterface.so', install_dir: get_option('libdir'))
```
and
```
dep_mat = subproject('ilasmat').get_variable('dep_mat')
```
in the main project meson.build

Neither find_library or declare_dependency works

Without install_data, the .so does not get copied into libdir.
In both cases ldd of a compiled .so that uses the precompiled library seems to be linked with the absolute path of the library instead of the name

```
❯ ldd libmatint.so
	linux-vdso.so.1 (0x00007ffd991a1000)
	/home/guillaume/workspace/1-rescu/subprojects/ilasmat/ILasMatInterface.so (0x00007f4ec717c000)
	libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f4ec6e97000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4ec6ca5000)
```
Is there a way to copy the .so to the install and have the library be searched by name like the others? Setting LD_LIBRARY_PATH to the libdir does not help because of the absolute path.

Using find_library in the main meson.build (instead of a subproject) does not help.

I've also tried  the process suggested in the last part of the issues
https://github.com/mesonbuild/meson/issues/6609
Which did not work saying my .so is a not a target.

My install prefix is not a standard one if it's at all relevant ($HOME/.local)

Thanks

**Comment by xclaesse** [comment]
My guess it this is an rpath issue, I wouldn't be surprised precompiled only works with static libraries at the moment. Usually meson sets the absolute path to shared libraries for libs/executables in the build directory so they work for unit tests without having to set LD_LIBRARY_PATH. Upon installation meson edit the path to set only the name so it uses the installed library instead.

But in your case since the library is found by cc.find_library(), meson does not know it is going to be installed in a different place, so it probably won't change the path upon installation.

**Comment by PhilippeRo** [comment]
Hi,
I ran into the same issue, and like you, I tried both method.
I tried another one with custom_target, but to no avail, since the executable is linked to the library with a semi absolute path (does that exists) such as "subprojects/ilasmat/ILasMatInterface.so" (to use the example you gave).
 Have you found a workaround ?
Thanks

**Comment by GuillaumeQuenneville** [comment]
Nothing I liked sadly... I'm only targetting linux so I copy the lib manually and use patchelf to fix the path.  Patchelf isn't installed by default for most distro's so it's not an ideal solution.

```PREFIX ?= ${HOME}/.local/

install:
	DESTDIR=${PREFIX} meson install -C build
	cp $(shell pwd)/subprojects/ilasmat/ILasMatInterface.so ${PREFIX}/lib/ILasMatInterface.so
	patchelf --replace-needed $(shell pwd)/subprojects/ilasmat/ILasMatInterface.so ${PREFIX}/lib/ILasMatInterface.so ${PREFIX}/lib/LIBTOFIX.so
```

**Comment by GuillaumeQuenneville** [comment]
@jpakkane Not sure how to ping the maintainers sorry.

 I'm not too familiar with meson source code but I'd be happy to attempt to contribute this feature/fix if it's something meson should support. If you could give me the general idea how to implement it would be appreciated.

**Comment by eli-schwartz** [comment]
I believe this has nothing to do with rpath, but rather your precompiled lib doesn't have a soname field. So the linker, when given `path/to/libname.so` rather than `-lname`, decides to write the full path rather than the (nonexistent) soname.

Can you build the precompiled lib with a soname, even if it doesn't have anything after `.so`? I'd not, can you patchelf that before integrating it into your source tree?

**Comment by PhilippeRo** [comment]
Thanks a lot. That did it.
I used the command : patchelf --set-soname libfoo.so libfoo.so
and it did the trick. Now, I have to remember to run the command every time I will include a new version of the library.

**Comment by GuillaumeQuenneville** [comment]
I think this is worth documeting.
I can add it to
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Shipping-prebuilt-binaries-as-wraps.md when I have a second. It's the first meson doc when googling this kind of issue.

**Comment by eli-schwartz** [comment]
That makes sense, I eagerly await your patch. :)

**Comment by eli-schwartz** [comment]
(It should be noted that meson guarantees any library has a soname, whereas shared_module does not. This has benefits for third party tracking e.g. of symbol evolution. But not all third-party built libraries do the semantically correct thing...)
