### ISSUE TITLE
install: true or false not enough for a very common scenario. Exe + libraries.

### ISSUE THREAD

**Issue by germandiagogomez** [mesonbuild/meson#8832]
Hello everyone,

I would like to propose an idea and see what you think. Following the philosophy that in Meson every second spent in the build system is time wasted, I think it would be a good idea...

## Use case

I have an executable program. This program can either compile its support libraries (I do not mean subprojects, but libraries living in the project itself) as static or dynamic.  So it makes sense to:

- when using static libraries, install only the executable (not the static libraries)
- when using dynamic libraries, install both the executable and the dynamic libraries.

For this I have to use conditional code to `install: true` or `install: false`. 

I think this covers a common use case

## Proposal

 Add `install: 'when_static'`

This would work the way I want:

- When compiling the executable and static libs only the exe is installed.
- When compiling the executable and dynami libs both the libraries and the exe are installed.

Greetings.

**Comment by dcbaker** [comment]
How are you controlling whether to build the libraries as static, are you using the `library()` function, and then setting `-Ddefault_library=(static|shared)` to select the different types? if you are then you can do:
```meson
library(
  ...,
  install : get_option('default_library') != 'static'
)
```
Be aware that there's also a `both` for default library that builds both, and in that case we prefer linking against the shared library unless you intervene, so `!= 'static'` is intentional.

**Comment by eli-schwartz** [comment]
Meson has install_tags now.

`meson install --tags runtime` will only install artifacts designated as the "runtime" tag -- which includes both executables and shared libraries, but not static libraries.

I believe this does exactly what you want, and it does so better than adding support for additional meanings of "install", because using install tags means that:
- this works out of the box for all meson projects by default, and is backwards compatible
- it is the user's choice whether to refrain from installing static support libraries, which commonly serve additional roles for a software ecosystem rather than being an internal implementation detail of the executables


If for some reason your executables are the only allowed users of the library and you don't want to install static libraries, the above `get_option != 'static'` suggestion seems reasonable. But also I wonder why you need to allow shared libraries anyway? If it is just to share code between multiple executables, a multi-call binary (e.g. busybox style) might be more apropos.

Anyway, since this is practical to do without adding new meson.build API, I don't think we will be adding a dedicated value "when_static".
