### ISSUE TITLE
Support custom linkers.

### ISSUE THREAD

**Issue by abdullah-saal** [mesonbuild/meson#9072]
Getting this error when trying to use a different linker 
`Unsupported linker, only bfd, gold, and lld are supported, not mold.`  

I am trying to use this https://github.com/rui314/mold.  
Is it possible to add support for custom linkers?

**Comment by dcbaker** [comment]
Meson needs to know about the linkers it invokes, as we have abstractions that site on top of them.

**Comment by Sahnvour** [comment]
I was looking to add support for `mold` as it's a drop-in replacement for GNU `ld`, and didn't seem to require much modification in meson.<br/>
However, since meson uses `-fuse-ld=` pervasively, it will not work with GCC as is because it is reported as an incorrect argument (it only allows `ld`, `gold` and `lld` as parameters I guess). Do you have recommendations on how to handle this cleanly ?

**Comment by dcbaker** [comment]
You'll probably have to do the -B trick that the mold documentation explains passed as LDFLAGS. We should see about adding detection logic for mold though

**Comment by Sahnvour** [comment]
This is getting official support in [GCC 12](https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=ad964f7eaef9c03ce68a01cfdd7fde9d56524868) :)
