### ISSUE TITLE
Idea: ability to add patch/overlay also by relation to another .wrap file

### ISSUE THREAD

**Issue by denizzzka** [mesonbuild/meson#9086]
Idea: provide ability to add patch/overlay also by relation to another .wrap file
Something like:

`some_package.wrap`:
```ini
[wrap-git]
url = https://github.com/some/package.git
revision = 0.1.2

patch_wrap = some_package_overlay
```

`some_package_overlay.wrap`:
```ini
[wrap-git]
url = https://github.com/3rd/some_package_overlay.git
```

it will give ability to use any available way to get/fetch patches from elsewhere.

Technically, wrap related from another wrap can be considered as `subprojects/packagefiles` content.

**Comment by eli-schwartz** [comment]
I don't think it is useful to split the wrap into two .wrap files, one for the source and one for the overlay. Just add the patch_url directly to the first wrap, rather than via pointers.

**Comment by denizzzka** [comment]
> I don't think it is useful to split the wrap into two .wrap files

It isn't about splitting - it is about supporting of patches delivery by another (git, etc) whan http zip archive

**Comment by eli-schwartz** [comment]
The ticket you opened, asked for "also by relation to another .wrap file"

A different, unrelated ticket would be "add support for wrap-git to deliver patches via git instead of http, for example by adding a patch_git setting to specify a git clone url".

However, I do not find this compelling either... the main advantage of git is incremental pulling, or being able to develop on the source code, but patch overlays are copied into the project's git repo so you cannot actually develop on them like that. Might as well use the github generated tarballs.

**Comment by denizzzka** [comment]
> but patch overlays are copied into the project's git repo so you cannot actually develop on them like that

Probably, you cannot develop patches/overlays by any way inside of Meson subproject - you still need to copy back into another reposity you changes.

This proposal is about convient way to provision of code.

Huh, all these archives URLs with checksums are really disgusting. It can be used in homeopathy doses, yep, but if you need to maintain many packages (https://github.com/mesonbuild/meson/issues/9085#issuecomment-895787401) it will drive you crazy.

**Comment by eli-schwartz** [comment]
> Huh, all these archives URLs with checksums are really disgusting. It can be used in homeopathy doses, yep

This doesn't seem like a technical objection. Also it doesn't seem like a productive discussion.

> but if you need to maintain many packages it will drive you crazy.

If you need to maintain many packages you might want to invest in workflow tooling. You can take a look at the wrapdb for inspiration as one example of existing tooling, if you would like.

**Comment by denizzzka** [comment]
(I will try to be productive)

Hypothetical tooling can't predict `patch_hash` what will be calculated from archive made by Github.

**Comment by eli-schwartz** [comment]
> Hypothetical tooling can't predict `patch_hash` what will be calculated from archive made by Github.

Github archives are, in fact, predictable and you can code-sign them for cryptographic security without downloading the archive from Github, instead calculating what the hash and contents will be ahead of time.

```bash
$ git config --get alias.github-release 
!f() { local repo=$(basename "$(pwd)") tag=$1; git archive --prefix=${repo}-${tag#v}/ -o ${repo}-${tag#v}.tar.gz ${tag}; }; f
```

This is what I use to generate guaranteed bit-for-bit reproducible archives for PGP-signing, because I don't want to just trust whatever I download from Github if I'm the one PGP-signing it. The algorithm:

```bash
git archive --prefix=${repo}-${tag#v}/ -o ${repo}-${tag#v}.tar.gz
```

where "repo" is the name of the repo on github, including capitalization, and "tag" is either a git tag or a commit hash... and tags get the "v" removed from the beginning, if there is one.

This will spit out a gzipped tarball, the argument to -o could actually be anything as long as it ends with ".tar.gz"

**Comment by denizzzka** [comment]
I would reformulate the problem (like "[enhancement] Ability to use patch/overlay by any supported by wrap system protocol" without detailing how to) in a more general way

This is not really a critical problem. It just makes project a little more flexible.

**Comment by xclaesse** [comment]
I'm not sure to understand the use-case here, when would you use that? If the overlay is on git, why don't you just fork the project and create a branch with your patches?

**Comment by denizzzka** [comment]
> I'm not sure to understand the use-case here, when would you use that?

I would use this in all cases of open source projects on Github. Just because it is more convenient to maintain than http URL + checksum.

> If the overlay is on git, why don't you just fork the project and create a branch with your patches?

This is exactly what I am doing now. But most of changes in base packages isn't need to change meson.build files.

**Comment by xclaesse** [comment]
I don't understand why you don't simply fork the upstream project in github, create a branch where you commit your meson.build files, and use [wrap-git]. It is much easier than using overlays in wraps.

**Comment by eli-schwartz** [comment]
... and I find http url + checksums more convenient to maintain, because I can autogenerate them and they don't depend on git.

But IMO the support for git for source code is not about "more convenient to maintain", because really it isn't, and checksums are good for security when you automatically download stuff. You could manually maintain a pinned git commit hash, but this is no better or worse than a checksum...

The reason why wrap-git exists is, instead, because it allows the people using them, to work on both the primary project and the git subproject, that's why we even have a setting to allow you to define a push url for your wrap-git subprojects. There is a major workflow ***enabled*** (which would otherwise be totally impossible) by the ability to use wrap-git, which is not just "some people find it convenient to not write hashes".

Absent that, well, meson has as a design goal that, where possible, there should be one intuitive way to do anything, and people should prefer to do that and work to make it better if needed.

So I don't like the idea of adding additional options to the wrap file format, which need to be maintained and tested, and don't actually provide any benefit other than "I don't need to write out a hash." There are multiple ways to achieve your goals within the existing support matrix:
- take advantage of git support, and just point at your fork with meson.build added; regularly rebase on upstream as needed
- add the files in patch_directory, checked into the project that needs that wrap
- write a release script that generates and uploads the archive, and updates the hash in the .wrap file

**Comment by denizzzka** [comment]
@xclaesse 

> I don't understand why you don't simply fork the upstream project in github, create a branch where you commit your meson.build files, and use [wrap-git]. It is much easier than using overlays in wraps.

I am already do it by this way. Before @eli-schwartz explained me it I thought my proposal was a good idea:

> This is not really a critical problem. It just makes projects a little more flexible.

**Comment by eli-schwartz** [comment]
So does that mean that the "wraps collection" subproject idea I mentioned in https://github.com/mesonbuild/meson/issues/9085#issuecomment-896068798 is suitable for your needs?

**Comment by denizzzka** [comment]
@eli-schwartz no

Briefly, in this ticket I tried to convey idea that it isn't good to give an advantage to some delivery methods for patches over others. (At least because this method is too cumbersome and may irritate people away with all these checksums.)

And if it was invented specifically for wrapdb (gradually turns out to this) and should not be used anywhere else, it is necessary to make a note in the manual, because users can pin great hopes on this method.
