### ISSUE TITLE
cmake2meson  fails to generate "if" statements corectly

### ISSUE THREAD

**Issue by kpeace** [mesonbuild/meson#913]
when running cmake2meson I get bad "if" statments.
For instance
if '${CMAKE_CXX_COMPILER_ID}', 'STREQUAL', 'Clang'
instaed of:
if '{CMAKE_CXX_COMPILER_ID}' == 'Clang'

and
OpenSSL_dep = dependency('OpenSSL')
if 'OPENSSL_FOUND'
instead of:
OpenSSL_dep = dependency('OpenSSL')
if OpenSSL_dep.found()

**Comment by jpakkane** [comment]
That code was written before Meson had proper dep support and the like. The CMake converter script was always meant to only do a rough translation from CMake to Meson. Since CMake's script is Turing complete it is extremely difficult to make a fully working converter script (especially since many things are expressed very differently in CMake vs Meson). Unfortunately we have very little manpower to spare for this at the moment. Sorry.

**Comment by scivision** [comment]
As someone who uses CMake alongside Meson in most projects, I find in my opinion that it's often actually OK that cmake2meson.py doesn't automatically convert the CMake `if()` statements, because there is frequently a simpler way to implement the logic in Meson, particularly thanks to `disabler()` allowing me to avoid many if() clauses.
