### ISSUE TITLE
cc.has_header_symbol() not working reliable for strlcat

### ISSUE THREAD

**Issue by OliverHaag** [mesonbuild/meson#9140]
cc.has_header_symbol() is not working for strlcat with my setup (reports it found the symbol in the header although it's not defined there). I'm using clang 12 with gcc 11 libs on CentOS 8 Stream.
I guess this happens because the command calls the compiler which may not have -Werror=implicit-function-declaration set and thus only gives a warning but does not fail with an error code?

**Comment by eli-schwartz** [comment]
This works fine for me, e.g. I attempted to test for "strlcart" instead and it reported an error.

The check is for `strlcat`, not `strlcat()`, so it triggers a `warning: statement with no effect [-Wunused-value]` but isn't actually a function call so it doesn't trigger implicit-function-declaration.


Could you post builddir/meson-logs/meson-log.txt? It might have useful info in it (it will at least report the exact test file snippet used).

**Comment by OliverHaag** [comment]
Here the requested log, see line 402 and the wrong result in 412:
[meson-log.txt](https://github.com/mesonbuild/meson/files/7048479/meson-log.txt)

Can be fixed by appending "-Werror=implicit-function-declaration" to CFLAGS, so I assume that should be done by meson itself?

**Comment by dcbaker** [comment]
I can reproduce this, but only with clang. GCC returns an error, but clang happily warns you that the symbol doesn't exist, but that's fine. We can add the error to the check arguments.

**Comment by eli-schwartz** [comment]
I was just debugging this in a fairly obscure way: gentoo has a QA linter that checks for configure logs containing implicit-function-declaration warnings/errors and diagnoses them as potentially being fallout from GCC 14 / clang 16 making these errors by default, and causing badly written configure checks to fail.

Of course, meson's check is well-formed. Also, of course (ha), the QA linter was complaining that the configure check was not well-formed and was prone to getting itself wrong. But what confused me was that this was only reproducible with clang, not gcc...

The actual cause of the issue is this:

```
/tmp/badcode.c:9:32: error: call to undeclared library function 'aligned_alloc' with type 'void *(unsigned long, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    9 |             void *a = (void*) &aligned_alloc;
      |                                ^
/tmp/badcode.c:9:32: note: include the header <stdlib.h> or explicitly provide a declaration for 'aligned_alloc'
1 error generated.
```

Clang provides this fixit suggestion. GCC does something similar. But clang's fixit suggestions, for functions that have a fixit available, actually cause the type of error to change, from something that is always an error, e.g.

```
/tmp/badcode.c:9:32: error: use of undeclared identifier 'time'
    9 |             void *a = (void*) &time;
      |                                ^
1 error generated.
```

to something that is toggle'able by the user as either an error or not an error, depending.

(GCC's fixit suggestions don't have this failure mode.)

Obviously, this was reported to llvm way back in 2017, at which point they promptly fixed it. Ha! Just kidding, of course they didn't fix it.

https://github.com/llvm/llvm-project/issues/33905

So endeth today's lesson on *exactly why* clang is such a trash heap of a compiler. Since when is an *additional diagnostic* something that's supposed to cause invalid code to be allowed when it previously wasn't?
