### ISSUE TITLE
Fail "meson test" if tests are skipped

### ISSUE THREAD

**Issue by hadess** [mesonbuild/meson#9155]
While skipping tests if a setup doesn't have all the prerequisites is nice so that at least _some_ tests are run, it also means that it's too easy to have tests accidentally be skipped in situations where we absolutely need to run that test.

For example, `libgudev` requires the `fr_FR.UTF-8` locale to be available to run a test against it. Skipping the test on machines where the `fr_FR.UTF-8` locale is simple enough, but I'd like the CI to always run the test, and make sure it's never skipped so that if there is suddenly a problem with the CI's setup and `fr_FR.UTF-8` becomes unavailable, the CI rightfully fails.

I checked the print meson manual, the manual on the website and issues filed and couldn't find a way to achieve this that wouldn't involve post-tests parsing of test reports.

**Comment by dcbaker** [comment]
Why not just put a stage in your CI that checks that `fr_FR.UTF-8` and fails if it's not? Alternatively, meson test writes a junit.xml file, you could easily parse that and decide if tests skipped you didn't want to?

I'm not saying it wouldn't be useful, but this kind of feature is pretty difficult to get right for everyone. Some tests should absolutely skip every time (say because a test only works on windows and your running linux), other tests might need exotic requirements, or only matter when you have specific versions of dependencies (here's a path for glb <= 2.4, and another for > 2.4).

**Comment by xclaesse** [comment]
Not sure to understand, why don't you just make missing `fr_FR.UTF-8` a fatal error in your test instead of skipping the test?

**Comment by dcbaker** [comment]
That seems pretty annoying. I don't have a French locale enabled, so if I tried to run the tests they'd just fail? This seems like the classic case of either adding a "IS_CI" env variable where tests fail instead of skip, or adding a pipeline stage to test that your CI environment is what you expect.

**Comment by dcbaker** [comment]
I think this is relation to this MR: https://gitlab.gnome.org/GNOME/libgudev/-/merge_requests/19

**Comment by xclaesse** [comment]
s/77/99/ maybe? https://mesonbuild.com/Unit-tests.html#skipped-tests-and-hard-errors

**Comment by xclaesse** [comment]
ah ok I see, you want to skip when run manually but not when run in CI. IMHO that's indeed not Meson's responsability, you can change the return value depending on env.

**Comment by hadess** [comment]
In both cases that means having to synchronise the environment checks with the tests, or modifying the tests themselves. The post-check mentioned the libgudev bug is nicer, I just wish it was part of meson, so I could run `meson test --noskip` and be certain that it would fail hard on skips.

**Comment by hadess** [comment]
I finally went with running a script, in the CI, that checks the junit report after the tests are run.

https://gitlab.gnome.org/GNOME/libgudev/-/commit/ffd452c1b76efa65682b159f96bad802fef95143
