### ISSUE TITLE
`meson install --tags` causes recompilation of unrelated targets

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#9268]
**Describe the bug**

Whenever I make a tiny change to `meson.build` trying to debug installation, I get 3 hundreds of irrelevant targets getting rebuilt. I presume it's unneeded to say that this is annoying.

To make things worse, while recompiling these targets in such way it goes into some kind of silent mode where the progress is not shown until the very end of compilation.

**To Reproduce**

```bash
 λ ls
meson.build  myfile  test.c
 λ cat meson.build
project(
  'test',
  ['c'],
)

executable(
  'my_executable',
  ['test.c'],
  install: true,
)

install_data('myfile', install_dir: '/etc/', install_tag: 'mytag')
 λ ~/Projects/meson/meson.py build
The Meson build system
Version: 0.59.99
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
 λ cd build
 λ DESTDIR=/tmp/ ~/Projects/meson/meson.py install --tags my_tag
ninja: Entering directory `/tmp/foo/build'
[2/2] Linking target my_executable
Nothing to install.
 λ find -name test.c.o
./my_executable.p/test.c.o
```

**Expected behavior**

There should be no `test.c.o` file, because it was not marked with `my_tag`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build ? Native
* OS: Archlinux
* Python version: 3.9.6
* `meson --version`: current development version at commit 87e13af1c85c03
* `ninja --version`: 1.10.2

**Comment by eli-schwartz** [comment]
Your title and description state "recompilation", but the command output you posted shows only that things are being compiled for the first time.

> Whenever I make a tiny change to meson.build trying to debug installation, I get 3 hundreds of irrelevant targets getting rebuilt.

Nothing should ever be rebuilt unless the command line or input files have changed. This is handled by ninja, not meson.

When meson.build changes for any reason whatsoever, meson does a reconfigure of the build system based on the new information. If it didn't, then your debugging attempts would not actually do anything, because they wouldn't be in the processes coredata used by `meson install`. However, the reconfigure only updates the build.ninja file and, depending on the actual changes you made, may or may not change the compile commands for the targets. I make small changes to meson.build all the time, kick off a full reconfigure, and end up with maybe 3 out of 100+ targets actually being built.

> To make things worse, while recompiling these targets in such way it goes into some kind of silent mode where the progress is not shown until the very end of compilation.

I am not actually sure what this means. Are you saying that no data is written to the terminal when running `meson install` but it is when you run `ninja && meson install`?

Because in both cases ninja will overwrite previous output rather than using a newline, to collapse build status for commands that don't print warnings to stderr. But this is not at all the same as nothing being printed until the end... also it's nothing new to meson install with --tags support, certainly; it has always been the case with ninja specifically.

**Comment by eli-schwartz** [comment]
And yes, meson install will build all targets before running installation. This is what it always used to do, because it needs to in order to well, install it.

If your problem is that you expected the brand new --tags support to also come with a new feature to skip building targets that aren't part of the requested tags, then no, that isn't how the feature was introduced.

It is at best an enhancement request, and not a regression. And actually trying to implement it would be... complicated, probably.

**Comment by Hi-Angel** [comment]
> When meson.build changes for any reason whatsoever, meson does a reconfigure of the build system

I should note that since "tags" functional is not released, I can not just run `ninja -C build` after I changed a Meson file, because that would cause the system Meson to do reconfiguration. Instead per suggestions on this bugtracker I run `/current/development/meson --wipe build`.

> the reconfigure only updates the build.ninja file and, depending on the actual changes you made, may or may not change the compile commands for the targets. I make small changes to meson.build all the time, kick off a full reconfigure, and end up with maybe 3 out of 100+ targets actually being built.

The number of targets being rebuilt is hard to measure exactly, because when `meson install` causes a rebuild, meson won't print progress. The only reason I know it recompiles targets is because I see multiple `cc`es hogging CPU in `top`.

So my "3 hundreds" is a ballpark measure, I just know I have to wait.

> I am not actually sure what this means. Are you saying that no data is written to the terminal when running `meson install` but it is when you run `ninja && meson install`?

Hmm… Actually now that you said this, I realized it's a bit more complicated. Your suggested commands produce the progress.

What actually happens is I have a `meson` target which creates a single package out of two dozens, which I call like `ninja -C build services/foo-service.deb`. Internally that target has to call `meson install --tags my_tag`.

Now, `meson install --tags my_tag` causes a full rebuild, but no progress is printed in this case.

**Comment by eli-schwartz** [comment]
> Hmm… Actually now that you said this, I realized it's a bit more complicated. Your suggested commands produce the progress.
> 
> What actually happens is I have a `meson` target which creates a single package out of two dozens, which I call like `ninja -C build services/foo-service.deb`. Internally that target has to call `meson install --tags my_tag`.

Okay, that is an important detail. ***EXTREMELY*** important.

You are using ninja to invoke ninja. This may work, but it will not work nicely. Because ninja will buffer output for one target (in this case `services/foo-service.deb`) and only print the output after it does internal accounting and finishes the command.

There is a hack...

> `console` (since 0.48.0): keyword argument conflicts with `capture`, and is meant for commands that are resource-intensive and take a long time to finish. With the Ninja backend, setting this will add this target to [Ninja's `console` pool](https://ninja-build.org/manual.html#_the_literal_console_literal_pool), which has special properties such as not buffering stdout and serializing all targets in this pool.

Or, you could have this target `depends: [list, of, all, targets, with, this, tag]` and ninja will ensure only those targets are up to date, and run those targets *before* invoking `meson install --tags my_tag`. I would actually very much advise this, because then you could also pass `--no-rebuild` to meson install and it won't try to rebuild targets you don't need.

--no-rebuild is actually used internally by meson's own `ninja install` alias for running `meson install` without arguments. Since it depends on "all" and thus knows that ninja already guarantees it is up to date. :)

(Actually, `ninja install` uses the console pool too BTW.)

**Comment by Hi-Angel** [comment]
> Or, you could have this target `depends: [list, of, all, targets, with, this, tag]` and ninja will ensure only those targets are up to date, and run those targets _before_ invoking `meson install --tags my_tag`. I would actually very much advise this, because then you could also pass `--no-rebuild` to meson install and it won't try to rebuild targets you don't need.
> 
> --no-rebuild is actually used internally by meson's own `ninja install` alias for running `meson install` without arguments. Since it depends on "all" and thus knows that ninja already guarantees it is up to date. :)

Oh, the `--no-rebuild` is an amazing idea! Yes, I only have one target per single tag *(I don't count calls to `install_data`, `install_subdir`)*, so there's no need to rewrite dependencies for me, it just works. Thank you again!

**Comment by eli-schwartz** [comment]
Great!

**Comment by eli-schwartz** [comment]
Note there is currently a proposal to add a method for getting the actual `meson` command  which may not be in PATH or may be named something else like meson.py, which you may be interested in as well.
