### ISSUE TITLE
Building python packages: adding C extensions with subdir removes sources installed using install_sources

### ISSUE THREAD

**Issue by daknuett** [mesonbuild/meson#9275]
**Describe the bug**
I try to build a python package using `meson` and `mesonpep517`. This is probably the way packages should be built in the future as by PEP517 and PEP518. I have a couple of source files (python modules) that I install using `python_installation.install_sources`. This works fine by itself.
When I add C extension (using `python_installation.extension_module`) either the compiled C extensions or the python modules are missing. This problem might be related to  #6331.

**To Reproduce**
I have built a [toy project showing three cases](https://github.com/daknuett/python_module_with_meson) you can use it to reproduce the problem.

- on branch `master` I set `subdir:''` (because of the comments in #6331). The compiled extension is placed in the wheel's root directory as expected. This is not how `setuptools` would do it; but most importantly the python modules are missing.
- on branch `subdir_as_by_setuptools` the `subdir` is set to match the layout from `setuptools`. Again, the python modules are missing.
- on branch `extension_no_subdir` I removed the `subdir` from `extension_module`. Then the extension is missing in the `whl` but the python modules are present.

In all three cases you can build the wheels using `python3 -m build .` and inspect the resulting `whl` in the `dist/` directory. Installing the wheel or source dists using pip does not yield different results.

**Expected behavior**

Both python modules (`install_sources`) and C extensions (`extension_module`) should be present. Ideally the `subdir` could be chosen automatically to match the layout from `setuptools` but that is just a bonus.

**system parameters**
* Native build. (via `python3 -m build`)
* Fedora 34 Workstation
* Python 3.9.7
* meson 0.59.1
* ninja 1.10.2

**Comment by eli-schwartz** [comment]
I don't see any bug here.

- `master` is behaving as expected, meson installs `site-packages/mymath/test.py` and `site-packages/mymath.mymath.cpython-39-x86_64-linux-gnu.so`
- `extension_no_subdir` is not a useful case to demo, it is merely demonstrating that the issue you linked exists which is not news
- `subdir_as_by_setuptools` is behaving as expected, meson installs `site-packages/mymath/test.py` and `site-packages/mymath/mymath.mymath.cpython-39-x86_64-linux-gnu.so`


meson is behaving perfectly correctly, except in the `extension_no_subdir` case which is an acknowledged and fixed bug that you linked to.

Your meson.build is probably buggy in all three cases, since you declare the library name `python.extension_module('mymath.mymath',...)` which is totally wrong, and cannot be imported, because you want to create a `mymath` module in the `subdir: 'mymath'`. python won't import a module with dots in the name, if you tell it to then it will look for a filesystem file named similar but with the dot replaced by a directory separator. This is broken both:
- if you install `site-packages/mymath.mymath.{SOEXT}`
- if you install `site-packages/mymath/mymath.mymath.{SOEXT}`

I built both the `master` and `subdir_as_by_setuptools` branches using `python -m build` and installed the resulting wheels, in both cases the same files got installed into the virtualenv as was installed by `ninja install`.

Fix:

```diff
diff --git a/meson.build b/meson.build
index 86ac303..1921e3a 100644
--- a/meson.build
+++ b/meson.build
@@ -10,4 +10,4 @@ python.install_sources(
   subdir:'mymath'
 )
 
-mymath = python.extension_module('mymath.mymath', 'src/mymath.c', dependencies:pydep, install:true, subdir:'mymath')
+mymath = python.extension_module('mymath', 'src/mymath.c', dependencies:pydep, install:true, subdir:'mymath')
```

**Comment by daknuett** [comment]
Thanks for the quick response. It indeed seems like the issue is not with meson. Your proposed fix works when installing the package using meson. However, resulting wheel is still faulty (which is probably an issue with `mesonpep517`).

**Comment by daknuett** [comment]
After doing a bit more searching (now that I know where to look) it seems like the `pure:true` is wrong in `install_sources`.

**Comment by eli-schwartz** [comment]
That sounds like a bug in mesonpep517 and best documented in the mesonpep517 docs -- or better yet fixed.

**Comment by eli-schwartz** [comment]
@thiblahute ^^

**Comment by eli-schwartz** [comment]
Looking at the current mesonpep517 code it only packages files which contain "site-packages", This may be the same underlying problem as #9130, since this is basically a dirty heuristic and it may not be true on all systems... it's difficult to know more without having e.g. the output of `tree installdir/` after `DESTDIR=$PWD/installdir ninja install`

**Comment by thiblahute** [comment]
Can you report the mesonpep517 bug [here](https://gitlab.com/thiblahute/mesonpep517/-/issues) please? I am now reworking the way we build the wheel in a cleaner way so I might already have it fuxed in that branch but I would like to ensure it is the case.

**Comment by daknuett** [comment]
@thiblahute I reported the bug on your GitLab.

FYI I updated the repository I mentioned above to meet the requirements of the [issue on gitlab](https://gitlab.com/thiblahute/mesonpep517/-/issues/17). It no longer satisfies the description above.
