### ISSUE TITLE
Meson treats paths differently for porjects vs subprojects

### ISSUE THREAD

**Issue by Makogan** [mesonbuild/meson#9341]
**Describe the bug**

I have 2 projects, A and B, where B is a dependency of A. B compiles on its own. B has a custom target that relies on a script that outputs files to `B/build` i.e. the build directory of the B project. And again this works fine with meson if B is the main project.

B then declares a dependency that uses this custom target that is to be used by A.

A has a `subprojects/B` directory. And A's meson.build file includes the dependency like this:

```
B_proj = subproject('B')
b_custom_dep = neverengine_proj.get_variable('b_custom_dep')
```

Meson returns the following error:

`subprojects/B/custom_dep.cpp: No such file or directory`

Which makes sense, because it should be trying to find that file in `subprojects/B/build/custom_dep.cpp`

Since that's where output files need to go. 

Since you can only declare custom targets like this:

```
custom_target = custom_target(
    'custom_target',
    output : [
        'custom_target.cpp',
        'custom_target.hpp'],
        build_always_stale : true,
        command : ['python3', meson.current_source_dir() / 'Scripts/script.py', meson.current_source_dir()])
```
Meson does not allow you to specify where the targets go, so when using it as  main project, it assumes the files go into build, so why is it assuming they go into the project root when it is a subproject?

**Comment by eli-schwartz** [comment]
Okay, first of all you can just use `find_program('Scripts/script.py')` and it will search for a program with that name, relative to the current source dir. If it is a script with a python shebang, it will automatically handle running that script via python.

Second of all, you haven't posted your script. So I am going to guess what it does.

> relies on a script that outputs files to `B/build` i.e. the build directory of the B project

This is totally wrong, your script should never ever write to "build/". It should be passed one of the following arguments:
- `@OUTDIR@` which meson will replace with the correct output directory based on the build root, current subdir, and whether it is a subproject
- `@OUTPUT0@ @OUTPUT1@ ...` which meson will replace with the correct output filenames again based on the same logic, where it expects to find the files

Hardcoding current_source_dir and then, I guess, having the script internally use `os.path.join(first_argument, 'build', 'custom_target.cpp')` is incredibly broken, and not just for subprojects. It will also break if you configured your project as

```
meson setup builddir/
```

instead of
```
meson setup build/
```



> Meson does not allow you to specify where the targets go,

meson does not allow you to *choose* where the outputs go. It chooses where the outputs go. This is very different from meson not allowing you to tell your script where meson wants it to be output -- meson does indeed provide a mechanism to communicate its choice to your script command.

**Comment by Makogan** [comment]
If the script writes into `subprojects/B/` it is now polluting the root of the directory :\

It really should write into a subdirectory, even if meson is the one to pick it.

If you are iterating on both the subproject and the parent project you risk adding a bunch of unneeded files to source control.

**Comment by eli-schwartz** [comment]
No, this will never be the case.

Again, if you use meson's documented placeholder tokens then meson will take care of ensuring that your script is invoked with the correct directory.

This will not be `subprojects/B/`, because ***meson*** has a policy about not polluting the source tree, so it is not going to violate its own rule. This directory will be the one meson chooses, inside of the build directory. It will be different depending on whether it is built as a subproject or not.

**Comment by Makogan** [comment]
`@OUTDIR@`

Resolves to `subprojects/B` for me. 

Basically I changed my script to try to abide by the pattern you described and I do this:

```
preprocessing_program = find_program('Scripts/preprocessing.py')
pre_target = custom_target(
    'Preprocess',
    output : [
        'UniformObjects.cpp',
        'UniformObjects.hpp'],
        build_always_stale : true,
        command : ['python3', preprocessing_program, meson.current_source_dir(), '@OUTDIR@']) ```
 
 The very first thing I do in the script is print the third argument:
 
 ```
 def main():
    assert(len(sys.argv) == 3)

    cwd = sys.argv[1]

    print('aaaaaaaaaaaaaaaaaaaaaaaaaaa')
    print('aaaaaaaaaaaaaaaaaaaaaaaaaaa')
    print(sys.argv)
    ```
    
    This is what I see:
    
    ```
aaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaa
['/home/makogan/research/subprojects/neverengine/Scripts/preprocessing.py', '/home/makogan/research/subprojects/neverengine', 'subprojects/neverengine']
```

That last argument is `@OUTDIR@`, meson is telling the script to write the files into the subproject root.

**Comment by eli-schwartz** [comment]
The script will be running with the current working directory as "/home/makogan/research/build" and not "/home/makogan/research".

So "subprojects/neverengine" resolves to "/home/makogan/research/build/subprojects/neverengine" rather than "/home/makogan/research/subprojects/neverengine".

This is entirely separate from what meson.current_source_dir() prints, since meson.current_source_dir() is not the same as meson.current_build_dir() or meson.global_build_root()

**Comment by eli-schwartz** [comment]
```
   cwd = sys.argv[1]
```

This is an incorrect assumption. You should never assume the cwd is passed as an argument to the script, instead use:

```
cwd = os.getcwd()
```

Alternatively,

```
import sys, pathlib
outdir = pathlib.Path(sys.argv[1]).resolve()

print(outdir)
print(outdir.as_posix())
```

**Comment by Makogan** [comment]
Thanks to your advice, I managed to fix the issue by changing the arguments. The assumption is not so much incorrect as that script is brittle and was designed a long time before meson was the build system of this project. 

It very much requires the cwd to be passed into it, because it assumes a specific cwd. Fortunately it can be calculated in a system agnostic way using meson so it should work moving forward.

Thank you for the help again.

**Comment by eli-schwartz** [comment]
Ok, happy to help (I think).

FWIW, at least with the ninja backend (no idea about VS or xcode) the cwd is always going to be meson.global_build_root() which is where the ninja build file (`build.ninja`) is written to. ninja always launches all build commands using that directory as the cwd.

You can get the outdir as meson.current_build_dir() as well, which unlike replacing `@OUTDIR@` as a template string should generally be a full path. It should amount to the same thing either way.

**Comment by Makogan** [comment]
Yup I used `meson.current_build_dir()` to calculate the CWD.
