### ISSUE TITLE
Clean target should not run a reconfigure

### ISSUE THREAD

**Issue by lb90** [mesonbuild/meson#9359]
**Describe the bug**
After updating my system I generally run the clean target then rebuild. That's because of an issue in Meson (not important now). Anyway the clean target runs a reconfigure:

```
$ ninja clean
[0/1] Regenerating build files.
The Meson build system
```

I believe that the clean target should not issue a reconfigure, as this may cause leaving some files behind in the build directory.

**Comment by eli-schwartz** [comment]
I'm not sure this has anything to do with meson, particularly.

meson has a general build rule in the ninja description:

```
build build.ninja: REGENERATE_BUILD ../meson.build meson-private/coredata.dat
 pool = console
```

This is needed in the general case, because in general if meson.build is updated it should trigger a rebuild of build.ninja. But no individual targets depend on build.ninja being up to date -- instead ninja automatically runs any rule that rebuilds build.ninja, whenever possible and before anything else. I am not aware of a method for having any rule be exempt from that.

...

That being said, the "clean" target does 2 things:
- first, it runs the dependency rule "clean-ctlist" which executes  `meson --internal cleantrees <builddir>/meson-private/cleantrees.dat`
- then, it runs the command `ninja -t clean` which is a builtin ninja tool that cleans up all generated outputs known to ninja

So, you could at least run `ninja -t clean` yourself I suppose.
