### ISSUE TITLE
Does/will Meson support custom plugins?

### ISSUE THREAD

**Issue by WilliamBehrens** [mesonbuild/meson#9545]
Will Meson ever support gradle style plugins?

**Comment by eli-schwartz** [comment]
Why Gradle specifically? 😱

**Comment by xclaesse** [comment]
Always help to detail your use-case instead of the solution you think you need. Often we can help with other ways of doing it ;-) Describe what, not how.

**Comment by WilliamBehrens** [comment]
I guess a better way to describe it would be that I want to extend/create a custom meson function without having to have it be a part of the meson source code and instead be its own thing

**Comment by xclaesse** [comment]
That sounds like something you should be doing with an external python script and run_target(). Why is that not a good solution?

**Comment by eli-schwartz** [comment]
Well, generally no because of https://mesonbuild.com/FAQ.html#why-is-meson-not-just-a-python-module-so-i-could-code-my-build-setup-in-python

What exactly is involved in deploying the binary? Is this the kind of thing where you could have a program like e.g. `/usr/bin/rio-deploy /path/to/binary` and deploy it?

You could also allow people to build your deployment program as a meson subproject with override_find_program.

**Comment by WilliamBehrens** [comment]
@xclaesse I was hoping for something a bit more transparent, where I could just have someone do `deploy("args")` 
@eli-schwartz I actually didn't think of setting it up as a subproject, I think that might work, if I had the `run_target()` function defined in a subproject would I just run `ninja -C builddir deploy` or do I have to call the targets of subprojects separately?

**Comment by eli-schwartz** [comment]
```
ninja -C builddir subprojectname@@deploy
```

However, in order to pass arguments, I think what you'd instead do is define in the superproject,

```meson
myexe = executable('thing-to-deploy', 'thing-to-deploy.c')
run_target('deploy',
    command: [find_program('rio-deploy'), myexe]
)
```

And then the subproject wrap will build the program, and the eventual ninja rule(s) will be:

- build `builddir/subprojects/deploytool-project-1.0/rio-deploy`
- build `builddir/thing-to-deploy`
- run `ninja -C builddir deploy`
    - ninja will run `builddir/subprojects/deploytool-project-1.0/rio-deploy builddir/thing-to-deploy`
