### ISSUE TITLE
compiler.find_library(): keyword arg include_directories error

### ISSUE THREAD

**Issue by kevinconley19** [mesonbuild/meson#9551]
When calling compiler.find_library() with the include_directories keyword argument meson fails with:
ERROR: compiler.find_library got unknown keyword arguments "include_directories"

I'm using meson:
The Meson build system
Version: 0.60.1

According to the documentation this should be supported as a inc or list of inc:
https://mesonbuild.com/Reference-manual_returned_compiler.html#compilerfind_library

Its a pretty simple meson.build file. And yes, i know this is not a best practice but syntactically it should work, right?:

```
project('ktest', 'c', version: '0.0.0')

cc = meson.get_compiler('c')
libmowgli_2_dep = cc.find_library(
    'mowgli-2',
    dirs: [meson.global_source_root() / '../libmowgli-2/src/libmowgli'],
    has_headers: ['mowgli.h'],
    include_directories: include_directories('../libmowgli-2/src/libmowgli'),
    static: true)

executable('main',
    'main.c',
    dependencies: [libmowgli_2_dep],
    install: false)
```

Am I calling this correctly? Please advise...

**Comment by eli-schwartz** [comment]
The documentation is wrong here, sorry. We did a massive rewrite of how the docs are ordered and a couple things slipped through the cracks...

The old version of the documentation ([available here](https://github.com/mesonbuild/meson/blob/4deeb907b613760754c5be20e1af019d76b78515/docs/markdown/Reference-manual.md#compiler-object) in ugly-ish but usable markdown) pointed out:

> 

find_library(lib_name, ...): tries to find the library specified in the positional argument. The result object can be used just like the return value of dependency. If the keyword argument required is false, Meson will proceed even if the library is not found. By default the library is searched for in the system library directory (e.g. /usr/lib). This can be overridden with the dirs keyword argument, which can be either a string or a list of strings. (since 0.47.0) The value of a feature option can also be passed to the required keyword argument. (since 0.49.0) If the keyword argument disabler is true and the dependency couldn't be found, return a disabler object instead of a not-found dependency. (since 0.50.0) The has_headers keyword argument can be a list of header files that must be found as well, using has_header() method. ***All keyword arguments prefixed with header_ will be passed down to has_header() method with the prefix removed.*** (since 0.51.0) The static keyword (boolean) can be set to true to limit the search to static libraries and false for dynamic/shared.

**Comment by kevinconley19** [comment]
Thanks - but a followup question...
Doesn't a dependency carry the "include_directories" with it?
meson is reporting it finds the library and the required header file but the compile is still failing in main when included the header file.
Do i have to also add the include directories to the executable target also?

**Comment by eli-schwartz** [comment]
You need to add it to a declare_dependency.

```meson
foo_inc = include_directories('/opt/foo/include')
foo_lib = cc.find_library('foo', required: get_option('foo-support'), has_headers: 'foo.h', header_include_directories: foo_inc)
if foo_lib.found()
    foo_dep = declare_dependency(link_with: foo_lib, include_directories: foo_inc)
else
    # artificial not-found-dependency
    foo_dep = dependency('', required: false)
endif
```

This will provide the same manually constructed interface that a pkg-config dependency would provide, including both library link flags and compile include paths.

**Comment by kevinconley19** [comment]
both declare_dependency and compiler.find_library both return a DEP according to the documentation. I thought the only difference is how they search for the dependency. 

Are you saying some properties are left blank in the DEP object returned  by compiler.find_library even thought they
might be available/known by compiler.find_library?

It doesn't seem logical that the same object should have different behavior depending on how it was constructed? Sounds like a case of new object/type.

**Comment by eli-schwartz** [comment]
Well, originally find_library never had anything at all to do with headers, and when adding has_headers support it was only ever taught to look up the headers, not actually do anything directly with them.

I suppose that is something that could be added? There is no chance you would be able to use it before raising your minimum version of meson to 0.61
