### ISSUE TITLE
Require parallel tools when depending on HDF5

### ISSUE THREAD

**Issue by Julius-Plehn** [mesonbuild/meson#9555]
I have an application that specifically requires the availability of `h5pcc` instead of `h5cc`: https://github.com/mesonbuild/meson/blob/39ceb677744e1f959a0db6406d51a26d78f0ab68/mesonbuild/dependencies/hdf5.py#L97-L99

In my case HDF5 is only build with parallel compatibility and therefore `h5cc` is not available. 
My current workaround is to simple edit this line and specify the other tool directly. 

It there a more appropriate workaround for this issue?
Alternatively: Is it possible to add an optional parameter to `hdf5_dep = dependency('hdf5')` e.g. `dependency('hdf5', parallel: true)`

**Comment by eli-schwartz** [comment]
According to the hdf5 build system, only `h5cc` exists, and it will be installed as `h5pcc` iff "hdf5 is being built in parallel mode".

A pointless rename which, as with many parts of the hdf5 build system and install layout, is quite pointless and just causes trouble... but as they have decreed... since they can never exist at the same time (you either build --enable-parallel or not) it seems like it would make sense to just search for both of them and treat them both as h5cc.

I don't think adding a `parallel: true` kwarg makes much sense, since e.g. the pkg-config lookup method doesn't actually care, and as a matter of fact h5pcc will return the same compiler flags too.
