### ISSUE TITLE
Linking with Clang 3.9 using LTO is broken by Meson 0.57

### ISSUE THREAD

**Issue by nomis** [mesonbuild/meson#9569]
**Describe the bug**
Clang 3.9 does not support `-flto-jobs` (added by #7820 / #8087).

**To Reproduce**
Use `clang-3.9` as the compiler for a build and enable LTO.

The build fails when linking and clang is called with `-flto-jobs=0`, e.g.:

```
$ clang-3.9 -flto-jobs=0
clang: error: unknown argument: '-flto-jobs=0'
clang: error: no input files
```
```
$ clang-4.0 -flto-jobs=0
clang: error: no input files
```

**Expected behavior**
Meson should not try to use `-flto-jobs` with Clang 3.9

**system parameters**
* Ubuntu 18.04/20.04
* Python 3.8.10
* Meson 0.60.1
* Ninja 1.10.2.2

**Comment by nomis** [comment]
This code is not consistent with the comment:
```
        # In clang -flto=0 means auto
        if threads >= 0:
```

The comment states a meaning for 0 but then doesn't do anything different for 0. If "0 means auto" then the expression should probably be `threads > 0` and the argument would not be used unless a non-default value was supplied.

**Comment by eli-schwartz** [comment]
The comment is informational and is there to inform readers that `>=` is deliberate and not an accident. Meson itself uses 0 to mean auto, too.

This is a separate matter from the fact that -flto-jobs=0 is passed as the default. It's not necessarily the case that the clang default is auto, merely because the meson default is auto... however, in this case it is true, the clang documentation says that -flto-jobs=0 is the default.

So, it could be safely removed, yes. Not because of the comment, but because it is a default option and doesn't need to be manually encoded into the command line.

...

As you have pointed out yourself, this functionality actually works flawlessly on clang 4.0 and later, so... upgrading clang to a version that is not from the dark ages would thus solve your problem. Why do you need a compiler that is 5 years old and 10 major versions behind (my system clang is 13.0.0, for comparison)? :p

However, patches to detect clang 3.9 and handle this better will be welcome. :) I think you'd want to:
- refrain from adding any explicit flags for the `=0` case
- detect the >=1 case by raising a MesonException during configure if clang is too old, because it would still be a build-time error in that case

**Comment by nomis** [comment]
> As you have pointed out yourself, this functionality actually works flawlessly on clang 4.0 and later, so... upgrading clang to a version that is not from the dark ages would thus solve your problem.

> Why do you need a compiler that is 5 years old and 10 major versions behind (my system clang is 13.0.0, for comparison)? :p

Because unlike the "it works on my computer" approach I have a documented list of minimum requirements for dependencies and so I'm testing them. Ubuntu 18.04 provides Clang 3.9 and it doesn't go EOL until 2023.

**Comment by eli-schwartz** [comment]
> Ubuntu 18.04 provides Clang 3.9

Always Ubuntu. :(

What's the first version of clang with support for -flto (not -flto-jobs)? I think 3.9?

**Comment by eli-schwartz** [comment]
And a note on:
> Because unlike the "it works on my computer" approach

Clang is not the default compiler on Ubuntu, ***and*** the place where you have actually found clang 3.9 is on a distro that provides parallel versions of many clang packages all the way up to 6.0 -- I'd say it's pretty unreasonable to actually use the ones that are really old even for Ubuntu 18.04

And given that, I also think it's hardly surprising that the person who added lto-jobs support didn't test out this particular unlikely combination.
