### ISSUE TITLE
qt5.preprocess target error when using the same file name

### ISSUE THREAD

**Issue by ystreet** [mesonbuild/meson#959]
So, an invocation like:
`qrc_files = qt5_mod.preprocess(qresources : 'qml.qrc')`
In two separate directories reference separate qml.qrc files will fail with:
`Tried to create target "qml_qrc", but a target of that name already exists.`

Example of this are the two directories in https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/tests/examples/qt/

**Comment by nirbheek** [comment]
This is just a matter of using a better `custom_target` name in the module. The same problem plagues the `gnome` module.

**Comment by ystreet** [comment]
The same actually also happens with two executable() calls as well with the same name.

**Comment by ystreet** [comment]
And there's a test case (with static libraries) that explicitly tests that this fails.

**Comment by nirbheek** [comment]
As per discussion on IRC, it's not possible to support two `BuildTarget`s of the same type (`executable` or `static_library`) with the same name, and `CustomTarget` names don't affect anything in their outputs, so that is not an issue.

What is an issue is modules not using unique names for `CustomTarget`s.

**Comment by jpakkane** [comment]
Probably we should add an optional positional argument that the user can pass to get a unique name. So something like:

    qt5.preprocess(qresources : 'qml.qrc') # target name defaults to current behaviour
    # in some other dir
    qt5.preprocess('unique_name', qresources : 'qml.qrc')

**Comment by nirbheek** [comment]
Why bother when the name doesn't have any effect besides setting the Ninja target name and the target private dir?

**Comment by jpakkane** [comment]
If two targets are given the same name, they get the same private dir and can clobber each other. In addition:

 - consistency with other target types
 - non-ninja backends need a unique, user visible name (e.g. each has to be a VS "project" inside the solution)
 - current implementation stores targets in dicts by name, changing takes effort and then one target type would be stored in a different data structure which is confusing

**Comment by nirbheek** [comment]
No, I mean why bother with a kwarg when the module can just handle it transparently. :)

**Comment by jpakkane** [comment]
If we can come up with a good way to generate human-understandable unique names, then let's do that sure.

**Comment by nirbheek** [comment]
I added a patch for this that uses the positional argument as a unique name if specified. We can do this because for some reason the module already ignored the first argument and appended the rest to the list of sources.

**Comment by martingkelly** [comment]
Hey all, I just encountered this problem while using subprojects. In this case, both projects have a custom target that generates documentation, so naturally both targets are called "docs". This is super convenient because it means you can type "ninja docs" and have it just work. While I could effectively namespace it to try to make these targets unique ("ninja a-docs", "ninja b-docs"), this would make the invocations needlessly long and still not guarantee avoidance of namespace collision in all cases.

So this makes me wonder: When preprocessing subprojects, what if we just put each variable into a per-subproject namespace, so that collisions can't happen anymore? The namespaces can be hidden from the user such that something like this continues to work without breakage:

sp = subproject('a')
sp_dep = sp.get_variable('some_dep')

sp.get_variable would automatically look into sp's namespace when finding 'some_dep', but the user would not have to know the difference.

@jpakkane, @nirbheek do you think this sort of solution would be feasible? I haven't really touched the meson code or internal architecture so I don't know off-hand.

Without such a fix, AFAICT, the only solution is for my projects to have a longer "docs" generation target, which is inconvenient and eventually will break. In this case, I control the source code for these projects, but if I didn't, I would have to manually patch the projects to get them to work at all.

**Comment by martingkelly** [comment]
I just realized: Another way to handle namespacing would be to allow for meson variables to be private/public, and to default them to private. Then the only targets exposed from subproject to parent project would be explicit, such as declare_dependency, and other targets would have no collision issues.

**Comment by jpakkane** [comment]
[Meson already does this.](https://github.com/mesonbuild/meson/tree/master/test%20cases/common/90%20identical%20target%20name%20in%20subproject)

If it does not work for you, it is a bug.

**Comment by martingkelly** [comment]
Yep, I just noticed that by adding some debug prints. It appears what's happening is that some objects, like `executable`, are being namespaced with '@@' while others, like `run_target` (which is what I'm using here) are not being namespaced. The difference seems to be due to the `BuildTarget` class doing namespacing (in the `get_id` function), but the `InterpreterObject` class hierarchy (which `RunTargetHolder` comes from) does not do namespacing.

If you agree this is a bug, I'll file a bug. Or, if you point me in the right direction for how to cleanly fix this inside the class hierarchy, I may send a pull request :). I'm a bit afraid of messing with the class hierarchy without knowing the implications.

**Comment by martingkelly** [comment]
Looks like moving `get_id()` and the `subproject` constructor arguments from `BuildTarget` into `Target` might do the trick. Do you see any issues with this approach?

**Comment by martingkelly** [comment]
OK, I believe I fixed the issue and have submitted a PR for it: #2286
