### ISSUE TITLE
Meson can't detect VS2022 and wont tell me how to fix it

### ISSUE THREAD

**Issue by Veinhelm** [mesonbuild/meson#9641]
**Describe the bug**
When I try to generate VS2022 project files, it gives me an error saying it cant detect VS2022, and wont tell me how to fix it. But, it works when i tell it to use VS2019.
It gives me this error:
```
meson.build:1:0: ERROR: Could not detect Visual Studio using VisualStudioVersion: '17.0' or VSINSTALLDIR: 'D:\\Program Files\\Microsoft Visual Studio\\VS2022\\'!
Please specify the exact backend to use.
```

**To Reproduce**
Literally just run "meson setup build --backend vs" with VS2022 installed.

**Expected behavior**
Expected it to work just fine, since I set up VS2022 correctly (or at least I'm pretty sure I did.)

**system parameters**
* what operating system: Windows 10
* what Python version are you using: 3.10.0
* what `meson --version`: 0.60.2

**Comment by eli-schwartz** [comment]
This is because meson doesn't support VS2022 at all.

Support for it was added in #9558, so it will be available in meson 0.61 once that is released.

...

Aside: the PR to add support was submitted the day after VS2022 itself launched. Reporting a ticket to have it implemented makes sense. :)

Being surprised that it isn't already supported, makes less sense. It is difficult to have support for something that doesn't exist. :(
