### ISSUE TITLE
ldconfig during install causes exception during cross build

### ISSUE THREAD

**Issue by Princemachiavelli** [mesonbuild/meson#9707]
**Describe the bug**
Since https://github.com/mesonbuild/meson/commit/2c3a68bc30cf6e08c2e3b77b64718ef3a0e5d78c Meson attempts to update the ld.so cache during `meson install`. In https://github.com/mesonbuild/meson/commit/6b7d43ebe0d77ac85fa2c01e0e358efc64418126 errors from ldconfig are ignored but if the ldconfig binary is not compatible with the host during a cross build then Popen throws an exception that is not caught:

`OSError: [Errno 8] Exec format error: 'ldconfig'`

The issue *can* be avoided by configuring binfmt on the host system but that wasn't necessary prior to this change (https://github.com/mesonbuild/meson/commit/2c3a68bc30cf6e08c2e3b77b64718ef3a0e5d78c).

The issue is also being tracked in the NixOS project: https://github.com/NixOS/nixpkgs/pull/144779

I'm not a meson expert or even a NixOS expert so creating a simple test project was a bit rough. Let me know if you need more information. Let me know if you need more information:

**To Reproduce**

On a Linux machine during an cross build.
Also the machine's binmft is either not configured for the target system architecture or is disabled via:
`echo 0 | sudo tee /proc/sys/fs/binfmt_misc/status`.

Then the error will occur during the install action:
`meson install --no-rebuild`

src: nixos.c
```
#include <stdio.h>

int main(int argc, char **argv) {
    printf("Hello World");
}
```

meson.build
```
project('nixos', 'c')

cc = meson.get_compiler('c')
dirs = []
executable('nixos', 'nixos.c')
```

cross-file:
```
[properties]
needs_exe_wrapper = true

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[binaries]
llvm-config = 'llvm-config-native'
```
Meson/NixOS Log:

```
meson flags: --buildtype=plain         --libdir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/lib --libexecdir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/libexec         --bindir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/bin --sbindir=/nix/store/nqmnb64pxxzqyac4xdnsdl55  caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/sbin         --includedir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/include         --mandir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/man --infodir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/info         --l  ocaledir=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01 --cross-file=/nix/store/0d6bflf42rgrrxhp10visp67scqncd4g-cross-file.conf
  The Meson build system
  Version: 0.60.2
  Source dir: /build/crossmeson
  Build dir: /build/crossmeson/build
  Build type: cross build
  Project name: nixos
  Project version: undefined
  C compiler for the host machine: aarch64-unknown-linux-gnu-gcc (gcc 9.4.0 "aarch64-unknown-linux-gnu-gcc (GCC) 9.4.0")
  C linker for the host machine: aarch64-unknown-linux-gnu-gcc ld.bfd 2.35.2
  Compiler for language c for the build machine not found.
  Build machine cpu family: x86_64
  Build machine cpu: x86_64
  Host machine cpu family: aarch64
  Host machine cpu: aarch64
  Target machine cpu family: aarch64
  Target machine cpu: aarch64
  Build targets in project: 1

  nixos undefined

    User defined options
      Cross files  : /nix/store/0d6bflf42rgrrxhp10visp67scqncd4g-cross-file.conf
      auto_features: enabled
      bindir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/bin
      buildtype    : plain
      includedir   : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/include
      infodir      : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/info
      libdir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/lib
      libexecdir   : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/libexec
      localedir    : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/locale
      mandir       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/share/man
      prefix       : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01
      sbindir      : /nix/store/nqmnb64pxxzqyac4xdnsdl55caf462h9-nixos-aarch64-unknown-linux-gnu-0.01/sbin
      wrap_mode    : nodownload

  Found ninja-1.10.2 at /nix/store/dw1apaarjckv3myghjmw7q2y1ivpv3xi-ninja-1.10.2/bin/ninja
  meson: enabled parallel building
  @nix { "action": "setPhase", "phase": "buildPhase" }
  building
  build flags: -j16 -l16
  ^M[0/2] Compiling C object nixos.p/nixos.c.o^M[1/2] Compiling C object nixos.p/nixos.c.o^M[1/2] Linking target nixos^M[2/2] Linking target nixos
  @nix { "action": "setPhase", "phase": "installPhase" }
  installing
  install flags: install
  ^M[0/1] Installing files.
  Traceback (most recent call last):
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 138, in run
      return options.run_func(options)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 771, in run
      installer.do_install(datafilename)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 554, in do_install
      self.apply_ldconfig(dm, destdir)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 377, in apply_ldconfig
      apply_ldconfig(dm)
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/minstall.py", line 259, in apply_ldconfig
      proc, out, err = Popen_safe(['ldconfig', '-v'])
    File "/nix/store/7wll645a5mii618r6yknzm43x39ccvhv-meson-0.60.2/lib/python3.9/site-packages/mesonbuild/mesonlib/universal.py", line 1393, in Popen_safe
      p = subprocess.Popen(args, universal_newlines=True, close_fds=False,
    File "/nix/store/jqcpjgqzcci7284r7bp3xjy47w1qpj8y-python3-3.9.9/lib/python3.9/subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/jqcpjgqzcci7284r7bp3xjy47w1qpj8y-python3-3.9.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 8] Exec format error: 'ldconfig'
```

**Expected behavior**
The project should install without error. Meson should probably skip running ldconfig on cross builds.

**System Parameters**
* Cross build: building aarch64 on x86_64
* OS: NixOS 21.11
* Python 3.9.6
* Meson 0.60.2
* Ninja 1.10.2

**Comment by eli-schwartz** [comment]
The ldconfig change has caused a number of issues already. :/ It is potentially really slow, soft-bricked the OS on *BSD, spewed confusing messages if you install to custom prefixes but not using root...

That being said:
- it is not run at all when `$DESTDIR` is used, and nix is a package manager. Package managers traditionally use `$DESTDIR` because that's a fundamental part of building *packages*. So that should have sidestepped the problem, What is Nix doing here?
- it is being looked up from $PATH so to a certain extent I kind of wonder why executables for the cross-compile target are in `$PATH` to begin with, if they aren't configured for emulation. I am not terribly knowledgeable about the cross-compilation case but I *thought* (and perhaps @dabrain34 also thought) that cross-compilation doesn't set the `$PATH` to the target architecture's `$PATH`, but configures the cross file's `[binaries]` table to whichever cross toolchain programs are needed.

This problem I think would have already existed for `restorecon` and `selinuxenabled`, which I guess is somewhat rarer as most people don't have it installed at all, and we do ignore `FileNotFoundError`...
It would probably also have painful effects on the use of `meson.add_install_script()` if those invoke additional binaries from `$PATH`, but that might be unsolvable.

Regardless of whether ldconfig should have errored out here, it's still wasteful to run it at all in a cross-compile situation, I guess.

**Comment by dcbaker** [comment]
@eli-schwartz nix doesn't need to use destdir because every package (derivation) has a unique prefix by design, so it doesn't need to use DESTDIR.

I do have a patch to disable ldconfig in cross compilation, and I can send that. But... This is been such a source of pain. Does it make more sense to just add a switch to install like `--run-ldconf` and let people opt in, instead of trying to special case all of the opt out cases?

**Comment by eli-schwartz** [comment]
I wouldn't cry if we removed it. However, the original request to add it specifically asked for it to be run by default: #4737

The basic rationale is that people are installing new software, and they don't know they need to run ldconfig, so it surprises them that the software may not work after install.

`meson install && ldconfig` isn't really any harder than `meson install --run-ldconfig`, so, given the following choices:
- making it opt in
- special casing when to run it 
-  making it opt out

I can understand the reason to want options 2 or 3, but option 1 offers no utility and we should just remove the functionality entirely instead.

**Comment by Mindavi** [comment]
For nixpkgs I think opt-out would be fine. I think we don't use ld.cache at all (correct me if I'm wrong), so we would disable it for all builds. I guess in general distros would disable it since they have their own mechanism (though they may forget of course, if there's 'just' a perf regression)?

Only someone installing from source would then have this run automatically.

**Comment by AndersonTorres** [comment]
> Package managers traditionally use `$DESTDIR` because that's a fundamental part of building _packages_. 

As far as I remember, when I was a Slackware and an Arch user, DESTDIR was something like a staging area, something like a "poor man's fakeroot". A typical `make install` would pollute `/`, so a DESTDIR is employed in order to fixup and ziptar.

Nix in general, and nixpkgs in particular, do not employ this DESTDIR staging. They do everything in a dedicated filesystem, so to speak.

>So that should have sidestepped the problem, What is Nix doing here?

Briefly speaking, it just `make install prefix=/nix/store/<fancy directory name>`.

**Comment by eli-schwartz** [comment]
fakeroot is an unrelated concept, which permits simulating UID 0 and running commands that think they run as root, and thus pass checks for effective UID, install files that claim (to the fakeroot environment) that they are owned by root, etc.

Really, faked pseudo-permissions are tracked by a preloaded library and the `faked` daemon, no programs *actually* get more permissions, and when fakeroot quits, all filesystem modifications are revealed to have in reality been carried out by and for the invoking user. But it's pretty good at what it's intended for, which is simulating a root install for long enough to record the results into an archive.

...

The critical information here is that nix gives every single package a hermetic prefix, which suffices for tracking purposes without using DESTDIR... and apparently also can write directly to that during the build, without needing to stage anything by the builder, for later communication to the installer.

Fair enough.
