### ISSUE TITLE
Stop calling ldconfig on `meson install`

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/meson#9721]
We've now had three different bugs around this, and it's slow when we don't need to call it, and it doesn't always yield the desired results anyway. I'd like to call for its removal in 0.61. I'm opening this, so we can generate some consensus in a single place.

**Comment by eli-schwartz** [comment]
I was originally a bit nervous about the potential for this to behave unexpectedly, but I have to admit I never in my wildest dreams expected it to brick the OS as it did on *BSD.

I have no objections to removing it. I keep on fearfully expecting a 4th bug to be reported, obviously only after 0.61 is released.

**Comment by rubyFeedback** [comment]
It should perhaps become an option. On Linux I never ran into issues with ldconfig (unless I would mix different glibc-versions and the new compiled one can not be handled by older compiled programs, but there are ways to work around and deal with that; I also only rarely have to upgrade glibc as such); sad to hear that BSDs can not handle this. The default may then be to disable it, and only enable it if the author states so, and perhaps conditionally - just so that operating systems that get ldconfig-nuked don't get ldconfig-nuked any longer.

**Comment by jpakkane** [comment]
Originally we did not call it, but added it because people wanted it.

**Comment by jpakkane** [comment]
> It should perhaps become an option. 

No. No options. Either get it working reliably automatically or do nothing.

**Comment by dcbaker** [comment]
I don't think we can make it work reliably without a switch, because we have to know the intention of the user to know what the right thing to do is. That said, by the time we add a flag a user can just call ldconfig themselves...
