### ISSUE TITLE
gnome.mkenums @filename@ broken link when run in subprojects

### ISSUE THREAD

**Issue by thiblahute** [mesonbuild/meson#973]
When running gnome.mkenums with the headers passed as `sources`, the corresponding `#include @filename@` is broken and not properly linking to the file in tree when run as subproject.

For example in `json-glib` if I do:

```
json_glib_enums = gnome.mkenums('json-enum-types',
   sources: source_h,
   h_template: 'json-enum-types.h.in',
   c_template: 'json-enum-types.c.in',
   install_header: true,
   install_dir: install_header_dir)
```

and in `json-enum-types.c.in` we have:

```
 #include "@filename@" 
```

The build fails with:

```
subprojects/json-glib/json-glib/json-enum-types.c:12:60: fatal error: ../subprojects/json-glib/json-glib/json-parser.h: No such file or directory
 #include "../subprojects/json-glib/json-glib/json-parser.h"
```

It should include `"../../../../subprojects/json-glib/json-glib/json-parser.h"` instead as that include is relatiive to the `.c` file not relative to the build directory.

My current workaround is to replace the source_h files with `meson.current_source_dir() + '/' + h` so that the includes are absolute paths.

**Comment by jpakkane** [comment]
After thinking about this for a while I came to the following conclusion:

If a data generator writes *any* path segments into the files it creates, it is **fundamentally broken**. Generators should not know or even care about include paths, they are the domain of the build system.

The simple solution is to replace `#include "@filename@"` with `#include"json-glib.h"`, because you know what the file name is.

The slightly more involved (but most correct) solution is to fix mkenums to not write path segments in include directives. This requires upstream cooperation, and might take some effort.

The awful solution would be to invoke mkenum in cwds mimicking the way the Make setup does it. This is hideously terrible and just hiding the real problem and not something I want to put into Meson core if at all possible (because the we would need to support every piece of broken code out there rather than them fixing their generators to not hardcode Autotools file layout).

**Comment by QuLogic** [comment]
Possibly one can use `@basename@` instead and ensure the search path includes the files your want. Normally, you only put that `#include` in the source file, so that should be fine for any installation.

It could be a bit buggy if you want to preserve some subdirectory in the search or something.

**Comment by nirbheek** [comment]
Honestly, the simplest fix for this is to just use absolute paths for the source in `gnome.mkenums`.
