### ISSUE TITLE
`static_library` doesn't rebuild `custom_target` it depends upon

### ISSUE THREAD

**Issue by Hi-Angel** [mesonbuild/meson#9736]
**Describe the bug**

Given a `static_library` that depends upon `custom_target` *(where dependency is created by means of `declare_dependency`)*. Building the static library alone doesn't trigger rebuild of the custom target.

**To Reproduce**

```haskell
 λ cat empty.c
 λ cat main.c
#include "header.h"
 λ cat meson.build
project(
  'test',
  ['c'],
)

touch = find_program('touch')

header_h = custom_target(
  'header.h',
  output : 'header.h',
  command : [touch, '@OUTPUT@'],
  build_by_default: true
)

header_inc = include_directories('.')
lib_mylib = static_library(
  'mylib',
  ['empty.c',
   header_h
  ],
  include_directories : [header_inc],
  install: false,
)

dep_lib = declare_dependency(link_with : lib_mylib,
                             include_directories : header_inc)

lib_main = static_library(
  'main',
  ['main.c'],
  dependencies: [dep_lib],
  install: false,
)
 λ meson build
The Meson build system
Version: 0.60.2
Source dir: /tmp/foo
Build dir: /tmp/foo/build
Build type: native build
Project name: test
Project version: undefined
C compiler for the host machine: ccache cc (gcc 11.1.0 "cc (GCC) 11.1.0")
C linker for the host machine: cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program touch found: YES (/usr/bin/touch)
Build targets in project: 3

Found ninja-1.10.2 at /usr/bin/ninja
 λ ninja -C build libmain.a
ninja: Entering directory `build'
[1/2] Compiling C object libmain.a.p/main.c.o
FAILED: libmain.a.p/main.c.o
ccache cc -Ilibmain.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libmain.a.p/main.c.o -MF libmain.a.p/main.c.o.d -o libmain.a.p/main.c.o -c ../main.c
../main.c:1:10: fatal error: header.h: No such file or directory
    1 | #include "header.h"
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

```

**Expected behavior**

There should be no build failure.

It fails because `header.h` was not created, even though it is in dependencies for the `libmain.a` target.
**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build? Native
* OS: Archlinux
* Python version: 3.9.9
* `meson --version`: 0.60.2
* `ninja --version`: 1.10.2

**Comment by Hi-Angel** [comment]
It is worth noting that this bug is specific to `static_library`. If I replace it with `executable`, then all dependencies are rebuilt correctly.

**Comment by eli-schwartz** [comment]
mylib.a does not use header.h in any way, and main.a does. IMO your meson.build is wrong.

main.c.o doesn't depend on mylib.a -- only main.a depends on mylib.a

**Comment by eli-schwartz** [comment]
Specifically, this is part of the advanced notes at https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers

**Comment by eli-schwartz** [comment]
I said "use", not "claims to use". :)

It adds a wasteful requirement, but does not benefit from it. This reduced parallelism.

**Comment by Hi-Angel** [comment]
I don't quite get what was my mistake if any. The link you provided does things a bit different than me, specifically it uses `files()` to declare the sources.

Alright, I changed my testcase to replace plain text with a call to `files()`, but I still get the same compilation error.

**Comment by eli-schwartz** [comment]
files() just lets you create a list of sources in one directory and use them in another directory's static_library() without adding lots of `../path/to/directory` to each file.

The problem here is, as described by my link:

- you create a `libmylib.a`, which depends on `empty.c.o`, which in turn depends on `empty.c` and requires `header.h` to be built at least once
- you create a `libmain.a`, which depends on `libmylib.a` and `main.c.o`
- `main.c.o` depends on `main.c`, but does not depend on `libmylib.a`
- `main.c.o` uses `header.h` and cannot function until `header.h` is built at least once, but, it doesn't depend on it (as described by meson's dependency graph)


It would be inappropriate for meson to assume that because `libmain.a` depends on linking to `libmylib.a`, that all components sources of `libmain.a` cannot be built in parallel with the component sources of `libmylib.a`.

Ninja may attempt to build component sources in any order, as long as they don't violate the dependency graph. By pure chance, ninja may attempt to build `header.h` before `main.c.o`, or it may not, so you cannot assume that switching from static_library to executable "fixes it". You may have just gotten lucky.

**Comment by Hi-Angel** [comment]
Oh, I see now. I was confused because I mistakenly though that `declare_dependency` makes it depend at both compile and link-time, but I neglected the fact that my `declare_dependency` wasn't accepting the `header_h`. So the fix is to add `header_h` into the `declare_dependency` call.

Thank you, and sorry for the confusion.

**Comment by Hi-Angel** [comment]
> It adds a wasteful requirement, but does not benefit from it. This reduced parallelism

By the way, since the code by the link does it as well, I assume it's still needed.

**Comment by eli-schwartz** [comment]
No.

The code in the link doesn't specify the source code of `['foo-utils.c', 'foo-lib.c']`

The code in the link has the stated assumption, but without providing examples, that those files have content, and that among that content is `#include "foo-gen.h"`.

Hence, the code in the link requires that the header be built as a dependency of both libfoo and libbar.

If you are writing a makefile, you'd say:

```make
main.c.o: main.c header.h

# does this need to depend on header.h too? If so, when and why?
empty.c.o: empty.c

libmylib.a: empty.c.o

libmain.a: main.c.o libmylib.a
```
