### ISSUE TITLE
gtk4-update-icon-cache fails if the icon theme dir is empty

### ISSUE THREAD

**Issue by bilelmoussaoui** [mesonbuild/meson#9786]
**Describe the bug**

When building GTK 4 under windows with MSVC (on a CI), if it is built with `-Ddemos=false` no icons are installed and so `gtk4-update-icon-cache` fails with

```
gtk4-update-icon-cache.exe: Failed to open file C:/gnome/share/icons/hicolor\.icon-theme.cache : No such file or directory
```

Because there is nothing installed in `$prefix/share/icons/hicolor/`

**To Reproduce**

Build gtk4 with `-Ddemos=false` in a windows machine, or see https://github.com/gtk-rs/gtk4-rs/runs/4742617026?check_suite_focus=true

**Expected behavior**

the call to gtk4-update-icon-cache should be less error prone and avoid crashing the build because of the icon cache. 

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? native build on Github Actions using `windows-latest` & MSVC. 
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.): Windows
* what Python version are you using e.g. 3.8.0: 3.10.1
* what `meson --version` 0.60.3
* what `ninja --version` if it's a Ninja build `ninja-1.10.2.3`

**Comment by eli-schwartz** [comment]
I don't understand why this bug is supposed to have anything to do with meson?

Meson provides functionality for install scripts to run, and correctly reports that they fail if and when they fail.

Gtk unconditionally runs an install script, but only conditionally installs the files that the install script operates on -- this has a simple and obvious solution in the Gtk meson.build files.

Or gtk4-update-icon-cache should gracefully do nothing in this situation. That too is something to be fixed in the Gtk repository, not here.

**Comment by bilelmoussaoui** [comment]
Makes sense indeed. Thanks & sorry for the noise
