### ISSUE TITLE
Problem with ASTERISK(*) in `command` of `custom_target`

### ISSUE THREAD

**Issue by Bassem-Ramzy** [mesonbuild/meson#9790]
**Describe the bug**
I'm having a problem running `ar` command on Linux with ASTERISK `*.o` in `command` of `custom_target`.

My objective is to gather all `*.o` files, located in a specific folder, into a static `.a` library.
BTW, this step has `depends` of other custom_target to be built first, I'm not adding here for simplicity.

When running this command:
```meson
target_build_cmd = [
  'ar', '-qcs', '/home/bassem/meson/lib.a', meson.project_build_root() + '/tmp/*.o',
]
target_dma_lib = custom_target (
  'target_lib', 
  output: lib.a,  
  build_by_default: true,
  command: target_build_cmd,
)
```
I get error the following error when I run `meson install`:
```CMD
/usr/bin/ar -qcs /home/bassem/meson/lib.a '/home/bassem/meson/crono_dma_driver/tools/meson/bf5/tmp/*.o'
/usr/bin/ar: /home/bassem/meson/tmp/*.o: No such file or directory 
```
It appends single quote to the *.o part for an unknown reason.

While, when I run the command manually without the single quote it works:
```CMD
ar -qcs /home/bassem/meson/lib.a /home/bassem/meson/crono_dma_driver/tools/meson/bf5/tmp/*.o
```
Also, when I write one of the files instead of ASTRISK it works, no error is generated, and `ar` creates the file, e.g.
```meson
  target_build_cmd = [
    'ar', '-qcs', '/home/bassem/meson/lib.a', meson.project_build_root() + '/tmp/sysfs.o',
  ]
```
I tried to use unicode escape `/tmp/\N{ASTERISK}.o`, but got the same error.

How to pass `*.o` in the `command`?

Using `run_target` instead of `custom_target`, with the same command, creates the output `.a` file and doesn't generate the error, however, it adds only the first `.o` file to the archive, leaving the rest of `tmp/*.o` files not-added to the archive.

**To Reproduce**
```meson
target_build_cmd = [
  'ar', '-qcs', '/home/bassem/meson/lib.a', meson.project_build_root() + '/tmp/*.o',
]
target_dma_lib = custom_target (
  'target_lib', 
  output: 'lib.a',  
  build_by_default: true,
  command: target_build_cmd,
)
```
* Replace "/home/bassem/meson" with your own output folder.
* Put more than one .o files under `/tmp`

**Expected behavior**
No error is encountered 

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.). 
5.10.16.3-microsoft-standard-WSL2 # 1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
* what Python version are you using e.g. 3.8.0. 
3.8.10
* what `meson --version`. 
0.60.3
* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by eli-schwartz** [comment]
https://mesonbuild.com/FAQ.html#why-cant-i-specify-target-files-with-a-wildcard

**Comment by eli-schwartz** [comment]
> It appends single quote to the *.o part for an unknown reason.

Because arguments can have shell metacharacters in their actual, real filenames, running the full gamut of spaces, dollar symbols, brackets (did you know there is an actual disk file for the `[` program?) and, of course, asterisks.

And how is ninja supposed to know when your asterisk files are updated, so that it re-runs the ar command because the static library needs to be updated?

It would never have been reasonable or practical for the actual command to run, to use an asterisk. The only potential design that would encompass your goal would be to include a feature, as CMake does, to do `FILE(GLOB outvar *.o)` during configuration, and then write out build rules that (single quote and) list every single file.

But CMake warns that you should not use this feature.

And meson simply doesn't include this feature.

**Comment by Bassem-Ramzy** [comment]
Thanks @eli-schwartz for the explanation.

My higher objective is _to merge object files from a 3rd party static library, that I don't have source code for, with my static library .a file_. I went through all the relevant issues here, but didn't find a concrete solution for it, so I had to follow this approach as a workaround. 
As far as I found out, `extract_all_objects` and `link_whole` don't support a `.a` file, but rather a library built from source code files, most probably for the same reason you explained above. Is there any way to do that using meson native functions other than the configuration? 

By the way, in CMake I use the following approach (I just replaced the actual names with simpler ones):
```CMAKE
add_custom_target(lib.a ALL
        COMMAND ar -xv ${MY_LIB_DIR}/lib1.a
        COMMAND ar -xv ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}/lib2.a
        COMMAND ar -qcs ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}/lib.a *.o
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
        DEPENDS lib2
)
```

**Comment by eli-schwartz** [comment]
One possible solution would be to add a custom target which outputs `lib.a`, and accepts the names of the other lib files it merges as input files. Then use a custom script which internally extracts them to `@PRIVATE_DIR@` and then recombines them. The script would then be in charge of making sure it deletes outdated files etc.

An attempt was made to add a general version of such a thing, here: #9218
However, it is still in draft mode

**Comment by jpakkane** [comment]
A more general guideline would be that if you need to to complex stuff, do not write shell pipelines inside build files. They are typically unreadable and subtly broken. Instead write your functionality in a script file (possibly even Python for better portability to Windows, if that is a thing that matters to you) and then just call that.

This has the added bonus that you can develop and debug the script in isolation and you can call it directly from the command line rather than re-executing Meson all the time.
