### ISSUE TITLE
Decorating cpp object file name in the generated static library

### ISSUE THREAD

**Issue by Bassem-Ramzy** [mesonbuild/meson#9808]
**Describe the bug**
When building a static library `static_library` using cpp files that are found _on another folder_, e.g. '../..' (two levels up), I get the files in the archive as `.._.._myfile.cpp.o`. I need to have it `myfile.o`.
In cmake, there is an undocumented property called `CMAKE_CXX_OUTPUT_EXTENSION_REPLACE` does this all.

**To Reproduce**
A similar code:
```python
project_source_files = [
  '../../src/myfile.cpp',
]
static_library (
  TARGET_NAME,
  project_source_files,
  install: true,
  install_dir: OUTPUT_DIRECTORY,
  name_prefix : '',
  name_suffix : 'a',
)
```
With folder structure:
```
.
└── Project Folder/
    ├── src/
    │   └── myfile.cpp
    └── tools/
        └── meson/
            └── meson.build
```

Then, run `ar -t` for the generated static library, output will be `.._.._myfile.cpp.o`.

**Expected behavior**
Object files names are decorated inside the static library archive file, with no language in extension and with no prefix for the source code path, i.e. object file name will be `myfile.o` instead of `.._.._myfile.cpp.o`.

**system parameters**
* Is this a [cross build](https://mesonbuild.com/Cross-compilation.html) or just a plain native build (for the same computer)? 
Native
* what operating system (e.g. MacOS Catalina, Windows 10, CentOS 8.0, Ubuntu 18.04, etc.). 
5.10.16.3-microsoft-standard-WSL2 # 1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
* what Python version are you using e.g. 3.8.0. 
3.8.10
* what `meson --version`. 
0.60.3
* what `ninja --version` if it's a Ninja build
1.10.0

**Comment by eli-schwartz** [comment]
You say that you need this, but why?

The compiler doesn't care. Static archives don't care.

But doing what you ask for would mean that you cannot compile a `util.c` from two different directories, which is perfectly valid in C, or alternatively that you cannot compile both `util.c` and `util.cpp`, because they would overwrite each other.

**Comment by Bassem-Ramzy** [comment]
I understand your point of view and it's very valid. But, up to my experience, it is not really "common" to have util.c and util.cpp in the same project, however, taking this into consideration as a general case, why don't we provide a parameter for the other case?

For me it's not a stopper issue, but I need it because running routines to validate/handle the generated .o files names should take into consideration this name "difference".

My main objective is to merge the object files from 3rd party static-libraries with my library. Having .o files in the final static library with different prefixes and extension doesn't really "look" normal.
Also, for a reason or another, those files with `.._..` prefix are hidden on Linux. Developer should take this into consideration, e.g. when using `ls`

**Comment by eli-schwartz** [comment]
Adding a parameter has the unfortunate downside of adding new supported public API to the build language, which is not cost-free, and therefore needs to take into consideration questions of design as well as of "is this actually useful".

It's a difficult question to answer. My instinct is that demand for such a parameter is less common than having util.c and util.cpp in the same project. ;)

Again, why does it matter what it looks like? The static library can be considered as an obtuse container. The internal layout isn't really impactful to people.

The files with a `..` prefix are also in a private directory, do people often have a need to use `ls` on them? Would it help if the `..` was translated to something else, the same way we convert `/` separators into underscores?
If you created the static library in the `src/` directory, though, then the filenames as the static library saw them would not contain any directory components, translated or otherwise. :D The build directory layout location of the static_library file "probably" does not matter.

**Comment by Bassem-Ramzy** [comment]
OK, it's then a `nice-to-have` feature, it's not a show-stopper to me, I might have a special case.
Anyways, good to log it here for any future relevant question.
Thanks Eli
