### ISSUE TITLE
"install --tags runtime" shouldn't include bare .so file for shared libraries

### ISSUE THREAD

**Issue by keith-packard** [mesonbuild/meson#9811]
**Describe the bug**
When installing runtime files for a shared library, only the versioned library file should be installed

**To Reproduce**
Check out the [meson-tags package](https://github.com/keith-packard/meson-tags), then build and install using

    $ meson install --tags runtime

**Expected behavior**
Expect only the required runtime files to be installed, 'libfoo.so.1.2.3 and libfoo.so.1' without libfoo.so

**system parameters**
* native build
* debian unstable
* Python 3.9.9
* meson version 0.60.3
* ninja version 1.10.1

**Comment by eli-schwartz** [comment]
That does seem reasonable. It might need a bit of work in the backend to reclassify the bare .so file as a distinct install data, since currrently it is an alias attribute of the library target itself and doesn't get its own tag. :/

The latest version of meson does include `install_symlink()` and a corresponding installdata class for symlink objects, so a fair amount of the groundwork is thus set in order to factor that out.

Note to self: ldconfig doesn't recreate the .so file :D so this is not something that declining to install will result in it ending up installed anyway, but in a surprising manner.

**Comment by xclaesse** [comment]
@eli-schwartz gave that a try at https://github.com/mesonbuild/meson/pull/9816
