### ISSUE TITLE
how to add `-lm` portably as global link argument?

### ISSUE THREAD

**Issue by rgommers** [mesonbuild/meson#9863]
This is question rather than a bug report. I searched the docs and issue tracker, but couldn't find the answer.

I'd like to add `-lm` in a portable fashion to all my (100+) Python extensions with C code. The portable part is documented at https://mesonbuild.com/howtox.html#add-math-library-lm-portably. However, going around and adding `dependencies : m_dep` a hundred times is no fun, I figured that `add_project_link_arguments` would be the way to do this in one go:
```meson
m_dep = cc.find_library('m', required : false)
add_project_link_arguments(m_dep, language : 'c')
```
However that doesn't work (as kind of expected, because the first parameter is documented as `str`):
```
Library m found: YES

../meson.build:32:0: ERROR: add_project_link_arguments argument 1 was of type "ExternalLibrary" but should have been "str"
```

~So my question is: is there a way to do this efficiently? And if not, should there be?~ Found the answer I think, after typing this, so adding it to save the next person a bit of time:
```meson
# We need -lm for all executables built from C code that use math functions
m_dep = cc.find_library('m', required : false)
if m_dep.found()
  add_project_link_arguments('-lm', language : 'c')
endif
```

Please feel free to close straight away. If it makes sense to add this to the docs, I'm happy to open a PR.

**Comment by jpakkane** [comment]
Fortunately this will soon be a thing of the past. Glibc is the last libc that has a separate libm and they are going to get rid of it and merge it inside libc (or possibly they have already done so).

**Comment by rgommers** [comment]
That'd be nice. It looks like they're just moving the problem though, recent glibc versions introduce SIMD versions of `cos`, `sin`, `exp`, etc. so I'm now figuring out where I have to manually add `-lmvec` - looks like when linking static libraries that may contain SIMD code, and (possibly) mixed C/Fortran Python extensions with `link_language : 'fortran'`.

**Comment by eli-schwartz** [comment]
If the "m" library exists, that is a probable sign that:
- you are not on Windows
- you're using a POSIX platform

so `-lm` should be expected to work.

Although strictly speaking libraries aren't "supposed" to be added that way in meson, the libm is part of the base system and meson has a quirk that writes out `-lm` into the linker command line instead of resolving it to a path, because it is known to be one of a small list of special-cased system libraries (dl, rt, c, pthread are the rest, see mesonbuild/arglist.py UNIXY_COMPILER_INTERNAL_LIBS).

So, given you know the compiler argument convention is `-l` already, this should work fine.

The alternative is having a meson array containing universal dependencies, so that you can trivially add new ones to that list and they immediately affect every target in your entire build.

> Fortunately this will soon be a thing of the past. Glibc is the last libc that has a separate libm and they are going to get rid of it and merge it inside libc (or possibly they have already done so).

They have already done so last August for -lpthread, -ldl, -lutil, -lanl; they may be planning to do so for libm as well, but it is not currently the case (i.e. glibc built from git still has a separate libm and I have not seen any commits landing to move those functions into libc proper. I do have vague recollections of seeing discussion that it's on the roadmap, but I simply do not recall where I may have seen that).

> so I'm now figuring out where I have to manually add `-lmvec` - looks like when linking static libraries that may contain SIMD code

For the record, this should not be needed if you link libm already? Because glibc already installs libm as linker scripts "for transparent use of vector math library":
```
$ cat /usr/lib/libm.so
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /usr/lib/libm.so.6  AS_NEEDED ( /usr/lib/libmvec.so.1 ) )
```
```
$ cat /usr/lib/libm.a
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /usr/lib/libm-2.34.9000.a /usr/lib/libmvec.a )
```

**Comment by rgommers** [comment]
Thanks for all the details!

> For the record, this should not be needed if you link libm already?

I'm not sure, I've found in various places (e.g. https://sourceware.org/glibc/wiki/libmvec) info like: 
- _The library `libmvec.so` is linked in as needed when using `-lm`, no need to specify `-lmvec` explicitly._
- _For static builds with gcc needed to add both options with the following order: `-lmvec -lm`._

Your `cat /usr/lib/libm.a` seems to disagree with that, but it may not be the case on all platforms. I'm still trying to wrap my head around some very puzzling bug (https://github.com/scipy/scipy/issues/15414, it's from a `distutils` build so not conclusive evidence for `-lm` not being enough) where several users seem to report that `-lmvec` is needed).

Anyway, you have confirmed that the way I'm adding `-lm` in the Meson build is fine, so let me close this. Thanks again.

**Comment by eli-schwartz** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=20539

It's always a linker script, regardless of platform -- the glibc `math/Makefile` unconditionally does this using a mostly statically coded linker script (structure is guaranteed, it does have to dynamically calculate the libdir and glibc version embedded in the script) .

It is "new" since glibc 2.25 though, so I presume at least 2.24 had issues where this was broken.

The comments there are instructive. One person observes:

> For static builds needed to add both options with the following order: -lmvec -lm.
> It is reflected in documenation at https://sourceware.org/glibc/wiki/libmvec

Another person observes:
> It makes x86-64 different from other targets and makes libmvec less transparent.  Special rules are needed to create static executable for x86-64.

And then it was changed from a regular static library to a linker script including both static libraries.

So, your link seems to be out of date? Maybe it never got modified after that bug report. Or maybe they are recommending the "robust approach that works on glibc 2.24". I don't know.

**Comment by rgommers** [comment]
> It is "new" since glibc 2.25 though, so I presume at least 2.24 had issues where this was broken.

Lots more interesting details, thanks! I wish we didn't have to deal with ancient Glibc versions, but (thanks to the joys of `manylinux`) we've only recently been able to drop Glibc `2.12` support and are now at `2.17` as the required version. The next step up, which is a while away, will be `2.24`.

And then of course we have to deal with whatever is going on on platforms like AIX, IBM Z, BSD, etc. (and Musl libc, and who knows what else people are running), where we don't have much of a clue what is going on to begin with.

**Comment by eli-schwartz** [comment]
Well, libmvec is new since 2.22, right? And doesn't seem to automatically get used without added link flags, until 2.25 -- so I guess the question is whether you support those versions in the middle. Probably hard to get away with, unless you change the scope of the problem to supporting distros which are known to either have versions too old to have libmvec, or too new to have the inconsistency of needing to manually specify it or be penalized by mysterious missing symbols you never explicitly asked for.

**Comment by rgommers** [comment]
> Edit: if manylinux explicitly defines a level containing 2.24 then that is impossible/hopeless.

Yes it kinda does. In theory the fixed-glibc-version design was dropped with PEP 600, and replaces it with a generic `manylinux_x_y` scheme. However to build compliant wheels you need tooling, and the easiest thing to use there is `cibuildwheel` plus the Docker images from the `pypa/manylinux` project. And the most recent ones are Debian 9 compatible `manylinux_2_24`: https://github.com/pypa/manylinux#docker-images.

So I think we need to deal with it, but it's not too hard to add support now that we have a decent idea of what is going on.

**Comment by eli-schwartz** [comment]
Yeah, understanding the issue is half the battle right there... anyway, glad I was able to shed some light on what is going on.
