### ISSUE TITLE
Meson wraps rely on checksum of file instead of its content, even for sites like github

### ISSUE THREAD

**Issue by fiesh** [mesonbuild/meson#9924]
Right now, `gtest` and `nlohmann_json` broke, but the former is already working again.  I suppose `github` was doing something internal.

Anyhow, github's archives are not guaranteed to be stable as files themselves, they can be re-generated any time. Checksumming for them only makes sense if one checksums the archives' contents, not the archives themselves. Of course this assumes unpacking the archive itself may not already pose a security threat.

**Comment by eli-schwartz** [comment]
> Anyhow, github's archives are not guaranteed to be stable as files themselves, they can be re-generated any time.

They are deterministically re-generated with a stable checksum as long as the owner of the repo does not:
- rename the repo
- force-push a tag


and this works fine for me.

**Comment by fiesh** [comment]
> and this works fine for me.

Now it seems to be working again.

Can you reference where this is guaranteed?

This is a github employee saying that unless files are hand-uploaded, there is no such guarantee: https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745

**Comment by eli-schwartz** [comment]
I wrote about this a bit at https://lists.reproducible-builds.org/pipermail/rb-general/2021-October/002422.html, explaining why I don't think this is a legitimate problem. That comment you link to is out of date, basically.

Also for nlohmann_json it is a moot point because that one ***is*** a hand-uploaded file. So if it produced the wrong checksum when downloaded, I cannot fathom that this is a bug Meson should fix.

I remain eternally interested in seeing actual examples where github autogenerated tarballs changed their checksums for valid reproducibility issues. You assert this happened for gtest at the same time that hand-uploaded files broke, and now the gtest checksum is back to normal, which implies that the generated tarball didn't break, the github website broke. You are of course welcome to prove me wrong... the actual tarball in question would be very interesting to see. ;)

**Comment by fiesh** [comment]
> I wrote about this a bit at https://lists.reproducible-builds.org/pipermail/rb-general/2021-October/002422.html, explaining why I don't think this is a legitimate problem. That comment you link to is out of date, basically.
> 
> Also for nlohmann_json it is a moot point because that one _**is**_ a hand-uploaded file. So if it produced the wrong checksum when downloaded, I cannot fathom that this is a bug Meson should fix.
> 
> I remain eternally interested in seeing actual examples where github autogenerated tarballs changed their checksums for valid reproducibility issues. You assert this happened for gtest at the same time that hand-uploaded files broke, and now the gtest checksum is back to normal, which implies that the generated tarball didn't break, the github website broke. You are of course welcome to prove me wrong... the actual tarball in question would be very interesting to see. ;)

Thanks for the feedback.  I reckon something happened on github's servers then that triggered this behavior -- as it's not reproducible any more, I really have no way of saying what it was.  We circumvented this now by mirroring everything locally and adapting the wrap files accordingly.  This is probably the way to go anyway if you depend on it.

So I guess this is not anything meson can improve then, and I'll close the ticket.  Thanks for the explanation!
