### ISSUE TITLE
python.find_installation() fails on Windows

### ISSUE THREAD

**Issue by peterh** [mesonbuild/meson#9975]
The following meson.build file fails to build on Windows using a meson MSI installed package:

```
project('foo')

python = import('python').find_installation()
```

Same with both meson 0.60.0 and 0.61.1

Complete output:
```
The Meson build system
Version: 0.61.1
Source dir: C:\temp
Build dir: C:\temp\build
Build type: native build
Project name: foo
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (C:\Program Files\Meson\meson.exe runpython)

meson.build:3:0: ERROR: <PythonExternalProgram 'python3' -> ['C:\\Program Files\\Meson\\meson.exe', 'runpython']> is not a valid python or it is missing distutils

A full log can be found at C:\temp\build\meson-logs\meson-log.txt
```

This appears to be a regression of #5217

**Comment by peterh** [comment]
[meson-log.txt](https://github.com/mesonbuild/meson/files/8034565/meson-log.txt)

**Comment by tristan957** [comment]
Didn't Microsoft do something stupid where the Python on default Windows is just a program which launches and helps you to install regular Windows? On my default Windows 10 it is. Tell Microsoft they make broken software.

**Comment by peterh** [comment]
@tristan957  Microsoft does do that, but it doesn't matter because Meson bundles its own python. And meson is not trying to use the MS python. It's trying to use the bundled python via `meson.exe runpython`, and that is failing with
```
Program stdout:


ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```
in meson-log.txt

**Comment by eli-schwartz** [comment]
Actually the real error there is `ModuleNotFoundError: No module named 'distutils.command.install'`

I totally forgot `runpython` exists, because on Linux it just uses `sys.executable`.

Obviously this should not have a generic catch-all for exceptions that claims everything is a "meson bug", applying to that one meson subcommand which is literally a passthrough to sys.executable for platforms where sys.executable may not exist standalone. I keep finding odd edge cases for that "unhandled python exception" warning, but this is an especially odd one. Maybe I can somehow rethink how it applies...

Be that as it may, the python module will *always* claim any found python without distutils is an "invalid python".
(Or it will do so until either python 3.12, or we can migrate over detection of "links to libpython" to something else.)

**Comment by peterh** [comment]
On 2022-02-09 6:00 p.m., Eli Schwartz wrote:
> Be that as it may, the python module will /always/ claim any found 
> python without distutils is an "invalid python".
> (Or it will do so until either python 3.12, or we can migrate over 
> detection of "links to libpython" to something else.)

So the issue is that the msi doesn't bundle distutils?

(Aside: the meson.exe inside the MSI should statically know whether or 
not it "links to libpython", shouldn't it?)

**Comment by eli-schwartz** [comment]
The links_to_libpython part of the code has absolutely nothing to do with the issue, because that part works flawlessly in your reported environment. This is actually a regression since 05b5a1e56fe8f5400b65d0d69680cc6531fe74f8, which added usage of `distutils.command.install` for the purpose of detecting whether `deb_system` is one of the patched install schemes, and activating Debian-specific quirks.

That will go away once python 3.12 forces the hand of the Debian distribution by entirely deleting distutils, but is otherwise blocked on Debian adapting to a sane sysconfig world (it's a backwards-compatible change but apparently there's resistance to doing it).

Meson does bundle distutils in the MSI, but due to the way pyinstaller works, each import needs to be specified, not just the toplevel `distutils` package: https://github.com/mesonbuild/meson/blob/43c6860a3a129522886cc99ab93df1e23e4cd51f/packaging/createmsi.py#L52-L76

**Comment by peterh** [comment]
Works for me in 0.61.2 . Thanks for the quick fix.
