### ISSUE TITLE
sandbox violation warning shouldn't consider everything in subproject_dir a subproject

### ISSUE THREAD

**Issue by DadSchoorse** [mesonbuild/meson#9995]
**Describe the bug**
It would be great if the subproject_dir was also usable for things other than subprojects, e.g. might also be used for other dependencies which are handled differently for what ever reason. Currently directly using files from non-subproject directories in `subproject_dir` causes a sandbox violation warning.

**To Reproduce**
The affected project is https://github.com/HansKristian-Work/vkd3d-proton. There are sandbox violation warnings caused by https://github.com/HansKristian-Work/vkd3d-proton/blob/a078197e162edaeca6a9b323fd692d1855c8be43/meson.build#L67

As far as I can tell this boils down to basically this:
Consider the following directory structure
```
meson.build
subprojects/
            real_subproject/
                             meson.build
                             ...

            other_directory/
                            include/
                                     header.h

```
Using `subprojects/other_directory/include` as an include directory triggers a sandbox violation warning.

**Expected behavior**
Meson should only give a sandbox violation warning if the file in question is actually coming from a separate project that has its own meson.build, not for every file in `subproject_dir`.

**system parameters**
* Arch Linux
* Python 3.10.2
* meson version `0.61.1`

**Comment by eli-schwartz** [comment]
If they aren't subprojects then they shouldn't go in the subprojects directory.

**Comment by DadSchoorse** [comment]
Not if `subproject_dir` is just the directory where you put all your git submodules, whether they are used as subprojects or not. In that case I don't think it's great that meson forces you to change your general repository layout.

**Comment by eli-schwartz** [comment]
> whether they are used as subprojects or not

They sure seem like subprojects in spirit, regardless of whether the vkd3d-proton project actually invokes them as such. A thirdparty project which is separately installable, can and probably should be picked up as a system dependency, and in the case of vulkan-headers is available in the Meson WrapDB.

`dependency('SPIRV-Headers', method: 'cmake')` is welcome to be contributed to the Meson WrapDB, although it is not currently available...

**Comment by jpakkane** [comment]
> In that case I don't think it's great that meson forces you to change your general repository layout.

The unfortunate thing about rules, regulations, sandboxes and the like is that they are only effective when actually enforced. The entire point of the subprojects directory (which we have documented) is that each and every one of them is strongly isolated from each other. Currently people can rely on the fact that things don't poke into other subprojects' directories behind your back.

The unfortunate downside is that some workflows are not supportable in this setup. This is one of them. For your case a simple solution would be to create your own repo that is the upstream with a single commit that adds a `meson.build` file that does roughly this:

```meson
this_dep = declare_dependency(include_directories: 'include')
```

and then in the project that needs it do:

```meson
otherdir_dep = subproject('otherdir').get_variable('this_dep')
```

**Comment by DadSchoorse** [comment]
> A thirdparty project which is separately installable, can and probably should be picked up as a system dependency, and in the case of vulkan-headers is available in the Meson WrapDB.
> `dependency('SPIRV-Headers', method: 'cmake')` is welcome to be contributed to the Meson WrapDB, although it is not currently available...

The whole point of these repositories is that they provide headers, they won't change the location of the files. Your suggestions are pretty over engineered in my opinion. What vkd3d-proton does work and there's no reason to change anything, not counting the misleading meson warning. 

> Currently people can rely on the fact that things don't poke into other subprojects' directories behind your back.

In this case there is no other subproject though. There shouldn't be a sandbox violation warning because there's no sandbox. Even if you think that the subprojects directory is only for subprojects, and that such a policy is worth enforcing by breaking existing setups, the current warning is misleading. Instead of a sandbox violation it should warn about the misuse of the subprojects directory, if any anything.

> The unfortunate downside is that some workflows are not supportable in this setup. This is one of them.

It worked without a warning in the past, and changing the workflow just because meson changed behavior isn't great. I have nothing against sandboxing and subprojects in general. But I don't see why meson should be so opinionated about the location of my files. Meson could prove that there's no sandbox violation here because there's no `meson.build` with a separate project. But it doesn't, it just gets in the way of a perfectly fine working setup.

**Comment by eli-schwartz** [comment]
> But I don't see why meson should be so opinionated about the location of my files.

One good reason is because they aren't your files, they are the files of an independent project, incidentally a project that upstream recommends using via cmake `find_package` (meson supports this via `dependency(..., method: 'cmake')`and Linux distros want to install via apt rather than have vendored code especially vendored code that downloads at build time.

Your argument essentially amounts to "but headers are mystical and special".

**Comment by DadSchoorse** [comment]
The origin of the files is not really relevant for this issue.

<details>
<summary>But to add some background for why vkd3d-proton does it this way:</summary>
<br>
vkd3d-proton likes to use bleeding edge vulkan extensions, so what distros ship is often out of date. vkd3d-proton also isn't packaged by distos afaik, because it's mainly a window dll. So all the discussion about the current setup causing issues for packing are not really important. What's more important is that people can quickly build it themselves, even on an ancient debian based systems.

By the way, there are a lot of projects that ship vulkan headers directly, for example mesa and dxvk. The difference is that they copy-pasted them into their own `include` directory. I'm not sure why vkd3d-proton didn't do that, maybe whoever rewrote the build system preferred git submodules for ease of upgradability.
The `subprojects` directory was intended for all git submodules, the name was only chosen to allow using dxil-spirv as a subproject.

As for the cmake dependency method, when the original autotools buildsystem was replaced with meson in 2020, proton's build environment didn't have a new enough meson version with cmake support yet. Otherwise it would have been used for dxil-spirv, since the main author was more familiar with cmake. So that wasn't an option anyway.
</details>

To come back to the original issue: When meson support was added to vkd3d-proton, there was no warning. And there shouldn't be one today, as there is no subproject, and therefor no sandbox to violate. If anything meson should warn that the subprojects directory is only for subprojects, but that's just making people's life harder for no reason.

**Comment by Tachi107** [comment]
> meson should warn that the subprojects directory is only for subprojects

How can Meson know that in this specific case it shouldn't warn you for the (possible) misuse of the `subprojects` directory?

Anyway, I too think that what you're doing in vkd3d-proton should throw a warning: you're including a (header-only) dependency in the `subprojects` dir and accessing it by the path to its `include` directory to the include path. It should be instead treated as any other dependency :)

Since it is a third party dependency you should instead access it with [`dependency()`](https://mesonbuild.com/Reference-manual_functions.html#dependency) or [`subproject()`](https://mesonbuild.com/Reference-manual_functions.html#subproject), either by adding a `meson.build` file to its directory or, even better, by writing a small [wrap file](https://mesonbuild.com/Wrap-dependency-system-manual.html) and including the `meson.build` file in `subprojects/packagefiles/depname`. This way, you could even use `dependency()` to look for a new enough version in the system and fallback to the vendored dep if needed.

**Comment by DadSchoorse** [comment]
> How can Meson know that in this specific case it shouldn't warn you for the (possible) misuse of the `subprojects` directory?

The warning isn't for the misuse of the directory, it says I'm violating the sandbox of another project. But there is no `meson.build` in that directory which defines a different project.

> Anyway, I too think that what you're doing in vkd3d-proton should throw a warning: you're including a (header-only) dependency in the `subprojects` dir and accessing it by the path to its `include` directory to the include path. It should be instead treated as any other dependency :)

That's a perfectly valid opinion to have, and the option of wraps is not bad in any way. But a build system shouldn't try to force one way of dependency management. And especially not retroactive, meson used to not throw a warning for this.

**Comment by eli-schwartz** [comment]
It does have a CMakeLists.txt, which also defines a subproject.

The upstream CMakeLists.txt even exports a dependency object which is the upstream preferred way to add those headers as a target dependency.

If some other meson subproject internally does `cmake.subproject('SPIRV-Headers')` or something of that ilk, the thing you claim isn't a subproject but which meson says is a subproject, will in fact get *used* as a subproject. For example, some other project that wants to depend on both vkd3d-proton and the spirv headers.

**Comment by eli-schwartz** [comment]
> And especially not retroactive, meson used to not throw a warning for this.

Meson will always reserve the right to throw a warning at any time, regardless of what it used to do, for things which it never intended to support and which is non-idiomatic and considered to be wrong.

For things which it did intend to support and which are considered okay, it *also* reserves the right to start throwing warnings, however those warnings will traditionally be deprecation warnings and only emitted when the minimum required version of meson is sufficiently high to allow migration to whatever the nominated replacement is.

Please do not use "a new warning was added about this usage and that's bad because warnings bad" as an argument. Argue on the merit of the usage itself.

If there's a valid reason for the usage, then Meson should not warn, even if it always warned from day 1.

If there isn't a valid reason for the usage, then Meson shall warn, and the fact that it learned to warn on invalid usage is a feature not a bug. It is not like it's an error and broke existing usage in the wild. We are unlikely to drop support for deprecated stuff any time soon (perhaps we will do so for Meson 1.0 whenever that occurs).

Aside: I was fairly sure subprojects did not allow directly poking inside them since day 1, in fact, so I would have thought this warning would occur since day 1 too.
