### ISSUE TITLE
the Meson Error when using compile command(compile systemd)

### ISSUE THREAD

**Issue by mmdbalkhi** [mesonbuild/meson#9998]
**Describe the bug**

I do Compile the systemd and saw this error:

```
$ meson compile -C builddir systemd-pot

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 146, in run
    return options.run_func(options)
  File "/usr/lib/python3.10/site-packages/mesonbuild/mcompile.py", line 325, in run
    cdata = coredata.load(options.wd)
  File "/usr/lib/python3.10/site-packages/mesonbuild/coredata.py", line 1033, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mmdbalkhi/w/systemd/builddir/meson-private/coredata.dat'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

**To Reproduce**

https://github.com/systemd/systemd/blob/main/meson.build

**Expected behavior**

compiling systemd!

**system parameters**
* Cross Build: yes 
* ArchLinux 5.15.22-1-lts
* Python: 3.10.2
* meson: 0.61.1
* ninja: 1.10.2

**Comment by eli-schwartz** [comment]
You posted a badly formatted four thousand line meson.build file which crashed my phone when I tried to read it. Holy cow.

It also is completely unreproducible, because it immediately fails with the following error message:

```
meson.build:34:5: ERROR: Tried to access unknown option 'mode'.
```

Ah, but...

> I do Compile the systemd and saw this error

So why are you posting 4 thousand lines worth of the systemd repository into an issue here, why not just say "to reproduce: git clone the systemd repo, try to build it"?

**Comment by mmdbalkhi** [comment]
> Updated the original comment to not include those lines.

it's true! Sorry. Of course, I wanted to edit and give the link, but unfortunately, I gave up! I did not know what the problem was.

Thanks for editing @eli-schwartz

**Comment by eli-schwartz** [comment]
Did you first use `meson setup` to configure the build directory?

Because if you don't, then that file referenced will not exist. But normally it should definitely exist.

The python traceback is a bug, but it is fixed in meson git master. The next bugfix release of Meson should instead error out with this:
```
ERROR: Current directory is not a meson build directory: `/home/mmdbalkhi/w/systemd/builddir`.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.
```

**Comment by mmdbalkhi** [comment]
> Did you first use `meson setup` to configure the build directory?
> 
> Because if you don't, then that file referenced will not exist. But normally it should definitely exist.
> 
> The python traceback is a bug, but it is fixed in meson git master. The next bugfix release of Meson should instead error out with this:
> 
> ```
> ERROR: Current directory is not a meson build directory: `/home/mmdbalkhi/w/systemd/builddir`.
> Please specify a valid build dir or change the working directory to it.
> It is also possible that the build directory was generated with an old
> meson version. Please regenerate it in this case.
> ```


Thankful. I think the problem was in the argument of the command. Instead of build, I wrote Builddir, which has no external existence at all!
